### ISSUE TITLE
Can't get Electrum Cash to Import or Sweep Private key

### ISSUE THREAD

**Issue by mbthedude** [fyookball/electrum#10]
Tried to do a fresh install of Electrum Cash post Fork and from this I want to import the Private Key of another Bitcoin Client. I tried to input the Private Key during setup and copy it into the correct box however the NEXT button remains greyed out so I cannot proceed.

Also tried from a basic install to do a Sweep of the other wallet Private Key but this again will not proceed with the NEXT button greyed out.

My previous client is Waves Lite and I can get access internally to both the SEED and Private keys but Electrum Cash wont accept either.

**Comment by Otaci** [comment]
Is this the waves client you are using? https://wavesplatform.com/

**Comment by mbthedude** [comment]
Yes that's the one

**Comment by Otaci** [comment]
Are you sure that is a Bitcoin client? It looks like it uses the Waves blockchain, which is not the same as Bitcoin.

**Comment by mbthedude** [comment]
Oh, it does store Bitcoin as well I wonder if there is a way I can claim my BCH from it?
