### ISSUE TITLE
SSL warnings

### ISSUE THREAD

**Issue by igarciaes** [fyookball/electrum#100]
When you run from source code in Linux the file ./electron-cash you get several SSL related warnings which could prevent the wallet use to some users:

Electron Cash-2.9.2/packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Electron Cash-2.9.2/packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning

**Comment by fyookball** [comment]
Thanks for documenting  these warnings.
