### ISSUE TITLE
TypeError: __init__() takes exactly 2 arguments (4 given)

### ISSUE THREAD

**Issue by Pei116** [fyookball/electrum#101]
I've been trying to build executable for Windows.
I think step 1 and 2 goes well though I'm stuck in step 3 which runs ./prepare-hw.sh.
Here are what I see from my console.

```
478, in install_item
    self.process_distribution(spec, dist, deps)
  File "C:\python27\lib\site-packages\setuptools\command\easy_install.py", line 514, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given) <- This is the error I think.
fixme:msvcrt:__clean_type_info_names_internal (0xa41544) stub
fixme:msvcrt:__clean_type_info_names_internal (0x1e3b304c) stub
```

Actually I try to ignore it and move forward to step 4 but it fails with such error.

`TypeError: __init__() takes exactly 2 arguments (4 given)
`

FYI, I'm using Python 2.7.12 and Wine 1.8 (There's no 1.7 available in apt-get now) in Ubuntu 16.04.

**Comment by fyookball** [comment]
make sure you have wine installed per Ubuntu instructions. prior to that, I found it helpful to install cython, samba, and winbind in that order and then install wine.  start on a fresh machine if in doubt.  other than that I don't really have time to help you debug building a binary.
