### ISSUE TITLE
Trezor on macOS 10.12.6: No hardware wallet support found on your system

### ISSUE THREAD

**Issue by goodc0re** [fyookball/electrum#102]
Trezor fw 1.5.1 (latest)
macOS 10.12.6

Electron-Cash 2.9.2

"No hardware wallet support found on your system. 
Please install the relevant libraries (eg python trezor for Trezor)" 

reproduceable, every time when trying to create new standard wallet, hardware wallet with Trezor connected. 

Steps taken trying to solve the problem: 

1) Installed google chome extension for Trezor, used wallet.trezor.io, no problem 

tried again to set up the Trezor with Electron-Cash, same error as above 

2) Installed the latest Electrum Bitcoin wallet, set up new standard wallet, hardware wallet, Trezor was detected and working fine.

**Comment by fyookball** [comment]
thanks, will add this to trezor thread

**Comment by Mashuri** [comment]
Neither of these workarounds fix the issue for me. 2016 MacBook Pro with 10.12.5.

**Comment by Windowly** [comment]
I also have exactly the same problem even with the newest 2.9.3 version of Electron Cash
