### ISSUE TITLE
Version 2.9.2_Error:Transavtion was rejected by network rules.( 16:mandatory-script-verify-failed(Signature must use SIGHASH_FORKID)

### ISSUE THREAD

**Issue by josc66** [fyookball/electrum#103]
This is with the latest version when trying to send the BCC/BCH to another wallet on an exchange fro trading. What can be done to fix this? (I sign with Password and the Autheticator and then this error appears (in subject line))

**Comment by fyookball** [comment]
if its 2fa , see 2fa thread.  otherwise you are not connected to right server.
