### ISSUE TITLE
qrcode for reception reads bitcoin:someaddress

### ISSUE THREAD

**Issue by juriise** [fyookball/electrum#104]
`zbarimg Screenshot\ from\ 2017-08-09\ 16-59-13.png 
QR-Code:bitcoin:1D3zcccccccccccccccccccccccccccccccccayH
scanned 1 barcode symbols from 1 images in 0.01 seconds`

Message from coinomi_angelos: https://www.reddit.com/r/COINOMI/comments/6s0zv5/cant_send_bch_out_of_wallet/dla2nmv/
"This is a known issue, and it involves the URI in the QR of the service providing the address you're sending to. Most commonly it has the "bitcoin:" URI, while our application expects "bitcoincash:" "

So, I don't know if a standard is set up for this, but coinomi seems to expect bitcoincash: as tag instead. Another solution is to just drop the bitcoin: tag.

**Comment by fyookball** [comment]
duplicate of #35

**Comment by charleshsu168** [comment]
This might be a serious issue. 
What if someone send BTC to  electron cash address by accident?
It seems to me it can happen and once it's sent, it will be lost forever.

**Comment by juriise** [comment]
Not lost forever, you can see the transaction in a bitcoin wallet (for instance electrum) using the same seed and key derivation path.

By the way, I discovered the problem when I wanted to pay to an electron cash wallet from coinomi. I used the qrcode including the bitcoin: uri, and the coinomi wallet too helpfully arranged a trade with shapeshift to receive a corresponding value of btc in the address. In my case I stopped the action, but reports on reddit r btc indicates that at least one person (thinks) he lost the coins.

**Comment by charleshsu168** [comment]
that's something that needs to be fixed right away to prevent further mistakes.
