### ISSUE TITLE
unconfirmed transaction on BCC chain looks like my confirmed BTC transfer, says zero funds available

### ISSUE THREAD

**Issue by NoobNeedsHelp** [fyookball/electrum#105]
Hello, 

I followed the steps of transferring my BTC out of my wallet, then importing private keys to new electron cash wallet post fork.  However, it looks like that BTC transfer is duplicated on the BCH blockchain according to electroncash wallet, shown as an unconfirmed transaction.   This makes it look like there are zero BCH coins in my wallet.  

When I right click on this unconfirmed transaction to view on blockexplorer, it tells me that the transaction is not found.  When I right click again on the the unconfirmed transaction, look at details, copy the transaction id to blockchain.info, it is found there as my recent BTC transfer out from that wallet. 

Lastly, the way I got this to go away is advise from your other closed issues of changing the server instead of choosing automatic.  Here are screenshots on how to do this: 

![electron 1](https://user-images.githubusercontent.com/30870139/29134531-ea21fe58-7d04-11e7-810e-982330e3b637.PNG)
![electron 2](https://user-images.githubusercontent.com/30870139/29134538-ecfd5f8c-7d04-11e7-9d3e-51d8bab90a32.PNG)

I took the time to do the screenshots in case anyone else has had this problem, as this caused me quiet a bit of headache.  Thank you Fyookball for responding to people quickly on here, wanted to provide this on here so maybe you can reference to help others.

**Comment by fyookball** [comment]
thanks
