### ISSUE TITLE
Cannot send BCH to Bittrex

### ISSUE THREAD

**Issue by Chatwalkers** [fyookball/electrum#106]
![schermafbeelding 2017-08-09 om 15 26 58](https://user-images.githubusercontent.com/29835344/29140726-bccd0532-7d4b-11e7-83a2-dd4d45245441.png)

I have an error when I try to send my funds to bittrex, see picture. I put in the receiving adres. Fill in the password, the code and send. After that the attached warning shows. I don't know what I do wrong?

**Comment by fyookball** [comment]
connect to BCC server and check 2fa thread

**Comment by Chatwalkers** [comment]
How do I do that?

**Comment by Chatwalkers** [comment]
![schermafbeelding 2017-08-11 om 07 38 16](https://user-images.githubusercontent.com/29835344/29202402-1995032e-7e68-11e7-9da4-59ea76364afb.png)
Everytime it has a different warning. Please help me, there is no tutorial about this and I think there are more people with the same problem
