### ISSUE TITLE
No BCC from transfer

### ISSUE THREAD

**Issue by kuechlerbluewinch** [fyookball/electrum#107]
Hello :-)

I changed 2x BCC's by changelly.com and they was sendet to my Account.
1F1HpJKeGAoVppEMticsBBw3MRy3gjUR5b

But ther came no BCC.
MY question: Whats happen and how help?

Thankyou kuechler bluewinch

Transaction # c7a084017479
Input transaction hash | f380a6c8adacde48a2bd5321e3d9a579d7a4c3387ea80324e8817e7c8e1c38a3
Amount | 0.765 BTC
Money received | 09 Aug 2017, 23:05:04
Fee | 0.04100912 BCC
Exchange rate | 1 BTC = 10.24838703 BCC
Receiver | 1F1HpJKeGAoVppEMticsBBw3MRy3gjUR5b
Output transaction hash | 94c42401174f605802cf8f98dc36cb0f8909db30b0f32201ed4dfa7c35974828
Amount | 7.800816 BCC
Money sent | 09 Aug 2017, 23:15:58

and

Transaction # 2587816c8181
Input transaction hash | 3e7d84097ea607f541954704854331a93288f23a592a78742d8a2d793c402b84
Amount | 0.1485 BTC
Money received | 09 Aug 2017, 23:05:04
Fee | 0.00940542 BCC
Exchange rate | 1 BTC = 10.23081738 BCC
Receiver | 1F1HpJKeGAoVppEMticsBBw3MRy3gjUR5b
Output transaction hash | 49bb0b09999dc8fb4bffa705591a5452663a72408e3d2872096644aec2e5e5cf
Amount | 1.51168 BCC
Money sent | 09 Aug 2017, 23:43:04

**Comment by molecular** [comment]
There is indeed BCC on 1F1HpJKeGAoVppEMticsBBw3MRy3gjUR5b.

Can you verify your electrum is synced and you're on the correct chain?

To do that: please go to Tools -> Network ("Overview" tab) and look at "blockchain: xxxxxx blocks". Also look if it says "chain split detected" below that. Maybe you can do a screenshot of that dialog?

**Comment by fyookball** [comment]
I closed this because if you see BCC on your address and not in your wallet, its very likely you're simply not on the correct server.  manually connect to the right server please.  future versions will attempt to auto correct this behavior.
