### ISSUE TITLE
CLI help responses still return "electrum" and not "electrum-cash" 

### ISSUE THREAD

**Issue by tboydston** [fyookball/electrum#109]
Most CLI help responses still suggest using "electrum" in the help response and not "electrum-cash".

**Comment by molecular** [comment]
you mean like

    #> ./electron-cash history -h

I can't find one that has "electrum". Can you give some specific examples?

**Comment by fyookball** [comment]
not every single obscure error msg needs to be modified.  but if there's some you see, paste and ill fix
