### ISSUE TITLE
Electrum Cash 2.9.2 Signature ERROR : transaction reject 

### ISSUE THREAD

**Issue by bauvaisis** [fyookball/electrum#110]
Hi guys !

I'm having problems trying to send my Bitcoin cash.
I have a normal basic wallet opened up with money on it. I enter correct address, amount, password OK and google autenthicator code OK, then i get an error " the transaction was rejected by network rules: 16 mandatory -script- verifiy -flag-failed . Signature must use SIGHASH FORK ID ) 

I tried changing the server to electroncash like listed in some forums; that's ok , but still getting same error ...

Could you help me out please, I'm using windows 10.

thanks !!

**Comment by Chatwalkers** [comment]
I have the same sort of problem. Are there more forums about electron cash?

**Comment by bauvaisis** [comment]
It's crazy, I'm trying to send by bitcoin cash since 3 days already, each day the value is coming down and can't do what i want with my money !!!!

Tried sweeping the address with private key to another wallet, but it says that there's no money on it. Probably because it's not a paper wallet ....

Please, if someone can help us out quickly

thanks!

**Comment by fyookball** [comment]
this is almost always because A)  not connected to right server   or B) using 2fa or ms

**Comment by bauvaisis** [comment]
Hi fyookball i'm using server electroncash.cascharia.com , I'm not usiing 2FA just google authenticator .. is that the problem ? what do you call ms ? 

thanks for your precious help !

**Comment by bauvaisis** [comment]
oups yes it's written 2FA next to my wallet on top ! I guess i have to sweep it all and start a new wallet without this shit

**Comment by Chatwalkers** [comment]
Bauvaisis, I try to sweep my wallet, bud I don't know how? When I put in the private keys, the sweep button stays gray??? Did it wordk for you?

**Comment by bauvaisis** [comment]
i managed to get my money out of there! I was in 2FA wallet.

Solution is to go to restore /add new wallet 

click next then click 2FA wallet AGAIN !!! then restore with old seed words. And then click disable 2FA !! And then it worked perfect !!! good luck !
