### ISSUE TITLE
Still have issues sending BCC 

### ISSUE THREAD

**Issue by Chatwalkers** [fyookball/electrum#111]
![schermafbeelding 2017-08-10 om 22 38 39](https://user-images.githubusercontent.com/29835344/29191208-43346b84-7e1d-11e7-8265-7eacd8f65e32.png)

I still cannot send BCC, this is the new warning. Can you please give me a tutorial how to fix this. I have no technical background.

**Comment by Chatwalkers** [comment]
![schermafbeelding 2017-08-11 om 07 38 16](https://user-images.githubusercontent.com/29835344/29202450-90e5279c-7e68-11e7-915c-116c777ab233.png)
Their are different errors every time. Please come up with a solution. I think their are a lot of people with this problem. I use OSX Electron-cash 2.9.2

**Comment by kyuupichan** [comment]
Change server. That server is hosed. Let us know which one it is.

**Comment by Chatwalkers** [comment]
How do I change server?

**Comment by Chatwalkers** [comment]
![schermafbeelding 2017-08-11 om 07 49 18](https://user-images.githubusercontent.com/29835344/29202557-9dbdec50-7e69-11e7-9b51-48addee2273f.png)

**Comment by Chatwalkers** [comment]
Sorry for the questions, I am just not technical, bud i'll get there with some help :-)

**Comment by Chatwalkers** [comment]
I have changed server to abc1.hsmiths.com  60002 also to electroncash.cascharia.com 50002. Still have the same problem. Can you tell me exactly what to do? Because I am not a developer 
![schermafbeelding 2017-08-11 om 15 33 50](https://user-images.githubusercontent.com/29835344/29215252-8c67f4c8-7eaa-11e7-9104-dabb0ad73f38.png)

**Comment by kyuupichan** [comment]
Try 14.3.70.9

**Comment by Chatwalkers** [comment]
Nope, 14.3.70.9 doesn't work :-(

**Comment by Chatwalkers** [comment]
Can you help me kyuupichan. I am really starting to get frustrated. I don't think it is the server. I think it is the 2fa that is the problem. I try to restore my wallet, I try to sweep it. Bud it looks like I am doing it wrong. Please explain to me in many words how I can fix this. Otherwise I don't understand. best Ronald

**Comment by kyuupichan** [comment]
Sorry I have no idea.  I've only ever see 2FA cause a lot more problems than it solves.

I won't have time to look at this for at least a week.

**Comment by Chatwalkers** [comment]
Can I not turn off 2FA?

**Comment by Chatwalkers** [comment]
Are you the only person who does support for Electron-cash? Because I cannot wait another week. It has already been a week I am spanding every night try to solve this

**Comment by kyuupichan** [comment]
Ideally the original author of the software you used would support his users. He isn't so we're doing what we can. Trustedcoin, the 2nd signer, also have chosen to not support their users. You should make your complaints known to them.

**Comment by Chatwalkers** [comment]
Much appriciated your support!!! I hope you still can help me when you have the time next week.
I wil complain, this is crazy!  Best Ronald

**Comment by molecular** [comment]
which 2fa is it?

**Comment by fyookball** [comment]
we dont support 2fa in general because of what kyuupichan said.  there is also #41 thread with many good suggestions.

**Comment by Chatwalkers** [comment]
Solved the issue with the #41 thread :-))))) Thanks a lot! So happy :-)
