### ISSUE TITLE
Error trying to sweep a private key: unsupported operand type(s) for *: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by aecole** [fyookball/electrum#113]
I'm getting this error on OSX with the released binary and the latest development branch. There is nothing in the log when I run electron-cash with the -v switch. Help / pointers appreciated.

**Comment by molecular** [comment]
* is this on 2.9.2?

it's weird there's nothing on the stdout, definitely looks like an exception that should be printed ther. Are you starting from a terminal? Are you getting this error in a popup or where are you getting it?

**Comment by fyookball** [comment]
which log?

**Comment by aecole** [comment]
Yep, 2.9.2 and it's a popup on screen, can't grab a screenshot right now, but it's in the GUI and not on stdout. 

I ran the binary in the usual way - double click in OSX, the development version I ran from the terminal.

**Comment by aecole** [comment]
Which log - I'm referring to the Terminal when launched with the -v switch.

**Comment by robert-claypool** [comment]
I get this same error in 2.9.2 when trying to sweep a private key in WIF format (51 characters base58, starts with a '5'). Running `x86_64 Linux 4.12.6-1-ARCH`.

**Comment by robert-claypool** [comment]
The error message changes to `No inputs found. (Note that inputs need to be confirmed)` when I import a WIF compressed version of the private key (52 characters base 58, starts with a 'K' or 'L').

1. According to blockdozer.com, the address does contain BCC, and I'm positive that the address was holding Bitcoins on *August 1, 2017 at 6:12pm UTC*.

2. They were never held by an Electrum wallet, but I thought that doesn't matter? I am trying to import from a bitaddress.org paper wallet.

3. I tested this on Arch Linux and then on Windows 10. Same result.

4. I have verified the sha1 hash and gpg sig of the downloads. They are correct.

**Comment by robert-claypool** [comment]
Electron Cash connected itself to the *wrong freaking blockchain*!

Solution:  Go to "Tools > Network", then uncheck "Select server automatically", then right-click a BCC server from the list.

**Comment by fyookball** [comment]
chain fixes coming in next version

**Comment by aecole** [comment]
Juts confirming: my problem has gone away in the latest version
