### ISSUE TITLE
Hardware Wallets (KeepKey)

### ISSUE THREAD

**Issue by rickw** [fyookball/electrum#116]
Installing from the .dmg file on macOS the app does not see the hardware wallet. Was it built with the modules for the hardware wallets? (Electrum just connects.)

update: error from running form source directory:

```Traceback (most recent call last):
  File "/Electron Cash-2.9.2/lib/plugins.py", line 150, in get_hardware_support
    p = self.get_plugin(name)
  File "/Electron Cash-2.9.2/lib/plugins.py", line 178, in get_plugin
    self.load_plugin(name)
  File "/Electron Cash-2.9.2/lib/plugins.py", line 102, in load_plugin
    p = loader.load_module(full_name)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/Electron Cash-2.9.2/plugins/ledger/qt.py", line 12, in <module>
    from btchip.btchipPersoWizard import StartBTChipPersoDialog
ImportError: No module named btchip.btchipPersoWizard
^CTraceback (most recent call last):
  File "/Electron Cash-2.9.2/gui/qt/__init__.py", line 65, in eventFilter
    def eventFilter(self, obj, event):
KeyboardInterrupt```

**Comment by molecular** [comment]
I think when running from source you need to install python dependencies yourself.

    #> pip2 install btchip

**Comment by fyookball** [comment]
AFAIK , keepkey isnt supported yet anyway because they havent yet implemented SIGHASH_FORKID.

If I am wrong let me know.  For now im closing this.

**Comment by rickw** [comment]
They support it on the beta version. I’ll dig into it a little deeper and let you know.

**Comment by molecular** [comment]
The exception you posted is definitely unrelated to keepkey not being found. You can ignore it. If I remove my btchip python library, I get the same error, yet my trezor is detected fine.

Theres a "keepkey" library in pip2. I'm not sure it's included in our binaries. It's strange I don't see a similar problem with the keepkey plugin. I don't have "keepkey" python lib installed, yet no error.

**Comment by rickw** [comment]
On the Mac I get a depreciation warning for six-1.4.1 and the install fails
