### ISSUE TITLE
Turn off two-factor authentication on Electron_Cash_wallet

### ISSUE THREAD

**Issue by Chatwalkers** [fyookball/electrum#118]
I have tried to turn of my two-factor authentication on Electron_Cash_wallet by sweeping private keys and by restore wallet. When I put in the list of private keys, I cannot sweep, the button (sweep) stays gray. When I restore my wallet as a standard wallet, my wallet has 0 balance.

Can Anyone help me? Best, Ronald

**Comment by fyookball** [comment]
Most 2FA discussion should happen here: #41
