### ISSUE TITLE
ImportError: No module named pyaes

### ISSUE THREAD

**Issue by stevard6949** [fyookball/electrum#12]
```
./contrib/make_packages 
version 2.9.0
Traceback (most recent call last):
  File "./contrib/make_packages", line 33, in <module>
    f, pathname, descr = imp.find_module(module)
ImportError: No module named pyaes

```
pyaes (1.6.0) is on pip list

Any idea??

**Comment by fyookball** [comment]
i dont think this is a bug with electron but rather your setup with python being unable to find the module.  the imp.find_module looks in the python syspath.   try sudo apt-get pyaes.  watch where it puts the module into site packagaes..and make sure that is part of the sys path
