### ISSUE TITLE
Electron Cash 2.9.2

### ISSUE THREAD

**Issue by desy0305** [fyookball/electrum#121]
Hi All,

I've tried to claim BCC in ELECTRON cash but obviously something went wrong.

In order to get the private key I moved the BTC from Mycellium to ELECTRUM, copied the the Private Keys and in separate PC I have imported them in ELECTRON but no BCC mirrored there after all...

All APPs latest version as of 13/08/2017

BRGRDS
Lazar

**Comment by fyookball** [comment]
check the block explorer to make sure the BCC is in the address you think and that you imported the right wallet, and that you have all the keys, and that the electron cash is connected to right chain.  It has to be one of those things.

**Comment by desy0305** [comment]
all this shoul be fine. is it the privete key "compromized" when I moved out the btc from the Myceluim cold storage to elecrum and then extracting it? and then trying to claim via ELECTRON

**Comment by fyookball** [comment]
that's how you do cold storage... cold means you sign offline... but anyway if u want me to help, answer the first question:

check the block explorer to make sure the BCC is in the address you think

**Comment by desy0305** [comment]
Hi,

here it is https://www.blocktrail.com/BCC/address/1FVhZGEiBMSN1YqqTCZgCfWZVXT17RnjZo 
I have the seed 12 words pass from mycellium

BRGRDS
Lazar
