### ISSUE TITLE
Electron Cash hangs up Mac OS 10.13

### ISSUE THREAD

**Issue by sciack76** [fyookball/electrum#122]
Hello,

I think it is because of the new Mac OS High Sierra, but when I launch the Electron Cash it hangs up for 1 hour, then it loads but it is very slow and unresponsive.

Can you help?

**Comment by fyookball** [comment]
we'll have a new binary coming next release.  did you try running from source to see how it behaves?

**Comment by sciack76** [comment]
no I did not try to run it from source.

**Comment by fyookball** [comment]
can  you

________________________________

**Comment by sciack76** [comment]
I am trying but there is not apt-get in Mac OS X High Sierra, I can't go on

**Comment by sciack76** [comment]
If I try to launch it:

./electron-cash 
env: python2: No such file or directory

**Comment by fyookball** [comment]
the base folder is called electrum

go into that, and then do python setup.py install

then 

python electron-cash

**Comment by sciack76** [comment]
"python setup.py install" works ok

but if I do

python electron-cash

Error: Could not import PyQt4 on Linux systems, you may try 'sudo apt-get install python-qt4'

**Comment by sciack76** [comment]
any ideas?

**Comment by fyookball** [comment]
qt4 is a real pain to install because there's no brew packages for qt4, at least standard ones.  try to install qt5 instead.

**Comment by sciack76** [comment]
I cant do that... where I can download the 2.9.3 binaries for Mac OS X? I cant find them

**Comment by fyookball** [comment]
just published. electroncash.org

**Comment by sciack76** [comment]
yes but it still does not work with Mac OS High Sierra...
