### ISSUE TITLE
  // , Unable to import 2of3 wallet seed... consider merging #880 ?

### ISSUE THREAD

**Issue by v6** [fyookball/electrum#123]
// , I had a crack at importing some wallets from the Electrum modified by GreenAddress.

https://github.com/spesmilo/electrum/pull/880

If you'd like help with the git particulars, I can lend assistance, but I'm not too familiar with the Electrum source code.

Anyway, I did a successful recovery of a 2of3 GreenAddress wallet into Electrum following GreenAddress's 2of3 recovery instructions. 

I then started Electron Cash, and attempted an import from that Electrum Wallet into Electron Cash.

![screenshot from 2017-08-13 22-45-35](https://user-images.githubusercontent.com/5750764/29253940-6b80f8ce-8079-11e7-92cd-00240a9210ae.png)

I get a message about a backwards incompatible upgrade of the imported wallet from Electrum. 

![screenshot from 2017-08-13 22-45-52](https://user-images.githubusercontent.com/5750764/29253942-7570123e-8079-11e7-8387-9df09972c56e.png)

After I acknowledge that my wallet file format will not be backwards compatible, the client dies and displays the following `NoneType` trace: 

![screenshot from 2017-08-13 22-46-08](https://user-images.githubusercontent.com/5750764/29253932-465156a2-8079-11e7-9c92-37bcf93c6d8a.png)
```
ubuntu@ubuntu:~/Downloads/Electron Cash-2.9.2$ ./electron-cash 
Traceback (most recent call last):
  File "./electron-cash", line 377, in <module>
    d.init_gui(config, plugins)
  File "/home/ubuntu/Downloads/Electron Cash-2.9.2/lib/daemon.py", line 283, in init_gui
    self.gui.main()
  File "/home/ubuntu/Downloads/Electron Cash-2.9.2/gui/qt/__init__.py", line 215, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/home/ubuntu/Downloads/Electron Cash-2.9.2/gui/qt/__init__.py", line 175, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "/home/ubuntu/Downloads/Electron Cash-2.9.2/gui/qt/installwizard.py", line 251, in run_and_get_wallet
    self.storage.upgrade()
  File "/home/ubuntu/Downloads/Electron Cash-2.9.2/lib/storage.py", line 251, in upgrade
    self.convert_wallet_type()
  File "/home/ubuntu/Downloads/Electron Cash-2.9.2/lib/storage.py", line 331, in convert_wallet_type
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
```

https://bitcoin.stackexchange.com/questions/57526/how-can-i-reclaim-my-bitcoin-cash-from-my-greenaddress-wallet/57530#comment66202_57956

Anyway, I'm wondering if you know any way to get a 2of3 GreenAddress wallet, as imported into Electrum, into Electron Cash?

I posted about it here: https://www.reddit.com/r/btc/comments/6t6n23/help_wanted_how_do_i_get_bitcoin_cash_from/dliegox/

How can I get the BCC from my GreenAddress 2of3 private keys? Do you think this is the right approach? Are there any places you would recommend digging further into the code?

**Comment by fyookball** [comment]
Dont mean to ignore you, i just dont know much about green address.  i'll ask the team

**Comment by molecular** [comment]
You could try to cherry-pick that commit spesmilo#0dd52c7642e1bde1d1755bdaee244e945becbf17 (that GreenAddress Restore Plugin) into your local electron-cash git.

I'm a bit confused: what's the result of this *restore process*? A "normal" wallet?

I'm also confused about that "jnius" thing in the call path on your screenshot? Some java binding thingie? Why is it used?

**Comment by fyookball** [comment]
@v6 did you try pulling in the code from 880?

**Comment by fyookball** [comment]
we're dropping green address support.  they will never support BCH.
