### ISSUE TITLE
Electron Cash version 2.9.2 won't launch/ crashes on Mac OS X 10.9.5. Error message: "Electron-Cash quit unexpectedly." 

### ISSUE THREAD

**Issue by Spletharg** [fyookball/electrum#124]
Electron Cash version 2.9.2 won't launch/ crashes on Mac OS X 10.9.5. Error message: "Electron-Cash quit unexpectedly." 
From crash report: Crashed Thread: 0 Dispatch queue: com.apple.main-thread
Exception Type: EXC_BREAKPOINT (SIGTRAP) Exception Codes: 0x0000000000000002, 0x0000000000000000
Dyld Error Message: Symbol not found: _getentropy Referenced from: /Users/USER/Desktop/Electron-Cash.app/Contents/Frameworks/Python.framework/Versions/2.7/Python Expected in: /usr/lib/libSystem.B.dylib Thread 0 Crashed:: Dispatch queue: com.apple.main-thread

**Comment by fyookball** [comment]
closing this and if still a problem in 2.9.3 please open new ticket.  2.9.3 uses a newer mac build process
