### ISSUE TITLE
Unable to load Ledger multisig wallet

### ISSUE THREAD

**Issue by willyloman** [fyookball/electrum#126]
I have a multisignature wallet that includes a ledger S Nano hardware wallet. I have installed python-trezor and btchip-python but am unable to import/restore my hardware wallet in Electrum Cash 2.9.2. When going through the wallet restore wizard, the UI says "No hardware wallet support found on your system...". Is this user story currently supported? Or do I need to wait for future releases? I'm on macOS 10.12.6.

**Comment by fyookball** [comment]
not sure if ledger supports this yet?

**Comment by molecular** [comment]
I could try this, but would need to find that little bugger first. It's so.. *nano*

**Comment by willyloman** [comment]
I think Ledger does support this, as I can access BCH that are stored directly on the Nano S via their Chrome wallet app. I've contacted the support team at Ledger and they also confirm that this should be possible. FWIW, this feature works on Electrum (for BTC).

@molecular: any luck debugging this issue?

**Comment by molecular** [comment]
@willyloman didn't find time yet to look for my btchip thingie yet, sorry.

**Comment by molecular** [comment]
I found my hw.1, but the firmware is old. Trying to figure out how to flash it.

While this issue is not the same, issue #149 is relevant. When #149 is solved, probably this more complex one (multisig) is solved also or at least easier.

**Comment by willyloman** [comment]
@molecular: Thanks for looking into this. Let me know if I can provide any more details -- I am eager to access my BCC multisignature wallet.
To answer your questions:
1.) I am using Ledger OS 1.1.5 on the Nano S which is up-to-date and my USB information is:
![image](https://user-images.githubusercontent.com/30201235/30517029-84697ec8-9b05-11e7-976e-815e963a403e.png)

2.) I am able to successfully sign and broadcast multisignature transactions using my Nano S in Electrum v2.9.2.

**Comment by molecular** [comment]
@willyloman thanks for the info. Looks like the device should be supported by btchip-python: https://github.com/LedgerHQ/btchip-python/blob/ca989f74d77aa888e194585bbbc576cf7ae2e3ce/btchip/btchipComm.py#L213-L226

**Comment by marceloneil** [comment]
@fyookball this should work now
