### ISSUE TITLE
Electron Cash - Does not calculate fees, also keeps saying balance insufficient 

### ISSUE THREAD

**Issue by thekid92584** [fyookball/electrum#128]
Despite a sufficient balance, keeps saying balance is insufficient to send a transaction

Also has estimating fees... command at bottom however never calculates a fee so when a transaction is executed keeps saying " dynamic fees estimates not available"

Of note I am still waiting for my first transaction to be cleared and it has a red clock in front of it. These errors all started after performing a 'test' transaction to an address

**Comment by InfiniteProfitSolutions** [comment]
for now just use static fees, dont use dynamic fees (check preferences).  i will be fixing this soon

**Comment by fyookball** [comment]
use static fee as workaround
