### ISSUE TITLE
Using a space in the directory name is bad form

### ISSUE THREAD

**Issue by bladedoyle** [fyookball/electrum#130]
It is not best practices to use a space in path or directory names.  I suggest that you apply the suggestion to the wallet source code root directory at a minimum.

$ wget https://electroncash.org/downloads/2.9.2/win-linux/Electron-Cash-2.9.2.tar.gz
$ tar tzf Electron-Cash-2.9.2.tar.gz | head -1
Electron Cash-2.9.2/

Ref:  https://library.stanford.edu/research/data-management-services/data-best-practices/best-practices-file-naming
"Do not use spaces. Some software will not recognize file names with spaces, and file names with spaces must be enclosed in quotes when using the command line. Other options include:

    Underscores, e.g. file_name.xxx
    Dashes, e.g. file-name.xxx
    No separation, e.g. filename.xxx
    Camel case, where the first letter of each section of text is capitalized, e.g. FileName.xxx"

**Comment by fyookball** [comment]
which folder has a space?
