### ISSUE TITLE
"Use Tor proxy" checkbox doesn't stick across restarts

### ISSUE THREAD

**Issue by patrikr** [fyookball/electrum#132]
The client does continue to use Tor however, even though the checkbox is not checked.

**Comment by fyookball** [comment]
where do you see "Tor" option?

**Comment by patrikr** [comment]
Network dialog, Proxy tab. Seems to work now, guess 2.9.3 fixed it?

**Comment by fyookball** [comment]
I only see "use SSL" checkbox, nothing about Tor.  I guess you had to fill out a proxy to use it?

If its not a problem, i'll close it :) thx
