### ISSUE TITLE
bch balance disappeared 

### ISSUE THREAD

**Issue by JRYPZFQeqh** [fyookball/electrum#133]
i followed the instructions on electrum.org to claim a small amount of bch and i installed ElectronCash 2.9.2 in a windows VM.  i moved the funds from the btc wallet to a new one in Electrum (on macOS), got confirmation, then opened the (now empty) wallet in ElectronCash in the VM and the bch was there just fine.

2 days later i opened the same wallet in ElectronCash and this happened:

![screen shot 2017-08-19 at 09 24 24](https://user-images.githubusercontent.com/11840205/29488037-3b172bfe-84c0-11e7-829f-01d8a981aa74.png)

that 'unconfirmed' transaction is the amount i sent out from the wallet to the new wallet in Electrum before opening this wallet in ElectronCash.  the tx id is linked to the btc tx on the btc chain.  it looks like the balance is there (at bottom) but then trying to send a max transaction it says not enough funds.

what's the problem?

**Comment by Sejanus66** [comment]
I am also having the exact same problem.  I imported the wallet from Jaxx and it showed the balance but also shows an unconfirmed withdrawal of the entire amount.  

![screenshot 1](https://user-images.githubusercontent.com/8324126/29489585-3db3fcf2-84d9-11e7-9b1c-932a75457389.png)

**Comment by fyookball** [comment]
make sure youre connected to right server , click network button and make sure youre on the right chain.

**Comment by Sejanus66** [comment]
Thanks! It cleared itself up a couple of hours ago! Just put a good scare into me when I thought I might have been hacked! Thanks for getting back to me!

Ty Burgess
Tyburgess@gmail.com
(604) 720-7791
