### ISSUE TITLE
Address not reflecting total amount in Balance

### ISSUE THREAD

**Issue by dietereater** [fyookball/electrum#137]
Electron Cash v 2.9.2
Address show smaller amount than the balance. I did change from mBCC to BCC

I donated electroncash.bitcoinplug.com
Status: 274 confirmations
date: 2017-08-19 16:16
Amount sent: 0.0155402 BCC
Size: 225 bytes
Fee: 0.0002034 BCC
Outputs (2)
19dCtow3fWR2oBKtEq9DjGutkQJL8NAAou	     0.0155402 
1ALA4Mg4KA48YBR7ZJSTDzNFxw6bSs1rcy	     9.9842564 
Address amount it shows in Red as -10.
History amount shows in Red as -.0.0157436

I donated electron.coinucopia.io
Status: 225 confirmations
date: 2017-08-20 01:58
Amount sent: 0.0011655 BCC
Size: 226 bytes
Fee: 0.000339 BCC
Outputs (2)
1FKxpd4yshoEhFvnsq9QnaPSBr9UwBioBX	     0.0011655 
1NxbpEn3K9g4qdShMYucYLw2uQKqoHhPmK	     2.9984955
Address amount it shows in Red as -3.
History amount shows in Red as -.0.0015045

As you see I gave it a couple of days to propagate. What you suggest I do ?

**Comment by fyookball** [comment]
sounds like a server connection issue. try 2.9.3
