### ISSUE TITLE
BCC disappeared

### ISSUE THREAD

**Issue by droppss** [fyookball/electrum#14]
hey, a friend of mine sended me some BCC last night, when i opened wallet today, i saw the coins for like 2 secs and then they just got cleaned away, cant even see the history in my wallet anymore.. and here is the transaction link:  https://blockchair.com/bitcoin-cash/transaction/9725bef4b6c6d73826f9250fef400f86f8bca36232bdd01f6cf4355aef87bca2

**Comment by fyookball** [comment]
where it got sent to, is that one of your addresses? Are you sure you have the official electron and not some hoaxware?

**Comment by Otaci** [comment]
Have you checked that you are on the correct chain? See https://steemit.com/bitcoin/@electroncash/electron-cash-how-to-check-you-are-on-the-bitcoin-cash-chain

**Comment by danny91** [comment]
@fyookball You should be aware of this https://www.reddit.com/r/btc/comments/6r69x9/psa_electron_websites_multiple_are_fake/

Hopefully this isnt what droppss is having issues with.

**Comment by droppss** [comment]
its the correct Electron yes, and yes its the correct address, i had the coins for hours, but when i went to sleep and woke up, to log into my wallet i could see them for 2-3 secs then it just disappeared

**Comment by fyookball** [comment]
sounds like it might not be connected to the right server
