### ISSUE TITLE
Address Balance not reflecting total amount in Balance 

### ISSUE THREAD

**Issue by dietereater** [fyookball/electrum#140]
Electron Cash v 2.9.3
 Address show smaller amount than the balance. I did change from mBCC to BCC
Updated to v 2.9.3 same. No coins are missing as I can send them all.

I donated electroncash.bitcoinplug.com
 Status: 274 confirmations
 date: 2017-08-19 16:16
 Amount sent: 0.0155402 BCC
 Size: 225 bytes
 Fee: 0.0002034 BCC
 Outputs (2)
 19dCtow3fWR2oBKtEq9DjGutkQJL8NAAou 0.0155402
 1ALA4Mg4KA48YBR7ZJSTDzNFxw6bSs1rcy 9.9842564
 Address amount it shows in Red as -10.
 History amount shows in Red as -.0.0157436

I donated electron.coinucopia.io
 Status: 225 confirmations
 date: 2017-08-20 01:58
 Amount sent: 0.0011655 BCC
 Size: 226 bytes
 Fee: 0.000339 BCC
 Outputs (2)
 1FKxpd4yshoEhFvnsq9QnaPSBr9UwBioBX 0.0011655
 1NxbpEn3K9g4qdShMYucYLw2uQKqoHhPmK 2.9984955
 Address amount it shows in Red as -3.
 History amount shows in Red as -.0.0015045

As you see I gave it a couple of days to propagate. What you suggest I do ?

**Comment by fyookball** [comment]
can i see a screenshot? blur out addresses for privacy. not sure what u mean

**Comment by dietereater** [comment]
![electron cash](https://user-images.githubusercontent.com/30131809/29502786-e7bb9852-8675-11e7-9a30-2cd805ec5700.jpg)

**Comment by dietereater** [comment]
![electron cash_history](https://user-images.githubusercontent.com/30131809/29502856-75ac238e-8676-11e7-974e-41351f18b0d8.jpg)

**Comment by dietereater** [comment]
Should I send full amount to my 3rd address ?

**Comment by fyookball** [comment]
you sure you just dont have some money in change address or used address and thats why its not matching

**Comment by dietereater** [comment]
No imported from Bittrex and Coinspots and their balance shows 0

**Comment by dietereater** [comment]
Ok I send full amount to the 3rd address and now it all matching balances total up and the 2 previous address disappeared, So I never have a static $0 address.
