### ISSUE TITLE
Error. Transaction was rejected by network rules

### ISSUE THREAD

**Issue by BenBiCo** [fyookball/electrum#141]
Hi, anybody who can help with that??
see screenshot below... (I removed the docx file)...many thanks..

**Comment by omersiar** [comment]
One should never click that link!!!! Do not click attached .docx file above.

**Comment by BenBiCo** [comment]
@omersiar It`s a print of the error report. How else should I submit it??

**Comment by omersiar** [comment]
As plain text or screen shot, you can directly drag your images to github comment panel. DOCX can have malicious code, and not the best file type to exchange information other than the office users.

**Comment by BenBiCo** [comment]
![image](https://user-images.githubusercontent.com/31204157/29512686-33945358-8663-11e7-8e14-185949ef4520.png)

**Comment by BenBiCo** [comment]
@omersiar thx for the hint... hope this is done right now!?

**Comment by omersiar** [comment]
try version 2.9.3 , are you trying spend pre fork coins or after fork coins?

**Comment by BenBiCo** [comment]
@omersiar pre fork coins

**Comment by BenBiCo** [comment]
@omersiar just downloades 2.9.3 , the same error report.. any other ideas??

**Comment by fyookball** [comment]
all 2fa issues here please: #41
