### ISSUE TITLE
Android Crashes on Seed Restore

### ISSUE THREAD

**Issue by dmerkys** [fyookball/electrum#143]
Need change BCC to BCH, because BCC is used by BitConnect Coin.
I install electron android wallet 2.9.3. When I probe to recover wallet by seed i have crash and wallet closing. I use phone with Android 5.1.1. On Windows 10 recover by seed work perfect.

**Comment by quangld** [comment]
Confirmed! Electron Cash crashes on Android when trying to restore from seed (I already have a seed). It crashes on both Nexus 5 (Android 6.0.1) and Google Pixel XL (Android 7.1.2)

**Comment by SilverstrandBC** [comment]
now experiencing this problem too...  crashes when trying to restore from seed (I already have a seed)...  in addition to previous network 16 error

**Comment by fyookball** [comment]
i was able to recreate this on my new phone.  give me some time to look into it.  i have to root the phone in order to set up logcat

**Comment by fyookball** [comment]
found the problem.  i will fix it tonight.  i believe i broke it in the last release with the new coin type.  new parameters arent passed to the on_restore_seed from the android seed restore.

**Comment by fyookball** [comment]
This is now fixed and uploaded on electroncash.org as 2.9.3.1.apk.

The fix is commit 
e8116831d3dedaa7edab47981297ef304f32821f

2.9.3.1 also includes an additional fix for android
viewing of tx detail in commit  a312ca7af2e3cda652b313245c67cd1f69073b9c

**Comment by dmerkys** [comment]
Hi, now restore from seed work perfect. Thanks.
