### ISSUE TITLE
Unable to send - Transaction was rejected by network rules

### ISSUE THREAD

**Issue by erobinson-pb** [fyookball/electrum#144]
I tried to send from Electron Wallet and received this error.  This is the second time.  The first time, the transaction showed up as unconfirmed but reversed about 12 hours later.  This time it's been a couple of days and it's still 'unconfirmed' and unavailable to me.
Screenshots below:
https://i.imgur.com/pCVS5vU.png
https://i.imgur.com/WE0sx5H.png
Attempting to view the transaction on blockchair produces a 404 error.

I'm on 2.9.2 and am about to get 2.9.3.
These coins are pre-fork.  I was able to send them to electrum no hassle.  But i'm unable to send them out.

**Comment by erobinson-pb** [comment]
So I was reading about others who were having issues with sending on a 2fa enabled wallet... I decided to rebuild mine from seed and it's just finished... except it still shows '2fa' at the top despite me opting not to use 2fa.

https://i.imgur.com/O8DM8zL.png

**Comment by erobinson-pb** [comment]
Just tried 2.9.3 and looks exactly the same.  Going to try rebuild with seed now.

**Comment by molecular** [comment]
This keeps coming up (how to "remove 2fa"). I looked through reddit posts, but couldn't find any instructions on how to do this. I don't have any 2fa wallets myself, so I can't figure it out, either.

Anyone?

**Comment by erobinson-pb** [comment]
For a lot of users, the real issue is the fact that after this error, your cash is gone / unavailable / in limbo.  It's been more than three days now.

![image](https://user-images.githubusercontent.com/20299235/29569274-49618b2e-8753-11e7-915e-c6f0b47e7ae7.png)

**Comment by erobinson-pb** [comment]
So now it's magically reversed and the funds are 'available' except that I can't seem to create a non-2fa wallet before attempting to send cash :/
Any progress on that issue?

**Comment by fyookball** [comment]
In an effort to reduce the number of tickets, I kindly ask all 2fa issues be discussed here: #41
