### ISSUE TITLE
Transactions ID  63af804bf6f89df54d4d702948fb3ea6fb98d18962472da7437a33701d957296

### ISSUE THREAD

**Issue by Crash-030** [fyookball/electrum#145]
is not performed. Why?

**Comment by molecular** [comment]
Did you broadcast this transaction?

My abc node says:

```
~\> bitcoin-cli_abc.sh gettransaction 63af804bf6f89df54d4d702948fb3ea6fb98d18962472da7437a33701d957296
error code: -5
error message:
Invalid or non-wallet transaction id
```

**Comment by Crash-030** [comment]
Hallo,

ich wollte Bitcoin Cash auf Shafeshift wechseln. 
Seither steht die Transaktion wie laut Screenshot:



Ich bitte um ihre Hilfe um diese Transaktion abzubrechen oder durchzuführen.

Beste Grüße
Bernhard



Gesendet von Mail für Windows 10

Von: molecular
Gesendet: Dienstag, 22. August 2017 15:09
An: fyookball/electrum
Cc: Crash-030; Author
Betreff: Re: [fyookball/electrum] Transactions ID63af804bf6f89df54d4d702948fb3ea6fb98d18962472da7437a33701d957296 (#145)

Did you broadcast this transaction?
My abc node says:
~\> bitcoin-cli_abc.sh gettransaction 63af804bf6f89df54d4d702948fb3ea6fb98d18962472da7437a33701d957296
error code: -5
error message:
Invalid or non-wallet transaction id

**Comment by molecular** [comment]
Da musst du mit dem Shapeshift support reden, vermute ich.

Die sollen erklären, was mit tx 63af804bf6f89df54d4d702948fb3ea6fb98d18962472da7437a33701d957296 los ist?

Woher hast du denn diese TX id überhaupt?

**Comment by Crash-030** [comment]
Sieht man bei den transaktionsdetails.

Danke

Am 22.08.2017 3:45 Nachm. schrieb "molecular" <notifications@github.com>:

**Comment by fyookball** [comment]
@molecular can this be closed

**Comment by molecular** [comment]
@fyookball I think so, this seems to be a shapeshift support issue
