### ISSUE TITLE
Blockchain height falling behind

### ISSUE THREAD

**Issue by slanted3** [fyookball/electrum#146]
Edited.

Electron Cash version 2.9.3

Sometimes the wallet stops taking notifications. You can see it in the Tools/Network dialog, Overview tab. The blockchain height I am working with is lower than the numbers displayed after each server in the list of connected servers below.

I use Tor and automatic server selection. 

Closing Electron Cash and restarting fixes the problem. (Closing/opening a wallet is not enough).

I just saw that it is possible to manually select a (main) server from the list of connected servers by right-clicking. If this also mitigates the problem I will update here next time.

**Comment by molecular** [comment]
This is interesting. You wouldn't happen to be able to start electron-cash with the "-v" flag and capture the output when the falling back happens?

**Comment by slanted3** [comment]
Capture started, coming back with more info.

**Comment by slanted3** [comment]
Here is a screenshot I captured earlier. May be it has something to do with orphans.

http://tinypic.com/view.php?pic=10ogxmt&s=9

**Comment by molecular** [comment]
damnit, having trouble viewing your screenshots. A lot of ads popped up and now I can't view it any more. Can you try uploading here directly? (drag and drop works, also copy/paste of image data works)

**Comment by fyookball** [comment]
i reshotted it with imgur, much better than tinypic which has too many ads
http://i.imgur.com/oHAf7vA.png

**Comment by molecular** [comment]
just to preserve it here (copy-pasted the image):

![image](https://user-images.githubusercontent.com/589745/30001071-e61205ec-9082-11e7-9112-8a5ee823f48a.png)

**Comment by molecular** [comment]
it looks like you somehow got stuck on a very short branch (1 block long, or even 0).

You can switch to the longer one by right-clicking on "644e2d31f6@481946" and selecting "follow this branch" in the menu that pops up.

**Comment by slanted3** [comment]
I tried that, also closed one wallet (leaving another running), turned off tor proxy, everything, but the only remedy was to start electron cash over. One thing I didn't try was right click on the entity above the servers (branch) and "Follow this branch". Currently I have two branches, but the error has not reoccurred yet. 

A suspicion is many orphans happening in the frenetic hashing time when the difficulty was at the lowest.

**Comment by fyookball** [comment]
is it still a problem?

**Comment by slanted3** [comment]
I haven't seen more of it. You can probably close the issue.

**Comment by slanted3** [comment]
![image](https://user-images.githubusercontent.com/89167/30441492-e6e6fe96-9979-11e7-9804-947817144e83.png)

Got another just now. Sorry I don't have a log on.

**Comment by fyookball** [comment]
yeah i think that is just some weird server that is not up to date.  shouldnt be BTC though

**Comment by kyuupichan** [comment]
It is BTC - look at the fork height.  I suggest OP shuts electron cash, removes the "recent-servers" and "recent_servers" files if they exist, and restarts.  Make sure you're running the most recent code.

**Comment by slanted3** [comment]
I didn't think of that. I had recent-servers, renamed it before restart. I suspect it will solve the problem (for me).

**Comment by molecular** [comment]
@kyuupichan just as a side-note: this is probably a case where the auto-switch feature would've helped. Not voting for putting it in, though.
