### ISSUE TITLE
Both 2.9.0 and 2.9.3 Show vastly inflated balances.

### ISSUE THREAD

**Issue by Drac42** [fyookball/electrum#147]
eg.  My current balance is 3.003477 BitCoin Cash.  The Balance in CAD $15,532.58
While I wish the cash balance were right, unfortunatly only the 3.003477 is correct.  This error also affects the miner fees.   Even with the slider all the way to the max, the real amount of money sent is so tiny that all of my TX's get crippled with "Low Fee". I currently have one incoming for over 2 BCH pending for 3 hours now.  Any advice would be much appreciated.

**Comment by quangld** [comment]
1. Fiat Balance will never be accurate! It's just there as a reference (ElectronCash may use a different exchange than yours, so the rate will be different)
2. Confirmation is based on blocks not time, you have to check to see how many blocks has been generated since you sent your transaction not how long it had been sent

**Comment by fyookball** [comment]
@Drac42 you can manually set fee but i think slow confirmation is because of current dificulty

**Comment by Drac42** [comment]
Gee, no thanks for the script kiddie response.  I'll put it another way.
Your wallet is shit.  The fucking balance is not off by a little bit due to
some different exchange rate.  It is over 3 times what is actually in
there.  If I had $333,000.00 in there, it would say that I have a million
dollars.  That is not a slightly different rate.  If you had bothered to
read the god dammed complaint you would have known that I was trying to
help you fix a horrible, unacceptable problem with your product.  As you
obviously do not give a shit, I will just withdraw all of my funds
permanently from your worthless, poorly coded, and can't be bothered to fix
problems wallet.  I will also not ever pass by the chance to tell anyone
and everyone I ever meet about how totally shitty your response was.  In
case you did not think you were one of those people/companies that shit on
people who use your crap, well guess what... you have been fooling
yourself.  That is exactly who you are.

**Comment by fyookball** [comment]
I provide this wallet free of charge.   If it is not to your liking,  please use another wallet.  Goodbye.

**Comment by Drac42** [comment]
I only left you that last reply in the hopes that it would get you off of your ass to fix a major problem, since you did not bother to actually read the first, polite inquiry.  I was hoping to shame you into taking responsibility for causing probably many people confusion, fear, and loss of money.  I see that I have just wasted my time, and you are just one of those many people who fool the even less informed, into thinking that you are a programmer.  I say it again  (look it up)... you are a script kiddie.  No real programmer would defend bad code.

**Comment by fyookball** [comment]
Chris Pacia has an SPV Bitcoin Cash wallet.  Perhaps you will like that one better.  
https://github.com/cpacia/BitcoinCash-Wallet
