### ISSUE TITLE
Fiat conversion issue

### ISSUE THREAD

**Issue by Drac42** [fyookball/electrum#148]
Thank you, but I've already got one....
You really, really just do not get it.  I'll spell it out carefully this time, to make sure you understand.
From original message: " My current balance is 3.003477 BitCoin Cash.  The Balance in CAD $15,532.58"
Around 3 BCH does not equal even close to Fifteen thousand dollars CAD.  It is only around $2496.00
That is a difference of $15,532 - $2496 which equals $13,113.  In USD that would be a $10,438 difference.  Now, having cleared that up, if you still think that the price difference is just some trivial amount, not importaint enough for you to bother with, then please let me know immediately.  I have some hungry feral cats that you could donate the difference to.  I'll send you my BTC receive address, and my humblest appologies for having offended you.

**Comment by fyookball** [comment]
Thanks for reporting it.  We'll investigate.  I'm not offended.  Just doing my best to provide a service. thanks.

**Comment by HibGut** [comment]
I have seen similar outrageous values in the old Electrum. I believe it has to do with the conversion rate being pulled from, I think it was  LocalBitcoins, which sometimes has outrageous rates. In later versions, you can change the data source now at Settings > Fiat > Source. Have you tried that?

**Comment by Drac42** [comment]
I'm afraid in this release that option is not available.  In
 -Preferences/Fiat: The "Fiat currency" drop down was blank.  I could not
do anything with it except choose the only option, "None".  Choosing this
option did nothing, and is not reversible. The "Show History Rates"
checkbox is checked and greyed out.  Also not changeable. The "Source" drop
down box is greyed out and blank.  It also is not changeable.  As there are
no other options available under "Fiat" I'm afraid this is a dead end.. Are
there any console commands that may be used to alter the Fiat Source? Or
activate the greyed out Fiat options?  How about a debug mode?  In Exodus I
found a code problem that way.  The silly thing kept showing balances in
all the wallets.  Even when they were all empty. It also refused to
complete any transactions. In debug mode it was filled with
*"ECONNRESET" * errors.
Some code was no longer valid, and no one at Exodus support knew what to do
about it. A newer version of the wallet seems to have the problem fixed,
although there is no mention of it in their changelog.

**Comment by HibGut** [comment]
I'm not the developer, so can only guess. I assume that, when Electron Cash was first launched around the time of the split, there were no good sources for BCC rates available yet. Obviously couldn't use what was in there before, otherwise it'd show BTC rates, so it got taken out and appears blank or grayed out. 

Now that there are some data sources, their API has to be integrated first or at least the calls need to be adjusted to point at BCC, not BTC. And showing fiat currency values in the app is probably not top priority. But I'm sure it'll get fixed soon.

**Comment by verretor** [comment]
I think it has to do with this commit [https://github.com/fyookball/electrum/commit/cd6435c73a50478e3463df730a25f9d2c2a3b5a4](https://github.com/fyookball/electrum/commit/cd6435c73a50478e3463df730a25f9d2c2a3b5a4).

lib/currencies.json and lib/exchange_rate.py only have EUR and USD. It also only takes the price from Kraken which has BCH/USD, BCH/EUR and BCH/XBT. I think the only way for the moment to solve this would be to to BCH/USD from Kraken and USD/CAD from somewhere else (like Yahoo maybe).

**Comment by fyookball** [comment]
Just getting around to this issue... Sorry I don't see CAD as a choice.  I see USD and EUR from Krakken, both appear correct
