### ISSUE TITLE
New Electron Cash update does not import my BCC from Private Seed

### ISSUE THREAD

**Issue by RIPAC** [fyookball/electrum#151]
I have been trying for weeks, spending hours on end trying to get my BCC to no avail. My origional problam had to do with how I set up 2FA. 

Bitcoin Cash suggests to use this wallet, but does so in a way without verification themselves. 

I was excited to see new version of Electon Cash available but when I entered my seed, my new wallet shows a zero balance on my Windows computer. On my mac it shows the full balance though which is interesting. 

I have my Private key, hundreds of numbers. I have my wallet address where it's stored. I have my seed info. What can I do to get my new wallet to work. Sweep function does not let me do anything when I enter my private key, the button does not highlight. 

I copy my private key from export and put it right into the private key sweep on the new non-2fa wallet and again, the sweep doesn't work. Can we get a new 2.9.4 where this works? It will solve my problem and probably for thousands of others.

All other wallets will not work, I can't try Coinomi because I don't have android. BitcoinABC and Bitcoinunlimited along with BXT require these full node downloads that I can't do on my laptop. 

Are there any other solutions short of paying a hacker to hack your program? I'm out of ideas. I have tried everything. CVC files and Json files do nothing, or I don't know how to use them. 

Any ideas?

**Comment by fyookball** [comment]
see #41
