### ISSUE TITLE
Lost bitcoins from bitcoin core after sweep in Electron cash

### ISSUE THREAD

**Issue by pako8007** [fyookball/electrum#152]
Hi, i tried to claim BCH via Electron cash but didnt moved my bitcoins from bitcoin-core wallet to a new one.
After typing the private key and sweep , i received part of BCH (not all) and i can see it in the http://blockdozer.com but they are not in my electron cash wallet... And worse part is that all my BTC left my wallet to another wallet(unknown for me).... Is there any possibility to have them in another wallet, or what happens with them??
Thanks for the help

**Comment by fyookball** [comment]
not sure what you mean you received it but you dont see it in the wallet?

I don't see how Electron Cash is possibly effecting your BTC.  All transactions including the sweeping transaction use the new BCH tx format.   gui/qt/main_window.py sweep_key_dialog calls wallet.sweep which calls transaction.sign which should be serializing the preimage.  Even if that didn't happen it would just send them to the same address in BTC.

I will test it.

**Comment by fyookball** [comment]
Tested and sweep for me produces BCH tx not BTC.

**Comment by pako8007** [comment]
Ok i will explain step by step what i did in order to claim bch using private key from my bitcoin wallet 
  1. i installed electron cash, then
  2. i went to my bitcoin-qt wallet and i dumped a privatekey for my bitcoin wallet, (i forgot to sent my BTC away to another wallet, because somebody called me i was distracted and thought i did it).
3. i went to electron cash>wallet>privatekeys>sweep ........... and entered my private key..  4. then i noticed some bch showed on and waited to be confirmed...
  
  I did this step 3 times and every time some more bch came.. but still not what i had to have  at the last time it said that there is no more for this wallet (or something similar), then i went to my bitcoin wallet that is on the same machine and i saw that 4 transactions has been made and my bitcoin-core wallet was empty...  I can show you the transactions and the missing BCH 
and BTC  the last transaction of BCH that is the biggest is not sent to my electron cash wallet, it is send somewhere else(it is written in the blockchain... and i have no idea where the BTC are sent...
  I think somebody dumped my BTC wallet, using the private key, or BTC are sent somewere else....  
  so i have two issues here - 1. Not all BCH were credited to my electron cash; 2 - My BTC are missing from my bitcoin core wallet  
  If you can help me with this issue i will send you a reward....  
  thanks  





 >-------- Оригинално писмо --------

 >От: fyookball notifications@github.com

 >Относно: Re: [fyookball/electrum] Lost bitcoins from bitcoin core after sweep
 in Electron cash (#152)

 >До: fyookball/electrum  

 >Изпратено на: 29.08.2017 05:26



 
 
  
not sure what you mean you received it but you dont see it in the wallet?  
  
I don't see how Electron Cash is possibly effecting your BTC. All transactions including the sweeping transaction use the new BCH tx format. gui/qt/main_window.py sweep_key_dialog calls wallet.sweep which calls transaction.sign which should be serializing the preimage. Even if that didn't happen it would just send them to the same address in BTC.  
  
I will test it.

**Comment by ajonl** [comment]
Please Help.
I had bitcoin in Airbitz wallet before the Split in August to allow me to get the Bitcoin Cash.
I used the Airbitz recovery tool and Electron Cash Wallet and by accident swept it to my wallet address is Electron Cash. Its the correct address but its intended for BCC while the blockchain transferred BCH. My Electron Cash wallet isn't showing the 3 BCH that should have transferred or any BCC . Is there any way to help this?
