### ISSUE TITLE
Invalid status 6a80 when trying to generate a transaction

### ISSUE THREAD

**Issue by SteffenIvanhoe** [fyookball/electrum#155]
`Invalid status 6a80 when trying to generate a transaction` is what I get after signing a message on the ledger device.

**Comment by SteffenIvanhoe** [comment]
As a note: all these things work without a flaw on the Electrum wallet for Bitcoin.

**Comment by fyookball** [comment]
i dont think we support ledger because they havent updated their firmware to sign BCH tx

**Comment by SteffenIvanhoe** [comment]
Ledger has updated the firmware. They have developed a special firmware app BCH to sign BCH transactions. It works with their Chrome app. I have used this BCH app to sign the Electron transaction. This leads to the above error message. Probably some small incompatibility. It would be extremely helpful to solve this because it is the only way to spend BCH without arbitrarily mixing addresses (as the Chrome app does).
