### ISSUE TITLE
Swept private keys to claim bitcoincash, but clicked close instead of broadcast - my bitcoincash went to a different address

### ISSUE THREAD

**Issue by bdlflt** [fyookball/electrum#156]
Hello,

I used Electron Cash to claim my bitcoincash from my blockchain.info wallet address - 1MWBFVgv9Nk4ey4sR29QqyoAtBEa83x82i

I got my private key and went to Wallet -> Private Keys -> Sweep, entered the private key, and it showed me a screen much like this one (this is from an online forum, I did not take screenshots):
![image](https://user-images.githubusercontent.com/31425401/29799878-a686f416-8c1b-11e7-80c2-0e05826c3e13.png)

It was supposed to sweep my bitcoincash into this address - 1HwExPbXsCWAWbRqg7FpUjEnQk78s9rEkA

HOWEVER, **_I accidentally clicked Close instead of Broadcast_**. It appears this means my ~1 bitcoincash token didn't go to 1HwExPbXsCWAWbRqg7FpUjEnQk78s9rEkA, but instead went to 1BF6saPUmU45psmQFodTGnUEfJG2F7gBSo

You can see the inputs/outputs for that address here:
https://blockchair.com/bitcoin-cash/address/1BF6saPUmU45psmQFodTGnUEfJG2F7gBSo

When I sweep for my private key now (and immediately right after), it tells me No Inputs Found.

I believe that clicking "Close" shouldn't send the Bitcoincash to a random address, so any idea what happened here? Any way to get my bitcoincash back? Thanks

*edit - a word

**Comment by fyookball** [comment]
Close should do nothing

**Comment by bdlflt** [comment]
I agree - I would expect nothing to happen, but it looks like it sent my tokens to that other address. Has this happened to anyone else?

Thanks!

**Comment by fyookball** [comment]
no i havent heard of anything like that. do you own that address

**Comment by bdlflt** [comment]
Which address?

I own 1MWBFVgv9Nk4ey4sR29QqyoAtBEa83x82i and 1HwExPbXsCWAWbRqg7FpUjEnQk78s9rEkA but do not own 1BF6saPUmU45psmQFodTGnUEfJG2F7gBSo (where the bitcoincash went). 

Also, the address I don't own, 1BF6saPUmU45psmQFodTGnUEfJG2F7gBSo, received another ~6 bitcoincash earlier the same day (which it is has now spent). My ~1 bitcoincash has not been spent, so maybe they don't know they have it (if it's not a human-monitored address perhaps, I have no idea).

Thanks for the quick replies! If it's gone, it's gone, but it was strange that it happened.

**Comment by fyookball** [comment]
are you sure its not a change address or used address in your wallet?

According to electrum documentation:

 Sweeping private keys means to send all the bitcoins they control to an existing address in your wallet. The private keys you sweep do not become a part of your wallet. Instead, all the bitcoins they control are sent to an address that has been deterministically generated from your wallet seed.

**Comment by fyookball** [comment]
I tested and pressing "close" doesnt appear to do anything.

**Comment by verretor** [comment]
Could you please look at the folder gui/qt inside your ElectronCash directory? Is there a file called "main_window-mod.py"? If it does, you don't have the real ElectronCash wallet.

**Comment by verretor** [comment]
If you look closely, on the $BCH blockchain, 1BF6saPUmU45psmQFodTGnUEfJG2F7gBSo received coins from:
1MWBFVgv9Nk4ey4sR29QqyoAtBEa83x82i and 1EsLeGPWdXrWj3cXbzHruVpoax5AMd9CFo.

At the same time on the $BTC blockchain, 16KZ5b4KxPRuDT99P2vwL71MCHrJfSkyx1 received coins from:
1MWBFVgv9Nk4ey4sR29QqyoAtBEa83x82i and 1EsLeGPWdXrWj3cXbzHruVpoax5AMd9CFo.
