### ISSUE TITLE
Trusted Coin wizard stuck when restoring 2FA wallet from seed

### ISSUE THREAD

**Issue by harryscholes** [fyookball/electrum#157]
I am trying to disable 2FA on my wallet by following some instructions that I have found [here](https://bitcoin.stackexchange.com/questions/58261/my-bitcoin-cash-is-stuck-unconfirmed-when-sending-to-bittrex-from-electron-cash), so that I can send some BCH. When I choose `New/Restore > Wallet with two-factor authentication > I already have a seed`, the wizard hangs on a screen showing the Trusted Coin logo with a message saying `Please wait...`.

**Comment by fyookball** [comment]
go here: #41

**Comment by harryscholes** [comment]
My issue is **not** resolved by #41, but I have continued discussion there to keep all 2FA-related issues in one place.
