### ISSUE TITLE
Signature must use SIGHASH_FORKID - Mac Error

### ISSUE THREAD

**Issue by polishlove** [fyookball/electrum#160]
I can't send any bch due to 2fa being enabled. I have all the credentials except the seed. I never got a seed because you imported all my stuff from electrum wallet that i havn't used in a year but still resided in my computer.

The wallet shows my BCH balance that I imported from my paper wallet after I transferred my bitcoin to another wallet but I can't send any of my BCH due to this error.  I've tried multiple servers as well. Please Help!!

This is the error:

error: The transaction was rejected by network rules.  (16: mandatory-script-verify-flag-failed (Signature must use SIGHASH_FORKID))
[010000000109d415d26f16cea84a79af9557917636968db4f011c66b373763f9f42b133e4700000000fdfd00004830450221009ec6b5c15081555ffc1c33e02f8e907904ed6263e35567ca632202e62368

**Comment by fyookball** [comment]
#41 please for all 2fa.
