### ISSUE TITLE
No seed in Electron Cash 2FA wallet

### ISSUE THREAD

**Issue by jeaneldahdah** [fyookball/electrum#163]
Read the work around to disable 2FA in order to transact BCH.
It requires the seed of the current 2FA wallet.
Seed button of the Electron Cash 2FA wallet (version 2.9.2) is greyed out.
![screen shot 2017-09-01 at 7 40 17 am](https://user-images.githubusercontent.com/24587794/29984242-16b4d05c-8f62-11e7-9698-dd7e40d45b10.jpg)
How can I restore the 2FA wallet into a standard one?
Any help would be greatly appreciated.

**Comment by fyookball** [comment]
did you read the #41 instructions to recover your coins?  Once you recover the coins, set up a non 2fa wallet

**Comment by jeaneldahdah** [comment]
Hello.


Sorry for the late reply, I had some things going on with me and didn’t have the time…

Before closing the issue you said "did you read the #41 <https://github.com/fyookball/electrum/issues/41> instructions to recover your coins? Once you recover the coins, set up a non 2fa wallet”.
I’m not sure what you meant with “Once you recover the coins”…
My problem is that I can’t restore from seed because I can’t access it (the pic is in the  issue #163 post).
Besides I already tried restoring from the private key into a non-2fa wallet, and got nothing. (guess it is because the public addresses of the 2fa wallet are starting with 3, while those of the non-2fa wallet start with 1)
Please, I’d really appreciate if you follow up with me and would be more than happy to cover any fee you require (from the 1.003 BitCoin Cash we are trying to save. i.e. help me regain full control over it and the fee would be from this BitCoin Cash currency itself).

I thank you in advance waiting your reply,
Regards
—
Jean El Dahdah

**Comment by quintela78** [comment]
Hello,

Were you able to recover BCCs? Maybe I can help you. Call on leonardquintela@gmail.com
