### ISSUE TITLE
Lost Bitcoin after sweep to Electron Cash Wallet from Airbitz

### ISSUE THREAD

**Issue by ajonl** [fyookball/electrum#164]
Please Help.
I had bitcoin in Airbitz wallet before the Split in August to allow me to get the Bitcoin Cash.
I used the Airbitz recovery tool and Electron Cash Wallet and by accident swept it to my wallet address is Electron Cash. Its the correct address but its intended for BCC while the blockchain transferred BCH. My Electron Cash wallet isn't showing the 3 BCH or any BCC . Is there any way to help this?

**Comment by fyookball** [comment]
I need more info.  You swept using what tool ? Airbitz? or EC?

**Comment by ajonl** [comment]
Thank you so much. I followed these instructions: https://medium.com/airbitz/how-do-i-get-my-bitcoin-cash-from-airbitz-e97982e3fc4c

I then downloaded the Electron Cash wallet.  I got to set IV-4 and to get the BCC into the Electron Cash Wallet. It wasn't working. So I took the Receive Address from the Electron Cash Wallet and put it here: https://airbitz.co/recovery/   I then pressed sweep and it went through.    this shows that it went through https://blockchain.info/address/1AKX2RFKeCJDPCkFDCJfuG5hGFeRBFgErP   BUT now the Electron Cash wallet doesn't show any deposit.   I realized I was likely sending BCH to the Electron Cash wallet which was supposed to accept BCC.   Is there any way to get the BCH that  went to that wallet? or is it lost?

**Comment by fyookball** [comment]
Run an Electrum wallet with the same seed as your Electron Cash wallet , try that

**Comment by ajonl** [comment]
Please help me understand. I don't have any BCC or BCH in the Electron Cash Wallet at this time. 
It seems like the blockchain.info indicated it made to that wallet. 

I guess I could download and run the Electrum Wallet but what seed are you mentioning? Is this the 12 word key that helped set up that wallet? 
![image](https://user-images.githubusercontent.com/31577401/30025877-88c3a276-9148-11e7-8a9d-2719cda23fcf.png)

I assume the Electrum wallet is different than the Electron Cash Wallet.  Is there hope here that the BCC and BCH can be found?  Thank you so much. If you can help me, I'd be happy to reward you for your help.

**Comment by ajonl** [comment]
OK I setup and downloaded the Electrum wallet. I setup the account with the seed from Electron Cash Wallet. Here is the current screen. When I imported the seed from Electron Cash, It pulled in the address that the BCH was sent to. This looks good but nothing is in the account and when I try and load the transaction ID: 
a8c637c1ec085c0b28845652158f96498c9895a464ffd54257bef509a9299b1b

It says :{u'message': u"daemon error: {'message': 'No such mempool or blockchain transaction. Use gettransaction for wallet transactions.', 'code': -5}", u'code': -1}



<img width="952" alt="screen shot 2017-09-04 at 9 48 44 am" src="https://user-images.githubusercontent.com/31577401/30029663-1b4f63fa-9158-11e7-90b4-b6bcf1e6f653.png">

**Comment by ajonl** [comment]
We got the BCH to transfer using Electrum but we still don't have the BCC.

Its still pending in the Electron Cash Wallet. Any ideas.

**Comment by fyookball** [comment]
im really confused, can we can on IRC later today  so i can try to help

**Comment by ajonl** [comment]
Sure what is IRC?

**Comment by fyookball** [comment]
sorry i cant teach you irc. 

but i re-read what you wrote.

sounds like you didnt follow instructions correctly and instead of using electroncash sweep, you sweeped your bitcoins to some other address using airbitz.  You should create an electrum wallet using the same seed as your electron cash wallet and see if your BTC are there... however if you did do that by mistake, i dont know where you private keys are for the bitcoin cash since airbitz controlled them prior to sweeping. might want to contact them.

**Comment by ajonl** [comment]
I did get the BCH by using the Electrum wallet and was able to transfer it to Bittrex thankfully. It worked when I set the network to autoconnect and then loaded the transaction ID it found it and funded the wallet there. I then sent those bitcoin to Bittrex. 

Now I'm trying to see if I could get the BCC that to show up in the Electron Cash Wallet.
We were in contact with Airbitz and then suggested we try again using the Electron BCC wallet to see if we could get the BCC which should have been transferred there to show up. I did this again using the same Private key and the sweep function in Electron Cash Wallet. But nothing is showing up in the wallet there. 

Also when I search for the transaction ID, it gives me errors.

**Comment by fyookball** [comment]
BCH and BCC are the same thing...

**Comment by ajonl** [comment]
Sorry i meant I received the Bitcoin and was able to transfer it a Bittrex wallet using Electrum.

But I'd still trying to get the Bitcoin Cash and I followed the instructions of Airbitz and the Electron Cash wallet still doesn't show any holdings. Its still pending and when I tr to search for the transaction ID, it gives me an error. 
Any suggestions? and thanks so much for you help.

**Comment by fyookball** [comment]
yes but if you sweeped from Airbitz to Electrum, that means the pre-fork private keys (where your Bitcoin Cash was) is the private keys controlled by Airtbitz.  It sounds like what you should have done was sweep it using Electron Cash as the article said...but you didnt do that , and instead what you did was move those Bitcoins using Airbitz sweep.  But the point is , you moved the Bitcoins from their original pre-fork address.  right?

**Comment by ajonl** [comment]
I initially swept incorrectly to ELECTRON CASH wallet address and nothing transferred despite the BLockchain showing it went to that address.

When I installed Electrum and imported the seed, it did find the bitcoin and deposited in Electrum which I then transferred to Bittrex ( YEAH)

Now Airbitz told us the following:  
We tried this but still can't see the Bitcoin cash in Electron Cash wallet .
Thanks!!


 SEE BELOW: 

**### **_The instructions to get the Bitcoin Cash did not specify to hit the "Sweep" button at the Recovery Tool airbitz.co/recovery. Doing so resulted in transferring the BTC into a BCH address where it will show as invisible.

As you can see here: https://blockchain.info/address/1AKX2RFKeCJDPCkFDCJfuG5hGFeRBFgErP your BTC's are safely in that address that comes from your Electron Cash.

The Bitcoin Cash are likely still on your Airbitz account but also invisible because it does not support it. Here are the instructions to resolve this as quickly as possible.

1) Download and install Electrum https://electrum.org/ - This is similar to Electron Cash but for BTC
2) Setup your Electrum Wallet
3) Go back into your Electron Cash and get the SEED
4) Go into Electrum and recover your bitcoins by entering the SEED from Electron Cash

You will now have successfully transferred the BTC on Electron Cash and into Electrum.

Next if you still want the BCH to appear on Electron Cash follow these steps:

1) Do as you've done before and enter the Airbitz Private Seed at airbitz.co/recovery/
2) Look for the address that you know that has BCH and retrieve the Private Key
3) DO NOT HIT SWEEP on the recovery page
4) Instead go on Electron Cash and go to import to ENTER the Private Key Text 1 by 1 to transfer the BCH from Airbitz to Electron Cash

After doing these steps, you will now have the BCH inside your Electron Cash.

Let me know if you have any other questions!

Ticket: https://airbitz.freshdesk.com/helpdesk/tickets/7831_****

**Comment by ajonl** [comment]
I tried the advice of Airbitz but still can't get the BCH (bitcoin cash) to show up in the Electron Cash wallet.   Also I can't get the transaction ID to work which would search for and likely put the BCH in that wallet address.

**Comment by fyookball** [comment]
They are correct in that you didn't follow the instructions.

I took a look at the address you pasted, there is no address in Bitcoin Cash... BUT...
I went back and back and back, seeing where those coins came from as they were sent
from the blockchain.. i went back about 5 or 6 transactions and I think I found the address
where your Bitcoin Cash lives.  You will need to get the private key for this address from Airbitz if you don't have it.  Once you have it, you should import it into Electron Cash and make sure you see the balance. 

https://blockchair.com/bitcoin-cash/address/1BD5Ae7fNVWtK78AxstNSgjs55MQUEihxd

By the way, once you do that, then send it to a native address of the wallet so you can restore with seed.

**Comment by ajonl** [comment]
Fyookball. We DID IT!!!! we got the Bitcoin and the Bitcoin Cash. Thanks so much for your help. I learned alot in this exercise. Best wishes to you.  Adam

**Comment by fyookball** [comment]
YAY!!! :)
