### ISSUE TITLE
Electron Cash won't let me send my entire balance

### ISSUE THREAD

**Issue by Polyergic** [fyookball/electrum#165]
I opened my original Electrum wallet in Electron Cash, and tried to send all of my BCH to a new wallet without any BTC history.  I just hit "max" and didn't look too closely at the amounts, and 0.00001214 BCH was left behind.

I tried to send the remaining 0.00001214 BCH and got a message that made me think I shouldn't try to send such a small amount, so I transferred a little bit back so I could re-transfer a reasonable amount to my new BCH wallet.

Now I have 0.00149077 BCH in my old wallet and am trying to send it to my new wallet, but the most it will let me send is 0.00145677 BCH.  If I send this transaction I'll end up with 0.00003400 left behind.  I'm not concerned about the amount of money lost, I'm concerned about using a system that requires losing money.

**Comment by fyookball** [comment]
which version?  usually the left over is the fee

**Comment by Polyergic** [comment]
Version 2.9.3.  I didn't generate the block, the fee shouldn't stay behind in my wallet.

**Comment by fyookball** [comment]
As you play with the fee slider, do the amounts add up (fee + max) to your total wallet balnace?

**Comment by fyookball** [comment]
also are you doing this when all the inputs are confirmed or theres still unconfirmed

**Comment by Polyergic** [comment]
They do not add up to my wallet balance, there is a difference of 0.00003400

**Comment by Polyergic** [comment]
The first time, when leaving money behind actually happened, all inputs had been confirmed for more than a month.  When trying again it had only been hours, but was after the new input transaction had a checkmark.

**Comment by Polyergic** [comment]
Trying again now the difference has changed to 0.00001214, the same that was left behind by the transaction that actually went through.

**Comment by fyookball** [comment]
unfortunately i cannot seem to recreate this on my end at the moment.

**Comment by Polyergic** [comment]
So basically if I use your app I will lose money, and if the community uses your app the bitcoin cash ecosystem will leak until no money can be spent, and you're just going to leave it that way?

**Comment by Polyergic** [comment]
Trying again now, it said I could send 0.00145677 + 0.00003400 fee = 0.00149077 (my balance), so I thought whatever had made it change earlier made it change again and fixed the problem (for the moment), and I sent the transaction.

Now my ledger again shows a balance of 0.00001214

https://blockchair.com/bitcoin-cash/transaction/8ec6849a58fd6082334e4a0abc66fd255c1c1ac5bb1b39f0adc608349f4616c4

**Comment by fyookball** [comment]
so you are saying that it looks like it totals correclty but when you actually send it leaves dust behind?

**Comment by Polyergic** [comment]
No, it's not consistent; I've seen at least 3 different totals for different attempts to generate the same transaction.  This last time was the only time it showed the correct total, so I went ahead with the transaction, and it left dust behind.

**Comment by fyookball** [comment]
i wonder if its somehow using dynamic fees even though we removed them in 2.9.3.   Can you check  your config file (it is one directory up from your wallets folder) and see if there's anything in there about dynamic fee?

**Comment by Polyergic** [comment]
Output from `grep -i dynamic .electron-cash/config` is empty

**Comment by Polyergic** [comment]
Output from `grep -i fee .electron-cash/config` has 2 lines:

```
    "fee_per_kb": 10000, 
    "show_fee": true, 
```

**Comment by fyookball** [comment]
ok so its not that.  so currently are you able to recreate the problem before sending?

**Comment by Polyergic** [comment]
No, with only 0.00001214 in my wallet the max button is greyed out.  If I enter 0.00001214 in the send amount it says "Not enough funds"; if I reduce it to 0.00001213 the error goes away; if I set the fee to 0.00000002 the error should reappear but doesn't.

**Comment by fyookball** [comment]
if you can recreate it again, perhaps you can contact me privately on reddit and send me your pubkey so i can try to reproduce.  Also you should try on electrum with same settings to see what happens.

**Comment by Polyergic** [comment]
This is the same wallet I originally used in Electrum, which I'm transferring everything out of in an attempt to get a clean separation between my BTC and BCH.  Sending the BTC from Electrum worked correctly on the first attempt.

In order to recreate it again I'd have to transfer more money back into this wallet, and pay fees of a few times the dust for a third time.  I don't see how that could be worth it until after the bug is fixed.

It looks like Electron Cash created a new address for the 0.00001214 as part of the original transaction, as I'd expect for transaction that left nonzero change.  So it looks like the origin of the problem was that it didn't generate the transaction I requested.  https://blockchair.com/bitcoin-cash/address/1HjUNSJZuypwJ46FUHE1xtYjqT3prsDcop

**Comment by molecular** [comment]
Interesting bug. 
We should work on trying to reproduce it.
I also wonder wether this is somehow ledger-specific...

**Comment by molecular** [comment]
I'm looking at the address @Polyergic provided and this tx: https://blockchair.com/bitcoin-cash/transaction/243875245#o=0

That tx uses one unspent output with 0.00150489 BCC in it, so I made a tx that produces such an output and tried to spend that using electron. That worked without creating dust in a change address (tried different fee levels using the ruler)

The fee on the @Polyergic tx was 0.00002260 BCC, so I wanted to try paying that fee, but it wasn't possible to select exaclty that fee using the fee ruler, so I entered it manually. Previewing the tx revealed that it was correctly paying the fee, spending the whole balance and creating no unwanted change outputs with any dust.

My suspicion that this might be ledger-related is reinforced and I'll try to reproduce this again when I try to tackle the other ledger-related problems under the condition I have a functional ledger device (hoping btcchip has sent me a device, will check when back from vacation)

**Comment by fyookball** [comment]
@Polyergic this was ledger?

**Comment by Polyergic** [comment]
Not as in https://www.ledgerwallet.com/; when I said "ledger" I meant it in the common sense of a list of transactions - specifically, the one that that appears in the "History" tab of the app.

**Comment by molecular** [comment]
oh, sorry @Polyergic, I misinterpreted about this being ledger.
