### ISSUE TITLE
transaction reject error

### ISSUE THREAD

**Issue by wefdi** [fyookball/electrum#167]
![1](https://user-images.githubusercontent.com/31162030/30488241-bef9529c-9a70-11e7-8785-c64cb77dc420.png)

my electon bcc wallet.
I tried transfer to other address, but it doesn't with that message.

![2](https://user-images.githubusercontent.com/31162030/30488314-ec00bf28-9a70-11e7-8f6f-f4d5cae62ff8.png)

this is my balance

![3](https://user-images.githubusercontent.com/31162030/30488319-f0709038-9a70-11e7-937b-ab78661c9302.png)

so I make a new wallet with my private key, as you can see balance '0'
same public key, but old one has 24bcc, new one no balance... 
how can I solve it??

**Comment by fyookball** [comment]
We don't support 2fa but there are good workarounds to access your coins here: #41

**Comment by wefdi** [comment]
but I can't made a new wallet with seed. becuz it is unlimitied loading. 

and private key use, '0' balance

**Comment by fyookball** [comment]
Please post your question here: #41
