### ISSUE TITLE
bcc transaction is rejected from electroncash wallet in MAC

### ISSUE THREAD

**Issue by watertech666** [fyookball/electrum#168]
I meet problem with electron
<img width="795" alt="electroncash wallet" src="https://user-images.githubusercontent.com/6701783/30519435-e0d49936-9bc8-11e7-9306-b7c0b52d7184.png">
cash wallet. It's two-factor authentication wallet. When I sent bcc. It showed "error: The transaction was rejected by network rules. (16: mandatory-script-verify-flag-failed (Signature must use SIGHASH_FORKID)) [0100000001ee8e33f331d2ac4e3858bb6ab081355c5cb4d6ae30e74282fd491c7eb93ddcbf00000000fc00473044". Please help to fix it.

**Comment by fyookball** [comment]
we don't support 2fa.  Please find the workaround here #41

**Comment by quintela78** [comment]
Did you solve the issue? If not, call leonardquintela@gmail.com Maybe I can help you. I rarely go here.
