### ISSUE TITLE
Feature request: Add Electroncash to TAILS

### ISSUE THREAD

**Issue by btcarchive** [fyookball/electrum#171]
The Bitcoin Cash community desperately needs a safe way to store and manage their coins, without worrying about getting hacked. And not everyone has access to or confidence in hardware wallets. Therefore it would be great if Electroncash made it into the official TAILS distribution, like Electrum did.

**Comment by leto** [comment]
:+1:

**Comment by Danconnolly** [comment]
Note also here, may be out dated, should push for inclusion if we get this sorted out: http://www.openbitcoinprivacyproject.org/tails-linuxcrypto-currency-client-compatibility-tracker/

**Comment by haplo** [comment]
I would love to have Electron Cash in Tails, I have been using Electrum in Tails as my safe wallet for some time now, and I wish I could do the same for Bitcoin Cash. I would be happy to fund some kind of bounty to make this happen, or to do the coding myself. I guess we may need to talk with the Tails guys, I would expect they would not be happy about having both versions at the same time.

**Comment by haplo** [comment]
I would love to have Electron Cash in Tails, I have been using Electrum in Tails as my safe wallet for some time now, and I wish I could do the same for Bitcoin Cash. I would be happy to fund some kind of bounty to make this happen, or to do the coding myself. I guess we may need to talk with the Tails guys, I would expect they would not be happy about having both versions at the same time, unless they shared most dependencies.

**Comment by fyookball** [comment]
whats the issue now

**Comment by haplo** [comment]
The way I see it the issue shouldn't be on Electron Cash, but on Tails. I will try to contact Tails and see if this is possible, and if they need something from Electron Cash I will refer them to this issue.

**Comment by haplo** [comment]
OK so I contacted the Tails dev team and the unanymous response is that Tails won't have multiple Bitcoin wallets. However they are adding a feature in 2018 that will allow users to install any package available in Debian.

It's important for Electron Cash to be packaged in Debian, that's a clear prerequisite. Is anybody working on that @fyookball?

This is the thread in the tails-dev mailing list: https://mailman.boum.org/pipermail/tails-dev/2017-November/011852.html

**Comment by kyuupichan** [comment]
This is a distro issue, not an e-c issue
