### ISSUE TITLE
Don't copy electrum wallets

### ISSUE THREAD

**Issue by niopeer** [fyookball/electrum#174]
Copying over wallets from an existing electrum installation seems to be an undesirable feature for many users, and has been called out by would-be detractors as a security concern:

https://steemit.com/electrumcash/@idunno/do-not-use-electron-cash-and-electrum-on-the-same-machine

https://electrum.org/bcc2.txt

Because copying over wallets is not strictly necessary, and since most users will likely be creating a new wallet anyway, I think we should remove this as the default behavior.  Copying over existing wallets should be opt-in.

**Comment by niopeer** [comment]
@kyuupichan @fyookball any thoughts on this? based on the lack of response here https://www.reddit.com/r/btc/comments/720xta/community_feedback_disabling_existing_wallet_copy I don't think that this feature will be missed by the community.

**Comment by MohamedKiouaz** [comment]
I think this feature should be deleted too.

**Comment by fyookball** [comment]
im ok with removing it at this point

**Comment by omcnoe** [comment]
@fyookball Is there a time frame for the next release with this fix?
