### ISSUE TITLE
No support for new BCH adresses?

### ISSUE THREAD

**Issue by gboelter** [fyookball/electrum#177]
I've tried to send some BCH's to a BitPay-wallet using a new address like described here"
https://support.bitpay.com/hc/en-us/articles/115004671663

Looks like electrum don't accept this type of address.

Is this a known problem and will there be a solution, me be a new version?

**Comment by gboelter** [comment]
To make it more clear, this is a valid BCH address, where I like to sent some BCH's using Electron Cash:

Cbn4fEDV4CUsDAZuf8WhFKQGRuDp2R6NF7

Doing this, Electron Cash is telling me:

Warning - Invalid Lines found: Cbn4fEDV4CUsDAZuf8WhFKQGRuDp2R6NF7

![electron cash 01](https://user-images.githubusercontent.com/542529/30843487-0eab6462-a2bc-11e7-9c0d-2d8ce9b5b667.png)

**Comment by fyookball** [comment]
This is Bitpay's new address format that they just proposed last week.  I don't think anyone except Bitpay is supporting that.

**Comment by gboelter** [comment]
No need, I found a better solution ...
"del electron-cash-2.9.3.exe"

**Comment by fyookball** [comment]
lol ok.  are any other wallets besides Bitpay supporting that new address yet?

**Comment by gboelter** [comment]
Don't know too but Bitpay has an online-tool to convert old addresses to new addresses. You can use this tool to convert new addresses to the old format and then sent your coins to a bitpay wallet using the old address ...
