### ISSUE TITLE
BCC transaction was not made by me

### ISSUE THREAD

**Issue by RZC79** [fyookball/electrum#18]
I rescued the backup of a Blockchain (BTC) wallet in an Electron Cash 2.9.0 (BCC) portfolio at first appeared all right. I closed the wallet and after a while I opened it again and a transaction appeared that was not made by me.
An exclamation point appears plus the Low fee information and the balance 0.
I was hacked ?
Transaction Id
B0d3920e0c51b515eae299c334d399f9d70b49edb74686dd2caac13c0a7dcb08

**Comment by fyookball** [comment]
dont really know what you mean..screenshot?

**Comment by fyookball** [comment]
i dont see that tx id on blockchair. closing for now. if you have more info lmk
