### ISSUE TITLE
Use consistent naming

### ISSUE THREAD

**Issue by hegjon** [fyookball/electrum#180]
When making the RPM spec-file for Fedora [1] there was a lot of guessing between `electron`, `electron-cash`, `Electron Cash` and `Electron_Cash`.

It reduce packaging errors and time if the naming is consistent. My preference would be to include cash in the names to avoid name conflict with https://github.com/electron/electron.

[1] https://jonny.fedorapeople.org/electron-cash.spec

**Comment by Danconnolly** [comment]
Good point. Supporting inclusion in package management systems will help users.

**Comment by Danconnolly** [comment]
I think they have all been changed already for the next version.
