### ISSUE TITLE
Installing Electron Cash breaks Electrum

### ISSUE THREAD

**Issue by leto** [fyookball/electrum#181]
I installed the latest Git master of Electron Cash, `06d3f067`, which is a few commits ahead of 2.9.3, on the same machine as Electrum 1.9.7 .

It seems that the Electron Cash python egg has precedence and even when you try to run `electrum`, it pulls the `ElectrumGUI` python module from the wrong place and you get:

```
File "/usr/bin/electrum", line 175 in <module>
 gui = gui.ElectrumGui(config,network)
TypeError: __init__ () takes exactly 4 arguments (3 given)
```

Even doing a `apt-get remove electrum; apt-get install electrum` does not fully fix the problem, because the Electron Cash egg is still there, with the ElectrumGUI python modules.

On my particular Ubuntu machine, this command finally got rid of Electron Cash and made Electrum work again:

`cd /usr/local/lib/python2.7/dist-packages/; rm -rf Electron_Cash*`

**Comment by fyookball** [comment]
i think this will be fixed when we do the package name refactoring.
