### ISSUE TITLE
Error message when trying to transfer BCH using Electron-Cash 2.9.3

### ISSUE THREAD

**Issue by marethmum** [fyookball/electrum#185]
Hi, I can see my BCC balance in my Electron-Cash Wallet. When I go to send out to another address, I can sign the transaction (Using 2FA) - However when i broadcast I continually get this error
"error: The transaction was rejected by network rules. (16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element))
[01000000016c780def23baab6e1dd066fa3613e027b73c22563f717bbf755044cb032d308900000000fdfd0000483045022100d3fdf"
Can anyone help. My first import of BCH from a paper wallet transferred out ok but not the next one. I have setup the wallet multiple times but still does not work. I have also tried changing to a different server but no good. Sorry but I am completely lost. Any help would be greatly appreciated.

**Comment by fyookball** [comment]
We dont support 2FA directly so you'll need to use the workarounds, please see #41.
