### ISSUE TITLE
Electron Cash Wallet does not let me send my coins to another wallet

### ISSUE THREAD

**Issue by Rohan1359** [fyookball/electrum#187]
When I try to send my coins to a different wallet it shows the following error

mandatory-script-verify-flag-fail(signature must use SIGHASH_FORKID)

Please suggest

**Comment by fyookball** [comment]
can i see a screenshot?

**Comment by Rohan1359** [comment]
![image](https://user-images.githubusercontent.com/32577228/31307930-24c7ed10-ab3b-11e7-8437-1f3a2c89cc49.png)

**Comment by fyookball** [comment]
is it a 2fa wallet?

**Comment by Rohan1359** [comment]
Yes.

**Comment by fyookball** [comment]
we don't support 2fa directly but you can find a workaround here to access your coins. #41
