### ISSUE TITLE
My Transaction is Unconfirmed

### ISSUE THREAD

**Issue by Modysa** [fyookball/electrum#188]
Hi, I imported my private key from a paper wallet, but it is still showing that the transaction is **Unconfirmed** even after one hour waiting. what should I do?

**Comment by fyookball** [comment]
check it on the blockchair.com blockchain.  if it still shows confirmed on blockcchain but not on wallet let me know

**Comment by Modysa** [comment]
It is done,

Thank you.

On Oct 8, 2017, at 12:35 AM, fyookball <notifications@github.com<mailto:notifications@github.com>> wrote:


check it on the blockchair.com<http://blockchair.com> blockchain. if it still shows confirmed on blockcchain but not on wallet let me know
