### ISSUE TITLE
Bitcoin gold support

### ISSUE THREAD

**Issue by juanrodgil** [fyookball/electrum#190]
Not a bug, but an improvement.

With the new fork of bitcoin on the way (Bitcoin Gold, the 25 of October), will it be possible to support the coin in this wallet?

**Comment by wjcloud** [comment]
@juanrodgil  I think they should fork and customize for their wallets. For example, they could fork electrum and create Electrum_Gold or something.

**Comment by fyookball** [comment]
@juanrodgil   No, sorry.

**Comment by piotrekkaminski** [comment]
@fyookball are you aware this page https://www.electrongold.org/ is sending to this repository? It seems like a scam.
