### ISSUE TITLE
Change message for unconfimed transactions

### ISSUE THREAD

**Issue by n9jd34x04l151ho4** [fyookball/electrum#191]
This message came up when I received a new transaction which hadn't been confirmed yet:

![replaceable](https://user-images.githubusercontent.com/31981309/31342224-701ee432-ace2-11e7-876c-31a55aa3398d.png)

There's no Replace By Fee on Bitcoin Cash, so the transaction is not replaceable. Maybe the message could be changed to Unconfirmed.

**Comment by fyookball** [comment]
we removed RBF so i dont know how you got that. what version of Electron?

**Comment by kenman345** [comment]
@fyookball I can take a look through the code tonight maybe to verify we dont have any references like that. Might just be something that was missed.

@n9jd34x04l151ho4  can you perhaps confirm which version you were using when you saw that?
