### ISSUE TITLE
H*E*L*P

### ISSUE THREAD

**Issue by BabaCrypto** [fyookball/electrum#195]
Hi
I need HELP!

I claim my bitcoin CASH with "electron-cash" , decided to keep some "BCH" and send them to my Trezor, the "electron-cash" wallet generate a new "send" address every time by default , didn't know that.
then I decided to "shape shift" some of my BCH to BTC, by mistake I put in the receiving address the old "send" address from my "electron-cash" wallet, so now there is a full BTC in a BCH wallet.

I had tried to export all my privet keys from the "electron-cash" wallet to a electron wallet , and as well tried import all my privet keys from the "electron-cash" wallet to a blockchain info iPhone app..
both didn't show me the missing BTC!

I don't know how to find the privet key for the "send" address from the "electron-cash" wallet, can some one please help me?!

thank you

**Comment by fyookball** [comment]
All your addresses are available inside Electron Cash wallet and you can see private key for any address by right click , private key on the address tab.

If you go ahead and create the same wallet in Electrum (not Electron Cash) with the same seed, you'll have access to any bitcoin that you sent to the same address.

**Comment by BabaCrypto** [comment]
I see it was send to an address from my OUTPUT, I can't find it in my address

**Comment by fyookball** [comment]
where did the address come from?  Trezor?

**Comment by BabaCrypto** [comment]
yes

they are in my trezor , I had send BTC to an BCH on my trezor

**Comment by fyookball** [comment]
do you see the BCH address in your electron?
