### ISSUE TITLE
Problems with v2.9 installation (window closes)

### ISSUE THREAD

**Issue by joticajulian** [fyookball/electrum#20]
I follow the steps to install the software... after I define the password to encrypt the wallet it start to charge and finally the window closes, and the process closes in the Windows Task Manager.
When I open the folder %appdata%/ElectronCash there are some files but no a .exe.

Previously I uninstall my electrum software to ensure a good installation of electron cash.
Also the checksum of the downloaded exe is ok.
This is on Windows 10.

**Comment by fyookball** [comment]
this is provided as a stand alone EXE not an installation

**Comment by joticajulian** [comment]
then what I need to do to open the software

**Comment by fyookball** [comment]
Are you on windows?  Just double click the exe file.

**Comment by joticajulian** [comment]
I'm on windows 10. When I double click the exe file nothing happen. If I see it in the Windows Task Manager the program starts but after a few seconds it closes.

**Comment by fyookball** [comment]
check anti virus stuff
