### ISSUE TITLE
Impossible to send funds to wallet

### ISSUE THREAD

**Issue by coinstash** [fyookball/electrum#201]
Just set up Electron Cash on my new Android phone. The full address is not visible, and the app doesn't rotate when the phone is turned.

If I can't read the address I can't send to the wallet from elsewhere.

**Comment by clxcoltz** [comment]
You can hit Copy and paste it in whatever app/browser window you want, it'll show up there.

**Comment by coinstash** [comment]
That's fucking useless if I'm trying to send from a PC. Fix the problem.

**Comment by fyookball** [comment]
Will mark as enhancement so rotation can be done at future time.   From what I understand it is not a trivial change.
