### ISSUE TITLE
electron cash lost me my BCC

### ISSUE THREAD

**Issue by Chivalrouz** [fyookball/electrum#203]
Hello, i recently tried sending my BCC to binance through electron-cash-2.9 and it never made t to binance. I already checked with them and it shows no blockchain of the transaction. I am really hoping the BCC didnt just vanish from my wallet.

**Comment by fyookball** [comment]
do you have a transaction id?

**Comment by fyookball** [comment]
I don't see that on the block explorer
https://blockchair.com/search?q=ae47cbf3971dc8b9adc50edc2f744345c264d014b6dd29b47fd0e892f594672b

So it looks like there was no such transaction.

What do you see in your wallet?
