### ISSUE TITLE
Cold-storage signing fails

### ISSUE THREAD

**Issue by eriksank** [fyookball/electrum#204]
I can load a transaction successfully (into an off-line wallet) but when trying to sign the transaction, the wallet throws an error message-box saying only "value". It does not sign the transaction. Any way of getting the off-line signing to work again?

**Comment by fyookball** [comment]
you're using QR codes?

**Comment by eriksank** [comment]
No, just Tools->Load Transaction->From Text.

**Comment by fyookball** [comment]
and this is on 2.9.3?

**Comment by eriksank** [comment]
Yes, I specifically upgraded first to 2.9.3 hoping that the problem would go away by itself, but yeah, it didn't. ;-)

**Comment by fyookball** [comment]
I cannot reproduce the problem.  Its not a 2fa or anything weird, just a standard wallet?  Is it electrum seed or bip39? Can you try the verbose version and see if there is any useful console error msg, thx

**Comment by eriksank** [comment]
It is an electrum seed. In my impression, it tries to access the network, which is not possible, because it is disconnected from the network:

```
$ cat tx.txt | ./electron-cash signtransaction -w ~/.electron-cash/wallets/cold  -
Password:
Traceback (most recent call last):
  File "./electron-cash", line 419, in <module>
    result = server.run_cmdline(config_options)
  File "/home/vm/Electron Cash-2.9.3/packages/jsonrpclib/jsonrpc.py", line 288, in __call__
    return self.__send(self.__name, args)
  File "/home/vm/Electron Cash-2.9.3/packages/jsonrpclib/jsonrpc.py", line 238, in _request
    check_for_errors(response)
  File "/home/vm/Electron Cash-2.9.3/packages/jsonrpclib/jsonrpc.py", line 567, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/home/vm/Electron Cash-2.9.3/lib/transaction.py", line 727, in serialize_preimage | KeyError: \'value\'')
```

In the GUI, it sends up a dialog box with the KeyError (="value") in jsonrpc.ProtocolError. In Electrum, in the same circumstances, it does not try to access the network. There is no need to access the network for the `signtransaction` command, is there?

**Comment by fyookball** [comment]
it doesnt need to access network.  weird that your error message save cmdline as youre not running it command line. i'll try to dig a bit . on my end works fine

**Comment by adaseb** [comment]
I had this exact issue.

Basically the QR code option doesn't work like it does in Electrum.

So I opened the unsigned file and just copied the hash and imported it to the cold computer and it tries to connect to the server because it needs the input values.

You need to copy the entire unsigned.tx file for it to work. Just copying the hash "0100000....." won't work.

Trying QR codes gives this error 

type object 'QApplication' has no attribute 'primaryScreen'


This is with Ubuntu with qrencode dep installed.

**Comment by fyookball** [comment]
@eriksank can you try with 3.0 ?

**Comment by eriksank** [comment]
@fyookball It works like a charm now! Super! Thanks!
