### ISSUE TITLE
Crash in function: __pthread_mutex_lock

### ISSUE THREAD

**Issue by hegjon** [fyookball/electrum#205]
Details and fix at https://github.com/spesmilo/electrum/issues/2628

**Comment by fyookball** [comment]
@hegjon any steps to recreate this?  why merge this?

**Comment by hegjon** [comment]
TLDR, it segfaults when you try to scan a QR-code with the webcam

**Comment by hegjon** [comment]
Fixed in f70408cef5eff3eead108a06ee11a6106253f74d

**Comment by fyookball** [comment]
@kyuupichan  has this been fixed/merged in 3.0?

**Comment by kyuupichan** [comment]
I'm not sure; OP should comment on if the problem persists.

**Comment by hegjon** [comment]
This issue is solved in latest commit 459100eda0f3cdcf6d75e304d08345a627364078 (HEAD, fyookball/master)
