### ISSUE TITLE
Sent funds from wallet to exchange and unconfirmed, funds in stand-by!

### ISSUE THREAD

**Issue by zezazebretti** [fyookball/electrum#206]
Hi sent all BCC I have from wallet to Kraken account. The message was OK **FUNDS SENT** but the transfer is blocked in status **UNCONFIRMED**.
I can't de-block the transfer for making a new one. I can to nothing.

Here two screenshots as reference:

![d3gstiu3](https://user-images.githubusercontent.com/33071030/31964468-62f9f9f8-b904-11e7-95ea-00553f66e402.png)

![h5hcxlkr](https://user-images.githubusercontent.com/33071030/31964485-6d0faa00-b904-11e7-8112-21d2ce4c0614.png)

What I can do???
Thanks.

**Comment by clxcoltz** [comment]
Can you paste the address and txid in text here so it's easier for us to check on an explorer?

**Comment by zezazebretti** [comment]
Is this:

09202a824f77468d3a0f43207eb99f97d4cf468a35f5c8fc35aa57e4c08174a7

thanks!


Zeza


------ Previous message ------

**Comment by zezazebretti** [comment]
I did a new transfer using a new wallet with same seed but NO 2fa.

Transfer sent but... seems the same:



As the previous: UNCONFIRMED :-(


zeza



------ Previous message ------
From: "e P u b M A T I C | sergio" <sergio@epubmatic.com>
To: "fyookball/electrum" 
<reply@reply.github.com>; 
"fyookball/electrum" <electrum@noreply.github.com>
Cc: "Author" <author@noreply.github.com>
Sent: 25/10/2017 17:50:50
Object: Re[2]: [fyookball/electrum] Sent funds from wallet to exchange 
and unconfirmed, funds in stand-by! (#206)

**Comment by clxcoltz** [comment]
I honestly can't find your tx in any explorer. Care to send your origin address or destination address?

**Comment by zezazebretti** [comment]
send 3Ac1HEqNVijvnwTnk5SdrxzZHGd8C51QiN
receive 19bmngr5GYTrBPCJQiTYDdyHhqRjA7YGsi

**************************************************

thanks





------ Previous message ------

**Comment by zezazebretti** [comment]
I changed server and seems something happened.
The icon changed and is not more UNCONFIRMED:



------ Previous message ------
From: "e P u b M A T I C | sergio" <sergio@epubmatic.com>
To: "fyookball/electrum" 
<reply@reply.github.com>; 
"fyookball/electrum" <electrum@noreply.github.com>
Cc: "Author" <author@noreply.github.com>
Sent: 25/10/2017 18:17:09
Object: Re[2]: [fyookball/electrum] Sent funds from wallet to exchange 
and unconfirmed, funds in stand-by! (#206)

**Comment by clxcoltz** [comment]
Dude I checked that on explorere, that's a BTC address not a BCC/BCH address. Are you sure you got the right client installed?

**Comment by zezazebretti** [comment]
is Electron Cash, look here:


For Bitcoin I use Electrum!

thanks for letting me know



ze.



------ Previous message ------

**Comment by zezazebretti** [comment]
Update: status is now with 2 confirmations than maybe something happens :-)
Thanks everybody. Hope resolved. In a couple of hours I will check again the confirmations.

**Comment by zezazebretti** [comment]
I explain what happened for who will get same problem. If you want to send BCC from Electron Cash:
1) After typing the seed choose DISABLED 2fa
2) Select as server Casharia, no automatic server!

If you try other ways the transfer remains in status 'unconfirmed'.
Thanks everybody.
