### ISSUE TITLE
yet again trying to send me bcc to binance to transfer to another crypto and it goes unconfirmed again.

### ISSUE THREAD

**Issue by Chivalrouz** [fyookball/electrum#207]
![bcc](https://user-images.githubusercontent.com/32972851/31998135-aab7addc-b95c-11e7-9c46-e821e1228163.jpg)

Not sure why its going unconfirmed, i sent this over 8 hours ago and still has not reached my binance account.

**Comment by fyookball** [comment]
Because you are on a 2fa setting. Trusted Key has chosen not support Bitcoin Cash.  They are the 3rd party that operates 2fa.  Please see #41 to move your coins out of the 2fa wallet and into a normal wallet.
