### ISSUE TITLE
Exchange rate

### ISSUE THREAD

**Issue by clxcoltz** [fyookball/electrum#208]
When I hit "Settings" there's an option for "Fiat Currency", which I assume is used to choose exchange rates. But when I go in no options are available. Is it possible to complete that feature so the wallet is more usable for everyday use?

Thanks.

**Comment by fyookball** [comment]
i see this
![image](https://user-images.githubusercontent.com/7663756/32030706-d3c4b9c2-b9ca-11e7-9479-c11c1cf072e6.png)

**Comment by clxcoltz** [comment]
Weird, so it's working for desktop clients? I'm using the Android release and I see this
![screenshot_2017-10-25-18-25-36](https://user-images.githubusercontent.com/28605819/32030788-3e0ecade-b9b2-11e7-88a4-1c2ef120bb08.png)

**Comment by fyookball** [comment]
ah ok.

**Comment by expatmt** [comment]
Same problem using v2.9.3 on Linux: ![electron-cash-fiat-exchange-rates](https://user-images.githubusercontent.com/10192829/32134615-ff43b422-bbf0-11e7-9346-a6ed9162db29.png)

**Comment by Danconnolly** [comment]
Clear the "history rates" flag. Needs fixing though.

**Comment by clxcoltz** [comment]
Also, exchange rate still doesn't work on Android in 2.9.4. Can confirm works fine on Linux.
