### ISSUE TITLE
error: The transaction was rejected by network rules.

### ISSUE THREAD

**Issue by joticajulian** [fyookball/electrum#21]
This is on Android version 2.8.2

When I send some BCC to another address it says:
error: The transaction was rejected by network rules. (16: mandatory-script-verify-flag-failed (Non-canonical DER signature)) ... following by a signature.

My address has enough balance.

**Comment by fyookball** [comment]
i think this be related to the comment @daburra667 made about the fix.

**Comment by fyookball** [comment]
fixed by this:  https://github.com/fyookball/electrum/issues/6
