### ISSUE TITLE
NEW SEED SERVERS

### ISSUE THREAD

**Issue by fyookball** [fyookball/electrum#212]
with HF upgrade - Bitcoin ABC 0.16, we need new server list who are running electrumX on upgraded node.

**Comment by danny91** [comment]
This might help you https://github.com/danny91/electrum/commit/757a7e519aa2e3dee97f79a9e3d1b56aa45668d5

**Comment by fyookball** [comment]
https://www.reddit.com/r/btc/comments/7abc48/electron_cash/

**Comment by fyookball** [comment]
thanks @danny91

**Comment by Otaci** [comment]
electroncash.cascharia.com has been updated
