### ISSUE TITLE
Error in Sending

### ISSUE THREAD

**Issue by cancerea** [fyookball/electrum#214]
I am getting this 'The transaction was rejected by network rules. (16: mandatory-script-verify-flag-failed (Signature must use SIGHASH FORKID ))'

I am also trying to remove the 2Fa, when I try to follow the steps and its "Please Wait  . . . "  and then doesnt respond for long time. .

**Comment by fyookball** [comment]
f2a cant be supported because trusted coin doesnt support bitcoin cash.  see #41
