### ISSUE TITLE
unable to send from wallet

### ISSUE THREAD

**Issue by cornishpirate** [fyookball/electrum#216]
OS: MacOS High Sierra
ElectronCash: Version 2.9.3

I cannot send funds from the GUI. I enter the recipients wallet address (a Bitcoin Cash wallet created using the Copay app), then try to send funds.

I get this exception:

![pay-to-issue](https://user-images.githubusercontent.com/21303889/32403939-c2559a88-c13d-11e7-976f-c16bb4cd4a1a.jpg)

**Comment by fyookball** [comment]
we dont support copay addresses yet.  We may at some point.

For now, you'll have to use the copay/bitpay address converter

https://bitpay.github.io/address-translator/

**Comment by cornishpirate** [comment]
excellent, thank you @fyookball - my concern was that i couldn't ever 'send', but if its just to copay, then thats fine!
