### ISSUE TITLE
incorrect balance for some private keys 

### ISSUE THREAD

**Issue by johndooz** [fyookball/electrum#218]
I have installed electron cash 2.9.3 and imported my private keys coming from a bitcoin core wallet.

The first private key balance is ok, but the 2 others are shown with 0 balance and this is not what I can see in my wallet (with listaddressgroupings in console) .
I have also done a listtransactions and  verified on blockchain.info some of the transactions hashes , all is ok.  But when I try to broadcast those transactions in electroncash an error says it is rejected by network because of missing inputs   (and those transactions are seen as "not related to my wallet" by electron cash.

**Comment by fyookball** [comment]
is there anything special about these tx?  I will try to recreate.

**Comment by johndooz** [comment]
I don't know if there is something special , is there some way to send you privately some transactions ids so that you can check them ?

**Comment by fyookball** [comment]
you can send me your master pubkey so i can try to check it

**Comment by johndooz** [comment]
Yes but even if this is my pubkey I do prefer sending it only to you and not here.   Any email or private form on a website where I can send it ?

**Comment by johndooz** [comment]
I have installed the bitcoin abc client and it seems to see all the BCC coins so ,I will wait the sync and use this one even if it takes a lot of disk space and time to sync.
Thanks anyway.
