### ISSUE TITLE
error when trying to send Bitcoin Cash (Electron Cash 2.9.3)

### ISSUE THREAD

**Issue by CoinDiver** [fyookball/electrum#220]
"error: the transaction was rejected by network rules. 

16: mandatory-script-verify-flag-failed (Signature must use SIGHASH_FORKID) 
[010000000482fede383bd92127680856b0ebc8ad5b55e07161e349590c85224729eb978a2d00000000fdfd000047304402206be3cfb2d3a35ce095061e4915f25a38f1eb940db89ef2ec09136" 

I have absolutely no clue what to do. Can someone please help me?

**Comment by fyookball** [comment]
is it a 2fa wallet

**Comment by CoinDiver** [comment]
Yes it is

**Comment by fyookball** [comment]
Trusted Key does not support BCH.  Move your coins to standard wallet.  See #41

**Comment by CoinDiver** [comment]
So I opened a new standard NO 2F wallet with new seed (I never got a seed for the other one), looked up my receive address and tried to send my coins to the new NO 2F wallet. Of course my old wallet still asked me for pass and 2F digits. So I put in the info in and it says "Payment sent", but nothing is happening. No change in the history, nowhere, nothing. 

I'm running out of options here. In the thread it says I should open a new wallet with an existing seed. Well, I never received a seed for the defailt 2F wallet in question. Now what do I do?

**Comment by fyookball** [comment]
ask on #41 please

**Comment by quintela78** [comment]
Did you solve the issue? If not, call leonardquintela@gmail.com Maybe I can help you. I rarely go here.
