### ISSUE TITLE
Slow startup, slow editing address label

### ISSUE THREAD

**Issue by zyo2012** [fyookball/electrum#222]
I'm using electrum cash and find the application very slow to startup and very very slow to rename tag, sometimes over 20 sec. I don't experience any of that with the original Electrum wallet. I have a pretty powerful computer.

Using the windows build.

**Comment by fyookball** [comment]
I haven't experienced that.  anyone else?

**Comment by zyo2012** [comment]
Do you want you my seed words to test using my wallet? (joking here). Could it be related to the fact have a lot of transactions?

**Comment by fyookball** [comment]
>Could it be related to the fact have a lot of transactions?

It could be.  How many are we talking?  The software is not really designed to deal with a history of thousands of transactions.

**Comment by zyo2012** [comment]
Less than 1 thousand, more than 200 for sure. Is there a count somewhere?

**Comment by molecular** [comment]
Well, zyo2012 says on reddit that electrum doesn't suffer from this issue. I think it's worth looking into. It's hard to reproduce, but he's willing to help.

@zyo2012 are you on linux? If so, can you try starting electron-cash with the "-v" flag and see at what point in the debugging output it "freezes"?

**Comment by zyo2012** [comment]
I still experience problem:

Here is the benchmark.
~4 second to get the dialog asking for password. (fine)
Then I guet this "Non responding windows" for **2 minutes and 10 seconds**!!

![image](https://user-images.githubusercontent.com/3308951/35012062-612d67cc-fad6-11e7-90d7-6f8f118f0f36.png)

**Comment by fyookball** [comment]
i'll try creating a wallet with 1000 transactions.

**Comment by molecular** [comment]
It might be interesting to see the debeugging output during and right before the "freeze".

I think there is a "debug mode" binary for windows? (sorry, I use linux only)

**Comment by zyo2012** [comment]
@molecular  I have no clue how to enable that... is that from the command line or something?

**Comment by marceloneil** [comment]
The latest version is 3.2, does it work well with that version?

**Comment by marceloneil** [comment]
Also, I think we moved to a different version of QT which might be why its a bit faster
