### ISSUE TITLE
i can not see SEED after login electron cash 2.9.3

### ISSUE THREAD

**Issue by stralvm** [fyookball/electrum#225]
hello, if I log in my electron cash 2.9.3 for bitcoin cash I see the amount BCH that i have. But i don't see SEED. How is this possible? Because i have trouble two factor authenticator for  sending bch i have tried to solve this by downloading Electrum. But i dont have my SEED.
with a password i can login to my wallet, there the button Seed is not available.

can anyone help me with this i want to send my BCH to kraken.

**Comment by fyookball** [comment]
2fa issues , see #41.
