### ISSUE TITLE
Which version for upcoming DAA fork?

### ISSUE THREAD

**Issue by n9jd34x04l151ho4** [fyookball/electrum#227]
Hi @fyookball,

Which version of Bitcoin Cash should we install for the upcoming difficulty adjustment fork?

Last version is 2.9.3 from 20 August.

Only 4 days left!

**Comment by gropius365** [comment]
Looks like the [release notes](https://github.com/fyookball/electrum/blob/cash/RELEASE-NOTES) have been updated to include 2.9.4 in which the Nov. 13 fork is addressed.   I don't see any 2.9.4 versons available on the [homepage](https://electroncash.org/) yet, though.

Not really Electron Cash's fault, but this is cutting things awfully thin!  I sure hope everyone holding their BCH in an Electron Cash wallet is going to be OK come fork-time.

**Comment by Danconnolly** [comment]
Version 2.9.4 is being finalized now, it is expected to be available very soon.

**Comment by fyookball** [comment]
2.9.4 windows and linux is avail. working on android and mac. 

www.electroncash.org

**Comment by n9jd34x04l151ho4** [comment]
@fyookball Which tag do I check out for v2.9.4 code?

![image](https://user-images.githubusercontent.com/31981309/32646542-38731b56-c5d4-11e7-92d6-390d5ba615ac.png)

**Comment by fyookball** [comment]
i didnt tag it yet... still working on android and mac.  but it is the head of cash or pyqt4 branch
