### ISSUE TITLE
No reference to PyQt5 in Electron-Cash-2.9.4.tar.gz

### ISSUE THREAD

**Issue by rycee** [fyookball/electrum#229]
Just downloaded the source tarball from https://electroncash.org/downloads/2.9.4/win-linux/Electron-Cash-2.9.4.tar.gz and I suspect there is something wrong with it:

```console
$ wget -q https://electroncash.org/downloads/2.9.4/win-linux/Electron-Cash-2.9.4.tar.gz
$ sha1sum Electron-Cash-2.9.4.tar.gz
2261e6531213afb93032779899cd3d658ac22b2a  Electron-Cash-2.9.4.tar.gz
$ sha1sum -c <(curl --silent https://raw.githubusercontent.com/fyookball/keys-n-hashes/master/sigs-and-sums/2.9.4/win-linux/SHA1.Electron-Cash-2.9.4.tar.gz.txt)
Electron-Cash-2.9.4.tar.gz: OK
$ tar xf Electron-Cash-2.9.4.tar.gz
$ grep -R PyQt5 'Electron Cash-2.9.4'
Electron Cash-2.9.4/RELEASE-NOTES:  * Upgrade to PyQt5
$
```

That is the only reference to PyQt5 is in the release notes.

**Comment by rycee** [comment]
By the way, would it be possible to also/instead have a sha256 hash of the file in the keys-n-hashes repo?

**Comment by fyookball** [comment]
it was built off the pyqt4 branch.  Kyuupichan decided he wanted to move to pyqt5, but wine doesn't play nice with this on python2.  All the pyqt5 exe files expect python 3 and there is no suitable wheel.  i had to revert to pyqt4.  

I am doing SHA1 for now:

https://github.com/fyookball/keys-n-hashes/tree/master/sigs-and-sums/2.9.4/win-linux

**Comment by rycee** [comment]
Ok, thanks for the explanation!
