### ISSUE TITLE
history of payments takes forever to verified.

### ISSUE THREAD

**Issue by charleshsu168** [fyookball/electrum#23]
payment history remain unverified for more than 10 minutes.
it should be verified really fast like within a minute.
http://imgur.com/a/ZffVS

i tried to select a bunch of different electron cash servers, but it's still not working.

**Comment by l29ah** [comment]
Bitcoin Cash has inherited the difficulty from Bitcoin, so it will take a few hours to produce a block for some time.

**Comment by charleshsu168** [comment]
this is about unverified history of payments before the split on Aug 1. 
bcc server should be able to pull down the history and sync with the electron cash on those before Aug 1 right away.

**Comment by fyookball** [comment]
i dont think we are supporting prefork history.  sorry

**Comment by kyuupichan** [comment]
Of course we support all history

The first time the client is run it has to download all the headers. This can take 10 minutes. Please be patient, unfortunately nothing in the GUI shows what is happening in the background.
