### ISSUE TITLE
Additional fiat currencies for conversion

### ISSUE THREAD

**Issue by MitchRuns** [fyookball/electrum#231]
Currently there is only USD and EUR under Tools>Preferences>Fiat.
I'm sure it would benefit me and many others if more currencies were added like the list that Electrum has. 

I hope more currencies can be added in the near future.

**Comment by PaulBirchDev** [comment]
I'd second this - GBP would be great.

**Comment by PaulBirchDev** [comment]
#264  - Decided to so some work myself :)

**Comment by Danconnolly** [comment]
Only EUR and USD were available at the beginning, but you're right, we should add more.

Thanks @PaulBirchDev for GBP.

**Comment by gwestwood** [comment]
I've further updated the list of sources and currencies in #300.

**Comment by kyuupichan** [comment]
This is in much better state now.
