### ISSUE TITLE
2.9.4 Not on GitHub?

### ISSUE THREAD

**Issue by krakn** [fyookball/electrum#232]
Just curious as to why this tag isn't pushed to GitHub yet.

I maintain: https://aur.archlinux.org/packages/electron-cash-git/ and don't want to use a versioned tarball unless I absolutely have to.

Thanks!

**Comment by fyookball** [comment]
will be done very soon.  i wanted to get the binaries done first, i'm just finishing it up. things were a bit rusehd due to the hard fork so i wanted to get the windows exe out there.
