### ISSUE TITLE
Issue opening electron cash 2.9.4

### ISSUE THREAD

**Issue by Chivalrouz** [fyookball/electrum#233]
Hello,m trying to open up electron cash version 2.9.4 with my wallet in order to move my bch out to an exchange and the winodw immediantely closes itself once i sign into the wallet. I really want to get this ball rolling becuase bch is hitting 1k right now

**Comment by fyookball** [comment]
Use the verbose version on the site  , paste a screenshot of the console output here please

**Comment by Chivalrouz** [comment]
![electron cash 2](https://user-images.githubusercontent.com/32972851/32689599-cabb2396-c6b5-11e7-9a4a-e898c20d839d.jpg)

This is what i could manage since the application closes just as fast when i log in to my wallet.

**Comment by Chillout93** [comment]
I also get the same error after clicking next with default_wallet.

![capture](https://user-images.githubusercontent.com/3492169/32693643-4b2dfb0a-c726-11e7-8a10-65ab63866f51.PNG)

**Comment by fyookball** [comment]
ah 2fa wallet.  Yeah we dont support that because of trusted key.  See instructions on #41.
