### ISSUE TITLE
Upload electrum cash to android Playstore

### ISSUE THREAD

**Issue by wjcloud** [fyookball/electrum#234]
Do you guys have a plan to upload the apk file at playstore?
Or can I do it?

**Comment by fyookball** [comment]
I think it needs a 'real' sig not a debug 'sig'.  Which would change the hash.  i would let you do it except for that... i think i have to do it.  Can you shortcut my process by giving exact steps to sign an already compiled APK?

**Comment by Otaci** [comment]
Note: if this is done we could also add a QR code to the website for installing the app.

**Comment by fyookball** [comment]
it is done.
