### ISSUE TITLE
Help me out with electron cash. Can't send!!

### ISSUE THREAD

**Issue by jeffreytjuhh** [fyookball/electrum#235]
I can't send my BCH to another adres. Error (16: mandatory-script-verify-flag-failed (Signature must use SIGHASH FORKID ))

1. See picture (1) everything is good
2. I want to send. Type in right adress, type password and 2fa code from Google Authenticator
3. Get the error 16 seen in picture (2)
4. I have tried to create new wallet using my old phrase from my first wallet. But then it gets stuck after I put in the phrase and click next. Seen in picture (3)
Who can help me out please!!!

**Comment by fyookball** [comment]
2fa is not supported by trusted key on BCH.  See #41 for workaround to move to standard wallet (not 2fa).

**Comment by jeffreytjuhh** [comment]
Thanks but when I want to recover the wallet it gets stuck when I input my seed see picture 3
