### ISSUE TITLE
Can not receive money from blockchain

### ISSUE THREAD

**Issue by nhatbinh** [fyookball/electrum#238]
I sent more than 500$ from blockchain to electron cash 2.9.4.

The transaction is already done in blockchain. But in my electron cash 2.9.4, I have not receive nothing.

may I gotten a trap. 
 may I lost all my money? :/

**Comment by nhatbinh** [comment]
please leave you comment to let me know :(

**Comment by fyookball** [comment]
is it 2fa wallet?

**Comment by nhatbinh** [comment]
sorry, I do not know what you mean. 
until now, I still have not receiving anything in my electron cash 2.9.4. :/

**Comment by fyookball** [comment]
if you see the address in your wallet , it should match the block exporer blockchair.com 

post the txid

**Comment by nhatbinh** [comment]
![capture](https://user-images.githubusercontent.com/33594609/32699631-5d9b4b2c-c7fc-11e7-899a-0ba1bb59d791.PNG)

where is this money rightnow? i do not know :/ please help

**Comment by fyookball** [comment]
Will take a look in a bit. Not at desk.

**Comment by fyookball** [comment]
ok so this address you posted, do you see that address in your wallet? Go to addresses tab (view addresses)...you can do ctrl F find, or look in used addresses for receiving or change addr. 

is there or not?

**Comment by nhatbinh** [comment]
![capture](https://user-images.githubusercontent.com/33594609/32705901-2c73839c-c85c-11e7-9534-8e00949b2a1b.PNG)
 i see this address in my addresses tab for receiving.   What would I do next? thanks pro

**Comment by fyookball** [comment]
my question is:  

When you said in your first comment "I sent more than 500$ from blockchain to electron cash 2.9.4."
Which of these addresses did you send it to that's in the wallet?

**Comment by nhatbinh** [comment]
![capture](https://user-images.githubusercontent.com/33594609/32708215-0bd150f0-c86c-11e7-8803-d3014d962adb.PNG)
you can see this picture. I sent from my blockchain.info wallet.

My address sent is:  16vzev8YLSvKSMUa6bjqD2bkFxQccjuEd

![23584229_1708390725847391_434018696_o](https://user-images.githubusercontent.com/33594609/32708346-9a8069b2-c86c-11e7-88b4-016b0e1ba6da.jpg)

thank you so much.

**Comment by fyookball** [comment]
it looks like you sent it to a multisig address on blockchain.info, not to electron

**Comment by nhatbinh** [comment]
So, right now, how can i receive my money back? :/

**Comment by fyookball** [comment]
I don't think you ever sent this to your electron wallet. looks like you sent it to your block chain wallet.  you might want to look there.
