### ISSUE TITLE
Cannot access BCH available on Electrum Wallet

### ISSUE THREAD

**Issue by raghavnath583** [fyookball/electrum#240]
I have followed the steps mentioned in the thread for how to get the coins out of the 2FA Electrum wallet. 

However, when I go through the restore step, the wallet restored shows no history. When I open this wallet with Electron Cash, the balance shows up as 0. 

I have followed the steps to the T but am unable to get the coins out. Can someone help me please?

**Comment by fyookball** [comment]
Does it show the addresses you were expecting?
