### ISSUE TITLE
Unable to upgrade wallet 

### ISSUE THREAD

**Issue by PollysCracker** [fyookball/electrum#241]
I have followed instructions given in the work around #41 but my seed is not being recognized for some reason..
Also tried importing using the private keys but my balance still shows 0 while on the 2.9.2 wallet the bch are there. It is a 2fa wallet.

steps: 
create new wallet - standard wallet
keystore - I already have a seed
I enter my seed but the box next is still grey -( https://ibb.co/hnYeFw ), when i choose option BIP39 seed so that i can click Next. -( https://ibb.co/ksxT8G)
derivation - tried both m/44'/0'/0' and m/44'/145'/0' -( https://ibb.co/fkrYaw )
I set up a pw

generates adresses and empty wallet

Is it not possible to upgrade from 2.9.2 to 2.9.4 with the exported private keys from the 2.9.2 wallet that holds the bch when 2fa is enabled? i still have 2fa safely

**Comment by fyookball** [comment]
Did you follow darklordgms instruction @darklordGMS

**Comment by PollysCracker** [comment]
Ok so now things get weird, I followed his steps, managed to remove the 2fa and loaded the wallet up on electron 2.9.2 and was able to send the bcc there, still unconfirmed though.

Removed the electroncash folder in roaming appdata and tried with electron 2.9.4 and now i am crashing again when i open the wallet

**Comment by fyookball** [comment]
i think you need to create a new wallet file for 2.9.4 if it was 2fa before.
