### ISSUE TITLE
I can not transfer from my wallet 2.9.3

### ISSUE THREAD

**Issue by enkigardriver** [fyookball/electrum#242]
I have a MAC OSX version. My wallet is in 2.9.3 version. I tried to transfer from my wallet and I had never been able to do it. 
error: the transaction was rejected by network rules.

16: mandatory-script-verify-flag-failed (Signature must use SIGHASH_FORKID)
[0100000003f5a3dfd04135d186528a8823483a29660d970c59a6978e6bc8e3d2921b1c551100000000fdfe00004830450221

I also down load the 2.9.4 version in windows and when I tried to transfer the wallet into this version with the seed of 12 words it does not recognize  them.  I tried also in the option where the master public key is asked and with the seed of 12 words and also the 12 words had been not recognized. 

What can I do to transfer my BCH?

**Comment by fyookball** [comment]
i guess you have 2fa wallet?  #41
