### ISSUE TITLE
Electroncash 2.9.4 crashes if entering password

### ISSUE THREAD

**Issue by wpstephen** [fyookball/electrum#244]
I downloaded the new version 2.9.4. for MacOS and tried running the wallet from my 2.9.3. file. If I enter my password and press next, the client crashes.

**Comment by wpstephen** [comment]
I also tried recovering the wallet with an existing seed, but that doesn't work also. And when I tried to use 'zbar' to scan QR back-up code, the client also crashes.

**Comment by fyookball** [comment]
a few people have been reporting this issue.  workaround for now is to create a new wallet for 2.9.4 with the same seed.

**Comment by fyookball** [comment]
is this 2fa?

**Comment by wpstephen** [comment]
I have already tried creating a new wallet with the same seed, but I can't press 'Next' after writing out my 12-word seed. I have already disabled 2fa through the method described in #41

**Comment by wpstephen** [comment]
Is there still anywhere a download for 2.9.3, so I can use that wallet to send my funds to another wallet? I was being too rushed and deleted the 2.9.3 version after installing 2.9.4. Thanks.

**Comment by wpstephen** [comment]
It's been solved, found a 2.9.3 version on your github. Thanks anyways!
