### ISSUE TITLE
Error -5 from inflate: (null)

### ISSUE THREAD

**Issue by Gridosky** [fyookball/electrum#247]
Hi all,

I used 2.9.3 up until now.

I just downloaded 2.9.4 for windows and when executed I get
"Error -5 from inflate: (null)"
after accepting
"Error decompressing PyQt4.QtGui.pyd"
and then program crash windows message.

Any ideas?

**Comment by fyookball** [comment]
never seen that kind of error before.  Can you run verbose version and give me a full traceback of the error. thanks.

**Comment by Gridosky** [comment]
verbose version opens without any error message

**Comment by Gridosky** [comment]
is verbose version equally functional? can I use it instead?

**Comment by fyookball** [comment]
strange.  yes verbose version is equally functional although there are bugs (for both) that certain things are broken in 2.9.4 like signing messages.  i'll release 2.9.4.1 both ways as well.  I guess i'll close this for now as I cannot recreate.
