### ISSUE TITLE
Message signature/validation doesn't work in version 2.9.4

### ISSUE THREAD

**Issue by ypascal** [fyookball/electrum#248]
I encountered an issue with ElectronCash v2.9.4, when I try to sign a message, nothing appears in the "Signature" textbox. The "Verify" function doesn't work either.

Both operations work seamlessly on version 2.9.0. I use the windows version.

**Comment by fyookball** [comment]
I'm able to recreate this.  Pretty sure it's some PyQt4 to PyQt5 thing that was overlooked.  I should have time to fix in the next 2 days.

**Comment by molecular** [comment]
works on linux (running from source) version

**Comment by fyookball** [comment]
@molecular fyi im guessing youre on cash branch not pyqt4

**Comment by fyookball** [comment]
https://github.com/fyookball/electrum/commit/33f610f1ebd4a22472b0bc296dee6a00d1ba6cad

fixed

**Comment by molecular** [comment]
yes, I'm on cash branch. sorry 'bout that. So I assume windows 2.9.4 was built from pyqt4 bracnh.

**Comment by fyookball** [comment]
yes
