### ISSUE TITLE
2.9.4 does not start. 

### ISSUE THREAD

**Issue by d412** [fyookball/electrum#249]
I have no idea why it´s not working.  I open the application check that my wallet is selected. As soon i enter the password everything disappears i just get a tiny grey bitcoin cash symbol in next to the clock in taskbar, when i hover my mouse over it it vanishes and then application seem´s closed. I even tried to make a new default_wallet and enter my seed, but the next button remain´s non clickable. And I still have the old 2.9.3 exe also on my pc which opens just fine. But i was not able to sent any transaction´s only receiving was possible. :(  thank you

**Comment by fyookball** [comment]
is it a 2fa wallet?

**Comment by chaddybox026** [comment]
this seems eerily similar to my case.

**Comment by d412** [comment]
hey yes it is a 2FA wallet btw.

**Comment by chaddybox026** [comment]
2fa wallets are not supported. #41

**Comment by d412** [comment]
Is there a chance i can recover my coins?

**Comment by chaddybox026** [comment]
Yes issue #41

**Comment by d412** [comment]
holy shit those things sound way to technical for me...

**Comment by citrusBerry** [comment]
@chaddybox026 Recover is ok. But how to send the coin? Old version should not be used anymore, correct?

**Comment by chaddybox026** [comment]
Old version of what?

**Comment by citrusBerry** [comment]
@chaddybox026 Old version of electron cash.

**Comment by chaddybox026** [comment]
You should use the newest version of electron cash.

**Comment by citrusBerry** [comment]
@chaddybox026  Yes, but using the same seed, the balance is 0. In old version, it is the right amount.

**Comment by d412** [comment]
buh i hope there will be a fix from fyookball i tried but it didn´t work.. :(

**Comment by chaddybox026** [comment]
There is an issue solving your zero balance issue

**Comment by citrusBerry** [comment]
@d412 please check my comment in #41 .

**Comment by d412** [comment]
thanks for the reply i tried to make a new wallet but i still have this error why i can´t sent anything through the old wallet i assume due to 2FA..  is ther a way i can import my private keys or something in the new wallet?

**Comment by fyookball** [comment]
@d412 2fa cannot work in Electron because trusted key won't support it.  You have to unfortunately use the workarounds in #41 to move your coins out of that wallet.  Start with DarklordGMS method and ask questions in #41 if stuck.  Closing this.
