### ISSUE TITLE
An unknown transaction showing up from time to time

### ISSUE THREAD

**Issue by lz000** [fyookball/electrum#25]
There is one transaction (Unconfirmed) which I never made appears from time to time. See screenshot. When I right click on it and select "view on block explorer", it directs me to the error page https://blockchair.com/404. Any idea why?

![image](https://user-images.githubusercontent.com/5400124/28902719-d63efb1a-77ce-11e7-99e6-98c4be16d973.png)

**Comment by fyookball** [comment]
are you connected to the BCC server?  Are you sure its an official version?  Weird that it is for your entire balance.  Can right click and get a tx id?

**Comment by lz000** [comment]
I think I connected to the right servers (See below screenshot) and the software is Electron-Cash-2.9.0.exe (verified with signature). The transaction id is 1549057674249a928c124ebcf4344ec6984f64dfb7be5fbffd6507baf8ecdb15. 

![image](https://user-images.githubusercontent.com/5400124/28903005-7c75baea-77d0-11e7-889c-9d68e84266c3.png)

**Comment by fyookball** [comment]
i went to blockchair and looked that up -- seems like its on the bitcoin chain not BCC.    I dont know why you should see it here.  Is it intermittant?

**Comment by lz000** [comment]
Yes. I saw it disappeared once then after a while it came back.

**Comment by fyookball** [comment]
the TX comes from the servers... i think it is the servers acting weird, perhaps there are ones doing weird things , people testing, or goofing off.  try deselecting auto select server and just connect to one server and see what happens.

**Comment by lz000** [comment]
Sure, which server should I connect? any one?

**Comment by fyookball** [comment]
try cashcaria for the moment

**Comment by lz000** [comment]
So far I haven't seen it appears again. Thanks!
