### ISSUE TITLE
Electron Cash 2.9.3 - Error sending BCH to an exchange address

### ISSUE THREAD

**Issue by Chkuan** [fyookball/electrum#252]
When I send to the exchange address it returns an error: the transaction was rejected by network rules.

16: mandatory-script-verify-flag-failed (signature must use SIGHASH_FORKID) ................

Tried start a new wallet using 2.9.4 but reject seed list. Help!

**Comment by fyookball** [comment]
2fa wallet?

**Comment by Chkuan** [comment]
Ya. I finally got the problem solved by deleting the wallet and managed to create a new wallet without 2fa on 2.9.3. The sending works.........thks.
