### ISSUE TITLE
Transaction only says "Not verified" when in Tails OS, but works fine in Ubuntu.

### ISSUE THREAD

**Issue by pv8man** [fyookball/electrum#253]
Transaction only says "Not verified" when in Tails OS, but works fine in Ubuntu.

When receiving a transaction via ElectronCash 2.9.4 on Tails OS, the transaction says "not verified" even though it has 2 or more confirmations. I'm using latest version of TailsOS 3.3

When I open the same wallet up in Ubuntu using the same version ElectronCash 2.9.4 , it shows the transaction is confirmed like normal.

**Comment by fyookball** [comment]
and you're sure youre connected to a server at the right block height?
