### ISSUE TITLE
did not receive funds for the wallet

### ISSUE THREAD

**Issue by kozzanostra** [fyookball/electrum#254]
Sorry for my English.
I was transferred to my purse bitcoin cash. There were already 8 confirmations. said that you need to write to the technical support of the wallet because the funds already had to be credited. but they are not

**Comment by fyookball** [comment]
you can see the address in your wallet and also on the blockchain? and you're on 2.94.?

**Comment by gonzalorein** [comment]
Hello,
I can't see a transaction which has more than 30 confirmations. I can see it in the "blockchair" but I don't see it in my electron cash wallet. I upgraded to versión 2.9.4.
In Tools -> Network I see that the blockchain is  only 504033 blocks deep, but my transaction belongs to block n. 504327
Why aren't the new transactions loaded?
Thank you.

**Comment by gonzalorein** [comment]
Hello,
I think I solved the issue:
1) Tools --> Network
2) In "Overview" tab deactivate "Select server automatically"
3) In "Server" tab, select a different server by right-clicking on it
4) Since this server was in the longer branch (343e987501) now I see all my transactions
Kind regards.
