### ISSUE TITLE
Can´t open 2fa wallet in version 2.9.4 and can´t disable 2fa in 2.9.3

### ISSUE THREAD

**Issue by ipe1992** [fyookball/electrum#255]
Same kind of problem than many other people but can´t fix it by those helps.

So I have Elecrton Cash wallet 2fa in version 2.9.3. When I try to send by bitcoin cashes to other wallet or change it to bitcoins I always get the same error "error: the transaction was rejected by network rules.
16: mandatory-script-verify-flag-failed (Signature must use SIGHASH_FORKID)
[0100000001316c534818096e99fc72960766e09d06469dbda0799ed98216999c81aafd803300000000fc0047304402202e384cf0882bd14d67"

I have tried to disable 2fa by using seed, but after I have wrote the seed and put Next there reads just "Please wait.." and nothing happens. And this the wallet where i have my coins.

I also tried to do same in Electrum wallet and I managed to disable 2fa, but ofc it doesn´t help to my Electron cash wallet.

Next problem is when I tried to download newest version 2.9.4 and tried to get in to my wallet where is my coins there will be text " Electron-Cash Error      Open console    Terminate"

When I open console there will be this:
verror	13:35:14.683713 +0200	Console	Detected missing constraints for <private>.  It cannot be placed because there are not enough constraints to fully define the size and origin. Add the missing constraints, or set translatesAutoresizingMaskIntoConstraints=YES and constraints will be generated for you. If this view is laid out manually on macOS 10.12 and later, you may choose to not call [super layout] from your override. Set a breakpoint on DETECTED_MISSING_CONSTRAINTS to debug. This error will only be logged once.
oletus	13:35:14.728877 +0200	Console	[0x7fa01f9a8000] Created session
oletus	13:35:14.729182 +0200	Console	[0x7fa01f9a8000] Decoding: C0 0x002A0027 0x0006354A 0x11111100 0x00000000 766
oletus	13:35:14.729211 +0200	Console	[0x7fa01f9a8000] Options: 42x39 [FFFFFFFF,FFFFFFFF] 0001D060
oletus	13:35:14.729296 +0200	Console	[0x7fa01f9a8000] Decoding completed without errors
oletus	13:35:14.729924 +0200	Console	[0x7fa01f9a8000] Releasing session
oletus	13:35:14.838799 +0200	opendirectoryd	queuing request to connection - '<private>'
oletus	13:35:14.839265 +0200	opendirectoryd	queuing request to connection - '<private>'
oletus	13:35:14.845189 +0200	opendirectoryd	queuing request to connection - '<private>'
oletus	13:35:14.845464 +0200	opendirectoryd	queuing request to connection - '<private>'
oletus	13:35:18.735191 +0200	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
oletus	13:35:18.737057 +0200	com.apple.iCloudHelper	MacOS error: -67050
oletus	13:35:23.788806 +0200	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
oletus	13:35:23.790971 +0200	com.apple.iCloudHelper	MacOS error: -67050
oletus	13:35:24.452793 +0200	com.apple.WebKit.WebContent	Current memory footprint: 91 MB
oletus	13:35:28.993715 +0200	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
oletus	13:35:28.995882 +0200	com.apple.iCloudHelper	MacOS error: -67050
oletus	13:35:29.634874 +0200	coreduetd	Modulating pool 1073741825 (variant com.apple.coreduet.budget.energy, type 0, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.635063 +0200	coreduetd	Modulating pool 1073741827 (variant com.apple.coreduet.budget.network, type 0, with dailyval 13000000) to 9322592 from 9104523
oletus	13:35:29.635202 +0200	coreduetd	Modulating pool 1073741828 (variant com.apple.coreduet.budget.network, type 0, with dailyval 100000000) to 71712311 from 70034850
oletus	13:35:29.635404 +0200	coreduetd	Modulating pool 1 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.635666 +0200	coreduetd	Modulating pool 2 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.635826 +0200	coreduetd	Modulating pool 3 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.636076 +0200	coreduetd	Modulating pool 4 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.636209 +0200	coreduetd	Modulating pool 5 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.636623 +0200	coreduetd	Modulating pool 6 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.636848 +0200	coreduetd	Modulating pool 7 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.637041 +0200	coreduetd	Modulating pool 8 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.637226 +0200	coreduetd	Modulating pool 9 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.637298 +0200	coreduetd	Modulating pool 10 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.637412 +0200	coreduetd	Modulating pool 11 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.637566 +0200	coreduetd	Modulating pool 12 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.637651 +0200	coreduetd	Modulating pool 13 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.637842 +0200	coreduetd	Modulating pool 14 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.637970 +0200	coreduetd	Modulating pool 15 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.638115 +0200	coreduetd	Modulating pool 16 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.638247 +0200	coreduetd	Modulating pool 17 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.638404 +0200	coreduetd	Modulating pool 18 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.638653 +0200	coreduetd	Modulating pool 19 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.638756 +0200	coreduetd	Modulating pool 20 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.638876 +0200	coreduetd	Modulating pool 21 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.639017 +0200	coreduetd	Modulating pool 22 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.639123 +0200	coreduetd	Modulating pool 23 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.639297 +0200	coreduetd	Modulating pool 24 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.639450 +0200	coreduetd	Modulating pool 25 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.639549 +0200	coreduetd	Modulating pool 26 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.639694 +0200	coreduetd	Modulating pool 27 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.639819 +0200	coreduetd	Modulating pool 28 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.639956 +0200	coreduetd	Modulating pool 29 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.640153 +0200	coreduetd	Modulating pool 30 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.640261 +0200	coreduetd	Modulating pool 31 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.640385 +0200	coreduetd	Modulating pool 32 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.640557 +0200	coreduetd	Modulating pool 33 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.640639 +0200	coreduetd	Modulating pool 34 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.640821 +0200	coreduetd	Modulating pool 35 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.640929 +0200	coreduetd	Modulating pool 36 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.641130 +0200	coreduetd	Modulating pool 37 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.641214 +0200	coreduetd	Modulating pool 38 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.641297 +0200	coreduetd	Modulating pool 39 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.641376 +0200	coreduetd	Modulating pool 40 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.641459 +0200	coreduetd	Modulating pool 41 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.641529 +0200	coreduetd	Modulating pool 42 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.641600 +0200	coreduetd	Modulating pool 43 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.641736 +0200	coreduetd	Modulating pool 44 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.641920 +0200	coreduetd	Modulating pool 45 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.642099 +0200	coreduetd	Modulating pool 46 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.642239 +0200	coreduetd	Modulating pool 47 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.642476 +0200	coreduetd	Modulating pool 48 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:29.642584 +0200	coreduetd	Modulating pool 49 (variant com.apple.coreduet.budget.energy, type 2, with dailyval 9532) to 7477 from 6744
oletus	13:35:29.642773 +0200	coreduetd	Modulating pool 50 (variant com.apple.coreduet.budget.network, type 2, with dailyval 100000000) to 71712416 from 70034955
oletus	13:35:31.128635 +0200	Microsoft Word	open on /Users/ilpojaaskelainen/Library/Group Containers/UBF8T346G9.Office/MicrosoftShipAssertLog_MSWD1229_Send.txt: File exists
oletus	13:35:34.197561 +0200	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
oletus	13:35:34.199552 +0200	com.apple.iCloudHelper	MacOS error: -67050
oletus	13:35:39.233223 +0200	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
oletus	13:35:39.235263 +0200	com.apple.iCloudHelper	MacOS error: -67050
oletus	13:35:44.028524 +0200	coreduetd	CDDPools: decrement pool 1073741828 [com.apple.coreduet.budget.network] from 71712311 to 71712294
oletus	13:35:44.452456 +0200	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
oletus	13:35:44.454029 +0200	com.apple.iCloudHelper	MacOS error: -67050
oletus	13:35:47.489254 +0200	pboard	Installing local data provider: (uuid:953BCDEB-C16A-4E4E-9F5E-B666681E5DE3 gen: 21 item: 789514 flavor: 'public.utf8-plain-text') for gen: 21 index: 0 item: 789514
oletus	13:35:47.490799 +0200	pboard	[Local Pasteboard] Adding alias: public.text for type: public.utf8-plain-text
oletus	13:35:47.491557 +0200	useractivityd	[PBOARD CONTROLLER] Got type update from client, gen: 21, <private>
oletus	13:35:47.546290 +0200	pboard	Sending pasteboard update to server: <private>
oletus	13:35:47.546410 +0200	pboard	[Local Pasteboard] Adding alias: public.text for type: public.utf8-plain-text
oletus	13:35:47.546987 +0200	useractivityd	[PBOARD CONTROLLER] Got type update from client, gen: 21, <private>
oletus	13:35:47.912315 +0200	useractivityd	PICKING: FB84155F-CA04-4DF1-9813-F1295B022307/<private> as the current item-to-advertise.
oletus	13:35:48.484264 +0200	useractivityd	PICKING: 5A096C8E-3094-42DA-B359-EDA15968FFA8/<private> as the current item-to-advertise.
oletus	13:35:48.515015 +0200	com.apple.WebKit.WebContent	0x7fd20e415d20 - PerformanceMonitor::measureCPUUsageInActivityState: Process is using 0.1% CPU in state: VisibleNonActive
oletus	13:35:49.517249 +0200	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
oletus	13:35:49.519331 +0200	com.apple.iCloudHelper	MacOS error: -67050
oletus	13:35:49.929730 +0200	Safari	ENCODE: Caching encoded userInfo to use until we are marked dirty again, returning encoded result <private> opts={ LSUserActivityContainsFileProviderURL = 0; LSUserActivityContainsUnsynchronizedCloudDocs = 0; UAUserActivityContainsCloudDocsKey = 0;}
oletus	13:35:52.104615 +0200	useractivityd	-- Demoting self.advertisingProcess to nil (was UserActivityClient(pid=2373/com.apple.Safari uuids={5A096C8E-3094-42DA-B359-EDA15968FFA8 })) and trigger pickNewAdvertisement because the previous advertisingProcess had a current activity.
oletus	13:35:52.108892 +0200	useractivityd	PICKING: FB84155F-CA04-4DF1-9813-F1295B022307/<private> as the current item-to-advertise.
oletus	13:35:52.138395 +0200	com.apple.WebKit.WebContent	0x7fd20e415d20 - PerformanceMonitor::measureCPUUsageInActivityState: Process is using 8.1% CPU in state: VisibleAndActive
oletus	13:35:54.454460 +0200	com.apple.WebKit.WebContent	Current memory footprint: 91 MB
oletus	13:35:54.736046 +0200	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
oletus	13:35:54.738202 +0200	com.apple.iCloudHelper	MacOS error: -67050
oletus	13:35:59.235126 +0200	kernel	en0: Received EAPOL packet (length = 145)
oletus	13:35:59.235151 +0200	kernel	inputEAPOLFrame: 0 extra bytes present in EAPOL frame.
oletus	13:35:59.235165 +0200	kernel	inputEAPOLFrame: decrypting key data
oletus	13:35:59.235181 +0200	kernel	inputEAPOLFrame: Received message 1 of 2
oletus	13:35:59.235186 +0200	kernel	installGTK: setting cipher key (flags = 0x0)
oletus	13:35:59.235193 +0200	kernel	GTK-RSC
oletus	13:35:59.235194 +0200	kernel	:
oletus	13:35:59.235196 +0200	kernel	00
oletus	13:35:59.235198 +0200	kernel	00
oletus	13:35:59.235199 +0200	kernel	00
oletus	13:35:59.235201 +0200	kernel	00
oletus	13:35:59.235202 +0200	kernel	00
oletus	13:35:59.235204 +0200	kernel	00
oletus	13:35:59.235205 +0200	kernel	
oletus	13:35:59.235212 +0200	kernel	GTK
oletus	13:35:59.235213 +0200	kernel	:
oletus	13:35:59.235215 +0200	kernel	21
oletus	13:35:59.235216 +0200	kernel	22
oletus	13:35:59.235218 +0200	kernel	5e
oletus	13:35:59.235219 +0200	kernel	9f
oletus	13:35:59.235220 +0200	kernel	59
oletus	13:35:59.235223 +0200	kernel	dc
oletus	13:35:59.235224 +0200	kernel	7c
oletus	13:35:59.235225 +0200	kernel	5e
oletus	13:35:59.235227 +0200	kernel	9b
oletus	13:35:59.235228 +0200	kernel	12
oletus	13:35:59.235230 +0200	kernel	de
oletus	13:35:59.235231 +0200	kernel	de
oletus	13:35:59.235232 +0200	kernel	e6
oletus	13:35:59.235234 +0200	kernel	e4
oletus	13:35:59.235236 +0200	kernel	44
oletus	13:35:59.235238 +0200	kernel	14
oletus	13:35:59.235240 +0200	kernel	
oletus	13:35:59.235507 +0200	kernel	ARPT: 12544.187984: SetCryptoKey() bcmerr[0]:  ea[00:00:00:00:00:00]  R: keyIdx[1] keylen[16] flags[0x0000] algo[4] rxiv(hi[0x00000000] lo[0x0000])
oletus	13:35:59.235525 +0200	kernel	installGTK: GTK installed
oletus	13:35:59.862311 +0200	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
oletus	13:35:59.864552 +0200	com.apple.iCloudHelper	MacOS error: -67050
oletus	13:36:02.022919 +0200	coreduetd	CDDBatteryMonitor:	received batterycallback, currentPercentage:76.902087!
oletus	13:36:02.022360 +0200	kernel	SmartBattery: finished polling type 4
oletus	13:36:02.032944 +0200	powerd	Battery time remaining posted with value 0x200000000480293
oletus	13:36:04.512843 +0200	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
oletus	13:36:05.059147 +0200	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
oletus	13:36:05.061124 +0200	com.apple.iCloudHelper	MacOS error: -67050
oletus	13:36:05.514146 +0200	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
oletus	13:36:10.152917 +0200	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
oletus	13:36:10.154800 +0200	com.apple.iCloudHelper	MacOS error: -67050
oletus	13:36:15.299118 +0200	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
oletus	13:36:15.300747 +0200	com.apple.iCloudHelper	MacOS error: -67050

But when I made new standard wallet in older version 2.9.3 and tried to log in with that wallet in newest version 2.9.4 I get in, but it doesn´t help me because coins are in 2fa wallet.

I use Macbook

Thank you so much if you can help me!:)

**Comment by kozzanostra** [comment]
try version 2.9.2 and use 2fa (you may disable it in this version)

**Comment by ipe1992** [comment]
Thanks kozzanostra, but one more stupid question, from where? Can´t find that version from electroncash.org and maybe it is only safe site to donwload it?

**Comment by ipe1992** [comment]
Okay I found that version but same error, just "Please wait.." and nothing happens

**Comment by fyookball** [comment]
see #41 to disable 2fa

**Comment by quintela78** [comment]
Did you solve the issue? If not, call leonardquintela@gmail.com Maybe I can help you. I rarely go here.

**Comment by fyookball** [comment]
@quintela78 thank you for supporting our users.  regards, JF
