### ISSUE TITLE
Watching Address is less than offline address,How to add them?

### ISSUE THREAD

**Issue by watertech666** [fyookball/electrum#256]
I met the problem for Electron Cash wallet for cold storage. The watching address is less than offline wallet address. Offline wallet has 20 addresses but watching addresses only to be shown as 17. How to add the other 3 addresses to watching wallet?

**Comment by fyookball** [comment]
try from console (view console)

wallet.change_gap_limit(21)

**Comment by watertech666** [comment]
Yes. I did it. Showing “true”.  I don’t see any change. So What’s the next?

**Comment by fyookball** [comment]
are there balances between all the addresses?  I think with cold wallet it cannot see how many -- are some used?  Is it same wallet file but offline or completely new wallet file cold? does it maybe have 3 "used" and 17 unused?

**Comment by watertech666** [comment]
Offline wallet complete address. Watching address 17used. But can”t find 3 same cold wallet.

**Comment by watertech666** [comment]
How can I add 3  losing address to watching wallet?

**Comment by fyookball** [comment]
did you increase the gap limit on the cold wallet? try increaing to 50

**Comment by watertech666** [comment]
Yes. Cold wallet shows 5 extra addresses with red color(it has been used). So the 3(not be used) address (should be in watching wallet)is lost forever?

**Comment by fyookball** [comment]
sorry i didnt understand.  why would they be lost?  Are you sure they are wallet addresses by the way and not imported addresses?

**Comment by fyookball** [comment]
no respones in 8 days. closing.
