### ISSUE TITLE
Transaction rejected by network rules

### ISSUE THREAD

**Issue by cryptoforex** [fyookball/electrum#257]
Hello and error appears when I try to send BCC from my wallet.
Thanks.

![image](https://user-images.githubusercontent.com/30776743/32847893-79abfc54-ca2b-11e7-87d5-243bf4f82388.png)

**Comment by fyookball** [comment]
2fa wallet. see #41

**Comment by cryptoforex** [comment]
Hello,
Ok thanks I see the #41 but I have another problem now I lost my seed but I have my private keys exported.
When I create a new standard wallet and use the private keys to restore it it don´t allow me to continue.
Thanks.
![image](https://user-images.githubusercontent.com/30776743/32880690-d7f38ea2-caae-11e7-99c4-67256e44f79b.png)
