### ISSUE TITLE
How can I change where the blockchain_headers are stored?

### ISSUE THREAD

**Issue by pv8man** [fyookball/electrum#258]
By default on TailsOS, the  blockheaders are stored in /amnesia/.electron-cash/
Which means that after reboot, all data that is not in persistent storage folder is lost and has to be re-synced.

How can I change the directory so I don't have to re-sync all the headers after every reboot?

**Comment by fyookball** [comment]
not sure but isnt this an issue with the wallet file too? Wouldnt you have to copy your wallet file over?

**Comment by Newbie1980** [comment]
Pv8 man. Can u help me install electron on tails?
I am no expert with instructions I might be able. Your help would be appreciated. Thanks

**Comment by pv8man** [comment]
@fyookball 
I keep my wallet and seed inside the persistent storage folder so they are saved (/amnesia/Persistent/Tor Browser)
The blockchain_headers are stored in /amnesia/.electron-cash by default which is not inside the Persistent folder.

**Comment by pv8man** [comment]
@Newbie1980  Sure I'll try to help.
I don't actually install electroncash on tails, I just run the binary file.
Once I figure out how to change where the blockchain_headers are stored, I'll make a tutorial.

**Comment by Newbie1980** [comment]
Thanks dude. We really need this.

What does run the binary file mean.

**Comment by pv8man** [comment]
@Newbie1980 
It means just run the program without installing (like opening an .exe file)
I do it in the terminal, go into the folder and run "electron-cash" file by typing "./electron-cash"

**Comment by pv8man** [comment]
@fyookball 

Just donated $120 of BCH your way for motivation.   Let me know if you are able to come up with anything.

**Comment by Newbie1980** [comment]
Where do i store the exe file. On persistence?

**Comment by fyookball** [comment]
@pv8man  thanks!  I guess the question , if you're keeping your wallet and seed in another folder, why not just keep the blockchain headers there too and copy them over when you're starting the wallet.  

There is no configuration /preferences/option to store it elsewhere than where it is so you'd have to modify the code to customize it if you want it in a different place.

If that is what you're looking to do, I can point you in the right direction:

https://github.com/spesmilo/electrum/blob/e05854f0045138a68edd5f81c1a8d98e60360f24/lib/network.py#L953

the filename variable is defined a few lines of code higher b.path()

**Comment by fyookball** [comment]
does that help?

**Comment by Newbie1980** [comment]
I can donate small money if you can get it working :) thanks

**Comment by fyookball** [comment]
@Newbie1980 you two are talking different issues.  He wants different location of blockchain_headers and i think you just want it work in general, right?

**Comment by Newbie1980** [comment]
I think I will need it working the same way as he needs. Well I think so anyway. 

So I can install on tails and it will be working normal the same fashion as electrum does on tails. Thanks

**Comment by Newbie1980** [comment]
Okay I did what you said and it appears to be working.

Whats the difference in me doin this and "installing". Is there a shortcut I can make instead of using the terminal. 

Thanks again.

**Comment by Newbie1980** [comment]
Thanks again. Think this will do fine but let me know if u do install and how.

**Comment by Newbie1980** [comment]
Okay so everytime u reboot u have to restore wallet from seed. 

How to fix.

**Comment by pv8man** [comment]
@Newbie1980 

Ok, it may be best to NOT install electroncash to Tails.
Tails is meant to be locked down very strictly, it's a pain in the ass to install anything on a Tails OS.

What I do is just run it from terminal.  I store wallet, seed, and a copy of the file "blockchain_headers" all in persistence.  When I reboot, i put the "blockchain_headers" file into the folder "/amnesia/.electron-cash".  That way i don't have to wait for it to re-sync.  It's not perfect but it's good enough.

**Comment by fyookball** [comment]
@pv8man did i answer your question?

**Comment by pv8man** [comment]
@fyookball 

Yes, you did, thanks you very much.

**Comment by Newbie1980** [comment]
I understand issue is closed but how do I copy the blockchain headers file. I had some job trying to copy the wallet. Thanks

**Comment by fyookball** [comment]
how to copy?  cut and paste or cp command?

**Comment by Newbie1980** [comment]
I would probably need tails in front of me but to browse to directory wallet and blockchain headers are in, I found that hard. I know how to copy and paste.

Thank you for being so patient with me.

**Comment by fyookball** [comment]
blockchain_headers are in the folder where the wallet subfolder lives which is called .electron-cash , which usually is in the home user directory

**Comment by Newbie1980** [comment]
Sorry for delay. Okay will try and report back. Thanks
