### ISSUE TITLE
v2.9.4 won't run

### ISSUE THREAD

**Issue by chiwalfrm** [fyookball/electrum#259]
Previous version worked.  But this one had error on start.

```
vmware@vmware-virtual-machine ~ $ Downloads/electrum/electron-cash 
Traceback (most recent call last):
  File "Downloads/electrum/electron-cash", line 95, in <module>
    imp.load_module('electroncash', *imp.find_module('lib'))
  File "/home/vmware/Downloads/electrum/lib/__init__.py", line 3, in <module>
    from wallet import Synchronizer, Wallet, Imported_Wallet
  File "/home/vmware/Downloads/electrum/lib/wallet.py", line 65, in <module>
    import paymentrequest
  File "/home/vmware/Downloads/electrum/lib/paymentrequest.py", line 39, in <module>
    import paymentrequest_pb2 as pb2
  File "/home/vmware/Downloads/electrum/lib/paymentrequest_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
  File "/home/vmware/Downloads/electrum/packages/google/protobuf/symbol_database.py", line 184, in <module>
    _DEFAULT = SymbolDatabase(pool=descriptor_pool.Default())
AttributeError: 'module' object has no attribute 'Default'
vmware@vmware-virtual-machine ~ $ 

```

**Comment by fyookball** [comment]
2fa wallet?

**Comment by chiwalfrm** [comment]
nope.  plain wallet secured by a regular seed.

**Comment by molecular** [comment]
something wrong with google.protobuf lib

can you do the following?

```
#> **cd ~/Downloads/electrum/packages**
#> **python2.7**
Python 2.7.14 (default, Sep 20 2017, 01:25:59)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> **from google.protobuf import descriptor_pool**
>>> **descriptor_pool**
<module 'google.protobuf.descriptor_pool' from 'google/protobuf/descriptor_pool.pyc'>
```

The last line might shed some light about where that descriptor_pool is being loaded from.

**Comment by chiwalfrm** [comment]
@molecular Thanks!  That was it!!  After running "sudo pip2 install --upgrad protobuf" it worked!

`vmware@vmware-virtual-machine ~ $ cd ~/Downloads/electrum/packages/
vmware@vmware-virtual-machine ~/Downloads/electrum/packages $ python2
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.protobuf import descriptor_pool
>>> descriptor_pool
<module 'google.protobuf.descriptor_pool' from '/usr/lib/python2.7/dist-packages/google/protobuf/descriptor_pool.pyc'>
>>> 
vmware@vmware-virtual-machine ~/Downloads/electrum/packages $ sudo pip2 install --upgrad protobuf
[sudo] password for vmware: 
Downloading/unpacking protobuf from https://pypi.python.org/packages/4b/01/d6d8536d27d0619ff0e132ae8ec9c8c4738caa7e9ab6eb868d40e26fafb7/protobuf-3.5.0-py2.py3-none-any.whl#md5=1adddde919d3e676545505c27bdc9857
  Downloading protobuf-3.5.0-py2.py3-none-any.whl (388kB): 388kB downloaded
Downloading/unpacking six>=1.9 (from protobuf)
  Downloading six-1.11.0-py2.py3-none-any.whl
Downloading/unpacking setuptools from https://pypi.python.org/packages/d1/56/fe971f02e075c9e712f23d1fe5c427f573fce178c368deebf5794f80b7c9/setuptools-36.7.2-py2.py3-none-any.whl#md5=cb2de0d103f578273c61f7ff640cf697 (from protobuf)
  Downloading setuptools-36.7.2-py2.py3-none-any.whl (482kB): 482kB downloaded
Installing collected packages: protobuf, six, setuptools
  Found existing installation: protobuf 2.5.0
    Not uninstalling protobuf at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: six 1.5.2
    Not uninstalling six at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: setuptools 3.3
    Not uninstalling setuptools at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed protobuf six setuptools
Cleaning up...
vmware@vmware-virtual-machine ~/Downloads/electrum/packages $ python --version
Python 2.7.6`

**Comment by chiwalfrm** [comment]
I would like to say this issue can be closed, but there are still a bunch of warnings/errors that doesn't prevent the GUI from launching, and otherwise appears to be working.

```
vmware@vmware-virtual-machine ~/Downloads/electrum $ ./electron-cash 
"sni-qt/26066" WARN  09:02:49.866 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
Traceback (most recent call last):
  File "/home/vmware/Downloads/electrum/gui/qt/main_window.py", line 295, in on_network_qt
    self.history_list.update_item(*args)
TypeError: update_item() takes exactly 5 arguments (65 given)
Traceback (most recent call last):
  File "/home/vmware/Downloads/electrum/gui/qt/main_window.py", line 295, in on_network_qt
    self.history_list.update_item(*args)
TypeError: update_item() takes exactly 5 arguments (65 given)
Traceback (most recent call last):
  File "/home/vmware/Downloads/electrum/gui/qt/main_window.py", line 295, in on_network_qt
    self.history_list.update_item(*args)
TypeError: update_item() takes exactly 5 arguments (65 given)
Traceback (most recent call last):
  File "/home/vmware/Downloads/electrum/gui/qt/main_window.py", line 295, in on_network_qt
    self.history_list.update_item(*args)
TypeError: update_item() takes exactly 5 arguments (65 given)
Traceback (most recent call last):
  File "/home/vmware/Downloads/electrum/gui/qt/main_window.py", line 295, in on_network_qt
    self.history_list.update_item(*args)
TypeError: update_item() takes exactly 5 arguments (65 given)

```

**Comment by fyookball** [comment]
if you can run from source, can you try pyqt4 head?

**Comment by chiwalfrm** [comment]
@fyookball , it works now (see my answer above)

**Comment by fyookball** [comment]
clone pyqt4 branch and run it.
