### ISSUE TITLE
How to remove unconfirmed transaction?

### ISSUE THREAD

**Issue by dbeckwith** [fyookball/electrum#26]
I followed the instructions [here](https://electrum.org/bcc2.txt) for getting my BCH in Electron Cash, and now I want to transfer them to another wallet. But Electron Cash will not let me spend my BCH because my history looks like this:

Status | Amount
------------ | -------------
confirmed | `+1.000`
confirmed | `+2.000`
confirmed | `-0.500`
confirmed | `+2.000`
unconfirmed | `-4.500`

So my confirmed balance is `4.500`, but my unconfirmed balance is `0.000`. The unconfirmed transaction is the one I did after the fork to separate my BTC and BCH. How do I remove this transaction so Electron Cash will let me spend my BCH?

**Comment by dbeckwith** [comment]
Well the unconfirmed transaction seems to have disappeared on its own, but now when I try to send my BCH I get this message:
```
error: Your client produced a transaction that is not accepted by the network any more.  Please upgrade to Electrum 2.5.1 or newer.
```

**Comment by thatarchguy** [comment]
I'm experiencing the same issue myself. Currently waiting for the transaction to disappear.
The transaction is on the Bitcoin blockchain explorer but it is not on Bitcoin Cash's.

**Comment by dbeckwith** [comment]
I think re-selecting the server is what made it disappear on mine, not quite sure.

**Comment by dbeckwith** [comment]
Just read #6, do the updates referenced there fix my error? I'm currently on 375be106.

**Comment by thatarchguy** [comment]
@dbeckwith changing the servers got rid of the unconfirmed transaction, thanks.

**Comment by dbeckwith** [comment]
Okay I guess I just have a different issue now.
