### ISSUE TITLE
v2.9.4 doesn't open wallet file

### ISSUE THREAD

**Issue by onuringo** [fyookball/electrum#260]
I downloaded 2.9.4 and, deleted 2.9.0 afterwards. But now 2.9.4 doesn't open my wallet files. When I run it, it asks for password, I put it and click next, then it just disappears.. Can anybody please help?

**Comment by fyookball** [comment]
is it a mac?

**Comment by onuringo** [comment]
it is Win10

**Comment by fyookball** [comment]
run verbose version and give me a traceback please

**Comment by onuringo** [comment]
just tried verbose, it didn't open wallet file either

**Comment by fyookball** [comment]
yeah is there a console output with err msg?

**Comment by onuringo** [comment]
no, it immediately crashes after putting password and clicking next button. doesn't show any error msg

**Comment by onuringo** [comment]
2FA was activated on 2.9.0, but it is not on 2.9.4 i think, if it matters..

**Comment by fyookball** [comment]
its 2fa? ah.  yeah you need move coins out of there.  2fa was never really implemented in E.C. -- please see #41 not our fault... but trustedkey never supported it. so we removed 2fa completely starting in 2.9.4
