### ISSUE TITLE
My Electron Cash 2.9.3 reconecct and disconnect

### ISSUE THREAD

**Issue by mauromoises** [fyookball/electrum#262]
Hello Sir
I was trying to exchange coins with my wallet but at the time of sending them I was shown an error message that I could not broadcast the transfer and from there it disconnected and connected repeatedly, connecting and disconnecting from several nodes.
Then I checked that there was a new version of the electron cash, the 2.9.4 and downloaded and run it on my computer but it did not load and shut down, then I ran version 2.9.3 again and it was executed but it was connected and disconnected again.
then MacbookPro download the version for MacOS download the electron cash wallet and use my seed to restore my wallet there and use my funds, but I had to activate the option BIP38 because I did not accept the seed with 12 words and I did a warning that I was not sure after the configuration and installation, it turned out that the wallet showed me a balance of 0.
Worried I went back to the other computer and went back to running the wallet with version 2.9.3 and it showed me my previous balance but I still had the same problem of connecting and disconnecting
It can not be happening and I am concerned about accessing my funds and that these have not been lost
Please help me

**Comment by fyookball** [comment]
copy your seed out of 2.9.3 and create new wallet on 2.9.4

**Comment by mauromoises** [comment]
It's that I did, My seed of 2.9.3 used it in the new 2.9.4 and showed me that I do not have funds

**Comment by fyookball** [comment]
its a 2fa wallet?
