### ISSUE TITLE
Trezor does't work with Electron Cash 2.9.4 on Windows 7 or Windows 10.

### ISSUE THREAD

**Issue by tl121** [fyookball/electrum#263]
When I ran 2.9.4 on Windows 7 and attempted to install a hardware wallet the  app crashed.  This was on an initial installation.  Starting over and installing a regular wallet first I then tried "new" to install the Trezor and this time the app didn't crash, but it hung indefinitely on a wait window.  At no time did the Trezor display the PIN screen.

Please note that on this system the Trezor works with Electrum 2.9.3.  It also works via the mytrezor web site for both BTC and BCH.

Results were similar on Windows 10.

**Comment by molecular** [comment]
Can you run the verbose version and paste the output?

**Comment by tl121** [comment]
[verbose.txt](https://github.com/fyookball/electrum/files/1485016/verbose.txt)

**Comment by molecular** [comment]
oh no, I see this is a typo that has already been fixed by @Danconnolly

https://github.com/fyookball/electrum/commit/e8505a39bee13e6623f5e3e2fc2c28344025871f

**Comment by fyookball** [comment]
@molecular someone should PR for pyqt4 branch

**Comment by tl121** [comment]
I have tested 3.0 and the problem has been fixed.  Trezor works correctly on Windows 7 and Windows 10.
