### ISSUE TITLE
I cant recovery my wallet from my seed

### ISSUE THREAD

**Issue by mauromoises** [fyookball/electrum#265]
Hi Sir
I have seed that used for electron-cash wallet 2.9.3, It is 12 word list or phrases
But I dont use for new version 2.9.4 I write 12 phrases and not continue dont permit continue for recovery wallet... Only click on Avanced and Show me this
![whatsapp image 2017-11-16 at 8 57 59 pm](https://user-images.githubusercontent.com/33734421/32938418-b71f522c-cb41-11e7-9010-683bf1db5cb2.jpeg)
But I select BIP39 seed an then wallet show me Zero Balance and others address
Please Help me

**Comment by fyookball** [comment]
either you have 2fa wallet (see #41) or you mistyped your seed/have the wrong seed.  do not use bip39 unless it is a bip39 seed

**Comment by markblundeberg** [comment]
This sounds like it may be related to #958 ... user in question may have set a BIP39 passphrase on their BIP39 seed.
