### ISSUE TITLE
Electron Cash 2.9.4 - not sure i can access BCH...

### ISSUE THREAD

**Issue by Laza85** [fyookball/electrum#266]
So i decided to wait a while before trying to claim BCH from my electron cash wallet as I could see there were some teething problems at the beginning, particularly relating to wallets created in Electrum using TrustedCoin 2fa (like mine).

Am I right in saying that on the latest Electron Cash release there is still no way to get around this?

I have the seed for my original Electrum wallet and have even figured out a way to access a 'watching only' version of my Electron Cash wallet, but I cant do a full restore using my seed...

When I enter in Seed on Electron Cash wallet for either standard or multisig, the 'next' box remains greyed out..presumably because it identifies it as a 2fa seed which seems to not be compatible.

I would very much appreciate some guidance or even just an explanation to say its not ready yet but we're working on it at least.

Many thanks

**Comment by fyookball** [comment]
#41

**Comment by Laza85** [comment]
Thanks to Jonald Fyookball for responding, however, I would like to add specifically which advice on #41 worked as I went through every suggestion before eventually finding solution at very bottom

Credit to D412 

Here is what i did presumably not the only method but it worked.

1. Use 2.9.2 and create a new 2FA wallet.
2. Select I already have a seed and put in your wallet´s seed.
3. Click next and Disable 2FA at the next site.
4. Open 2.9.4 and create a new standart wallet on 2.9.4
5. Copy the receiving address from the 2.9.4 wallet.
6. Open your restored wallet on 2.9.2 and make a transaction to your new 2.9.4 wallet address. Be carefull and sent the full amount, it looks like the old versions have connection problems after one TX (I had to use 2.9.3 for this step since the TX was invalid and did not came through with 2.9.2.)


If someone having trouble with finding the older versions of the Wallet: https://github.com/fyookball/electrum/releases

**Comment by fyookball** [comment]
weird that 2.9.2 worked and not 2.9.3... anyway its nice to have old versions :)  I should put a link to them on the wesbite

**Comment by Laza85** [comment]
It worked for a test tx in 2.9.2 then stopped connecting. The final full tx was done with 2.9.3

However, I believe I still would have needed to create the 2fa wallet in 2.9.2, to be able to disable 2fa as the option to create a 2fa wallet in 2.9.3 didnt appear to exist. I had to open the 2.9.2 created wallet via 2.9.3 to get it to work eventually.

Thanks for the good work @fyookball

**Comment by sedaghatfar** [comment]
@fyookball followed the above with a 2fa wallet in 2.9.2 I see the correct balance, but receiving a Server did not answer error when attempting to send to a 2.9.4 wallet, using electroncash.casharia.com server

any advice on next steps

**Comment by BarackO** [comment]
@fyookball Sorry to bother you. I also get the problem to fail to transfer with 2.9.3. And I failed when following the method by@Laza85.
![20180110-2 9 3-](https://user-images.githubusercontent.com/7850632/34770218-423be450-f63b-11e7-92e9-e3ae2cfd2122.PNG)
![20180110-step1](https://user-images.githubusercontent.com/7850632/34769970-736b33ba-f63a-11e7-8ae9-3b91f584b33e.PNG)

Firstly, I create a new 2FA wallet.
When I tried to input my seed, the software stopped here and never went to the next step. I tried electron 2.9.2,2.9.3,2.9.4 and 3.0. But all the 4 versions of electron got the same result.
![20180110-step4](https://user-images.githubusercontent.com/7850632/34770123-f4bf4334-f63a-11e7-8508-549f187d16a2.PNG)

But when I chose create new seed, the software worked well and could go the next step.
![20180110-step3](https://user-images.githubusercontent.com/7850632/34770155-112017f6-f63b-11e7-931f-c1e725bf25c9.PNG)
I really have no methods to resolve the transfer problem. Hope you can offer help. Thanks very much!
