### ISSUE TITLE
(Looks easy to fix) Selected server "Overview" bug

### ISSUE THREAD

**Issue by DesWurstes** [fyookball/electrum#268]
Problem: It doesn't connect to a server automatically, and the overview tab is **ALWAYS** empty.

![](https://i.stack.imgur.com/4qTBC.png)

However, the servers appear on the "Servers" tab.

![](https://i.stack.imgur.com/qLIPt.png)

Also why are some of the servers are not in [this](https://github.com/fyookball/electrum/blob/b32f10a/lib/network.py#L54-L65) list and pre-HF?

**Comment by fyookball** [comment]
are you on version 2.9.4 ?  If not, you need to be.  if so, delete recent_servers file
