### ISSUE TITLE
New contacts (and tx descriptions) aren't saved

### ISSUE THREAD

**Issue by patrikr** [fyookball/electrum#271]
EC 2.9.4, Windows 8.1 64-bit

If I add a new contact everything looks OK, but when I restart the contact is gone.

Also, sometimes transaction descriptions have disappeared when I restart and I have to enter them again.

These bugs are new in 2.9.4, I think.

EDIT: I just did a new transaction, added a description, and then clicked Wallet > Labels > Export. The new transaction's description is missing from the resulting electron-cash_labels.json. After restarting, readding the description and reexporting, the description sticks.

**Comment by marceloneil** [comment]
Does this issue still affect you?

**Comment by patrikr** [comment]
Well, I only upgraded to 3.1.1 a couple of hours ago, but I tried it now and looks good: both a new contact and a new transaction description did stick around after a restart.

**Comment by marceloneil** [comment]
That's good news! Unless the issue comes up again, feel free to close the issue
