### ISSUE TITLE
error: the transaction was rejected by network rules

### ISSUE THREAD

**Issue by bitbadgerman** [fyookball/electrum#277]
16: manatory-script-verify-flag-failed (Signature must use SIGHASH_FORKID)

Hundreds of Bitcoin Cash Are Stuck in Segwit Addresses – But There Might Be a Way to Get Them Back
Stuck in No Man’s Land
https://news.bitcoin.com/hundreds-bitcoin-cash-stuck-segwit-addresses-might-way-get-back/
My opinion: BCC is a real sh... coin

**Comment by fyookball** [comment]
See #41 if its a 2fa issue.
