### ISSUE TITLE
how to restore wallet

### ISSUE THREAD

**Issue by onuringo** [fyookball/electrum#278]
Hello,

I deleted 2.9.0 and installed 2.9.4, now can not reach my wallet and coins. I have my seed phrase. Can you please tell me how to restore my wallet step by step?

I tried  file>new/restore>standart wallet> I already have a seed ......

But it just creates new empty wallet, doesn't restore ex-wallet with coins

P.S. 2.9.4 doesn't allow me to select 2fa and disable it later, as advised work around #41 

Please, help

Thank you

**Comment by mauromoises** [comment]
Is that I think that you should do it in version 2.9.0 or maybe in 2.9.2
In the 2.9.4 it does not let

**Comment by fyookball** [comment]
See #41.
