### ISSUE TITLE
Help with bitcoin cash on pybitcoin

### ISSUE THREAD

**Issue by teran-mckinney** [fyookball/electrum#279]
Hi fyookball,

I'm sure this is not the best way to contact you. Not sure of a better way though. Not directly related to electron-cash.

I wanted to add Bitcoin Cash support to [walkingliberty](https://github.com/teran-mckinney/walkingliberty-python). and decided the best approach would be to add in electrum support, then I could support both electrum and electron-cash.

I did that, and it's working. You can see the latest commits for walkingliberty. I also [forked pybitcoin](https://github.com/teran-mckinney/pybitcoin) and added support for electrum there.

I was able to get transactions to go to electron-cash, but they were rejected. Sure enough, didn't have the SIGHASH_FORK 0x40 bit set. So I have a branch where I'm trying to do that. It is working in the sense that the error message changes, now it seems like the signature is just bad although the deserialze call shows a transaction that at first glance, looks good to me. I'm in way over my head, most of this is all new to me. I've been comparing electrum and electron-cash as a basis for updating the signing functions in pybitcoin.

Here's a transaction as generated with this setup:

```
0100000001edc990f08c1ddd5102dfc7f4af32e7927a14fd8d0bc9996725f38ede549b91f8010000008a47304402203c8cfb468757abae2d3563fc37048c6213096d894f43e4b9f0ddb7c6851471f202204c6ac9a1e16aa80234a3aec208beef80977c38832efd593d849d4a8312eb5004414104e1c33577152151109fe5e02c600f386fda865594c1b989ce0fcfbc0fb0b144a2c8fd98053fd86a4ccc7e0dcbcdd6a15c38eb32a27b3653c54f78ba00ffd71d19ffffffff0210270000000000001976a9141a586975175967c83e2b90422bcd8af9a623156288ac25cc0d00000000001976a91470fb690a177e8721098d90284ab3c3304ee19cd588ac00000000
```

I compared it with an accepted transaction and I did notice that my pub_key and x_pub_key is a lot longer. Maybe compressed vs uncompressed public key? Not sure if it matters, though.

You can see my pybitcoin changes here, where I am setting SIGHASH and such: https://github.com/teran-mckinney/pybitcoin/tree/bitcoincash

Would greatly appreciate any help you can offer. Happy to move this over to my pybitcoin fork's issues section if that works better for you. Not really sure who else to ask at this point.

Thank you,

Teran

**Comment by teran-mckinney** [comment]
Ah, I did not know that. I think pybitcoin hasn't implemented bip143 at all.

https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki

Will try to understand that more and see if there's another Python library that might be easier to port over. If it supports bip143, can I just alter the SIGHASH and be set?

**Comment by fyookball** [comment]
essentially yes.  check the early commits on electron cash in late july.  you should see the relevant code
