### ISSUE TITLE
Error creating send transaction

### ISSUE THREAD

**Issue by dbeckwith** [fyookball/electrum#28]
When I try to send coins I get this message:
```
error: Your client produced a transaction that is not accepted by the network any more.  Please upgrade to Electrum 2.5.1 or newer.
```
I'm on version 2.9.0

Do the updates referenced in #6 fix this? It seems like a different error. I'm currently on 375be10.

**Comment by fyookball** [comment]
are you sure you're connected to the right server? That looks like an error from server side

**Comment by dbeckwith** [comment]
I've been connecting to BCH servers from the fork. Right now I have it connecting to bcc.arihanc.com manually, although the server seems down right now. But it was up last night when I was trying this.

**Comment by fyookball** [comment]
are you still getting this?

**Comment by dbeckwith** [comment]
I will try it again after work today.

On Aug 3, 2017 11:47 AM, "fyookball" <notifications@github.com> wrote:

are you still getting this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fyookball/electrum/issues/28#issuecomment-320026349>,
or mute the thread

**Comment by dbeckwith** [comment]
Well now I am having a different problem where no BCH fork servers are showing up in the network dialog. I put in bcc.arihanc.com manually but it like only connects for half a second every 10 seconds.

**Comment by dbeckwith** [comment]
I will try updating to the latest commit later and see if that fixes anything.

**Comment by fyookball** [comment]
i am about to release a new version, so please try on that and if still issue, open another ticket
