### ISSUE TITLE
Steals private keys

### ISSUE THREAD

**Issue by TomHetmer** [fyookball/electrum#280]
Hiya,

it is evident that private keys are being stolen during the import via a dropped VBA6 app.

Recommendation: Do not steal private keys.

![pk](https://i.imgur.com/RenNAZ8.png)

**Comment by TomHetmer** [comment]
Actually that might just be since https://electrongold.org/ links to this repo?
I'm having too much fun with disassembly I didn't even bother to check if it's the same owner. lol.

**Comment by fyookball** [comment]
what the heck lol.  Yeah, I have nothing to do with BTG or electrongold!  even though they dishonestly put my name on it.  scums.  thanks for posting @TomHetmer

**Comment by fyookball** [comment]
btw @TomHetmer there is a bounty for proving the Electron Cash binaries are non malicious.

**Comment by ftrader** [comment]
@TomHetmer :+1: 

the correct place to raise this issue then:

https://github.com/BTCGPU/BTCGPU/issues

**Comment by molecular** [comment]
https://electrongold.org/:

   Mac dmg signed by Calin Culianu
   All other files signed by Jonald Fyookball

disgusting

**Comment by cculianu** [comment]
Hi -- Calin Culianu here.  I haven't signed shit on that page either.  WTF.

**Comment by molecular** [comment]
They just copied the electroncash.org page and replaced the binaries. They even left links to the signatures and checksums which should all be invalid, of course. Despicable, but what do you expect: the goal was to steal keys, why not make the impression those binaries were signed by respectable persons. Their reputatin doesn't matter to them.

**Comment by cculianu** [comment]
I have contacted the FBI, via their cybercrimes unit.  Hopefully something will come of it.  If not I'll try and call the FBI sometime next week if I don't hear back.

I also contacted the registrar of the domain name -- letting them know and asking when what steps I may take to escalate this further.

I may also contact interpol.

I want this stopped.  Any ideas?

**Comment by fyookball** [comment]
@molecular of course its invalid as there is no such signatures or checksums for anything related to Bitcoin Gold in the keys-n-hashes repo.

**Comment by verretor** [comment]
162.255.165.182 is the same IP address as coinbella.com. coinbella.com/game/pk.php exists.
Proof:
https://archive.is/y7jfQ

The email address of the owner is coinbella@gmail.com

**Comment by t-logix** [comment]
What would be a good place to drop the doxx? 
it is kinda huge though, and many companies / websites are involved.

**Comment by diregro** [comment]
what would be the right place to drop full doxx?

**Comment by EagleTM** [comment]
Also please mail the abuse adress of the whois to get the domain blocked for spreading malware exclusively:

$ whois electrongold.org
Domain Name: ELECTRONGOLD.ORG
Registry Domain ID: D402200000003953612-LROR
Registrar WHOIS Server: whois.namesilo.com
Registrar URL: www.namesilo.com
Updated Date: 2017-10-24T10:16:22Z
Creation Date: 2017-10-18T11:53:16Z
Registry Expiry Date: 2018-10-18T11:53:16Z
Registrar Registration Expiration Date:
Registrar: Namesilo, LLC
Registrar IANA ID: 1479
Registrar Abuse Contact Email: abuse@namesilo.com
Registrar Abuse Contact Phone: +1.4805240066

I've had little success with namesilo so far but maybe the more people try....

**Comment by crypto2day** [comment]
@diregro I know a slack full of people who would love that information. You could email me at Krypt05h1nakam0t0@gmail.com ... would greatly appreciate the info.

**Comment by lichtamberg** [comment]
So did someone really check if this electrum version is safe?

**Comment by molecular** [comment]
@lichtamberg confusingly, *this issue* is about "electron gold", *this repo* (fyookball) is "electron cash". 

If you want to question the safety of electron-cash code that's fine, but I think you should make a different issue for that in order to not confuse people.

**Comment by verretor** [comment]
@molecular Because that's where the fake wallet points.

**Comment by Technophant** [comment]
I contacted http://sitereview.bluecoat.com to get the site reviewed and categorized as phishing.

**Comment by tnkmt** [comment]
@diregro Are you sure that you have the info about the real scammer?

The scammer can use someone else's identity. It's frighteningly easy for scammers to buy real document scans (passport copy, utility bill, etc.) and other personal data on the black market.
