### ISSUE TITLE
Electron Cash / Bitdefender quarantine

### ISSUE THREAD

**Issue by st3fanhans3n** [fyookball/electrum#281]
I like how Electron Cash works on Android, but I can't install the current version Version 2.9.4 on Windows, because my Internet Security Software Bitdefender considers it Malware and locks it into quarantine (I never had a problem with Bitdefender by the way).

Are you guys somewhat aware of this Malware issue and perhaps do you have any suggestions to fix it? Thanks in advance for your help.

(The same appears for Electrum and Electrum LTC)

![image](https://user-images.githubusercontent.com/33913623/33152116-427f06d0-cfdb-11e7-8169-9dfd7b370a24.png)

**Comment by fyookball** [comment]
have to contact bitdefender.  Sorry I don't have time .  Please contact them.
