### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4'

### ISSUE THREAD

**Issue by darkbluelight** [fyookball/electrum#284]
Hi everyone,
I upgraded to 2.9.4 because of the fork. After that I couldn't open my wallet anymore and got this error:

/Electron Cash-2.9.4/gui/qt/main_window.py", line 387, in open_wallet
    self.gui_object.new_window(str(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 26: ordinal not in range(128)

I found the cause and the solution to it, but I'm not really a programmer. The cause is that I use German letters in my wallet like ä,ö,ü etc. Electron 2.9.4 doesn't handle them correctly and crashes.

I googled for a solution, which I found here:
https://www.saltycrane.com/blog/2008/11/python-unicodeencodeerror-ascii-codec-cant-encode-character/#c1130

In main_window.py after line 70: from util import *
You need to put this in:

reload(sys)
sys.setdefaultencoding( "latin-1" )

With this addition 2.9.4 handles wallets with German letters correctly and works again.

**Comment by kyuupichan** [comment]
Does this happen in 3.0?

**Comment by fyookball** [comment]
seeems fixed in latest version.  I tested with ä character in wallet name.
