### ISSUE TITLE
Electron Cash is enforcing arbitrarily high fees

### ISSUE THREAD

**Issue by chernobyl169** [fyookball/electrum#285]
To reproduce this bug easily, send six inputs to a wallet and attempt to spend them all at the same time (craft a transaction of size >1kb), and manually set the fee to 0.00001 BCH. Electron Cash rejects this transaction, saying that the fee is too low to propagate the transaction; it isn't.

See also original report to Reddit https://redd.it/7f1vyn

**Comment by chiwalfrm** [comment]
agree on the transaction size.  mine was 1075 bytes and it had this error.

**Comment by fyookball** [comment]
try 3.0 we fixed fees
