### ISSUE TITLE
Sign Message doesn't work because of 'QString' object has no attribute 'strip'

### ISSUE THREAD

**Issue by cool007zqw** [fyookball/electrum#288]
I tried replacing all strip() in the /gui/qt/main_window.py with trimmed() then it works

**Comment by fyookball** [comment]
This was a pyqt4/pyqt5 thing.  I believe was fixed here:

https://github.com/fyookball/electrum/commit/33f610f1ebd4a22472b0bc296dee6a00d1ba6cad
