### ISSUE TITLE
Electron cash internationalisation

### ISSUE THREAD

**Issue by francis16** [fyookball/electrum#290]
In the preferences there are a lot of possible languages, but whatever is the selected one, it always speaks English ! (Electron Cash 2.9.4 / Linux Debian 9)

Comparing with the Electrum distribution, it looks the lib/locale directory is missing.
Is it the problem ?

Thanks and best regards
Francis

**Comment by fyookball** [comment]
try 3.0

**Comment by francis16** [comment]
Hello,
Either in Git or in the ZIP it looks to be 2.9.4..

Thanks
