### ISSUE TITLE
zero balance

### ISSUE THREAD

**Issue by gity84571** [fyookball/electrum#291]
I have just tried to claim my BCH balance.

I have read thread #41 and also #266 

The solutions proposed in the above seem to require version 2.92 but 2.92 doesn't seem to sync with the network anymore.

I have created two wallets using 2.94 with the seed from my electrum BTC wallet (2FA) - BIP 39 seed 44/0/0 and 44/145/0 -   both show zero balance.

Can someone advise me on how to proceed?

**Comment by fyookball** [comment]
doesnt matter if it syncs. follow the instructions to reset the wallet.  can't comment further here.  all 2fa discussion on #41 please
