### ISSUE TITLE
Android: Server list out of date

### ISSUE THREAD

**Issue by clxcoltz** [fyookball/electrum#292]
When choosing servers in the Android version, the list appears to be much longer and an older version of the post-DAA hardfork servers listed at https://github.com/fyookball/electrum/blob/cash/lib/network.py . As a result when automatically choosing peer the behaviour was erratic, some servers are not able to sync past the hardfork, and I'll have to manually choose a DAA-updated server to sync with. 

The server list appears to be just fine in the desktop (Linux) version.

**Comment by fyookball** [comment]
delete the recent_servers file.

**Comment by clxcoltz** [comment]
I tried to find recent_servers in file manager and in org.electron.electron there's only blockchain_headers and forks/ . Did I miss something? Also tried clearing cache and data file and restoring from seed, nothing changed. Will greatly appreciate if you can tell the location, or perhaps it requires root to see (device not rooted here).

**Comment by fyookball** [comment]
ah dang. you're right , on android its rooted.  that kind of sucks... if you dont hve a ton of history notes you can just restore from seed.

**Comment by clxcoltz** [comment]
Tried uninstalling, reinstalling and restoring from seed, didn't change anything. I guess the only way forward is rooting? =\

**Comment by fyookball** [comment]
just manually input a valid server.

**Comment by clxcoltz** [comment]
That's what I'm doing right now, just hoping this gets some love next release.

**Comment by fyookball** [comment]
yeah would be much better to have non rooted files.  i'll mark this an enhancement. :)
