### ISSUE TITLE
Electron Cash Mac 2.9.4 - Error on correct password

### ISSUE THREAD

**Issue by micoclarke** [fyookball/electrum#293]
Hello, first a disclaimer - I am pretty awful with software and coding language/jargon. Please explain solutions to me like the simpleton I am..

I stored some BCH in an electron cash wallet just after the August hard fork on version 2.9.2. Since then I have not opened the program or logged into the wallet. If it matters, I purchased the BCH outright and did not redeem from BTC.

Today I downloaded 2.9.4 to have a look at my BCH. On opening the program it had remembered my wallet name, but on entering password correctly I get the following error "Electron-cash error" with option to open console or terminate.

I'm not sure where to go from here. I have seen other threads about setting up a new wallet using the seed, but I don't seem to even have the option on the prompt when I open the program. 

Thanks for reading,

**Comment by fyookball** [comment]
was it 2fa wallet?

**Comment by micoclarke** [comment]
Hi fyookball,

I've just checked my google Authenticator app, which has a code for Electron Cash. So yes, this is probably the issue! 

I didn't really understand the instructions on the other threads. Would you be able to explain how I can set up a new wallet? I don't seem to have the option even if I re-install the application.

I'm on a Mac if that's useful.

Thanks,

**Comment by fyookball** [comment]
See #41 thx
