### ISSUE TITLE
Cannot create electron cash wallet from electrum seed

### ISSUE THREAD

**Issue by DDD13** [fyookball/electrum#294]
Hello, when I try to create electron cash wallet to get my BCH, I cannot press 'next' button when I enter the seed. Its grey and cannot be pressed. Anyone know this issue? I check the seed is correct and tried different types of wallet (multi-sig and standard)

**Comment by fyookball** [comment]
is it 2fa?  If so , #41. 

If not, means its typed wrong or mispelled or too much white space.
