### ISSUE TITLE
2.9.4 does not open my wallet

### ISSUE THREAD

**Issue by ItzEPi** [fyookball/electrum#296]
Hello,

I download elctroncash app in august version 2.9.2, i recently decided tomove my bch but while sending it gives some network rules error.So i thought of updating app.The newer version 2.9.4 crashes right after entering the password.Version 2.9.3 works like 2.9.2 gives error while sending.I have google authenticator enabled as well.Please help me out.

One more problem.I can create new wallet using app 2.9.4 but can't open my old wallet, it crashes or simple wont take password. So i decided to open 2.9.2 version went to address tab clicked on the addres which has my bch and took private key from there and went to create a new wallet and i  pasted it in private key option on creating new wallet, it accepted but there were no coins and the address also does not match the address key it is.Please help me out

**Comment by itsybits74** [comment]
hello,
I think I have a similar problem because my wallet won't open it is not taking my SEED words.  HELP

**Comment by fyookball** [comment]
is it 2fa wallet?

**Comment by ItzEPi** [comment]
Yes

**Comment by fyookball** [comment]
see #41 . post there if you need further help. thx.

**Comment by ItzEPi** [comment]
What you mean 2fa? it asks for 2fa while sending not at login

**Comment by fyookball** [comment]
we dont support 2fa regardless so you must create new wallet and move funds. #41.

**Comment by ItzEPi** [comment]
If i was able to move funds i wouldn't have been asking for help

**Comment by fyookball** [comment]
read #41 and if stuck, ask for help there.

**Comment by ItzEPi** [comment]
cannot find anywhere where to post about this issue
