### ISSUE TITLE
did not translate

### ISSUE THREAD

**Issue by iseeyxxx** [fyookball/electrum#297]
I transferred Bitcoin Cash to Bitcoin copied my address from the blockchain platform and the transaction went through. Can you return me back to my Bitcoin Cash balance? I'm just so stupid

**Comment by iseeyxxx** [comment]
cf861a54fe68621ee6c749f853bbc076f69d3d600ed3f9a15c1dd30b8e40b7f4 Transaction indicator

**Comment by fyookball** [comment]
if you sent to blockchain.com wallet you have to contact them
