### ISSUE TITLE
Gpg Public key not found

### ISSUE THREAD

**Issue by attibo** [fyookball/electrum#298]
I'm trying to verify signature for Electron Cash 2.9.4 but gpg tells me that can't found public key.
I've imported all keys published on Electron Cash website with gpg
What's wrong?
Thank you

**Comment by fyookball** [comment]
you imported jonaldkey2 ?

**Comment by attibo** [comment]
Thanks a lot for you reply, now I've imported jonaldkey2 but gpg tells me
than there is no trusted  signature.
this is the screenshot
[image: Immagine incorporata 1]

Il 01 dic 2017 3:17 PM, "fyookball" <notifications@github.com> ha scritto:

**Comment by fyookball** [comment]
so get the sig from the repo
