### ISSUE TITLE
Wrong balance displayed after importing BIP39 seed (from Bitcoin Android Wallet on testnet)

### ISSUE THREAD

**Issue by jimukgb** [fyookball/electrum#299]
It appears that for imported BIP39 transactions (from a seed) it incorrectly assumes that the first output is the change and the second is the payment instead of cross-referencing the addresses when calculating the total balance of the wallet, resulting in incorrect balance being calculated.

**Comment by fyookball** [comment]
testnet is not fully supported, thank you for reporting.
