### ISSUE TITLE
ubuntu bitcoin cash wallet display no servers and doesn't update payment confirmations

### ISSUE THREAD

**Issue by charleshsu168** [fyookball/electrum#30]
## 2. payment history remain **UNVERIFIED** even though it's confirmed 4 times. 

![blockchain no servers](https://user-images.githubusercontent.com/5799190/28905953-e079d2a4-77c8-11e7-9c27-d93146a8db45.png)

![unverified](https://user-images.githubusercontent.com/5799190/28906004-531d8cb0-77c9-11e7-98cf-f28fa5944192.png)

**Comment by charleshsu168** [comment]
this issue is happening with original Electrum wallet. not just this fork.
so  i will raise an issue there too.

**Comment by charleshsu168** [comment]
this seems to be a bug in electrum 2.9 initial blockchainheader download.
see this issue i've openned https://github.com/fyookball/electrum/issues/36

**Comment by fyookball** [comment]
i assume this will be fixed with headers
