### ISSUE TITLE
i sent by mistake BTC to my electroncash wallet

### ISSUE THREAD

**Issue by cevay** [fyookball/electrum#301]
Today i sent by mistake 0,4 BTC from my bitmex exchange acct under my name to my newly created elentroncash acct ..

what can be done?

how can i recover it?

as said above, both accounts are owned by myself.

Cevay

**Comment by fyookball** [comment]
yes, create a new Electrum (not Electron Cash) wallet www.electrum.org and use the same seed when you create your wallet.
