### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by tortuoise** [fyookball/electrum#302]
Just tried the 'Development version' install for this and faced the following issues which I didn't when I installed Electrum in a similar way.
1. Minimum Python version has been lowered from 3.5 to 2.7. Any particular reason ?
2. No syntax specified for proto file: lib/paymentrequest.proto warning. A simple syntax="proto2" will fix this.
3. No module named version: some of the files import version without specifying from where which leads to run time errors. 
If I get feedback these are worth changing, I'll send a pull request.

**Comment by fyookball** [comment]
you need to be on python2... electrum upgraded to python 3 , electron cash is on python2.

start there

**Comment by tortuoise** [comment]
1. Fair enough. Are there plans to upgrade to Python3 ?
I think the other two issues are version independent.

**Comment by fyookball** [comment]
Yes in about a month.  

Can you give me the whole console output for #2 

#3 sounds like you just need to install python modules

**Comment by tortuoise** [comment]
Console output (warning) for 2:
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: paymentrequest.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)

The python modules are installed. I'm not a Python dev - it may be that Python 3.5 onwards you may need to specify import path:
import version -> from . import version

**Comment by fyookball** [comment]
did you install protobuf?

**Comment by tortuoise** [comment]
Yes protobuf installed. Electron-cash is working. Look at the message carefully you'll see it's a **warning** about protobuf syntax version, not an **error**.

**Comment by fyookball** [comment]
ok so its running, that is good
