### ISSUE TITLE
I cannot create wallet for android mobile from the seed of 12 words

### ISSUE THREAD

**Issue by pablomgm** [fyookball/electrum#303]
I cannot create wallet for android mobile from the seed of 12 words.

The import in the windows PC is ok,  but in android the button to continue is not enabled after introducing the seed.

Regards

**Comment by fyookball** [comment]
is it a bip39 seed?

**Comment by pablomgm** [comment]
It's a bip39 seed from Multibit wallet.

**Comment by fyookball** [comment]
bip39 is not supported on android.
