### ISSUE TITLE
Spinning ball when trying to install on mac os

### ISSUE THREAD

**Issue by webiwoo** [fyookball/electrum#304]
I am trying to download 2.9.4 to my mac for the first time but when I launch the application it doesn't move past the first screen and a multicoloured spinning ball comes up and only goes away if I force the application to quit. Can anyone advise how I get past this? Thanks 

![screen shot 2017-12-03 at 21 27 36](https://user-images.githubusercontent.com/34220016/33530151-077525ce-d873-11e7-94f7-b38ec634ee14.png)

**Comment by Bidon15** [comment]
Hi Webiwoo!

I've got the same behavior(spinning ball) on my Mac, although I've installed the app.
Restarting the Mac fixed the issue for me(I've updated my Mac to latest updates and got this issue).

Hope this will help you too,
Best Regards

**Comment by cculianu** [comment]
Let me know if this is still happening on the latest versions!

**Comment by webiwoo** [comment]
Hi, 

I restarted and the problem seemed to fix itself. 

Thanks

**Comment by webiwoo** [comment]
Thanks for the advice. I got it sorted.

**Comment by cculianu** [comment]
Awesome!

Hey @fyookball  -- wanna close this issue? Whenever you get around to it... :)

**Comment by webiwoo** [comment]
Will do, thanks
