### ISSUE TITLE
Istallation problems .exe wont open

### ISSUE THREAD

**Issue by Martinusen** [fyookball/electrum#305]
Hi

When trying to install Electrum cash on win 7 64 bit the .exe won't open. I get the error message "Cannot open self C:\Users\ _..etc etc .._\Electron-Cash-2.9.4.exe or arctive C:\Users\._. etc etc..._\Electron-Cash-2.9.4.pkg".

Any help appreciated.

**Comment by cjmoles** [comment]
me too

**Comment by fyookball** [comment]
its supposed to be run not installed

**Comment by Martinusen** [comment]
Ok,. But it didn't run either. Anyways I could run the application on another machine. Also with the same OS so i have still no clue why this happened,

**Comment by fyookball** [comment]
try the verbose version

**Comment by Martinusen** [comment]
I did. Same problem

**Comment by fyookball** [comment]
can you show me screen shot of verbose console output

**Comment by Martinusen** [comment]
I'm not sure what that is, but if that is something in the program its not possible since it won't open.

**Comment by fyookball** [comment]
you dont know what that is?  You just told you "I did same problem".  Verbose version is on home page of electroncash.org

**Comment by Martinusen** [comment]
Im referring to console output,. not Verbose version.

**Comment by Santobak** [comment]
Hey all 
Please try for the correct software from https://electroncash.org/downloads/
Today i got same problem and my antivirus is blocking the link directly for windows as some trojan...!!

Beware of it and check the size of the new version exe downloaded; it should be around 31MB 
Please check and keep away from trojans..

Thanks, may be it will help you all

**Comment by fyookball** [comment]
Console is black command line window. If you don't even see that it means it is simply not running. Likely anti virus or something

**Comment by Martinusen** [comment]
Yes,. could be the antivirus. But as stated before I got it running on another laptop (with the same antivirus installed oddly enough) so no worries.

Thanx for helping!

**Comment by fyookball** [comment]
3.0 is out
