### ISSUE TITLE
2.9.4 Gets stuck on sending on windows

### ISSUE THREAD

**Issue by clovermebitcoin** [fyookball/electrum#306]
After putting in an amount and clicking send, the UI just stops responding. CPU stays at 25% and memory about 500mb, but never sends or returns an error. Tried on 3 different systems, two windows 10, one windows 7 and get the same response. Also, it's really sluggish to respond in the UI for anything else (such as changing something in preferences will cause a 1-2 minute delay) or in the send box, setting the amount can cause it to not respond for a few seconds.  I'm importing about 260 private keys on the setup, that may be part of the cause.

**Comment by fyookball** [comment]
sounds like youre overwhelming the system.  Just do less keys
