### ISSUE TITLE
wallet error with 2fa without seed

### ISSUE THREAD

**Issue by rjjerez** [fyookball/electrum#309]
wallet error with 2fa without seed

I have wallet 2.9.3 with 2fa
at the time of creating it
for some reason
I do not generate the seed
created on November 10
buy 0.31 BCC
now I can not spend them
the cash is withheld
and I can not reset because I do not have seed
please help me
I need to pay something

**Comment by fyookball** [comment]
You can try to post the question on #41 which is where we look at all 2fa related issues.  If you don't have the seed it may be a problem.  You should always always have your seed
