### ISSUE TITLE
Keepkey hardware wallet support

### ISSUE THREAD

**Issue by sfrdev** [fyookball/electrum#31]
I have 2 keepkey devices that have multisig setup using electrum. When i try to create a new wallet using the hardware device on electron cash, i get a message saying no hardware devices found. This works in electrum though.
When would electron cash come with hardware device support? Or is there any other way through which i can claim my BCH using keepkey and electrum?

**Comment by davided3p** [comment]
will you also be adding support for Digital BitBox as a hardware device?

**Comment by fyookball** [comment]
At some point we will attempt to support hardware.  My understanding is that the hardware first must support the new sighash format.

**Comment by sfrdev** [comment]
Keepkey will be supporting BCH soon. Would you be able to add support after that?
