### ISSUE TITLE
Can't Claim my BCC

### ISSUE THREAD

**Issue by itsybits74** [fyookball/electrum#310]
I saved my BTC onto a USB in August before the fork into my Electom Wallet.  I logged in to my account to move BTC funds and claim my BCC in Electon Cash by restoring from my BTC SEED,  Now, It doesn't seem to recognize my SEED.  I enter seed however I can not go any further from there.  When I click on NEXT, nothing happens.   My question is, what if my SEED is incorrect  Although I doubt it is, what if it is am I at loss?  Is there any possible get around.   Desperate in Nevada

**Comment by fyookball** [comment]
first of all is it a 2fa wallet?

**Comment by Riinehart** [comment]
I have the same issue -- try to restore from seed or from private keys and in both cases the "Next" button stays grayed out. My wallet does have 2fa -- is that the reason? If so, could you please point me in the right direction of what to do? Thanks!

**Comment by fyookball** [comment]
2fa, see #41 and follow up there w any questions.

**Comment by itsybits74** [comment]
Yes it is

**Comment by fyookball** [comment]
@itsybits74 2fa, see #41 and follow up there w any questions.
