### ISSUE TITLE
Android app not working with software rendering

### ISSUE THREAD

**Issue by 94b42c29dd** [fyookball/electrum#313]
I am using a fully free Android distribution (Replicant) that doesn't support GPU rendering. Unfortunately this app crashes when using software rendering. It does work with llvmpipe is enabled but that is unusable in its current state in Replicant. 

Would it be possible to add support for the android software renderer? Also, I hope you can make your app available in the F-Droid. Keep up the good work!

**Comment by fyookball** [comment]
thanks for the request. will mark as enhancement and hopefully be able to do at some point.  Feel free to create bounty for it if urgent
