### ISSUE TITLE
Issues running 2.9.4

### ISSUE THREAD

**Issue by venounan** [fyookball/electrum#314]
I had a 2.9.3 wallet running fine that I restored an electrum seed to in order to claim my bitcoin cash. I can't transfer out of that wallet or create a new one with my seed, when I input my seed it just freezes on "please wait..." and when I try to transfer it says "invalid OTP".

When I try and run the verbose version, the console window automatically closes so I can't get a screenshot of what it says. I'm running win10 64bit.

**Comment by fyookball** [comment]
try latest 3.0
