### ISSUE TITLE
New software version download link seems suspicious !!

### ISSUE THREAD

**Issue by Santobak** [fyookball/electrum#315]
Dear Electron cash team,
The new version link for version 2.9.4 on the site seems to be some malware/trojan, today when i tried to download it; the size was around 9.02 MB and when tried to install some trojan was detected by my quickheal antivirus.
Then i got the link from the server and when downloaded the software 2.9.4 for windows from your server it is around 31MB and worked well.
So just want to inform / bring to notice for the trojan or malware, please take care of same immediately on the official site of https://electroncash.org/ 

Thanks & Regards,
Santobak

**Comment by fyookball** [comment]
which link is suspicious? I'm confused.  The one on electroncash is 31 MB

**Comment by Santobak** [comment]
As i mentioned in my earlier communication, i had faced this problem of some malware got downloaded of  around 9MB and was blocked by my antivirus; that's reason i got to know and got correst software from your other server link..
Please check as per attached file, hope this will clarify your question and please do the needful to correct the link..

Thanks 
![github](https://user-images.githubusercontent.com/34331731/33753577-f395f6de-dc0d-11e7-86c7-2468a9f885d5.jpg)

**Comment by fyookball** [comment]
couldnt find any issue
