### ISSUE TITLE
error: The transaction was rejected by network rules. (16: mandatory-script-verify-flag-failed (Signature must use SIGHASH_FORKID))

### ISSUE THREAD

**Issue by moisesmartinezliranzo** [fyookball/electrum#316]
error: The transaction was rejected by network rules. (16: mandatory-script-verify-flag-failed (Signature must use SIGHASH_FORKID))

This happend when try to send my bitcoin cash
Note: I have 2fa active

![bitcoin cash problem](https://user-images.githubusercontent.com/4712003/33725519-be96c000-db48-11e7-8a2e-d2d610b56d27.PNG)

**Comment by fyookball** [comment]
trustedkey never supported 2fa in BCH.  Please see #41 and post any questions there.
