### ISSUE TITLE
Dont disable 2fa when importing private keys from electrum to electron cash

### ISSUE THREAD

**Issue by dare2win2** [fyookball/electrum#32]
Dont be greedy and compromise your bcc by disabling 2fa on your seed when you import them to electron cash.its really easy for hackers to gain access to your bcc when you dont have 2fa authenticator.fyookball in how many days we can expect the new release to be launched which enables 2fa seed holders to send their bcc out of their electron wallet?

**Comment by fyookball** [comment]
2fa depends on trusted key to do updates.

**Comment by dare2win2** [comment]
I had a word with these guys at trustedcoin.they say that multisig is broken in electron cash so its not supported.whats your comment on this?
