### ISSUE TITLE
Script is looking for python2 module

### ISSUE THREAD

**Issue by tluge** [fyookball/electrum#323]
As far as I understand, xmlrpclib is not part of the python3 libraries any more. However, when (after I build and install) I run electon-cash, I get

> $ python3 /opt/usr/local/bin/electron-cash 
> Error:  No module named 'xmlrpclib'. Try 'sudo pip install <module-name>'

However, there is no such installable module.

I thus tried to edit plugins/cosigner_pool/qt.py as follows, but to no avail:

> from xmlrpc import client
> from xmlrpc.client import ServerProxy as XMLServerProxy

Any ideas?

**Comment by tluge** [comment]
Installing the jsonrpc and jsonrpclib-pelix modules solved it for me.

**Comment by fyookball** [comment]
This is caused by trying to reinstall python3 version in same directory as python 2 version.  Needs clean directory.

**Comment by tluge** [comment]
I doubt that. I am new to Electron cash and started out with version 3.

**Comment by Eibriel** [comment]
Same here, fresh install on virtualenv initiated with `virtualenv -p python3 venv` using python 3.5.2

**Comment by JulienFavre** [comment]
I'm having the same problem when running version 3.1 on Linux:
`Error: No module named 'xmlrpclib'. Try 'sudo pip install <module-name>'`
 
But version 3.0 is still working perfectly, I'm not sure what's going on...
I tried installing jsonrpc and jsonrpclib-pelix but it didn't help

Any suggestions?
I'm not a coder, I have very basic knowledge of Python.
