### ISSUE TITLE
Problems installing python3-pyqt5

### ISSUE THREAD

**Issue by mic702** [fyookball/electrum#327]
I have Electrum installed and running no issues, and that has the same dependencies I believe 

mard >> [~/Documents/Electron Cash-3.0] $uname -a
Linux mard-desktop 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

mard >> [~/Documents/Electron Cash-3.0] $./electron-cash 
Error: Could not import PyQt5 on Linux systems, you may try 'sudo apt-get install python3-pyqt5'

mard >> [~/Documents/Electron Cash-3.0] $sudo apt-get install python3-pyqt5
[sudo] password for mard: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-pyqt5 : Depends: libqt5designer5 (>= 5.0.2) but it is not going to be installed
                 Depends: qtbase-abi-5-5-1
E: Unable to correct problems, you have held broken packages.

mard>> [~/Documents/Electron Cash-3.0] $sudo apt install qtbase-abi-5-5-1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package qtbase-abi-5-5-1 is a virtual package provided by:
  libqt5core5a 5.5.1+dfsg-16ubuntu7.5 [Not candidate version]
  libqt5core5a 5.5.1+dfsg-16ubuntu7 [Not candidate version]

E: Package 'qtbase-abi-5-5-1' has no installation candidate

mard >> [~/Documents/Electron Cash-3.0] $sudo apt install libqt5designer5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libqt5designer5 : Depends: qtbase-abi-5-5-1
E: Unable to correct problems, you have held broken packages.

**Comment by fyookball** [comment]
did you install in a different (fresh) directory?
