### ISSUE TITLE
SHA256.ElectronCash-3.0-PORTABLE.txt

### ISSUE THREAD

**Issue by HeimoL** [fyookball/electrum#328]
checking the checksum on the downloaded file i find the SHA1 instead which is different to SHA256. how can i be sure the file is alright? 

![grafik](https://user-images.githubusercontent.com/34415577/33804507-cc5fcef6-dda6-11e7-9795-41dd11bcda57.png)

**Comment by fyookball** [comment]
you need a sha256 check. try 7-zip on windows
