### ISSUE TITLE
No module named 'dns'

### ISSUE THREAD

**Issue by bstin** [fyookball/electrum#329]
Trying to run on Fedora 27 results in:

Error: No module named 'dns'. Try 'sudo pip install <module-name>'

What is the actual module name? 

As a side note, you should probably include a pip freeze from your virtualenv as a "pip.freeze" file as part of the source distribution.

**Comment by bstin** [comment]
Replying to my own comment to help others who arrive here via google/ddg search:

## Its a little convoluted to install Electron Cash 3.0 on Fedora 27, however I did get it working (I hope / think?) 

Here are the basic steps:

1. Install following from dnf: 
`
sudo dnf install python3-dns
sudo dnf install python3-pyaes
sudo dnf install python3-ecdsa
sudo dnf install python3-qrcode
sudo dnf install python3-pbkdf2
sudo dnf install python3-google
sudo dnf install python3-google-api-client-1.6.3-2.fc27.noarch 
sudo dnf install python3-google-apputils-0.4.2-9.fc27.noarch 
sudo dnf install python3-protobuf
sudo dnf install python3-qt5
`

2. Install the old jsonrpclib via pip3
`
pip3 install jsonrpclib
`

*NOTE: This install the python2 version of jsonrpclib which must then be converted by doing following:*

3. Convert jsonrpclib to version 3.

`
2to3 -w jsonrpc.py
2to3 -w SimpleJSONRPCServer.py
`

4. Finally, edit SimpleJSONRPCServer.py file to make sure uses python3 declarations

`
#lines 50-53
from xmlrpc.client import Transport as XMLTransport
from xmlrpc.client import SafeTransport as XMLSafeTransport
from xmlrpc.client import ServerProxy as XMLServerProxy
from xmlrpc.client import _Method as XML_Method

...
#line 168
from http.client import HTTPConnection
...
#line 186 change to
class UnixHTTP(HTTPConnection):
`

That should hopefully get you going. 

Tips appreciated if this helps you: 16WmsryFxpzongtH7t54ekgSG8ZPFkGc68

**Comment by fyookball** [comment]
glad you got it going.  Sounds like a convoluted way to install a module.

**Comment by hegjon** [comment]
> Install the old jsonrpclib via pip3

jsonrpclib have switched upstream to -pelix as of 0.3.1 on Fedora 27 and later: https://apps.fedoraproject.org/packages/python-jsonrpclib

**Comment by hegjon** [comment]
Do you know why python3-google-api-client-1.6.3-2.fc27.noarch python3-google-apputils-0.4.2-9.fc27.noarch is required? I am working on a RPM for Fedora

**Comment by bstin** [comment]
Hi Hegjon. 

You know, as I research more....I don't think python3-google-api-client is required at all. I think in my quest to get it working I was trying to get the protobuf stuff working and that got installed by accident.

I just uninstalled python3-google-api-client and electron-cash still launches fine, so safe to say scratch that.

Also, regarding the python-jsonrpclib issue....Yes, I noticed about 2 days ago that a new python3-jsonrpclib-0.3.1 appeared therefore I uninstalled the mangled one I had done 2-to-3 on (via pip3). Instead I installed the regular version in Fedora repositories via dnf and all is working fine.

Glad you are getting an RPM together....will you be maintainer or is this just for personal?

**Comment by hegjon** [comment]
> Also, regarding the python-jsonrpclib issue....Yes, I noticed about 2 days ago that a new python3-jsonrpclib-0.3.1 appeared therefore I uninstalled the mangled one I had done 2-to-3 on (via pip3). Instead I installed the regular version in Fedora repositories via dnf and all is working fine.

Great to hear that the updated version is working fine.

> Glad you are getting an RPM together....will you be maintainer or is this just for personal?

I have had personal RPMs for Electron Cash since 2.9.3, but my main goal is to maintain it in Fedora once I feel it have matured enough. I want #340 to be working before sending the RPM for review.

**Comment by hegjon** [comment]
It have been submitted for review, see #341 for more information

**Comment by hegjon** [comment]
Just wanted to let you know that the package is now in the standard Fedora repository: https://apps.fedoraproject.org/packages/electron-cash

Quick intro: https://youtu.be/DUh1_qkPass
