### ISSUE TITLE
Error running from cmd line

### ISSUE THREAD

**Issue by pomocrypto** [fyookball/electrum#33]
Used Git CMD to clone the repo, and used 

`python setup.py install
`
to successfully (i think) install dependencies. When I try to run the program using 
`python electron-cash` 
I'm returned:

`C:\Users\jacks\electrum>python electron-cash
Traceback (most recent call last):
  File "electron-cash", line 71, in check_imports
    import jsonrpclib
  File "C:\Users\jacks\AppData\Local\Programs\Python\Python36\lib\site-packages\jsonrpclib-0.1.7-py3.6.egg\jsonrpclib\__init__.py", line 5, in <module>
  File "C:\Users\jacks\AppData\Local\Programs\Python\Python36\lib\site-packages\jsonrpclib-0.1.7-py3.6.egg\jsonrpclib\jsonrpc.py", line 50, in <module>
ModuleNotFoundError: No module named 'xmlrpclib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "electron-cash", line 90, in <module>
    check_imports()
  File "electron-cash", line 73, in check_imports
    sys.exit("Error: %s. Try 'sudo pip install <module-name>'"%e.message)
AttributeError: 'ModuleNotFoundError' object has no attribute 'message'`

What am I missing?

**Comment by fyookball** [comment]
sounds like your jsonrpclib is missing dependencies of its own.  try to install xmlrpclib

**Comment by pomocrypto** [comment]
@fyookball First off can I just say that it's ridiculous that you are personally responding to support tickets without any help from other members of the community. I bet you are exhausted and I really appreciate the service you're providing, and the fact that you are invested enough to even acknowledge half cocked tickets like this one.

I'm not a coder but I gave it my best shot updating the xmlrpclib in python to no avail. I don't expect you to walk me through this but I would mention that there are probably a lot of users out there like me who had 2fa wallets and can now access their coins but not spend them. Since I'm not a coder I have no idea how much rigamarole it is to push out a new version with the fix applied, but I'll be waiting with bated breath, especially since Bittrex just turned on BCC deposits.

I
