### ISSUE TITLE
No packages directory in ElectronCash-3.0.tar.gz

### ISSUE THREAD

**Issue by slanted3** [fyookball/electrum#332]
...which is inconsistent with the README.rst file

"If you downloaded the official package (tar.gz), you can run
Electron Cash from its root directory (called Electrum), without installing it on your
system; all the python dependencies are included in the 'packages'
directory."

And obviously I get problems running it "from source" too.

**Comment by willyloman** [comment]
@slanted3: Did you run `python3 setup.py install` prior to trying to run `./electron-cash`? I just downloaded the `.tar.gz` on the latest macOS and am able to run the program.

Are you on macOS or Linux?

**Comment by slanted3** [comment]
It is Linux, Ubuntu 16.04 64bit. I tried to run without the setup command yes.
My previous installation works, and experience tells me I get hell if I do the install.

**Comment by fyookball** [comment]
ok may be an issue with the new release process. i'll investigate.

**Comment by QuavoLecso** [comment]
same problem here
