### ISSUE TITLE
Missing Electron Cash v3.0 .dmg download for macOS

### ISSUE THREAD

**Issue by willyloman** [fyookball/electrum#334]
I'm on macOS 10.13.1 and *am* able to run the Linux build, but I'm curious to know if/when there will be a v3.0 `.dmg` available for download on the [website](https://www.electroncash.org/) for easier install. 

I think it's a good idea to release the v3.0 `.dmg` from a usability point of view for users who are less comfortable installing from source.

Awesome work iterating quickly from v.2.9.4!

**Comment by fyookball** [comment]
done
