### ISSUE TITLE
Windows Defender reports Trojan: Win32/Fuerboos.B!cl

### ISSUE THREAD

**Issue by proehlen** [fyookball/electrum#335]
Followed these steps:
1. Went to https://electroncash.org/#download
2. Clicked on Electron-Cash-3.0.exe download
3. Attempted to open the program but it failed with an error message
4. Windows Defender pops up a warning and on further inspection it has quarantined the executable with these details reported:

![image](https://user-images.githubusercontent.com/8384068/33930034-249adbbe-e01e-11e7-92dd-8159eef1932d.png)

**Comment by gasull** [comment]
[Uploaded file to VirusTotal](https://www.virustotal.com/#/file/cb52998a067a1bf086b2f231b5f5c27ec362d4c7d12a3922f8047a230063724b/detection).  It's detected, falsely or not, as a virus by 2 antivirus.

**Comment by fyookball** [comment]
only solution for this is contact those virus detection companies and have it whitelisted.  Any help is appreciated!

**Comment by gasull** [comment]
I just found that [Electrum has even more false positives than Electron Cash](https://www.virustotal.com/#/file/f030699fe93e38d882c0734664207000756a32d0606ed714473f2f29e8156a31/detection).  Maybe this needs to be fixed upstream.
