### ISSUE TITLE
Document how to verify signature

### ISSUE THREAD

**Issue by hegjon** [fyookball/electrum#340]
I want to verify the tar-ball containing the sources before building for Fedora.

What I tried so far: https://jonny.fedorapeople.org/electron-cash.spec

Example from command line:
```
$ gpg2 --export --export-options export-minimal D56C110F4555F371AEEFCB254FD06489EFF1DDE1 > gpgkey-electron-cash.gpg

$ gpgv2 --keyring ./gpgkey-electron-cash.gpg ElectronCash-3.0.tar.gz.sig ElectronCash-3.0.tar.gz
gpgv: no valid OpenPGP data found.
gpgv: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.

$ echo $?
2
```
What is the recommended way for verifying the published tar-balls?

**Comment by hegjon** [comment]
Sorry, I used the none-raw URL for the .sig file. It would still be nice to have a small guide to do a proper validation

**Comment by stabwah** [comment]
Added in PR https://github.com/fyookball/electrum/pull/462

**Comment by fyookball** [comment]
@stabwah ty
