### ISSUE TITLE
 Review official Fedora package that is sent to review

### ISSUE THREAD

**Issue by hegjon** [fyookball/electrum#341]
This is a message that informs you that I have submitted a review request of Electron Cash as a Fedora package:

https://bugzilla.redhat.com/show_bug.cgi?id=1526429

It would be great if you could spend 2 minutes just checking that summary, URL, description etc is correct. We also verify the signature for the tar-ball before the build, it would be great that this is also reviewed.

Feedback can be left here or in the bugzilla ticket. Thanks

**Comment by hegjon** [comment]
It would be nice if developers and tester could test the official package that is in Fedora testing and give feedback here https://bodhi.fedoraproject.org/updates/FEDORA-2017-b329e6d79d

Howto:
`sudo dnf install --enablerepo=updates-testing electron-cash`

**Comment by rfjakob** [comment]
I have tested the package on Fedora 27 x86_64. Seems to work fine, thanks!

* Launching works
* Menus work
* Importing private key works
* Watch-only wallet works

![screenshot from 2017-12-22 23-20-25](https://user-images.githubusercontent.com/286847/34313854-c4a5252c-e76e-11e7-936e-7d9d48b66d23.png)

**Comment by hegjon** [comment]
Great to hear, thanks for testing.

**Comment by hegjon** [comment]
I made a screen cast, do you think I skipped the backup section too fast? I wanted it to be short, but not if people are loosing money.

[Electron Cash on Fedora in under 2 minutes](https://youtu.be/DUh1_qkPass)

**Comment by hegjon** [comment]
Closing issue since the package have been included into the official Fedora repository: https://apps.fedoraproject.org/packages/electron-cash
