### ISSUE TITLE
PROBLEM!! MISSING ACCESS to BTC Address After import private keys from Electrum wallet (2.9.3) to Electron Cash wallet (3.0)

### ISSUE THREAD

**Issue by Mhyza** [fyookball/electrum#347]
I created Electron Cash wallet by importing key from BTC Electrum wallet (2.9.3) to have the same wallet address name (BTC and BCH): 16YoT6uDGUhbdLEd8HzQx5fQdT2ziLpb5v
After open BTC Electrum wallet (password protected), ALL BTC was sweeped to unknown BTC address: 1LKQR5S26uZr7x3EDFUWRcrVFM5y3bTHCF
This address is not among my private key addresses.. HOW can I access MY BTC please?

https://blockchain.info/tx/2667bfa044ad5feb3023f38e00efbed35728ef6020c2de5dd628b1c63efb209b

**Comment by fyookball** [comment]
looks suspicious.  possible hack/virus?  i see a very high fee on that tx
