### ISSUE TITLE
Electron Cash Error since 2.9.4

### ISSUE THREAD

**Issue by hulkerbse** [fyookball/electrum#348]
Since Version 2.9.4 i can not login to my default wallet.
<img width="576" alt="screenshot 2017-12-18 23 39 22" src="https://user-images.githubusercontent.com/34664304/34131660-cea3ed58-e44c-11e7-9c01-11551ae91b3a.png">

Any ideas ?
I tried the older versions an it works.

I also tried to create a new Wallet with the known seed or private key but both were not recognized. Doesnt work with them. In the older Versions it does but i can not send any bch from the older verions because they rejected by network rules.
Thanks for you help!

**Comment by fyookball** [comment]
let me guess. 2fa wallet?

**Comment by hulkerbse** [comment]
Maybe.
I don't know anymore because i can not login :D But i think it was, yes.

**Comment by hulkerbse** [comment]
But any ideas how to fix that ?

**Comment by fyookball** [comment]
Please see #41 and follow up there for help. thanks!
