### ISSUE TITLE
Can't install Electroncash 3.0 from my seed

### ISSUE THREAD

**Issue by vologdagde** [fyookball/electrum#349]
Hello,
I had bitcoins in Electrum wallet prior to BCC fork 8/1/17 on computer A. I moved BTC (bitcoin) to hard wallet sometime in the mid of august and because I was pretty green about crypto did not realize I can claim BCC (Bitcoin Cash).
So... Now in December I understand a little more.... :))  I have zero balance in my Electrum. I lost access to computer A (Ubuntu - Linux which I was just testing the new operating system) and had to download Electrum on computer B (Windows 10). I had the seed saved and was able to get into my Electrum wallet...
Now I started the process of claiming my BCC.
I downloaded electroncash 3.0 and started installation as an administrator.
- the first screen - default_wallet I clicked next
- "what kind of wallet do you want to create" - I choose standard
- "do you want to create a new seed..... " - I choose I have a seed"
- "enter seed" - I entered my seed (from my old electrum wallet where I had BTC but "Next" button  is NOT getting active - so I cannot proceed from here.... My guess I don't know what I am doing... and kind of stuck... not sure where to find help.
Please guide me if you could.
Thank you.

**Comment by vologdagde** [comment]
Continued...
I borrowed the computer C from my friend and installed the ElectronCash on the computer C and tried to run electroncash from there... same issue....

**Comment by fyookball** [comment]
is it a 2fa wallet?

**Comment by vologdagde** [comment]
I used Google Authenticator through trusted coin

**Comment by fyookball** [comment]
see #41 and post there if need help.
