### ISSUE TITLE
QRCODE: receiving address in electron cash wallet is recognized as btc address.

### ISSUE THREAD

**Issue by charleshsu168** [fyookball/electrum#35]
I can't send payment to electron cash wallet from Coinomi mobile phone wallet.
electron cash wallet's QR code is recognized as **BTC, NOT BCC,** address when i scanned it in coinomi mobile app.
therefore, it's **not** possible to send BCC coins to electron cash wallet.

**Comment by charleshsu168** [comment]
NOTE this might be a bug with Coinomi qr code scanner, NOT electron-cash wallet.
Not sure. i can still send payment from electron-cash to electron-cash wallet.

**Comment by charleshsu168** [comment]
please close this bug. it's not problem with electron cash wallet. coinomi QR scanner has a bug.

**Comment by fyookball** [comment]
but thank you for raising the issue , bitcoin cash needs to decide on scanner prefix.  i have passed that along to the appropriate people.

**Comment by shawnpringle** [comment]
Coinomi uses a prefix like 'bitcoin:' or 'doge:' before each address before it is converted to a QR code.  I believe the BIP for QR codes specify this idea.  If you are accepting something that is not the segwit bitcoin, the text shouldn't start with 'bitcion:'.

**Comment by molecular** [comment]
@charleshsu168 what's the prefix coinomi uses for Bitcoin Cash?

I can't even add Bitcoin Cash as a coin in coinomi (android version)

**Comment by shawnpringle** [comment]
There is a way.  Didn't you get the instructions in COINOMI itself?  I wish
I had had my coins over on coinomi.  There would have been no need to
install another program.

**Comment by shawnpringle** [comment]
Coinomi formats addresses like this before creating a QR code: bitcoincash:1KVqnW7wZwn2cWbrXmSxsrzqYVC5Wj836u

**Comment by charleshsu168** [comment]
@molecular you need to update coinomi to latest version.

**Comment by molecular** [comment]
@charleshsu168 how to update? Playstore says there is no newer version.

**Comment by molecular** [comment]
deadalnix suggests we use *xbc* as prefix for bitcoin cash.

**Comment by shawnpringle** [comment]
https://medium.com/@coinomi/collecting-your-free-bitcoin-cash-coins-44fcc6008bb6

**Comment by molecular** [comment]
thanks, @shawnpringle I checked it out.

Coinomi uses **bitcoincash** as prefix

**Comment by juriise** [comment]
A workaround is to enter the address in the receiving address by hand in stead of the qr-code.

**Comment by juriise** [comment]
We have this list of uri schemes, bitcoin is included with reference to Dave Thaler, but no bitcoincash:

https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

**Comment by juriise** [comment]
I pinged mr David Thaler, the owner of the bitcoin: uri scheme. If we go for bitcoincash:, the same as coinomi does, it should weigh heavily.

There is also a camera/qrcode function for sending in Electron Cash, I don't know if it works but it should give a big warning if the receiving uri is bitcoin:, not bitcoincash:

**Comment by fyookball** [comment]
ok let me know, id like to get this fixed @juriise

**Comment by shawnpringle** [comment]
Rather than fight Coinomi, it is better to just adopt what is out there.
Now XBC looks like a good currency symbolnfor bitcoincash.

**Comment by juriise** [comment]
I got no response from mr David Thaler

see also

https://github.com/Bitcoin-ABC/bitcoin-abc/issues/68

which also has a link to

https://lists.linuxfoundation.org/pipermail/bitcoin-ml/2017-August/000073.html

**Comment by zander** [comment]
> Update: Zander has already decided on bitcoincash: for Bitcoin Classic

To be clear, I followed the consensus on the mailinglist discussion.

**Comment by molecular** [comment]
Skimmed the ml. Harding, Zander, coinomi... enough for me to go for *bitcoincash:*

**Comment by molecular** [comment]
urgh: grepping through the sources I just found we have a similar issue with payment requests (https://github.com/fyookball/electrum/blob/a2245ea0ee9ca152526a4ab5ac54971f5e2d3b35/lib/paymentrequest.py#L52-L53):

    REQUEST_HEADERS = {'Accept': 'application/bitcoin-paymentrequest', 'User-Agent': 'Electrum'}
    ACK_HEADERS = {'Content-Type':'application/bitcoin-payment','Accept':'application/bitcoin-paymentack','User-Agent':'Electrum'}

**Comment by molecular** [comment]
sorry for the commit reference spam, I'm learning to squash commits.

**Comment by molecular** [comment]
more complete set of changes:

molecular/electrum@b7412356232a4b93b63b5c4229dbbd42f15236f2

**Comment by fyookball** [comment]
ready to pull?

**Comment by molecular** [comment]
I made a pull request towards your repo: https://github.com/fyookball/electrum/pulls
