### ISSUE TITLE
Opened account TODAY I created seed before I sent , is this a problem??? WALLET EMPTY 

### ISSUE THREAD

**Issue by TitaniBitDAVO** [fyookball/electrum#352]
I transferred bitcoin from bittrex to the address I copy/pasted under "Receive" tab. I did this at 2pm today, there is still nothing in my wallet? What should i do? Bittrex confirmed the transfer.

**Comment by TitaniBitDAVO** [comment]
I looked up address on block explorer and it says its at 22 confirmations, still nothing in my wallet. Please help

**Comment by fyookball** [comment]
if you have the address in your wallet it should be same address on blockchain... make sure youre not confusing BTC for BCH and also make sure that the wallet is sync'd properly.

**Comment by TitaniBitDAVO** [comment]
I'm a noob. Need serious help. I sent BTC (Bitcoin) to the address in my electron cash wallet. It's still not there this morning. Can someone please email me and help me, I'm freaking out. email is jad8depo@gmail.com

**Comment by TitaniBitDAVO** [comment]
Fyookball, can you please help me here? I sent the BTC (bitcoin) from bittrex account to newly setup Electron Cash Wallet, I sent to the address that was located under my receive tab. I have no coins in my Electron wallet and it is gone from Bittrex

**Comment by kyuupichan** [comment]
Right click the address you sent to in the address tab - view menu if you haven't enabled it. Import that private key into electrum. Easy.

**Comment by TitaniBitDAVO** [comment]
I have a Mac. I don’t understand

**Comment by TitaniBitDAVO** [comment]
Can you be more specific. Please and thank you in advance.

**Comment by TitaniBitDAVO** [comment]
Talk to me like I’m an 8 yr old
