### ISSUE TITLE
Electron-Cash Error

### ISSUE THREAD

**Issue by sWShakespeare** [fyookball/electrum#353]
Non-specific, won't open :(

All details https://www.reddit.com/r/btc/comments/7kx0xc/electroncash_error/

**Comment by fyookball** [comment]
what version and platform?

**Comment by andosteinmetz** [comment]
I'm getting the same error – using Electron-Cash v3.0 on Mac OS 10.9.5. I looked on the Console and saw nothing more specific than "Electron-Cash Error"

**Comment by fyookball** [comment]
Try 3.1.2 , and let me know if still a problem.
