### ISSUE TITLE
Help please- accidentally sent btc via evercoin into electron cash

### ISSUE THREAD

**Issue by jjsph** [fyookball/electrum#354]
So i meant to purchase BCH with LTC to send to my Electron Cash wallet via EVERCOIN, but I accidentally hit BTC instead of BCH. Evercoin is being absolutely no help. I'm unsure where to start. Am i shit out of luck?

**Comment by jjsph** [comment]
https://live.blockcypher.com/ltc/tx/0f873741a549f49442d59097ea32018aa010da2f2f152e0ed4e4b444a1460353/#spentby-0862a7840a3589c0eb993e7c77ee080ee892e95c17f6fd4a2ec87d03ea5cc9bb-0

**Comment by jjsph** [comment]
CAn somebody contact me so i can share with them the receiving wallet address to get this sorted?

**Comment by fyookball** [comment]
Sounds like you accidentally bought BTC instead of BCH.  I think if you want BCH you have to then sell your BTC and get BCH.  I dont think this has anything to do with this wallet.

**Comment by jjsph** [comment]
Hey, I did accidentally purchase btc AND sent them to my electron cash
wallet, where they seemed to have disappeared. I see the transaction on the
blockchain. Can you tell me how I can retrieve these btc that apparently
vanished into thin air? I'm desperate

**Comment by jjsph** [comment]
When I open my electron cash wallet, there's nothing. When I open my
electrum ltc wallet, I see my outgoing transaction.  They're lost in
cyberspace.. need help. It's a huge loss for me based solely on my own fuck
up

**Comment by jjsph** [comment]
Basically how do i recover the 0.03341608 BTC that I sent to my Electron Cash BCH wallet? I purchased the BTC with Litecoin via Evercoin. Didn't realize i hit btc instead of bch. I know they're there, how do i get them back?

**Comment by jjsph** [comment]
transaction 0f873741a549f49442d59097ea32018aa010da2f2f152e0ed4e4b444a1460353

sent 0.03341608 BTC

???

**Comment by jjsph** [comment]
electron cash has my 0.03341608 BTC, but i cannot see it or move it somewhere else

**Comment by kyuupichan** [comment]
Electron cash has nothing. Right click the address you sent to in the address tab, show private key, import into electrum as a new wallet

**Comment by jjsph** [comment]
Thanks, I did that just now- imported into electrum as a new wallet. Able
to see my bitcoins there. I sent them back to coinbase just to route them
back to my bank account.

This is Electrum to Coinbase
tx: c381339083383ffd29e7cc611ce2ce446a37db2996559e8483da9a92fec0b5ed
This is what I saw when I imported to new wallet (initial amount coming
in): c381339083383ffd29e7cc611ce2ce446a37db2996559e8483da9a92fec0b5ed

Can you tell me if it worked?

**Comment by kyuupichan** [comment]
Based on your own explanation I'm sure it did
