### ISSUE TITLE
accidental transfer of BCH to BTC wallet

### ISSUE THREAD

**Issue by mastkis** [fyookball/electrum#356]
I transferred all my BCH to BTC wallet on coinbase. I used Electron-cash wallet on my android phone. Below are the details. The transaction has been confirmed multiple times. Is it possible to get the BCH back in my wallet?
Transaction Id : af11660b10c12f62612333855095043533adea26c7e9eb904c3e203793438399

amount : 591.77528

Date: 2017-12-14 10:55

Thanks

**Comment by fyookball** [comment]
if you sent your BCH to a BTC address that COinbase controls you'll have to contact Coinbase as they control the keys to that address.
