### ISSUE TITLE
The Application "Electron-Cash" can't be opened

### ISSUE THREAD

**Issue by mhelfer** [fyookball/electrum#357]
I have downloaded Electron 3.0 dmg on to 3 different mac computers. I have confirmed the checksum and all of them. However, when I run it, it fails to start showing only the error message 'The Application "Electron-Cash" can't be opened.

Any thoughts?

**Comment by fyookball** [comment]
The build process is different, we are on python3 in 3.0 and must have missed something.  For now, i would just say revert to 2.9.4...i'll have to find out from Calin (who did the build) what the debug proecss would be here.

**Comment by kyuupichan** [comment]
Screenshot?

**Comment by cculianu** [comment]
What MacOS are you on?

Also any debug output?

Try (from the terminal)

# /Applications/Electron-Cash.app/Contents/MacOS/Electron-Cash

and paste whatever error message it complains about.

Also try 3.1.2 and see if that works better for you!

**Comment by stabwah** [comment]
Launching with

`/Applications/Electron-Cash.app/Contents/MacOS/Electron-Cash -v`

can also provide some more information

**Comment by fyookball** [comment]
no response from OP, closing.
