### ISSUE TITLE
transfer of balance from watching only address

### ISSUE THREAD

**Issue by kekecr** [fyookball/electrum#359]
Hi, 
I created a new electron cash wallet, started with sweep, importing old addresses to claim my BCH.  BCH showed up in the balance but the wallet is in watch only mode so I can't transfer any fund anywhere. 

I created a new wallet with seed, sweep the old address and when I get the option to transfer the balance  I can't change pay to address,  it's is always  the old address so in essence,  electron wallet each times makes a transaction to itself, pays fees, but balance in the new wallet is still 0. 

How to I transfer this balance to a working wallet.

**Comment by kekecr** [comment]
To solve the problem I installed bitcoin abc, donwloading the whole bch  blockchain, copied wallet.dat from bitcoin qt to abc folder and  as sync is going on BCH is showing up as well so hopefully I'll be able to claime my BCH this way

**Comment by fyookball** [comment]
was on vacation ,...everything ok?
