### ISSUE TITLE
"not connected" problem with Electron Cash 3.0

### ISSUE THREAD

**Issue by jessejames01** [fyookball/electrum#360]
My Electron Cash 3.0 wallet indicates that it's not connected, so I can't see my transaction and the balance stays at 0 BCC. I went in my Electron Cash "Tools">"Network" settings, unchecked "select server automatically" and tried multiple alternative "BCC"/"Electron Cash" servers, but the status remains at "not connected". I have the same problem with the 2.9.4-version.

Any solutions?

**Comment by latoxine** [comment]
Same problem here...Please help us !

 First notice on 2.9.x version before to update to 3. 

Did same things than OP plus I tried to install electron-cash on further PC with my seed and still nothing.  Same issue. 

Erase the ''certs'' files and  the '' blockchain_headers" do not work, still  red light.

**Comment by WurstCommander** [comment]
same here, can't connect. 
Electron 2.9 AND 3.0, fresh Windows 10 64bit install.

**Comment by deusmax** [comment]
same problem, can't connect. Tried all the servers on the list.
Electron 3.0, Linux 64 (Debian 9)

**Comment by Nikratio** [comment]
+1

**Comment by StaticNoiseLog** [comment]
+1, Windows 10, ElectronCash-3.0-PORTABLE.exe

**Comment by Nikratio** [comment]
Could someone clarify what kind of connection(s) Electron Cash is trying to establish?

**Comment by WurstCommander** [comment]
Me again (2-3min), after a while Cash connected and everything is fine.

**Comment by deep9th** [comment]
Just wait a bit and it will connect

**Comment by fyookball** [comment]
firewall eh...thx...good to know. closing.
