### ISSUE TITLE
I Checked the checksum, but my BCH gone to unknown address

### ISSUE THREAD

**Issue by bricketom** [fyookball/electrum#365]
I don't remember how much BTC I had on this adress. Almost all my funds was on another, and I decided to check. I downloaded 3.0 , choosed "import keys", connected and see two transactions +0.1 and right in the same time -0.1 - gone to unknown adress. What does it mean?

**Comment by ryankemper** [comment]
@bricketom Did you disclose your private key to an untrusted party? It's possible they got stolen.

Please PM me if you want help resolving this, to dig further into it you will have to provide your address (NOT your private key) so we can see what happened

**Comment by bricketom** [comment]
Sorry, how can i PM u? First time on github, and don't see PM )
