### ISSUE TITLE
FYOOK PLEASE HELP?ANYONE?

### ISSUE THREAD

**Issue by TitaniBitDAVO** [fyookball/electrum#366]
I sent the BTC (bitcoin) from bittrex account to newly setup Electron Cash Wallet, I sent to the address that was located under my receive tab. I have no coins in my Electron wallet and it is gone from Bittrex. Did i do anything wrong? Why is my bitcoin sitting on blockchain still? How can i get it back. Please speak to me like an 8 year old. I’m somewhat new to this but follow instructions very well.

**Comment by TitaniBitDAVO** [comment]
I’m on a Macintosh. FYI.

**Comment by TitaniBitDAVO** [comment]
WHY WILL NOONE HELP ME?????

**Comment by MannyC** [comment]
You need to find out if bittrex never sent the coins or if they sent it to an address that isn't controlled by electron or if it's just that electron can't retrieve your balance from the server.  

Start by searching for your address on a bitcoin cash blockchain explorer and seeing if you see any relevant transactions.

**Comment by TitaniBitDAVO** [comment]
Thanks. I figured it out.
