### ISSUE TITLE
seed from electrum with 2fa

### ISSUE THREAD

**Issue by bj97301** [fyookball/electrum#367]
I did something really stupid and sent my bitcoin cash to an electrum bitcoin wallet.  When I created this wallet I also enabled 2fa.  Is there a way to use my seed to recreate the same address with electron cash?  If there are other options feel free to let me know because I have private keys also but have no idea how to import them from electrum into electron cash. 

Thank you in advance for any help.

**Comment by philipmatthew** [comment]
I also am in the same boat. Somehow ShapeShift allowed me to transfer $5000 USD to a BTC Electrum wallet with multifactor enabled (TrustedCoin). I am not able to use the seed in electron cash (it crashes) to restore the wallet. I am willing to donate 10% of any recovered funds to the project.

**Comment by fyookball** [comment]
#41 for all 2fa.
