### ISSUE TITLE
Had BTC on Electrum on 8/1 but my BCH is not coming up on Electron Cash

### ISSUE THREAD

**Issue by voyagerz** [fyookball/electrum#368]
I can see the balance of BTC I had on Electum on August 1st when the fork happened. But when I downloaded Electron Cash and used the same seed to access my wallet - the BCH is not coming up on the balance. It's 0. Not sure what I can do to access it. Help please!

**Comment by ryankemper** [comment]
@voyagerz Did you have it *before* the fork, or just after? If you had it before the fork, the method you used should give you access to BCH. To me, this implies you didn't get your BTC till after the fork occured. Or, perhaps you used the wrong seed?

**Comment by kyuupichan** [comment]
@voyagerz is this solved?  What kind of wallet is it?  We need more details otherwise this is useless.

**Comment by voyagerz** [comment]
Hi! Apologies for the delay, I've been traveling with limited access to wifi. No - this is still not solved and I have yet to access my BCH.  I did have the BTC before the fork on electrum and I can confirm that I am using the correct seed. The BTC wallet on electrum had a 2 factor - which for BCH it doesn't give me the option when I use the same seed, plus it prompts to continue before I type the whole seed. I suspect that has something to do with it.  I hope that makes sense.

**Comment by kyuupichan** [comment]
I see, so it's a 2FA seed.  Can you try the list of things in #41 .
