### ISSUE TITLE
after spending few days trying to claim my Bitcoin cash

### ISSUE THREAD

**Issue by vologdagde** [fyookball/electrum#370]
I have a zero balance of my Bitcoin cash in the electron cash
Here is my electrum wallet (I reinstalled it from seed and disabled the 2fa - however I still see the [2fa])
![image](https://user-images.githubusercontent.com/34665698/34243919-5d4c9bd8-e5e0-11e7-91f5-eb0ccba354f9.png)

Electron cash
![image](https://user-images.githubusercontent.com/34665698/34244075-03b9824c-e5e1-11e7-96e6-6226f2c4f055.png)

**Comment by DiogenisPanagiotis** [comment]
I am having the exact same issue.. observing the same blank electron cash wallet.

**Comment by fyookball** [comment]
#41 for all 2fa support.
