### ISSUE TITLE
Bitcoin Cash from Bitcoin QT not showing correct balance.

### ISSUE THREAD

**Issue by yeastmeister** [fyookball/electrum#374]
Followed the instructions for getting bitcoin cash from my Bitcoin QT wallet.  But electrum isn't seeing my balance right.  It seems to be including multiple addresses when I look at the transaction details.  For instance, if I sent 3.6 coins to someone back in 2013, and there was a different address(not one of my sending addresses) in the same block that sent 20.4 coins to someone else, electrum is showing that I spent 24.0 coins, when its clear that I sent 3.6 coins.  The only transactions that do not match between qt and electrum are the sends.  It reads the received coins correctly, but its not giving me cash for them because its reading the blocks wrong.

**Comment by kyuupichan** [comment]
I find this hard to believe.  If you try a different server and get the same results, it's simply a fact.  You can check all the transactions on a block explorer by right-clicking them in your history.

**Comment by mwaeckerlin** [comment]
@yeastmeister, where are these instructions? Could you please provide a link?
