### ISSUE TITLE
Bitcoin Cash 2fa Wallet from 2.9.3 Electron Cash 

### ISSUE THREAD

**Issue by KingParanha** [fyookball/electrum#375]
I was holding some Bitcoin Cash in an Electron Cash Wallet version 2.9.3, I had not realized that it was no longer supported. When I realized this I also learned that I had to create a new wallet from my seed and disable 2fa in the creation process to be able to use the wallet in supported versions. However when I go to make a wallet from the seed in any prior version of electron cash, I just get a "Please Wait..." dialog pop up. I' have even tried creating a fake wallet in 2.9.3 with 2fa then trying to create a wallet and disable 2fa via creating a wallet with the seed. can someone confirm this by trying it for themselves with a fake wallet from a version of electron cash prior to 2.9.4.

**Comment by kuziozmc** [comment]
Hello,
did you manage to restore wallet without 2fa? I have the same problem and donno how to proceed in order to recover from seed. 
Cheers

**Comment by KingParanha** [comment]
No this is total bs. I msged electron cash on twitter and they havent responded and no one on here seems to care. How can electron cash just remove network compatability and not make everyone knows, what if you are holding for a long time and dont really check up on ur wallet. This is unacceptable. And the worst part is electron cash seeds cant be restored via any other wallets. So I have just given up because no one seems to be able to help and it looks like my money is going to be forever stuck in that stupid wallet. Btw if you or anyone find a fix please let me know, thanks.

**Comment by kyuupichan** [comment]
@KingParanha Electron Cash hasn't removed anything.  Your problem is that your service provider, TrustedCoin, abandoned you and your money by refusing to sign BCH transactions.  You should complain to them.

**Comment by kuziozmc** [comment]
@kyuupichan How to get in touch with them? cheers

**Comment by KingParanha** [comment]
Yes can u please let us know how to get in touch with them, thank you.

**Comment by kuziozmc** [comment]
@KingParanha I have the answer from Trustedcoin. HAve a look email below. It Works for me. Good luck mate.

BCH is not supported by Trustedcoin however there are recovery options linked to on the Electron Cash website in the section labeled "What if I need support?"

Alternatively, I also created a recovery tool:

https://trustedcoin.com/static/recover/standalone.html

Where you can enter your seed and it will create a Electron-compatible version of your wallet that can be spent from without Trustedcoin. 

If you use the recovery tool, I recommend opening the wallet it created in the latest version of Electron ... 2.9.3 has bugs.

**Comment by KingParanha** [comment]
OMG thank you sooo sooo much @kuziozmc , you are a lifesaver, the recovery tool worked perfectly with electron cash version 2.9.4. For any one having the same problem i was having, once you have opened the recovered wallet from the recovery tool in version 2.9.4 of electron cash all you have to do is choose a server manually and choose the "electroncash.cascharia.com" server and you will have a properly functioning wallet.

Once again thank you so much to @kuziozmc for be so patient with me when i was so frustrated. THANK YOU!
