### ISSUE TITLE
Stuck unconfirmed, accidentally sent BCH with Old Electron Cash wallet

### ISSUE THREAD

**Issue by haakonstorm** [fyookball/electrum#376]
Tried sending BCH with old Electron Cash wallet.. 
Have upgraded to latest Electron now.
tx (a0e98c31c091daa7d1f9736b8b8b3b5fca2df506e7f0b0fcb0e8f902101fc8f8) unconfirmed, propably because old client created an invalid tx.
My funds are stuck in limbo land.
How to delete the transaction?
Tried exporting the private key (WIF) to sweep to Exodus.app, but the private key is in Bitcoin format and Exodus resolves the wrong address from the private key. 
* Tried deleting the blockheaders and everything else in .elec*
* Tried creating new wallet, importing single private key but the tx is imported along, funds=0
How to export/convert a bitcoincash-compatible WIF private key that can be imported in other wallets? 
* Automatic server enabled, green light, connected
* Any other tips?
Thanks again for great work on this electrum port for bch.

**Comment by verretor** [comment]
Your transaction is valid.
https://truevisionofsatoshi.com/tx/a0e98c31c091daa7d1f9736b8b8b3b5fca2df506e7f0b0fcb0e8f902101fc8f8

**Comment by haakonstorm** [comment]
Thanks a bunch, just saw that - took many hours, maybe because of low fees from the old client. Thanks again.
