### ISSUE TITLE
Can I recover BCH with this product?

### ISSUE THREAD

**Issue by pelicanbadger** [fyookball/electrum#377]
Prior to July 30th, I purchased .5 btc on Coinsbank.  Coinsbank did not, and still doesn't support BCH.  Today, that .5 btc is still sitting in coinsbank.
Can I use your service to 
1.  Remove my BTC from Coinsbank, and keep it in your
wallet instead,   AND
2.  recover and account for the .5  BCH
that I'm entitled to since the fork occurred?

Thank you!

**Comment by ryankemper** [comment]
@pelicanbadger No, your BCH is gone unless Coinsbank decides to release it to you. This is because you never owned your BTC private keys.

If you want to send BTC, you should use Electrum. This is electron cash, which is a fork of electrum for bitcoin cash (BCH).
