### ISSUE TITLE
Please also make a Debian package

### ISSUE THREAD

**Issue by jidanni** [fyookball/electrum#387]
I was reading #232 and thought: please also put a .deb package on Debian like https://packages.debian.org/sid/electrum .

**Comment by jidanni** [comment]
OK I also made http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=885426
By the way they have a good man page...

**Comment by hegjon** [comment]
Maybe it help asking the maintainer of Electrum, I mantain both Electrum and Electron Cash packages at Fedora and they are pretty similar.

**Comment by jidanni** [comment]
@hegjon Yes, let's hope
> Maintainer for electrum is Debian Bitcoin Packaging Team <pkg-bitcoin-devel@lists.alioth.debian.org>

saw my http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=885426 .

**Comment by haplo** [comment]
A Debian package would also make using Electron Cash in Tails easier, see #171.

**Comment by fyookball** [comment]
We definitely should try to make a .deb package.  I'm marking as enhancement and closing for now in the effort to keep the repo clean.  We'll circle back to enhancements soon.
