### ISSUE TITLE
Some Android error messages

### ISSUE THREAD

**Issue by jidanni** [fyookball/electrum#390]
Some error messages I saw on  Android 7.0 logcat.

12-27 18:33:57.708 V/pythonutil(13773): Library loading error: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.electroncash.electroncash-1/base.apk"],nativeLibraryDirectories=[/data/app/org.electroncash.electroncash-1/lib/arm, /system/fake-libs, /data/app/org.electroncash.electroncash-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libpython3.5m.so"
12-27 18:34:55.215 W/linker  (13935): /data/app/org.electroncash.electroncash-1/lib/arm/libpython2.7.so: is missing DT_SONAME will use basename as a replacement: "libpython2.7.so"
12-27 18:34:56.547 W/linker  (13935): /data/data/org.electroncash.electroncash/files/app/lib/python2.7/site-packages/kivy/graphics/cgl_backend/cgl_glew.so: is missing DT_SONAME will use basename as a replacement: "cgl_glew.so"12-27 18:34:56.483 W/linker  (13935): /data/data/org.electroncash.electroncash/files/app/lib/python2.7/site-packages/PIL/_imaging.so: is missing DT_SONAME will use basename as a replacement: "_imaging.so"12-27 18:34:55.218 V/pythonutil(13935): Library loading error: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.electroncash.electroncash-1/base.apk"],nativeLibraryDirectories=[/data/app/org.electroncash.electroncash-1/lib/arm, /system/fake-libs, /data/app/org.electroncash.electroncash-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libpython3.5m.so"

**Comment by fyookball** [comment]
try again when android 3.1.2 comes soon
