### ISSUE TITLE
The word electrum still shows up often

### ISSUE THREAD

**Issue by jidanni** [fyookball/electrum#391]
There are many places when using the Android app that the word electrum shows up. Therefore I would go through the entire code, and replace the word electrum with a variable. And that variable in the headers could be changed to electron cash, or even Litecoin something.

**Comment by jidanni** [comment]
For instance I see it says 10 connections to the electrum servers. Well with a variable instead of a hard-coded name, the next time somebody forks this package, they can just insert the type of currency that the package is intended for.

**Comment by fyookball** [comment]
ElectrumX is still the name of the server software btw.  Do you have another example?

**Comment by jidanni** [comment]
OK at least it is not as bad as https://github.com/pooler/electrum-ltc/issues/133 , but wait,
github.com/fyookball/**electrum**/ needs to be rebranded... but probably too late for that.

**Comment by fyookball** [comment]
we'll clean up "electrum" as we see it.  👍
