### ISSUE TITLE
downloaded electrum cash wallet, closed it, then opened it again address changed

### ISSUE THREAD

**Issue by gapingforensics** [fyookball/electrum#399]
so i sent some funds to my bch electrum wallet manually typing in the key and it worked like a charm...however i closed it again and reopened and copy and pasted that same key into where i was sending from again. i see the transaction as pending from where i sent it, but my wallet doesnt see it anymore...i check the receive tab and low and behold the key is different! what the heck? am i missing something? is this normal? what happened to my old address? how do i get it back?

**Comment by gapingforensics** [comment]
here was my problem everyone. dont use VPNs with electrum cash 3.0. that was the problem all along. as for the address changing, i figured out how to view all my addresses and they all connect to my wallet. this is how a lot of wallets and ex's work. sorry to clog up space but i hope this was useful to others.

**Comment by fyookball** [comment]
not sure what you did but sounds like youre ok
