### ISSUE TITLE
Cannot connect to BCH server (OSX)

### ISSUE THREAD

**Issue by sxv** [fyookball/electrum#40]
Cannot connect to BCH server. Client defaults to BTC servers. When I choose one manually the client goes into a loop of connecting and disconnecting. I am not able to select a "group" of servers to connect to because the list keeps flashing / resetting.

See gif: https://d26dzxoao6i3hh.cloudfront.net/items/0C2m2n151W2z012c3A1U/electron.loop.gif?v=73bcf767

**Comment by ecdsa** [comment]
sx contacted me on IRC. I believe the cause might be that electron-cash does not validate the headers sent by the BCC servers after the the recent difficulty reset.

**Comment by fyookball** [comment]
i dont have that problem on windows.  I will try testing on mac.  @ecdsa  why would this be mac specific?

**Comment by ecdsa** [comment]
nobody said it is mac specific

**Comment by molecular** [comment]
@ecdsa electron-cash starting at 2.9.0 verifies headers with recent diff adjust just fine.

**Comment by molecular** [comment]
@sxv do you think you can start elctron-cash with "-v" flag and post the relevant output?

I'd also like to see you proxy tab.

**Comment by molecular** [comment]
It would also be interesting to start with
    #> electron-cash -v -1 -s electrum-abc.criptolayer.net:50012:s
to force it to one cash server

**Comment by sxv** [comment]
So I tried running with the command above and it seemed to be performing somewhat better. It spent some time in the "Synchronizing" phase and then connected me to the server. Unfortunately my Balance is still showing up as 0. mBTC for some reason. See the attached screenshots of requested outputs:

verbose log and server tab: https://d26dzxoao6i3hh.cloudfront.net/items/1l1y0D0n1x0h2T1w0l1b/Image%202017-08-03%20at%203.17.12%20PM.png?v=41fb69b0
proxy tab: https://d26dzxoao6i3hh.cloudfront.net/items/3D1G1S0b2K1k2O2d413b/Image%202017-08-03%20at%203.17.19%20PM.png?v=934c0f78

**Comment by sxv** [comment]
Resolved by switching to linux machine, create new standard wallet, seeding from 2FA electrum wallet seed, disabling 2FA, and the BCC finally appears!, but doesn't send [due to issue 6, so then modifying lib/transaction.py](https://github.com/fyookball/electrum/issues/6), restarting Electron Cash, and the tx sent (in confirmation now).

**Comment by fyookball** [comment]
i am releasing a new version soon. if problems, please open new issue  thx

**Comment by molecular** [comment]
Just as a sidenote: you started with "-v -1 -s elecgtrum-abc.criptolayer.net:50012:sqlitebrowser.app"

I would omit the "qlitebrowser.app", maybe there is a silent ignore and the servername doesn't parse?
