### ISSUE TITLE
Electron cash Multisig Does not work

### ISSUE THREAD

**Issue by grajnikanth** [fyookball/electrum#400]
The issue is more of a comment I have about how electron cash is working. I sweeped my electrum multisig to electron cash multi sig wallet. I also sent BCH out of this new electron cash wallet. I did not have to sign the transaction using both the mutlisig wallets. I was able to send transaction out using just one or the other wallets. On electrum, I would have to sign, save it as a file load it into the second wallet, sign, save the file and then broadcast. I am assuming that electron cash does not have the multisig features enabled.

**Comment by fyookball** [comment]
@kyuupichan was fixing multisig.  Not sure the status.

**Comment by marceloneil** [comment]
I've been able to use multisig (with the ledger) on the current master branch.

**Comment by kyuupichan** [comment]
@grajnikanth clearly it's not possible to send multisig with a single signature, unless you provided several private keys when you restored your wallet.  I don't think this report is useable as-is.
