### ISSUE TITLE
packages for Linux

### ISSUE THREAD

**Issue by fyookball** [fyookball/electrum#402]
https://www.reddit.com/r/btc/comments/7n54zc/electron_cash_already_included_in_5_linux_distros/ds0uyjd/

**Comment by marceloneil** [comment]
That's me! I'll look into it :)

**Comment by fyookball** [comment]
someone suggested 'build enivornment docker file. then everyone can use same dependencies"... is that related?

**Comment by marceloneil** [comment]
I think it could make the build process a bit easier, so I'll investigate it

**Comment by Germano0** [comment]
https://src.fedoraproject.org/rpms/electron-cash :-)

**Comment by fyookball** [comment]
related to #387.  enhancement. closing for now to keep repo clean.
