### ISSUE TITLE
trouble claiming BCH on windows computer (electrum electron)

### ISSUE THREAD

**Issue by DivAlec** [fyookball/electrum#403]
Hi, i had BTC before the hard fork of august 1st, but having trouble claiming my BCH.
1. Transferred BTC from  my electrum default wallet second new electrum wallet (issues with 2fa on electrum)en then send to nano ledger s
2. Downloaded electron cash 3.0 exe wallet (option standard wallet) 
3. Imported old electrum seed from electrum (yes, the right seed and then checked BIP39)
4. Balance is 0 BCH (i changed the server from and to "electroncash.cascharia.com"a few times but same result) Also tried to import my private keys but then got a "whatching only" wallet.
What am i doing wrong?

**Comment by fyookball** [comment]
sounds like its a 2fa ?   See #41

**Comment by DivAlec** [comment]
Many thanx @fyookball and, it was indeed #41 issue!! Had been trying for days
