### ISSUE TITLE
Accidentally Sent BCH to a Watch Only Wallet

### ISSUE THREAD

**Issue by bigswiss89** [fyookball/electrum#405]
Hello,

I sent BCH to my Electrum wallet, then realized I needed to download ElectronCash for BCH. Once I opened it, it told me that it was a Watch Only wallet and not to use it for spending BCH...

How can I get my BCH out? I have my Electrum wallet's seed if that helps.

Thanks,

**Comment by fyookball** [comment]
create a new (BCH) wallet with the seed and you should be good to go
