### ISSUE TITLE
weird electrum/elctroncash BCH fork issue 

### ISSUE THREAD

**Issue by nardusg** [fyookball/electrum#406]
Hi

Hope I can get some help. I listened to a podcast this morning and realised that I do have some unclaimed BCH. I only moved my BTC a few months after the fork has happend. I installed electroncash and restored my electrum wallet. I had about .5 BTC before the fork. Right after I have imported the wallet my .5 BCH was not in my wallet any more. I looked like it was send to another unknown address. Did I loose my BCH and was this an old transaction that replayed ?

Help will be appreciated.

Nar

**Comment by fyookball** [comment]
use a block explorer and see which BCH address the coins are on, and then see if it matches an address that is generated by your seed.

**Comment by nardusg** [comment]
Hi

Thanks fro the reply. The weird thing is that I used the electroncash android app from the playstore. It showed it and then send it to the address. Was the mobile app compromised ? I can see it on the block explorer.

Regards

Nardus

**Comment by nardusg** [comment]
Hi

No, it is none of the address that was generated by my seed.

Thanks

Naruds

**Comment by fyookball** [comment]
sounds like you have malware possibly
