### ISSUE TITLE
Electron Cash 3.0 crashed when tick/untick Show Fiat balance for addresses 

### ISSUE THREAD

**Issue by LightSunChen** [fyookball/electrum#407]
Electron Cash 3.0 crashed when tick/untick Show Fiat balance for addresses

**Comment by kyuupichan** [comment]
Fixed by b03a80cec75f261003d21862426f9d4ffe17575f

**Comment by LightSunChen** [comment]
Excuse me, how can I update it to ElectronCash in Windows ?
