### ISSUE TITLE
Unintentional address reuse

### ISSUE THREAD

**Issue by 1ib3r7yr3igns** [fyookball/electrum#409]
When sending funds to an electron-cash 3.0 address, I accidentally sent much less than I intended. After it was confirmed, I wanted to send the rest of the funds. The wallet offered the same receive address for the new funds. So this address now contained two UTXOs. I then sent funds from this address, and the wallet correctly sent the remainder of the larger UTXO to a change address, but did not also send the smaller UTXO to the change address. This has created the situation where I have an address that has a spent TXO but still contains another, smaller UTXO.

I would think the wallet should send both UTXOs to the change address to prevent address reuse.

A possible way to prevent this would be to have the receive address never be an address with an UTXO. This would prevent multiple inputs from being forgotten to be sent to the change address.

**Comment by kyuupichan** [comment]
This is what the Privacy coin chooser does.  We should make it the default.  Change it in your preferences in the mean time.

**Comment by 1ib3r7yr3igns** [comment]
Oh thanks, I didn't realize there was an option for this already. I'm not seeing this in the preferences. Could you be more specific?

**Comment by kyuupichan** [comment]
I removed it in 3.1; the coin chooser is privacy by default.
