### ISSUE TITLE
Compatibility with BIP 70

### ISSUE THREAD

**Issue by Kalfer** [fyookball/electrum#412]
Hi. It is impossible to send BCC from Electron Cash 3.0 to a BitPay wallet. 
I guess this is not a bug, but a lack of compatibility. I hope Electron Cash developers will soon add it. Thank you.

**Comment by mooncryption** [comment]
This is BitPay's fault, and not the other way around. Make sure you update your BitPay wallet app ASAP, as the `cashaddr` new unified address format is coming soon.
