### ISSUE TITLE
Electron crashes when trying to open bitcoin cash

### ISSUE THREAD

**Issue by HCNSDK** [fyookball/electrum#413]
Hi Guys,
Hope for some help claiming my bitcoin cash.
I had som bitcoing in Electrum wallet 1.aug 2017 and now would be nice to get the bitcoin cash available.

I can see the bitcoin cash in an Electron wallet but only in watching mode.

Tried to open the Electrum wallet (where I can see all the bitcoin transactions) with Electron, but it crashes.

Any suggestions?

Thanks!

**Comment by fyookball** [comment]
sounds like a 2fa issue #41

**Comment by HCNSDK** [comment]
Thanks!
I dont see a solution that works in  #41..
If I try to make a new wallet from seed can't choose disable 2fa
Im using version 3.0.3 running windows 

Hope for some help, thanks
