### ISSUE TITLE
SHA256 mismatch for ElectronCash-3.0.exe

### ISSUE THREAD

**Issue by coelhopsi** [fyookball/electrum#414]
SHA256 hash for file https://electroncash.org/downloads/3.0/win-linux/ElectronCash-3.0.exe doesn't match the hash published at https://github.com/fyookball/keys-n-hashes/blob/master/sigs-and-sums/3.0/win-linux/SHA256.ElectronCash-3.0.exe.txt.

The downloaded file has a hash of 65ae9382f6434629f603adea266270ff91de3f6838293b85da0b5e76b1a6151c while the correct one should be cb52998a067a1bf086b2f231b5f5c27ec362d4c7d12a3922f8047a230063724b.

The downloaded file shows 6 detections on VirusTotal and a first submission date of 2017-12-11. When trying to run the downloaded file, an error shows up.

The direct download from Github (https://github.com/fyookball/electrum/releases/download/3.0/ElectronCash-3.0.exe) presents no issues and has a matching SHA256.

**Comment by fyookball** [comment]
sounds like a partial download error?  it works for me. 

its also possible that someone is intermittantly screwing w the file, in which case we should upgrade servers.

**Comment by coelhopsi** [comment]
Most likely the second option.... a corrupted/partial file wouldn't have shown up at VirusTotal as having already been submitted almost 1 month ago.

Thanks for checking...
