### ISSUE TITLE
Locktime on transaction dialouge preview

### ISSUE THREAD

**Issue by fyookball** [fyookball/electrum#415]
This started showing up in 3.0.   Don't know what it is.. I assume its probably some segwit junk pulled in from Electrum.  Let's investigate and if appropriate, remove.

**Comment by fyookball** [comment]
![image](https://user-images.githubusercontent.com/7663756/34585272-05d47572-f16d-11e7-8719-68fe32cc11d9.png)

**Comment by kyuupichan** [comment]
Nothing to do with segwit; it's from original BTC
