### ISSUE TITLE
electrum cash shows exception error when sending from Coins tab with Ledger Nano S

### ISSUE THREAD

**Issue by LightSunChen** [fyookball/electrum#418]
electrum cash shows exception error when sending from Coins tab with Ledger Nano S

**Comment by mooncryption** [comment]
Are you on version `3.1` or `3.0`? The latest version 3.1 should have this fixed.

**Comment by marceloneil** [comment]
If you are on windows this should be fixed as of `3.1.1`

**Comment by marceloneil** [comment]
@LightSunChen any update?

**Comment by LightSunChen** [comment]
@marceloneil still don't have chance to try again yet

**Comment by marceloneil** [comment]
Alright, let us know when you do!

**Comment by kaczan3** [comment]
I can't send coins either, in both 3.1.1 and 3.1.2.

**Comment by marceloneil** [comment]
@kaczan3 are you using Windows? Are you getting an error of some sort?

**Comment by kaczan3** [comment]
Yes. There was a popup with Exception: invalid channel. The dot in the bottom right was red. Later I was getting read error. And after many tries and tinkering it worked and I managed to send all my BCH to an exchange. Is my Nano Broken?

When starting this wallet I also got some weird errors saying nano is used elsewhere and some others I think.

**Comment by marceloneil** [comment]
@LightSunChen If the error reads "Invalid Channel", make sure that Browser Support is disabled for the bitcoin cash app

**Comment by kaczan3** [comment]
Thank you, this solved my problem.
