### ISSUE TITLE
Cannot Load Wallet error in Windows (Electron Cash version 3.1)

### ISSUE THREAD

**Issue by the-beer-engineer** [fyookball/electrum#423]
Hi,
I have just downloaded version 3.1 of electron cash. The first time I opened it it said it would have to update my wallets to a new format (irreversible) but upon trying to start the application after this, I get the following error:
Cannot load wallet:
No module named 'distutils'
![image](https://user-images.githubusercontent.com/35157502/34635679-d891ecac-f2de-11e7-82ce-deb7205bd3dc.png)

Should I just delete the wallets and start again? They are all generated from my Ledger device so it's not a  huge issue.

**Comment by marceloneil** [comment]
@the-beer-engineer This issue was fixed in the new update 3.1.1
