### ISSUE TITLE
Ledger Nano S

### ISSUE THREAD

**Issue by deathbybinary** [fyookball/electrum#425]
Trying to connect my Ledger Nano S (Firmware 1.31) to Electron-Cash 3.1 OSX

At the wizard I select New Wallet > Standard > Use HW Device > An unnamed Ledger [ledger, intialized]

And receive the error: "Exception: Invalid Channel"

Electron-Cash correctly detects I've exited the app ("Device not in Bitcoin Cash Mode" message)

If I re-run the Bitcoin Cash app on the nano I get: 
'NoneType' object has no attribute 'handler'

Is there a way to enable log files easily? I don't see anything in ~/.electron-cash

**Comment by chrulri** [comment]
Same problem on Windows 10 with Electron-Cash 3.1.1. With 3.1(.0) it didn't recognize my Ledger Nano S.

**Comment by marceloneil** [comment]
@chrulri the 3.1.1 release should have fixed that, are you still experiencing this issue?

**Comment by chrulri** [comment]
@marceloneil Please see my edited comment.

**Comment by marceloneil** [comment]
Great @chrulri ! Windows can be a hassle with usb devices sometimes, but I'm glad you got it working.

@deathbybinary I'm still working on reproducing your issue, could you try the 3.1.1 release if you have the chance?

**Comment by deathbybinary** [comment]
@marceloneil I will try to reproduce as soon as a 3.1.1 OSX build is available. Thanks.

**Comment by fyookball** [comment]
there is one in now @deathbybinary

**Comment by deathbybinary** [comment]
@marceloneil Sadly, I still get the error: "Exception: Invalid Channel"

If I exit the Bitcoin Cash app and run the Bitcoin Cash app on the nano I get:
'NoneType' object has no attribute 'handler'

Trying a few more times I ended up getting:
"HW1 firmware version too old. Please update at ledgerwallet.com"

Is there a way to generate debug logs with the compiled version? If not, I will pull the git source so I can get you some more useful information.

Thanks @fyookball

**Comment by marceloneil** [comment]
@deathbybinary try running:
```
/Applications/Electron-Cash.app/Contents/MacOS/Electron-Cash -v
```
That should give us a bit more information

**Comment by deathbybinary** [comment]
@marceloneil OK here's what I got trying a few of times with both Bitcoin and Bitcoin Cash ledger app:

[Plugins] loaded digitalbitbox
[Plugins] loaded keepkey
[Plugins] loaded ledger
[Plugins] loaded trezor
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
=> b'e0c4000000'
=> b'f026000000'
[DeviceMgr] Registering <electroncash_plugins.ledger.ledger.Ledger_Client object at 0x119949438>
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
=> b'e0c4000000'
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
=> b'e0c4000000'
<= b'1b30010105010003'9000
=> b'f026000000'
<= b''6d00
[DeviceMgr] Registering <electroncash_plugins.ledger.ledger.Ledger_Client object at 0x11994e6d8>
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
=> b'e0c4000000'
<= b'1b30010105010003'9000
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
=> b'e0c4000000'
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
=> b'e0c4000000'
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
=> b'e0c4000000'
=> b'f026000000'
[DeviceMgr] Registering <electroncash_plugins.ledger.ledger.Ledger_Client object at 0x11994eac8>
[DeviceMgr] scanning devices...

**Comment by marceloneil** [comment]
Hmm, and you said you get the error "invalid channel"?

**Comment by marceloneil** [comment]
Do you have any other apps running that might be using the ledger?
Have you tested if the ledger works with the Ledger Chrome Wallet?

**Comment by deathbybinary** [comment]
The Invalid Channel error only usually occurs the first time. 

I then get errors such as 'NoneType' object has no attribute 'handler'

No other applications that use the ledger are running (that I know of). The ledger definitely works with the Chrome app, I regularly use it.

**Comment by marceloneil** [comment]
This seems like a btchip-python problem, you may want to file an issue over there:
https://github.com/LedgerHQ/btchip-python/blob/master/btchip/ledgerWrapper.py#L55
https://github.com/LedgerHQ/btchip-python/blob/master/btchip/ledgerWrapper.py#L78

Do you know if electrum works with your ledger wallet?
I'll look into it a bit more later

**Comment by deathbybinary** [comment]
@marceloneil FYI Still having the same behaviour with ElectronCash 3.1.2 - I am posting a new issue with LedgerHQ thanks for the pointer.

Just confirmed the Ledger Nano S IS working correctly using the Bitcoin Ledger App with Electrum 3.0.5

Here is the log output:

[Plugins] loaded digitalbitbox
[Plugins] loaded keepkey
[Plugins] loaded ledger
[Plugins] loaded trezor
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
=> b'e0c4000000'
<= b'1b30010105010003'9000
=> b'f026000000'
<= b''6d00
[DeviceMgr] Registering <electrum_plugins.ledger.ledger.Ledger_Client object at 0x11c122e10>
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
=> b'e0c4000000'
<= b'1b30010105010003'9000
=> b'e024000000'
<= b'01'9000
=> b'e02280000130'
<= b''6d00
=> b'e040000005018000002c'
[E-X.not.fyi] requesting chunk 33
<= b'41043c6e42736f808d038132b3be556d38f830cc9028a1cf3de29ef3e9d18fe70028bb624ad33119a6793a3c6f0454e8ab7710844a90075389dd7c3567b811b2131f223139773961734634757a4a71664b6761706a31714e466e5351314a4e577648734d566ec82fdf0ab1a39c00bd23f099e3c1f4a444b33926e89e7e11cb046d4212e670'9000
=> b'e040000009028000002c80000000'
<= b'4104f1ff9c514e306f8b0b304d244403d30248149d18ee6b5960769dcde0a39ee4753a4063adc9355405b4e84353438f5f73fefa542dae11f674e0888a3fc7494a8722313375575047456e4333544e676e386475636b7576534476316e7757327145797956b7d6c853ce1ac516de50dc16657eba2a3ac44c60379bc1865968ab0b2f6b4603'9000
[DeviceMgr] scanning devices...
=> b'e040000009028000002c80000000'
<= b'4104f1ff9c514e306f8b0b304d244403d30248149d18ee6b5960769dcde0a39ee4753a4063adc9355405b4e84353438f5f73fefa542dae11f674e0888a3fc7494a8722313375575047456e4333544e676e386475636b7576534476316e7757327145797956b7d6c853ce1ac516de50dc16657eba2a3ac44c60379bc1865968ab0b2f6b4603'9000
=> b'e04000000d038000002c8000000080000000'
<= b'4104b330df955b344db1210dc06f62d2aedf3edac5965b1e2ed1950966d8270fef39ae58c93b8d165b8670d1ab4c53ffbd0783cf383dbf5040bb0caa68c01ef4be1f2231357170464559526556475658517a64756356536a42507142387934756b527a6f6a58a489020fb6d4a3821d74ae1a23820421654d191bd5046035c9fde146c51822'9000
[profiler] load_transactions 0.0000
[profiler] build_reverse_history 0.0000
[profiler] check_history 0.0000
[DeviceMgr] getting client for keystore
[DeviceMgr] scanning devices...
=> b'e040000009028000002c80000000'
<= b'4104f1ff9c514e306f8b0b304d244403d30248149d18ee6b5960769dcde0a39ee4753a4063adc9355405b4e84353438f5f73fefa542dae11f674e0888a3fc7494a8722313375575047456e4333544e676e386475636b7576534476316e7757327145797956b7d6c853ce1ac516de50dc16657eba2a3ac44c60379bc1865968ab0b2f6b4603'9000
=> b'e04000000d038000002c8000000080000000'
<= b'4104b330df955b344db1210dc06f62d2aedf3edac5965b1e2ed1950966d8270fef39ae58c93b8d165b8670d1ab4c53ffbd0783cf383dbf5040bb0caa68c01ef4be1f2231357170464559526556475658517a64756356536a42507142387934756b527a6f6a58a489020fb6d4a3821d74ae1a23820421654d191bd5046035c9fde146c51822'9000
[DeviceMgr] end client for keystore

**Comment by deathbybinary** [comment]
LedgerHQ responded quickly - the solution was to ensure the Browser Support setting is Off in the Bitcoin Cash Ledger app settings (v1.1.5). 

Would you like me document this somewhere in case other people run into the same issue?

Thanks for all your patience! @marceloneil
