### ISSUE TITLE
weird android electrum/elctroncash BCH wallet import issue

### ISSUE THREAD

**Issue by nardusg** [fyookball/electrum#426]
Hi Guys

Hope you are well and hope I can get some help. I listened to a podcast a few days ago and realised that I do have some unclaimed BCH. I only moved my BTC a few months after the fork has happend, so after the fork, BTC was still available to get it on BCH. I installed this electroncash android app and restored my electrum wallet with my electrum wallet seed. I had about .5 BTC before the fork. Right after I have imported the wallet my .5 BCH was not in my wallet any more. It looked like it was send immediately after I imported it to another address. This seemed like a trigger in the app.

Did I loose my BCH and was this an old transaction that replayed ? Is this app compromised, I installed it from the Play Store ? At the moment the issue might points to the developer ? 

Destination address of where my BCH went : 12FSNtEA8MKvYJZDVbWm7CNseWT8wTegRm

It is not allot of money but it is allot to me. This is not in the spirit of open source software. 

If this is malware please pull the app from the Google Play Store, to prevent this from happening to anybody else? If this was a test address, please return money to my wallet?

Regards

![screenshot from 2018-01-05 21-24-33](https://user-images.githubusercontent.com/29011858/34641111-8daa65a6-f307-11e7-91de-a53e442bf662.png)
![screenshot from 2018-01-05 21-19-13](https://user-images.githubusercontent.com/29011858/34641112-8df6179e-f307-11e7-9ac1-9eb9110b6dee.png)
![screenshot from 2018-01-05 21-18-05](https://user-images.githubusercontent.com/29011858/34641113-8e41cb08-f307-11e7-8592-8bf629bd715b.png)
![screenshot from 2018-01-05 21-17-07](https://user-images.githubusercontent.com/29011858/34641114-8e8d8520-f307-11e7-9eaf-c00eb0527dd3.png)

**Comment by DarkLordGMS** [comment]
Can you post the link to the app you downloaded?

**Comment by nardusg** [comment]
Hi

Strait from the play store

https://play.google.com/store/apps/details?id=org.electroncash.electroncash

Ciao

Nar

**Comment by DarkLordGMS** [comment]
Can you send some pictures of the wallet you made in that app?

**Comment by nardusg** [comment]
![capture _2018-01-06-18-55-19](https://user-images.githubusercontent.com/29011858/34641916-acb92994-f313-11e7-9d32-eba56a9a0599.png)
![Uploading Capture+_2018-01-06-18-55-09.png…]()

**Comment by DarkLordGMS** [comment]
That's really odd. Do you have a PC? 
Try Downloading the desktop version and restore the wallet using your seed.

**Comment by DarkLordGMS** [comment]
@fyookball Can you take a look?

**Comment by DarkLordGMS** [comment]
It looks like the address is still sending and receiving BCH: 

https://blockchair.com/bitcoin-cash/address/12FSNtEA8MKvYJZDVbWm7CNseWT8wTegRm

**Comment by marceloneil** [comment]
Maybe it had something to do with the JSON-RPC security vulnerability

**Comment by nardusg** [comment]
Yes, what really weird is, the transaction happenend almost immediately, almost like a builtin trigger.

**Comment by fyookball** [comment]
malicious apps can do that , did you have any weird apps?
