### ISSUE TITLE
3.1.1 crash windows10/64

### ISSUE THREAD

**Issue by jkister** [fyookball/electrum#429]
Electron cash 3.1.1 on windows10/64 will reliably crash if you try to export your private keys but click "cancel" while the "Please wait xx/xx" message is calculating.

**Comment by ndamukrazed** [comment]
I'm trying to run 3.1.1 on windows 10/64 as well, and I get a warning from windows defender when I first open the .exe. I click run anyways, and then a minute later windows automatically shuts down the program and also deletes the .exe file. When I try to redownload the file, windows tells me I don't have permission to save in this location. Restarted my computer and was able to redownload, but everything else happened again.

**Comment by jasonbcox** [comment]
I ran into something similar: When prompted to update my wallet's format from 2.x -> 3.x, I clicked cancel and electron-cash hung.  I'm not on Windows however: Ubuntu 16.04.

**Comment by marceloneil** [comment]
I was able to reproduce @jkister's issue on linux
@ndamukrazed look at #335
