### ISSUE TITLE
Cant open electron

### ISSUE THREAD

**Issue by Razdva122** [fyookball/electrum#43]
Sorry guys i am undestand what this question is dumb, but i hope you can help me. I download  zip from git unzip it. And via cmd use python setup.py install, is create few new folders but i still cant undestand how i can open the program. I dont see any exe files or smth like that

**Comment by togic8** [comment]
Same problem. Can't seem to figure out how to run it on Windows 10.

**Comment by fyookball** [comment]
after python setup.py install

python electron-cash
