### ISSUE TITLE
Show amounts with thousands separator

### ISSUE THREAD

**Issue by kingvest** [fyookball/electrum#430]
Amounts should be shown with thousands separator.

When using Bits as the base unit it becomes difficult to read the exact value without a thousands separator.

**Current Format:**

2 BCH = 2000000 Bits
(hard to read)

**Expected Format:**

2 BCH = 2'000'000 Bits
(easy to read)

I believe `'` to be the best separator for thousands.

More confusing separators would be `_`, `,` or `.`

**Comment by joseluis** [comment]
I agree, but only as a visual aid. Meaning that it would be better not to include the separator when copying the amount, but just the number.

**Comment by kingvest** [comment]
@joseluis - yes, just the visual representation

**Comment by deathbybinary** [comment]
@kingvest Interested to hear why you feel `,` is a confusing separator as it seems to be the scientific and mathematical standard in most countries IE: `2,000,000`

**Comment by joseluis** [comment]
@deathbybinary in my country we use the dot `.` for thousands separator and the comma `,` for decimals. When a software doesn't allow to customize that locale settings it can get very annoying.

**Comment by marceloneil** [comment]
Thoughts about a space as a seperator? Ie. `2 000 000`

**Comment by rt121212121** [comment]
Electron should follow a standard approach.  That should be , and . based on locale.  There would be standard ways of doing this.  Taking a custom approach for something where there is a standard approach results in a feeling of lower quality.

**Comment by fyookball** [comment]
"I agree, but only as a visual aid. Meaning that it would be better not to include the separator when copying the amount, but just the number."

How would that be possible?  Most of the time when most people copy, they mouse over something and copy it.  

Overall, I'm not sure adding comma separators is worth it.  Sounds like a lot of work for little benefit, and especially if people can't agree on the separator.  Using a locale based separator sounds overkill.   There's more important things we can be working on like an iOS version of the wallet.

**Comment by marceloneil** [comment]
> How would that be possible? Most of the time when most people copy, they mouse over something and copy it.

You could have a copy button
> Overall, I'm not sure adding comma separators is worth it. Sounds like a lot of work for little benefit, and especially if people can't agree on the separator. Using a locale based separator sounds overkill. There's more important things we can be working on like an iOS version of the wallet.
@kyuupichan did mention that the code around comma separators and such is pretty messy, so it does sound like a lot of work

**Comment by fyookball** [comment]
will mark this as enhancement and may decide to do later.

**Comment by simon-v** [comment]
I think it's worth mentioning that this is a regression. In previous versions, the thousands separator was dictated by the computer's locale.
