### ISSUE TITLE
Ledger - Confirming receiving address

### ISSUE THREAD

**Issue by jonasbkarlsson** [fyookball/electrum#434]
Thanks for adding Ledger support! Great!

Could you please add the possibility to confirm that the Receiving address shown in the Receive tab is actually part of the Ledger wallet? That is, the Receiving address should be possible to be shown in the Ledger device window. This is supported by the offical Chrome app for Ledger, so there should be an API call for this.

**Comment by marceloneil** [comment]
I'll check it out, thanks for the suggestion!

**Comment by jonasbkarlsson** [comment]
Thanks!

It took a while to find it. I almost gave up. But eventually I found it in the Addresses tab. :-)

Now, for usabillity reasons, this needs to be in the Receive tab as well. How about adding another icon next to the "Copy to clipboard" icon?

Also, you need to get the Ledger people to support the Cash address format...

**Comment by marceloneil** [comment]
Will do!

**Comment by marceloneil** [comment]
Will do!

**Comment by marceloneil** [comment]
CashAddr is now supported as of 3.2
