### ISSUE TITLE
Electron Cash 3.1.1 Windows fiat doesn't work

### ISSUE THREAD

**Issue by LightSunChen** [fyookball/electrum#435]
Electron Cash 3.1.1 Windows fiat doesn't work, please see pic :

![image](https://user-images.githubusercontent.com/5553519/34654637-22c42fe4-f431-11e7-80b8-aadeaedb6d04.png)

**Comment by yurkazaytsev** [comment]
@LightSunChen Do you use portable version? Can you check it in 3.1.2 release?

**Comment by marceloneil** [comment]
I was able to reproduce this using some black magic on linux, I'm looking into it

**Comment by marceloneil** [comment]
Ok, it seems like "history rates" is a bit broken. So a temporary solution in order to restore basic fiat features is to go to your config file (`%appdata%/Electron Cash/config`, or something like that) and remove the line `"history_rates": true`. Enabling "Show history rates" will break it again.
