### ISSUE TITLE
How do I check the checksum?

### ISSUE THREAD

**Issue by kaczan3** [fyookball/electrum#438]
On Electron Cash homepage it says I should do it and there's a link to sums, but I don't know how to check it.

**Comment by Harewolf** [comment]
Windows, Linux, Mac?

**Comment by kaczan3** [comment]
Windows 10.

**Comment by Harewolf** [comment]
https://www.nextofwindows.com/5-ways-to-generate-and-verify-md5-sha-checksum-of-any-file-in-windows-10

**Comment by kaczan3** [comment]
Thank you, I will try this.

**Comment by Harewolf** [comment]
If you are using Total Commander (Double panel  file manager) You can also verify checksum as following:  copy sha256 sum to clipboard, then highlight the file You want to check, then go to menu of total commander and choose file/checksum.
Good luck!

**Comment by fyookball** [comment]
7-zip has a nice sha checker too
