### ISSUE TITLE
error: The transaction was rejected by network rules. (16: mandatory-script-verify-flag-failed) 

### ISSUE THREAD

**Issue by dBIOSatrx** [fyookball/electrum#44]
Issue with the android wallet when creating a transaction. 

The wallet has been created using the seed from electrum. 
![screenshot_20170803-030512](https://user-images.githubusercontent.com/30701426/28935881-2da69a0e-7886-11e7-9084-26f06e36a347.png)

**Comment by fyookball** [comment]
will be fixed in upcoming release

**Comment by goldcountry** [comment]
@fyookball when is the next release?

**Comment by tex83rb** [comment]
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup
ImportError: No module named setuptools


when building from the source at the command 
phyton setup.py install
