### ISSUE TITLE
No module named 'httplib' 

### ISSUE THREAD

**Issue by jonahar** [fyookball/electrum#442]
When trying to run electron-cash I get an error 
`Error: No module named 'httplib'. Try 'sudo pip install <module-name>'`
When looking for a solution online I found out that `httplib` is not the name of this module anymore in python 3, and tried to use the 2to3 tool to fix this, but without success.
Does anyone have an idea?

I used `ElectronCash-3.1.1.tar.gz` on Ubuntu

**Comment by mlundyCO** [comment]
It appears the 3.1.1 tarball does not include the "packages" directory included with previous versions. Perhaps the tarball needs to be repackaged and signed?

**Comment by marceloneil** [comment]
Yep, the `./contrib/make_packages` command changed slightly so there was an issue with generating the `packages/` directory properly

**Comment by marceloneil** [comment]
This should be fixed in the 3.1.2 release

**Comment by jonahar** [comment]
Is there a workaround until the new release is out?

**Comment by mlundyCO** [comment]
The 3.1.2 release is out now.

**Comment by jonahar** [comment]
Thanks. Issue is indeed fixed.
