### ISSUE TITLE
Unfortunately Electron Cash become totally unusable

### ISSUE THREAD

**Issue by evadogstar** [fyookball/electrum#443]
Unfortunately it become totally unusable. Last working version is 2.9.4
Then it do not rn at my Fedora 25 system, because of no of dependencies. They request TONS of dependences. I install 5-6 of then at stop on `Error: No module named 'google.protobuf'`, because there is not such package. 
BTW, I do not happy with any GOOGLE modules at all, but this is unavailable at the repos. 
I also know other users at last Debian and many other OS who can not use Electron Cash not, because there are the same issues with missing dependencies.

**Comment by mlundyCO** [comment]
It appears the 3.1.1 tarball does not include the "packages" directory included with previous versions. Perhaps the tarball needs to be repackaged and signed?

**Comment by marceloneil** [comment]
`pip3 install protobuf` should work to install `google.protobuf`

If you want to build the package from source (so you don't need to manually install dependencies)
```
VERSION=3.1.1
# Download the source code
wget "https://github.com/fyookball/electrum/archive/$VERSION.tar.gz"
tar -xzvf $VERSION.tar.gz
cd electrum-$VERSION/
# Package the dependencies
./contrib/make_packages
# Compile the icons file for Qt
sudo apt-get install pyqt5-dev-tools
pyrcc5 icons.qrc -o gui/qt/icons_rc.py
# Compile the protobuf description file
sudo apt-get install protobuf-compiler
protoc --proto_path=lib/ --python_out=lib/ lib/paymentrequest.proto
# Create translations (optional)
sudo apt-get install python-pycurl gettext
./contrib/make_locale
# Copy packages
cp -r contrib/packages .
# Package binary
sudo apt-get install python3-setuptools
python3 setup.py sdist
```
@fyookball will have the tar.gz include the `packages/` folder soon

**Comment by hegjon** [comment]
Just a note, it will be easier when you upgrade to Fedora 27, that version ships Electron Cash in the default repository.

https://apps.fedoraproject.org/packages/electron-cash

**Comment by marceloneil** [comment]
Adding on to @hegjon's point, you can probably download the rpm and install it directly, although I don't use fedora so this is just a hunch.

https://koji.fedoraproject.org/koji/buildinfo?buildID=1014203

**Comment by hegjon** [comment]
It will probably work, but it depends on python3-jsonrpclib that needs also be installed manually

**Comment by marceloneil** [comment]
Also, the 3.1.2 release includes the `packages/` directory, so @evadogstar should be able to run it normally using that version
