### ISSUE TITLE
Distribute latest version on Android

### ISSUE THREAD

**Issue by seby2k** [fyookball/electrum#444]
Is this a finance software that aims for security or? The version in google play is still 2.9.4 (vulnerable to jsonrpc bug and subject to theft).

The latest version on the website is 3.1.1 which removes the cors code but does not merge the latest real fix that actually password protects the interface.

The app is hanging all the time. I suggest trying to do a better job.

**Comment by Red54** [comment]
I think this issue should be reopen, because the version in Google play is 3.1.3.1, but the latest version is 3.1.6.
