### ISSUE TITLE
Lost seeds!! Payment in BCH!!!

### ISSUE THREAD

**Issue by andrebonini9494** [fyookball/electrum#447]
Using "electron cash wallet", I want to send my bitcoin cash to another wallet, and I receive the error 16 because the 2 factors authentication does not work properly, I already know that I have to create another wallet to send my bitcoin cash and input my seeds to diseable the 2 factors authentication, but I HAVE LOST MY SEEDS, and from my 2.9.2 version I cannot retrieve the seeds from the application, may someone tell me how to send away my bitcoin cash??? Either by diseabling 2 factors authentication or retrieving the seeds? Please HELP ME!!! I have no idea what to do! Payment of 150€ in BHC for the correct solution

**Comment by fyookball** [comment]
i think you have to contact trustedkey if you lost your 2fa access and dont have the seed.  See #41
