### ISSUE TITLE
Ledger support

### ISSUE THREAD

**Issue by yura-pakhuchiy** [fyookball/electrum#45]
Ledger supports bitcoin cash in official client. It would great to support electron cash too.
@btchip Couldn't you submit patch? Must be trivial for you since you wrote original code for electrum.

**Comment by dare2win2** [comment]
Electron cash is not a crypto.i had a word with the guys at ledger.they says its not possible for them to import the electrum keys to ledger wallet

**Comment by fyookball** [comment]
this doesnt make sense.  how are they supporting bitcoin

**Comment by yura-pakhuchiy** [comment]
@fyookball https://blog.ledger.co/managing-the-bitcoin-cash-fork-7229dde3f358

**Comment by Aragonite** [comment]
1. From the source code, change line 656 of keystore.py:   44'/0' to 44'/145'
2. Update your LedgerHQ/btchip-trezor library and Trezor/python-trezor library

You should be good to go!

**Comment by Aragonite** [comment]
... sorry forgot to mention that your have to transfer your BCH to BIP44 "coin 145" addresses... but your coin splitter (beta-wallet.trezor.io - or ledgerwallet.com) would have done that for you already

**Comment by yura-pakhuchiy** [comment]
@Aragonite I tried applying change you proposed to 2.9.2 and to latest git, in both cases it still does not work.
I moved coins already to m/44'/145' using official ledger application and I'm using btchip-python-0.1.20 (latest version available in pip). 
ins ✓ ~/electrum/electrum-cash-git(cash)*$ ./electron-cash
```
"sni-qt/2739" WARN  06:14:45.848 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
Traceback (most recent call last):
  File "/home/yura/electrum/electrum-cash-git/plugins/ledger/ledger.py", line 411, in sign_transaction
    inputSignature = self.get_client().untrustedHashSign(inputsPaths[inputIndex], pin, lockTime=tx.locktime)
  File "/usr/local/lib/python2.7/dist-packages/btchip/btchip.py", line 383, in untrustedHashSign
    result = self.dongle.exchange(bytearray(apdu))
  File "/usr/local/lib/python2.7/dist-packages/btchip/btchipComm.py", line 119, in exchange
    raise BTChipException("Invalid status %04x" % sw, sw)
BTChipException: Exception : Invalid status 6a80
Traceback (most recent call last):
  File "/home/yura/electrum/electrum-cash-git/gui/qt/util.py", line 582, in run
    result = task.task()
  File "/home/yura/electrum/electrum-cash-git/lib/wallet.py", line 1103, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/yura/electrum/electrum-cash-git/plugins/ledger/ledger.py", line 422, in sign_transaction
    self.give_error(e, True)
  File "/home/yura/electrum/electrum-cash-git/plugins/ledger/ledger.py", line 201, in give_error
    raise Exception(message)
Exception: Exception : Invalid status 6a80
```
@fyookball why this issue was closed?  Are you not interested in supporting Ledger hardware wallets?

**Comment by Aragonite** [comment]
https://github.com/LedgerHQ/btchip-python is at version 0.1.21 - use git instead of pip to get the latest  mods.

**Comment by fyookball** [comment]
@yura-pakhuchiy I closed it because I thought @Aragonite provided what was necessary to resolve the issue.
