### ISSUE TITLE
BCH to Electron-Cash

### ISSUE THREAD

**Issue by shwimmy** [fyookball/electrum#450]
I have sent BCH to Electron Cash as suggested by a fellow online user. However I am unable to verify receipt of the BCH.  I am a total newb when it comes to Electron-Cash.  I just downloaded the software yesterday.  

I am seeing the inputs however it is telling me that the transaction is unrelated to my wallet.

Please help.

**Comment by shwimmy** [comment]
I know the address that I sent the BCH to and I know the address that I sent the BCH from as well as all security characteristics of the wallet that moved the BCH from.   I guess i really just do not know how to properly navigate Electron-Cash yet.

**Comment by fyookball** [comment]
confused how you are 'seeing the inputs'.  screenshot?

**Comment by shwimmy** [comment]
I am showing the inputs into the wallet and also an output.  
![screen shot 2018-01-10 at 10 48 06 am](https://user-images.githubusercontent.com/35299990/34781434-d16d426a-f5f3-11e7-9fcb-37b1221e4e62.png)
![screen shot 2018-01-10 at 10 48 06 am](https://user-images.githubusercontent.com/35299990/34781461-e223b04e-f5f3-11e7-9152-bbf09b252605.png)

**Comment by shwimmy** [comment]
Sorry about posting the screenshot twice

**Comment by shwimmy** [comment]
I am showing the inputs into the wallet and also an output.
![screen shot 2018-01-10 at 10 48 06 am](https://user-images.githubusercontent.com/35299990/34782586-2e66bf5c-f5f7-11e7-9289-3927373a4f5a.png)

**Comment by shwimmy** [comment]
Again I am very new here and I know that I am probably overlooking something very simple....

Could this be of help to you in helping me?

![screen shot 2018-01-10 at 10 48 06 am](https://user-images.githubusercontent.com/35299990/34783060-7ccbda00-f5f8-11e7-8ed9-971c2e8cdd24.png)

**Comment by shwimmy** [comment]
Again I am very new here and I know that I am probably overlooking something very simple....

Could this be of help to you in helping me?


![screen shot 2018-01-09 at 11 38 05 pm](https://user-images.githubusercontent.com/35299990/34783101-9a5d7574-f5f8-11e7-9bf3-60b49f3f2e48.png)

**Comment by shwimmy** [comment]
@fyookball Can you take a look?

**Comment by fyookball** [comment]
you just loaded a signed transaction.  but is your addresses that you are interested in showing up in your wallet ?

**Comment by shwimmy** [comment]
Correct

**Comment by shwimmy** [comment]
I am having trouble actually seeing this transaction in my wallet

**Comment by fyookball** [comment]
is this address 1KtSD......nfKY in your wallet?
