### ISSUE TITLE
BCH Fork on 13th Jan

### ISSUE THREAD

**Issue by Ringo982** [fyookball/electrum#451]
Hi to all!
I've just be informed that on 13th of Jan there will be a BCH fork, and for each BCH owned we will receive 1000 CDY.
I would like to know if Electrum Cash will support this and what i need to do to be sure to receive CDY.
Thank you!!

**Comment by fyookball** [comment]
I think Electron Cash will remain a BCH-only wallet for the near future at least. 

Maybe open another issue in a month as a reminder, I can take a look at how to claim
