### ISSUE TITLE
'receive' requests ledger

### ISSUE THREAD

**Issue by Human108** [fyookball/electrum#454]
Hi,

I've just installed 3.1.2. on a Mac running HighSierra 10.13.2. When I create a receive request and save it, then quit the application and re-open it, the save request disappears from the ledger. One request is for a live receive transaction (currently 1 confirmation). Please advise if this is a known bug? And if it's somehow possible to resurrect the 'receive' requests ledger? I am concerned that maybe the live transaction will not complete (as there is no corresponding request in the ledger).

Also when I created this wallet there was no option to create it with 2FA, is the 2FA option included in 3.1.2?

Thank you.

**Comment by marceloneil** [comment]
2FA is not currently supported, because electrum uses [trustedcoin](https://api.trustedcoin.com/#/) for 2FA which doesn't support BCH.

**Comment by fyookball** [comment]
#41 for workarounds related to recovering funds stuck in a 2fa wallet.
