### ISSUE TITLE
verifying Electron Cash 3.1.2

### ISSUE THREAD

**Issue by tomsmyname** [fyookball/electrum#456]
Likely I'm making a beginner's error but the SHA256 hash I generate of electroncash-3.1.2(1).exe using Hash Generator v5.5,  (f450e488b4592175db5c47feb13b11bbc229b767776ba0117c1e21bfdb2dc1d8), doesn't match the ElectronCash-3.1.2.exe.sig SHA256 hash which begins with "ff" and ends with "ad".   Can someone please help me understand why that is?  Thanks.

**Comment by fyookball** [comment]
Sigs and hashes are two different things.  You don't need both, either are a good way to verify.
The hash you wrote is exactly what I have , here:

https://github.com/fyookball/keys-n-hashes/blob/master/sigs-and-sums/3.1.2/win-linux/SHA256.ElectronCash-3.1.2.exe.txt

If you want to verify the sig, you use gpg.

**Comment by tomsmyname** [comment]
Thanks!
