### ISSUE TITLE
hi can someone help me recover my bch im getting a error

### ISSUE THREAD

**Issue by jamescrypto** [fyookball/electrum#464]
I send it like normal it looks like its about to send then ill get this error. ( I've attached a photo) 

this was my coins I received when btc forked and bch started.

thank you for your
![electrum cash errer](https://user-images.githubusercontent.com/34698113/34861158-a6f992c0-f717-11e7-8838-546fc6997e10.png)
 help

**Comment by marceloneil** [comment]
From https://electroncash.org/
> Versions prior to 2.9.4 are incompatible with network rules.

Can you upgrade to a more recent version?

**Comment by jamescrypto** [comment]
i also downloaded the new version 3.1.2 on a different computer and it let me enter my seed but it was not detecting my seed. i confirmed all spelling and checked twice.

**Comment by fyookball** [comment]
#41 for all 2fa issues.   All discussion/support/comments must go there if you still need help.  Closing.
