### ISSUE TITLE
Exception: invalid channel - NanoS

### ISSUE THREAD

**Issue by kaczan3** [fyookball/electrum#466]
I get this error when trying to send BCH from my Electron with Nano S. When I created the wallet I was also getting some errors about the devide being used by another app, but when I closed the browser, everything was fine.

**Comment by marceloneil** [comment]
Make sure that you are using the ledger "Bitcoin Cash app" (you should be able to download it using the Ledger Manager) and under settings for that app "Browser support" is disabled.

**Comment by kaczan3** [comment]
Yes, it seems the browser support being on was the problem. Even though I thinkk I tried that before, but I'm not sure. So it's safe to transfer the funds back?

BTW, I almost deleted the BCH app from nano, wanting to reinstall it. Would that delete they keys and I'd lost access to my BCH?

**Comment by marceloneil** [comment]
No, you should be safe to remove and add apps, they all derive keys from the same 24 word phrase. There is a page on the ledger zendesk about that I believe, so you don't need to trust me :)

**Comment by kaczan3** [comment]
Oh, I keep my 24-word phrase safe, so if any problems with Nano S arise, I'll never lose my money, as long as I have that?

**Comment by marceloneil** [comment]
Correct!

**Comment by kaczan3** [comment]
Thank you!

**Comment by marceloneil** [comment]
@deathbybinary wrote some documentation for using the ledger with Electron Cash, so hopefully that will help future users :)

**Comment by marceloneil** [comment]
@kaczan3 If you were able to receive and send without any issues please let me know and close the issue :)

**Comment by kaczan3** [comment]
Please wait a bit. Blocks are slow, so my tx got stuck on the way to Binance. When it gets there I'll try to send it back and make sure everything works.

**Comment by kaczan3** [comment]
OK, everything seems to be working fine. Thank you.

**Comment by marceloneil** [comment]
Great!
