### ISSUE TITLE
Electron-Cash 3.1.2 / Debian 9 : GUI doesn't start after upgrade

### ISSUE THREAD

**Issue by francis16** [fyookball/electrum#467]
Hello,

I run from the Electron-Cash root directory.
First execution : OK. It upgraded my wallet. I exited properly.
Further execution : the GUI doesn't show.
I noticed that when I click on Quit in the GUI, it exists but a process stays active : 
python3 /usr/local/Electron-Cash/electron-cash.
If I kill this process I can log again in Electron-Cash.
This did not happen with 2.9.4 (python2).

Thanks and best regards
Francis

**Comment by fyookball** [comment]
it shouldnt keep happening though as the upgrade is a one time thing
