### ISSUE TITLE
0 BCH outputs should not be produced

### ISSUE THREAD

**Issue by tjin92** [fyookball/electrum#469]
In Electrum, when you spend the entire balance of a UTXO (including all outputs and fees), it will know to not produce a change address:

![clipboard23](https://user-images.githubusercontent.com/5661419/34912421-2fcb79f4-f8af-11e7-9c2b-ee911555df3c.png)

However, in a similar situation Electron Cash will produce a change output of 0 BCH, causing the transaction to be rejected by the network as dust:

![clipboard24](https://user-images.githubusercontent.com/5661419/34912428-59a4f94e-f8af-11e7-8f25-6211aca520dd.png)

Note that this is for sending a regular transaction using a seed-based wallet, not sweeping private keys (which works just fine in both).

**Comment by kyuupichan** [comment]
This was fixed by https://github.com/fyookball/electrum/commit/9bf3b81fa28b627dc52c9d1609c31dd2965d0f01

**Comment by tjin92** [comment]
It seems that no new desktop version has been released since 3.1.2, which still contains the bug. When will the next desktop version be released?
