### ISSUE TITLE
multsig sending with trezor as cosigning device fails with UnexpectedDER: trailing junk after DER sig: 41

### ISSUE THREAD

**Issue by molecular** [fyookball/electrum#47]
```
RECEIVED PART OF SERIALIZED TX (39 BYTES)
SIGNED IN 10.244 SECONDS, CALLED 5 MESSAGES, 303 BYTES
adding sig 0 0 02c41936c0affe3a0b1d828dcc68dd4377a32bd7494ea8722b694a92f29ad317f4 304402207cbfb086e450496ce16a850e38c76a8939434b62780ba10afa4a68294651a04f022004305c3416ed9d891ae752a4cbd0c25ceec382df1584fa70eead5cd7c396056e41
Traceback (most recent call last):
  File "/home/nick/bitcoin/electron-cash/gui/qt/util.py", line 582, in run
    result = task.task()
  File "/home/nick/bitcoin/electron-cash/lib/wallet.py", line 1103, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/nick/bitcoin/electron-cash/plugins/trezor/plugin.py", line 66, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/home/nick/bitcoin/electron-cash/plugins/trezor/plugin.py", line 245, in sign_transaction
    tx.update_signatures(raw)
  File "/home/nick/bitcoin/electron-cash/lib/transaction.py", line 562, in update_signatures
    r, s = ecdsa.util.sigdecode_der(sig.decode('hex')[:-1], order)
  File "/usr/lib/python2.7/site-packages/ecdsa/util.py", line 240, in sigdecode_der
    binascii.hexlify(empty))
UnexpectedDER: trailing junk after DER sig: 41
```

**Comment by dabura667** [comment]
Ahhh, somewhere 01 is hard coded as a check, and the new sighash 41 is viewed as junk

**Comment by dabura667** [comment]
Probably in tx.update_signatures

**Comment by Aragonite** [comment]
@molecular Did you upgrade your Trezor to firmware 1.5.1 ?   I also modified keystore.py line 656 from "m/44'/0'/%d'" to "m/44'/145'/%d'"  which the new BIP44 number for BCH on Trezor (ref: SLIP44: https://github.com/satoshilabs/slips/blob/master/slip-0044.md)

Had a successful transaction with my Trezor and a modified version of electron-cash, as per above.

**Comment by dabura667** [comment]
Nevermind, it looks like Trezor plugin is adding 01 sighash on the end after the 41 sighash.

**Comment by Aragonite** [comment]
I also upgraded my python-trezor library to latest commit...

**Comment by junderw** [comment]
@Aragonite changing 0' to 145' will prevent people from recovering their old bitcoins... The electron new wallet also uses 0'

**Comment by junderw** [comment]
@molecular Can you confirm that you are using the latest firmware and which version of python-trezor you are using?

**Comment by Aragonite** [comment]
@junderw 

Looking at the big picture, in terms of hardware wallets - many years from now - Electron-cash should not be seen as a recovery or splitting tool, for hardware wallets.  If that is want you want, than you are misrepresenting what the Electrum technology was for over 6 years.  Trezor themselves made the distinction and created a seperate splitting tool.  

Electron-cash should allow Trezor / Ledger / KeepKey transactions according to established standards.  For this to occur, the BIP44 coin ID for BCH should be 145, not 0.   Electrum-LTC has a BIP44 Coin ID of 2,  and Electrum-Dash a Coin ID of 5.    Up to you to follow the standard or not, but if you don't, good luck in having customer penetration. 

For Electron-cash wallets that are no based on hardware wallets - who cares!  Electrum never agreed to BIP44 for its software based wallets.  So you can use anything you want in the derivation.  But for hardware wallets, you have to follow BIP44 standards.

**Comment by fyookball** [comment]
@Aragonite,  I am not that familiar with how the hardware wallets work as I've never owned one.   Isn't it conceivable that some users would have their seeds on the hardware wallet only and want to get their Bitcoin Cash?  

My thought on the software side is that for pre-fork balances, users can retrieve normally.  In the future, we'll probably add BIP39 with both 0 and 145.

**Comment by Aragonite** [comment]
@fyookball the mod (145') proposed in keystore.py is only for hardware wallets. It has to be implemented for Trezor/Ledger/KeepKey to be able to use your software to transact with the BCH network.  The relation between seed and hardware wallets have nothing to do with Electrum - seeds are provided by the hardware wallets to the users via their HW screens - never transmitted to a PC - ever.    

If you have a hardware wallet and want to split your BCH from BTC, you have to use a tool like SatoshiLabs put together.   Get a Trezor and find out how it works - if you want to be a serious maintainer of this software...

**Comment by jhoenicke** [comment]
@dabura667 in my unit tests the transactions returned by `sign_tx` are correct, only `41` not `01` at the end of the signature.  Who do you think adds the 01?  Maybe the bug is in `tx_inputs` in trezor/plugin.py.  The signature should be send without the sighash byte.

**Comment by jhoenicke** [comment]
That was the problem.  I'll send a pull request..

**Comment by fyookball** [comment]
can someone test this now that it is merged?

**Comment by molecular** [comment]
I retested and confirm cosigning multisig using trezor works.

Thanks you guys!!! You are the best!

**Comment by fyookball** [comment]
yes thanks Trezor... for supporting BITCOIN CASH.
