### ISSUE TITLE
I can't sign transactions offline on mac osx

### ISSUE THREAD

**Issue by Olorin22** [fyookball/electrum#470]
Hi there, Just tried to sign a bitcoin cash transaction using electron cash v3.1.2 on mac os x 10.11.6. I load the transaction file on my offline computer and the sign button is not highlighted, thus not "pushable". Do you have a fix for this? There are basically NO cold storage light wallet for bitcoin cash at the moment, and electron cash doesn't seem to live to the job.

**Comment by fyookball** [comment]
we'll look into it.  can you try signing offline with 2.9.4 ?

**Comment by cculianu** [comment]
Hi -- I'm the Mac guy on this project.  I'll look at you tomorrow and hopefully can recreate it and hopefully can fix it!  We may be able to get a build out quickly.  Be patient!

**Comment by Olorin22** [comment]
Hi , Thanks for the replies. @fyookball : no i didn't try with previous version, just with the latest, i.e. 3.1.2.
@cculianu thanks for your help, I am a super patient guy !
Just to further share some of my thoughts: I was pissed by ledger nano S a couple of days ago as I realized they were not broadcasting my low fees BCH microtransactions on the network ( 6 unconfirmed transactions so far...). I said, fuck them, I can't trust them with my funds. So I went through pretty much all BCH storage solutions, and electron cash just seemed to be the kind of wallet I was looking for: light and with cold storage, offline signing feature. So far, I got the best results with mac osx, as I did manage to do everything except the offline signing thing. I'm very much a linux guy too, so I installed it on my linux mint desktop. Unfortunately, even if  I was able to create wallets,  I was not able to get to see the balances, as the GUI won't launch, it sorts of crash. 
Ideally, I would love to install electron cash on an offline raspberry pi 3 , so I can generate and manage my funds from there, and do the offline transaction signing. 
So I would say lets tackle the mac os x issue first and let's see what we can do to sort the linux/Pi issues after. I'm sure this can be of interest for quite a few fellow bitcoin cashers here !

**Comment by cculianu** [comment]
Hi -- I can't reproduce this behvior on my Mac.  I can save tx's, load them, sign them.  I'm also on 10.11.6.

You know the "sign" button goes gray if the tx is **_already_** signed, right? Are you sure the tx isn't already signed?  Do you see a "broadcast" button that's not gray?  If the broadcast button is not gray (and the sign button is gray) -- the tx was already signed!

You are loading the tx from a file, correct?  It's saved as a .txn format?

If you're absolutely sure it's not signed, email it to me: calin.culianu@gmail.com.  You have my word of honor I won't broadcast it (even if it's signed).  

You saved it with what? Electron cash on another computer? Or the same computer?

Sorry -- provide more details so I can reproduce this issue, if it is indeed an issue.

**Comment by Olorin22** [comment]
Hi, Just sent the file. I generated it with electron cash on the "online" computer by importing the public key of my "offline" wallet, thus creating a "watch only" wallet, and then clicking on send->preview->save on USB. I could not have possibly signed it as the private key of that wallet is in another computer, the one I try to use to sign it, without success as the sign button doesn't work. Anyway, thank you very much for your help, it is very much appreciated.

**Comment by cculianu** [comment]
I was able to reproduce this and I don't think it's a macOS specific issue from the looks of it.

To reproduce:

1. create a deterministic seeded wallet on machine 1
2. xfer some BCH to machine 1 wallet
3. on machine 2, create a watch-only wallet on the address that is on machine 1
4. on machine 2, create an unsigned tx, save it
5. copy the tx to machine 1, open it.  Machine 1 thinks it's not a key in its wallet and it doesn't know how to sign it.  

What I know so far: The code fails in keystore.py, class XPub, function get_pubkey_derivation -- the wallet on machine 1 can't find the public key in the TX, even though it DISPLAYS the same tx in the gui.

If you save an unsigned txn *ON* the signing machine and open it later, it works ok.  

Only fails if you save an unsigned txn on machine 2, which is watch-only and has "Imported" keystore type in the code.

I am not familiar enough with the codebase to troubleshoot this further easily -- but I can plug away at it.

Any insights from @fyookball  or anyone else would be appreciated.

**Comment by fyookball** [comment]
Calin Culianu, [15.01.18 13:55]
he did something non-standard

Calin Culianu, [15.01.18 13:55]
he created a bip32 wallet on the offline (signing) machine

Calin Culianu, [15.01.18 13:55]
and then exported the key

Calin Culianu, [15.01.18 13:56]
the PRIVATE key

Calin Culianu, [15.01.18 13:56]
to 1 address
 
Calin Culianu, [15.01.18 13:56]
then he imported the key into another watch only wallet as a single key

Calin Culianu, [15.01.18 13:56]
what he SHOULD have dne (because EC is broken and only supports this usecase:) is exported the XPUB Bip38 master public key to the watch-only wallet

**Comment by cculianu** [comment]
MORE INFO: Wallet 1 on machine 1 is BIP32 based (xpub key nonesense)
Wallet 2 on machine 2 is basically an imported keystore where he pasted in the private key (not the xpub seed key, just the private key).

Wallet 1 *should* realize wallet 2 is creating a tx it has the key for (using key type 'fd'), but Wallet1 only likes key types 'ff' if it's Bip32 based.  The code that fails to recognize it is in get_key_derivation in class XPub, called by wallet.py can_sign()

So that's the problem.

I am not familiar enough with the code to fix it easily but I am going to try.  

But there is a workaround for the user to try which I will paste in here as a separate comment.

@kyuupichan  -- any ideas?

**Comment by Olorin22** [comment]
Sorry, but I exported and pasted the Public key of my offline wallet (machine 1), not the private key, in order to create a watch only wallet on machine 2. I pasted this 12FNeYp9KCVjg9cZk4mc3o8sR3HFQqXfAk which is indeed a public key ( i successfully sent transactions to that adress ).

**Comment by cculianu** [comment]
Here's the workaround:


As a workaround -- you should create a "watch only" BIP32 based wallet on the online "wach only" machine.  

Here is how you do it:

On the offline Signing Machine:

1. Go to Wallet->Information
2. Copy the "Master Public Key" (starts with 'xpub')


On the online Watch-Only machine:

1. Close Electron Cash
2. Rename your ~/.electron-cash folder to a backup, and type (in Terminal.app):

``   mv ~/.electron-cash ~/.electron.bak

3. Start electron cash again, it will ask you a bunch of stuff.  Say you want to do do "Standard Wallet" -> "Use wallet or private keys" -> paste in that 'xpub' key you got in step (2) in the previous section.

Now your watch only wallet is a Bip32 wallet and it will create tx's in a format the signing machine will understand.

It's a bug.  Sorry.

**Comment by cculianu** [comment]
@Olorin22  yeah sorry i meant to say public key. Sorry.  Fixed.

**Comment by Olorin22** [comment]
Ok, I followed through the workaround and used the Master public key xpub to open a watch only wallet on machine 2 and succesfully created, signed and broadcast the transaction which i received in my bitcoin.com wallet. So the workaround works, but maybe it is just the way i should have done it in the first place as suggested by fyookball? Neverthesless, what i was intending to do with my wallets works, so I thank you guys Cculianu and fiookball for your help and support! Now I wish i could do the offline part of all of this on a raspberry pi 3. I'll open a new thread i think. Cheers!

**Comment by Olorin22** [comment]
But still maybe there is some debugging to do in order to be able to do the same by just importing a raw public key, not just the masterkey, don't know. I have another question: the master public key can be public right? As far as i know, it only allows for the generation of all public adresses attached to the master private key ( or seed) that was used to create the wallet in the first place, but not in any case the recovery of any of the private keys, nor the master private key, am I right on this?

**Comment by cculianu** [comment]
You're welcome. Yeah.. I mean, honestly you did exactly what I would have done. I could see myself getting hit by this bug, TBH.

This taught me a lot about tx formats though -- Bitcoin (Cash) is intricate! :)

Hopefully I or someone else will figure out a fix..

**Comment by fyookball** [comment]
https://github.com/spesmilo/electrum/issues/2897

"online address + offline seed setup is not implemented; and there is no user-friendly way to implement it"

**Comment by cculianu** [comment]
Good find @fyookball !  👍 

It's not implemented but there's no technical reason why it shouldn't be.

The fix for it is about 3-5 lines of code.

Someone here made a fixed-tree:

https://github.com/goblin/electrum/tree/fix_2897

I can implement this if you want. His fix is actually was what I was working on as my approach too. It just gives me confidence my approach was ok (I was reading up on Bip32, etc). 

I can merge just that fix (the 5 line change --It's in the keystore.py, Xpub class) into Electron Cash.

The workflow to workaround this fix is unnatural to me.  Working with private keys directly on the online wallet seems more natural to me and to the average user.

The "correct" workflow that works now of importing the Bip32 xpub key to the online wallet is probably "the right way", but it's not obvious...

**Comment by cculianu** [comment]
OK created pull request #484  -- tested and works.  Recommend merging so our wallet can be the best!

**Comment by kyuupichan** [comment]
Hold on, it's not entirely surprsiing this is unsupported.  I'm not averse to doing something sensible though, but I'm not a fan of the scanning.  Why not just find the address in the wallet?

**Comment by cculianu** [comment]
You need the public and private key in the keystore class anyway to sign.  To get it you have to figure out which of the sequence the public address is.  Only way to do it is to scan, AFAICT.

**Comment by kyuupichan** [comment]
The wallet has a list of the addresses - we should use that.  Scanning is a hack - what if the address is number 1000?  Generating 1000 addresses is very expensive.  And you never know if you've gone far enough.

If it's in the wallet we should use it, and that doesn't require a scan.  Otherwise fail like now.

**Comment by fyookball** [comment]
@cculianu yeah but like it was mentioned, how do you know how far to scan?

**Comment by fyookball** [comment]
The more I think about this, the more I think we shouldn't try to hack to fix this, but maybe instead update the help docs and/or the tooltip.

**Comment by cculianu** [comment]
@fyookball , @kyuupichan  -- you guys are right.  The hack sucks, but is better than nothing.

I did a non-hack hack, where it actually gets the sequence number from the wallet address list.

See #484, which has been updated.

Leet me know what you think!

**Comment by fyookball** [comment]
Seems you are allowing it to follow a unique code path in this case @cculianu ? I looked at it and general idea seems ok, .. would like @kyuupichan to review.

**Comment by fyookball** [comment]
@kyuupichan see this chat I had with @cculianu for clarity on his fix:

CCul, [16.01.18 15:49]
like in a deterministic wallet
 
JF, [16.01.18 15:49]
but if he isnt using an xpub on the online watching wallet, how  does he get a sequence?
 
CCul, [16.01.18 15:49]
he doesn't!

CCul, [16.01.18 15:50]
soit generates a different format txn...

JF, [16.01.18 15:50]
ok ...  so then what does the offline do?
 
CCul, [16.01.18 15:50]
it figures out what the missing sequence number is so it can actually sign the tx.

JF, [16.01.18 15:51]
it just expects it in the keystore?

CCul, [16.01.18 15:51]
well it looks up the public address

CCul, [16.01.18 15:51]
i mean it has a list of addresses it generated
 
CCul, [16.01.18 15:52]
  the assumption is if he's watching some addresses.. he GOT them from the offline wallet
 
JF, [16.01.18 15:53]
i think its still possible for the user to have problems, but it sounds like your fix doesnt make it worse

CCul, [16.01.18 15:54]
which TBH is ok.. i mean.. the address wont' even BE there in his wallet.. (offline) singing wallet.. so it's not confusing..

JF, [16.01.18 15:54]
it will fix it in the cases where the offline wallet has the address at least.
 
CCul, [16.01.18 15:54]
in the other case you describe... he won't see the address and he'll be like "oh ok oh well"

JF, [16.01.18 15:55]
right

JF, [16.01.18 15:55]
ok.

CCul, [16.01.18 15:55]
and then you can tell him to actually use the xpub seed key thing

JF, [16.01.18 15:55]
well that is what the 'unrelated to this wallet means'

JF, [16.01.18 15:55]
so i guess your fix is good from the standpoint of the fact that they wont get that error when the address is there
