### ISSUE TITLE
Multisig + Send max amount: weird dust issue

### ISSUE THREAD

**Issue by imaginaryusername** [fyookball/electrum#472]
Only tried in desktop (Linux 3.1.2): Tried to empty a multisig (2-of-2) wallet to two separate addresses using the CSV format. Calculated fees and payment amounts to leave exactly zero satoshi, but the transaction generated keep getting a zero-amount (!) output, making it impossible to broadcast due to dust. Similar transaction that does not attempt to empty wallet does not have that problem.

**Comment by kyuupichan** [comment]
It's fixed in github; not sure if in most recent release
