### ISSUE TITLE
Cannot create "watch-only" (Online) Wallet using bitcoincash: (cashaddr) format addresses

### ISSUE THREAD

**Issue by cculianu** [fyookball/electrum#475]
It only lets you paste in regular legacy address format Public addresses, not the new bitcoincash: bech32 based addresses.  Steps to reproduce.

1. On a VM or having backed up your ~/.electron folder and renamed it, run Electron-Cash
2. Say you want to use a public/private key and you get the dialog to paste public and/or private keys
3. The "OK" button stays grayed for CashAddr (Bech32) style addresses, but if you paste in the legacy address for the same address, it accepts it and you can create the watch-only wallet.

Expectation is that Bech32 style addresses should be on "equal footing" with legacy addresses and either should be accepted as input here.

If you guys are busy -- I can take a stab at fixing it.  Let me know!  I just wanted to have the issue here on record.

**Comment by fyookball** [comment]
thanks for reporting and sure, try to fix...also see 476

**Comment by kyuupichan** [comment]
Huh?  I tried to create a watch-only wallet and it worked fine.  Your step 2 and 3 are too vague to reproduce.

**Comment by cculianu** [comment]
Hey man I am not sure if you deleted this message but I updated the
instructions to reproduce: you need top copy/paste the bitcoin address to
the watch-only wallet as opposed to the Bip32 pubKey Seed.. if that makes
sense.

So watch-only wallet signs a tx with public key type 'fd' based on the
bitcoin address (and not the public key seed).

But offline signing wallet expects key type 'ff' (which encodes a sequence
number)... which is why this bug happens.

I hope this makes sense...

**Comment by cculianu** [comment]
Huh.. this works fine in the latest off master!

On the released build (3.1.2) on my mac it fails with cashaddresses but works ok with regular bitcoin addresses.

Works fine when using the git off master.

Investigating why this would be... (if it's related to the build itself or if the code's changed recently or what)!

**Comment by cculianu** [comment]
Ok well I'm closing this issue.  It 100% definitely happens on the released build (on macOS I tested it). Can't import cash public addresses.

Doesn't happen on the current sources -- doesn't happen when I build for macOS on the current sources, so it's not related to building.

I'm assuming some of the code's changed with the validation of address input or whatever.  Since it now works -- closing it.  If you have info on what changed that fixed it -- would be nice to know just for my own information. 

Thanks for looking at this!

**Comment by kyuupichan** [comment]
Sorry I have no idea; don't recall touching anything related to this recently
