### ISSUE TITLE
Funds not received in my wallet electrum cash

### ISSUE THREAD

**Issue by edllanos** [fyookball/electrum#48]
Hi, I just sent my BTC funds from my wallet in Airbitz to my Electron cash wallet following all the instructions (using the private key of my Airbitz portfolio from http://www.airbitz.co/recovery and indicating my wallet in Electron cash) expecting to receive the equivalent in BCH, it turns out that now my balance in my wallet Airbitz appears at zero and I do not see reflected any balance in my Electron Cash portfolio.
Please I require your collaboration, which I can do, thank you very much.

**Comment by fyookball** [comment]
do you see it on the blockchain?  if so, you should see it on your wallet if connected to right server

**Comment by edllanos** [comment]
Hi Fyookball, In blockchain appears the transfer and the BTC balance appears in the Electrum cash account but it is hidden, please as I can remove these BTC and send them to my BTC wallet, Also change server and port in Electrum cash to “electrum-abc.criptolayer.net” and Port 50012.

Basically what I want in removing my BTCs in electrum cash.

Thank you very much.

Edward Llanos

De: fyookball <notifications@github.com>
Responder a: fyookball/electrum <reply@reply.github.com>
Fecha: jueves, 3 de agosto de 2017, 16:19
Para: fyookball/electrum <electrum@noreply.github.com>
CC: edllanos <edllanos@hotmail.com>, Author <author@noreply.github.com>
Asunto: Re: [fyookball/electrum] Funds not received in my wallet electrum cash (#48)


do you see it on the blockchain? if so, you should see it on your wallet if connected to right server

**Comment by fyookball** [comment]
they are 2 different blockchains BCC and BTC.  You can't "remove and send to your BTC wallet"

**Comment by edllanos** [comment]
Then my BTCs were lost ?? Ok I understand that they are two different chains and therefore I do not know what happened, but according to blockchain in my address of electrum cash appears my balance of BTC, although in the platform of Electrum the balance appears in zero, if you understand me?


De: fyookball <notifications@github.com>
Responder a: fyookball/electrum <reply@reply.github.com>
Fecha: viernes, 4 de agosto de 2017, 08:54
Para: fyookball/electrum <electrum@noreply.github.com>
CC: edllanos <edllanos@hotmail.com>, Author <author@noreply.github.com>
Asunto: Re: [fyookball/electrum] Funds not received in my wallet electrum cash (#48)


they are 2 different blockchains BCC and BTC. You can't "remove and send to your BTC wallet"

**Comment by fyookball** [comment]
Check a block explorer to know the actual balance.

**Comment by edllanos** [comment]
As I said in blockchain the balance appears with the BTCs that I send and there they are

De: fyookball <notifications@github.com>
Responder a: fyookball/electrum <reply@reply.github.com>
Fecha: viernes, 4 de agosto de 2017, 09:23
Para: fyookball/electrum <electrum@noreply.github.com>
CC: edllanos <edllanos@hotmail.com>, Author <author@noreply.github.com>
Asunto: Re: [fyookball/electrum] Funds not received in my wallet electrum cash (#48)


Check a block explorer to know the actual balance.

**Comment by edllanos** [comment]
How can I remove them and send them to my BTC wallet?

De: Edward Llanos <edllanos@hotmail.com>
Fecha: viernes, 4 de agosto de 2017, 09:26
Para: fyookball/electrum <reply@reply.github.com>
Asunto: Re: [fyookball/electrum] Funds not received in my wallet electrum cash (#48)

As I said in blockchain the balance appears with the BTCs that I send and there they are

De: fyookball <notifications@github.com>
Responder a: fyookball/electrum <reply@reply.github.com>
Fecha: viernes, 4 de agosto de 2017, 09:23
Para: fyookball/electrum <electrum@noreply.github.com>
CC: edllanos <edllanos@hotmail.com>, Author <author@noreply.github.com>
Asunto: Re: [fyookball/electrum] Funds not received in my wallet electrum cash (#48)


Check a block explorer to know the actual balance.

**Comment by fyookball** [comment]
if they are on BCC chain you will see them in your BCC wallet.  Make sure you are using latest 2.9.2 
Honestly i am having a hard time understanding you. if you paste screenshots and links it might make communication easier
