### ISSUE TITLE
Accidentally swept Bitcoin Cash to Watch-Only Wallet

### ISSUE THREAD

**Issue by togra87** [fyookball/electrum#480]
Hi there! I took my seed from bread wallet an created keys with bip39-standalone tool. With my generated public key I created a watch-only wallet in electrum cash. Then I did a sweep with my generated private key from bread wallet to claim 2.5 BCH in electrum cash. I can see the 2.5 BCH in the balance bu as I can't spend them (watch-only), they seem to be stuck in the watch-only wallet. And as I didn't get a seed while creating the wallet, I cannot recover the wallet as a standard one and have no idea how to get them out there. What can I do now? And why is it possible to sweep BCH to watch-only wallet if they are lost then? Please help me!

**Comment by marceloneil** [comment]
If you created a watch-only wallet using a public key generated from a private key that you own, you should be able to recover the funds

**Comment by fyookball** [comment]
is it a 2fa wallet @togra87

**Comment by fyookball** [comment]
im unclear how you created a watch only wallet? Where did you get the xpub to create it in the first place

**Comment by togra87** [comment]
Hi, thanks for your fast answers. I used bread wallet for iOS before and only had a seed (12 words). This seed I entered in bip39 stand-alone tool to generate public keys and private keys. Than I took the public extended key (xpub) and created a wallet in electron-cash OS X where I did a sweep with the generated private key. It’s not 2FA. Does that answer your questions?

**Comment by marceloneil** [comment]
You should be able to create a new wallet and enter your private key to access the funds

**Comment by togra87** [comment]
I think the mistake was to sweep/claim the bitcoin cash into a watch-only wallet. When I want to transfer the balance from my wallet the signate and broadcast buttons are grayed out. That feels so bad...

**Comment by togra87** [comment]
When I create standard wallet and enter the private key (from brad wallet) it shows the old wallet where balance is zero because of transaction to the watch-only wallet. Problem is that you can create a watch-only wallet without getting a private key or seed.

**Comment by marceloneil** [comment]
But the watch only wallet was create from the public key, which was derived from the private key that you own.

**Comment by togra87** [comment]
Yeah, that’s right.

**Comment by marceloneil** [comment]
:/

**Comment by togra87** [comment]
Why can I create a watch only wallet without getting a seed and then sweep coins in there if it’s impossible to get them out again. I don’t get the use case behind. It’s like throwing money in a black hole, that’s crazy, isn’t it?

**Comment by marceloneil** [comment]
Usually people own the wallet that they are watching, (which in this scenario it seems you do as well, so you should be able to recover your funds)

**Comment by togra87** [comment]
Oh, I found another advise: The Header Bar says: Electron Cash 3.1.1. - wallet_name (imported_addr, watching only). That means I set up the watch only wallet like this:

- File > New/Restore
- Entered wallet name and pressed "next"
- Import Bitcoin addresses or private keys
- Entered Bitcoin address from old bread wallet
- Wallet > Private keys > Sweep
- Entered Private key from old bread wallet
- Got 2.5 BCH Balance
- Now stucking and cannot get them out

Sorry for confusion, maybe that helps to find the solution?

**Comment by kyuupichan** [comment]
I've read this but it's very unclear.  You're going to have to be more clear, including what the tool does.  If you have a seed and the address was generated from the seed, you will be able go get it back.  But we don't support people doing random things - not really fair to expect us to help resolve all the arbitrary things people go and do.

**Comment by fyookball** [comment]
WHy not just create a new wallet with the bip39 seed?

**Comment by togra87** [comment]
Sorry guys for wasting your time, I thought you're the only experts around and as no one else could help me so far, I wanted to give it a try... If someone can help to get my 2,5 BCH I would send over 0,5 BCH just to say thank you, maybe thats fair enough?

@fyookball Creating a new wallet with the old seed doesn't work because the sweep transferred all BCH to the new "imported_addr, watching only" wallet in electrum-cash. Doing so will just show me my old empty wallet with the transfer history.

So the main problem still is, that I created an "imported_addr, watching only"-wallet which comes along WITHOUT a seed. Then I swept 2.5 BCH from my old wallet to the "imported_addr, watching only"-wallet in electrum-cash. So the Coins are inside the new wallet but there is no seed or private key to create a new standard wallet. I can just see my balance, transaction and the BCH address in the wallet and thats it. But it seems to be impossible to get the coins out again.

Was that a better descripton now? Sorry for my English, I come from Europe and am not a native speaker.

Cheers

**Comment by fyookball** [comment]
@togra87 we are trying to help you, but it is not clear what you did.  

If you have a bip39 seed, you should be able to recover any funds from those addresses.  I think we are all on the same page as far as that goes.

But it sounds like you created ANOTHER address which you then swept the funds to.  How did you create that other address?

**Comment by imaginaryusername** [comment]
You said you 

File > New/Restore
Entered wallet name and pressed "next"
Import Bitcoin addresses or private keys
Entered Bitcoin address from old bread wallet
Wallet > Private keys > Sweep
Entered Private key from old bread wallet
Got 2.5 BCH Balance
Now stucking and cannot get them out

That sounds like the watch only wallet was created from an address from the "old bread wallet". In other words, seed/privkey from that very same wallet (where you got the address from in the first place) should be able to help you.  There IS a privkey, you just need to get it from the old bread wallet, for which you still have the seed. You basically moved BCH from one (or multiple) addresses from that wallet to another address on the same wallet.

**Comment by fyookball** [comment]
doesn't sound like E.C. issue, closing... @togra87 if you still need help, you can keep posting , we will try to assist based on information provided.

**Comment by inducer** [comment]
I think what @ghost is complaining about is a user interface issue: The "sweep" UI option was enabled for a watch-only wallet despite being a really bad idea in that situation, and I think he's suggesting that that option be disabled.
