### ISSUE TITLE
On startup, every transaction from August 26th onward is "Not Verified"

### ISSUE THREAD

**Issue by patrikr** [fyookball/electrum#482]
When I start EC 3.1.2 (and previous versions) all transactions from August 26th 2017 onward have "Not Verified" in the Date field, until I connect to a server. (I connect through Tor, so if Tor Browser isn't running the client stays like this forever.)

I suspect something isn't saved that should be, and has to be re-downloaded on each connect?

**Comment by marceloneil** [comment]
Thats odd.

The blockchain headers sync to a file called `~/.electron-cash/blockchain_headers`, and you can check the currently synced block height by accessing the "Network Tool" go to tools>network or click the green/red orb in the bottom right. 

The current height as of writing this is 513113, and your blockchain headers should persist throughout sessions.

Maybe try removing `~/.electron-cash/blockchain_headers` and syncing it again? This may take some time if you do it over tor :/

**Comment by patrikr** [comment]
This is a Windows 8 laptop, is C:\Users\Patrik\AppData\Roaming\ElectronCash the correct path to that file? The size of the file is 41 049 280 bytes, how big should it be by now?

The last transaction that shows a date on startup is included in block 482568 (2017-08-25 04:33 UTC) and shows 171 confirmations.

**Comment by marceloneil** [comment]
Yeah thats the correct directory, my file is also `41 049 280 bytes`, so that should be correct. Is there anything interesting when you open the network tools within electron cash?

**Comment by patrikr** [comment]
I don't see anything strange, other than that it says "Blockchain: 482738 blocks" on startup.

**Comment by marceloneil** [comment]
What do you mean it says that on startup? Is there a popup or something?

**Comment by patrikr** [comment]
No, I opened the Window and looked.

**Comment by marceloneil** [comment]
Oh in the network tools

**Comment by marceloneil** [comment]
Are you disconnected from the internet? Do you have any connected nodes?

**Comment by patrikr** [comment]
??? - Like I said in the very first post, everything is OK once I connect, so of course I'm connected to the Internet.

**Comment by marceloneil** [comment]
I just wanted to verify, what does it say under "Connected Node", and node heights

**Comment by patrikr** [comment]
Let's see if this works, trying to Ctrl+V a screenshot in here: 
![image](https://user-images.githubusercontent.com/802611/34970129-3e5bb420-fa7b-11e7-8c45-b8d0d092a2c9.png)

**Comment by marceloneil** [comment]
Ok, so the reason that you are behind is because you aren't connected to any nodes. Are you able to connect to any tor or non-tor nodes?

**Comment by patrikr** [comment]
And after starting Tor: 
![image](https://user-images.githubusercontent.com/802611/34970171-7bca5cc6-fa7b-11e7-913b-4a85c7f8f439.png)

**Comment by marceloneil** [comment]
Ok, thats expected, so you said that rebooting it _without_ tor put you behind again?

**Comment by marceloneil** [comment]
So you're saying that if you restarted, it would go back to block 482738?

**Comment by patrikr** [comment]
Yes.

**Comment by marceloneil** [comment]
And you've tried backing up and removing the `blockchain_headers` file?

**Comment by patrikr** [comment]
I haven't tried removing it, because it's up to date (as we already determined) and being updated with every new block.

**Comment by marceloneil** [comment]
Yes, but there is a chance that there might be an incorrect header in that file, that _somehow_ is being overlooked when you reconnect. It would be nice if you could get a log, but I'm not quite sure how to do that on windows

**Comment by patrikr** [comment]
Hmm, I opened the config file and see this line: 
"blockchain_index": 478559,
What does that mean?

Anyway, I renamed blockchain_headers to blockchain_headers.bak now and restarted. Syncing...

**Comment by marceloneil** [comment]
Thats a good catch, it seems like `blockchain_index` was put in place for the bitcoin/bitcoin cash fork in order to verify users where using the right chain. Try backing up your config and removing that, I'll bet that does something

**Comment by patrikr** [comment]
Removing blockchain_headers did NOT work, same issue still. I'm not going to start deleting random things in the config. 478559 is the fork block, I found out.

**Comment by fyookball** [comment]
sounds like you got a bad block maybe from an old electrumx server running abc 0.15... i would just start over an reinstall after backing up wallet files and seeds.

**Comment by patrikr** [comment]
I just re-downloaded all the block headers, so if that's the case I got the same bad block again...

I'll probably switch to the portable version at some point, hopefully the problem goes away then.

**Comment by fyookball** [comment]
did you try deleting recent_servers file?

**Comment by marceloneil** [comment]
OK, I can reproduce this error when I use the server `bitcoincash.quangld.com`
@patrikr I would suggest switching nodes

**Comment by fyookball** [comment]
and delete recent servers.
