### ISSUE TITLE
bitcoin cash stuck in watching only wallet 

### ISSUE THREAD

**Issue by daveheap** [fyookball/electrum#483]
I tried to transfer out bitcoin cash to my wallet but did not realise that my Electrum Wallet would only accept BIT COIN.
After waiting and watching 2 days I realised this mistake and opened an Electron Cash Wallet and was able to receive the bit coin cash into a watching only wallet, by importing the electrum address.

NOW after researching many things I am unable to do anything with this bitcoin cash which still shows in the Electron Cash Wallet, but I cannot spend it as I cannot send it anywhere.

I do have the private key that originally belonged to the imported electrum address 

I hope someone can help me with this

**Comment by marceloneil** [comment]
Can you create/restore a new wallet with electron cash and input your private key? Make sure that you are running the verified release from https://electroncash.org/

**Comment by fyookball** [comment]
is it a 2fa wallet @daveheap

**Comment by daveheap** [comment]
Thanks for your replies, tried the following 2 things:

1) New / Restore -> create "Standard Wallet" -> use public or private key -> create keystore from a master key "to create a spending wallet, please enter a master private key" ->  pasted the private key that belongs to the previous ELECTRUM BITCOIN address but it doesn't work, "Next" button is greyed out

2) New / Restore -> Import Bitcoin addresses or private keys - Import Bitcoin Addresses - pasted the private key that belongs to the previous ELECTRUM BITCOIN address -> resulted in error message "Electron Cash Error" - only options are "Open Console" or "Terminate"

@fyookball this is not a 2FA as it's a watch only wallet

**Comment by fyookball** [comment]
private key is likely in wrong format.  I am able to import private key with:

New / Restore -> Import Bitcoin addresses or private keys - Import Bitcoin Addresses - pasted the private key

**Comment by daveheap** [comment]
thanks for this fyookball and totally agree our bitcoin private key is almost certainly in wrong format to put into an elctroncash wallet -
However we don't have any other private keys - any other ideas on this ?

**Comment by fyookball** [comment]
https://cashaddress.org/  (go to wallet details)

best to use offline if a lot of money

**Comment by daveheap** [comment]
totally agree but anyone any idea how I can get this money out ??!! It shows in the watching wallet !

**Comment by kyuupichan** [comment]
I have yet to see a coherent explanation of what happened.

**Comment by kyuupichan** [comment]
Why don't you get the private key from Electrum and import it into Electron Cash.  That will work fine.

**Comment by daveheap** [comment]
thanks for this kyuupichan but I've tried the following things: 

1. New / Restore -> create "Standard Wallet" -> use public or private key -> create keystore from a master key "to create a spending wallet, please enter a master private key" -> pasted the private key that belongs to the previous ELECTRUM BITCOIN address but it doesn't work, "Next" button is greyed out

2. New / Restore -> Import Bitcoin addresses or private keys - Import Bitcoin Addresses - pasted the private key that belongs to the previous ELECTRUM BITCOIN address -> resulted in error message "Electron Cash Error" - only options are "Open Console" or "Terminate"

3. Under "Wallet" -> "Private Keys" -> it only gives me the option to "sweep", not import.

I'm not a programmer, far from it, but I am pretty sure that my mistake of accidentally trying to put bitcoin cash in an ELECTRUM  wallet is not the first such mistake ! 

The transaction received many many confirmations on the blockchain and obviously this was sufficient to put the money into a watching only ELECTRON CASH wallet which I set up by importing the ELECTRUM  address. 

AS a layman I feel as sure as I can be that there is a technical solution to this - - - HELP !!

**Comment by fyookball** [comment]
@daveheap I am following your #2 option and when it is a valid key, it works fine.  This should be for a single private key.  I don't get this Electron Cash Error.  Can you try with a few different private keys and tell me if youre able to at least import a private key that way?

**Comment by daveheap** [comment]
thanks once again fyookball tried with several other private keys and got the same error message as before in my option 2

**Comment by daveheap** [comment]
I also tested importing an electron cash private key and it works just fine - SO it seems that as the private key I have is an ELECTRUM private key the electron cash wallet cannot process it 
And once again as a layman I am absolutely sure I am not the first to make this mistake and feel there must be a technical solution somehow !! Many thanks for help thus far and fingers crossed !!

**Comment by fyookball** [comment]
can  you try changing the priv key to different formats using "wallet details" tab on cashaddress.org?  Use an offline copy of this for safety please , or better yet dont use your actual priv key, just check the format of one that doesnt have a balance

**Comment by daveheap** [comment]
thanks so much for keeping trying fyookball but this is the message I got when  I entered another private key from the previous electrum wallet under wallet details just as you said 
The text you entered is not a valid Private Key
Version 133 not supported!

**Comment by daveheap** [comment]
As I said already although I'm not a programmer I am absolutely certain I am not the first person to accidentally try to put bitcoin cash into a bitcoin wallet and I also cannot believe there is not a technical solution out there.
If this money is truly lost it's a very sad reflection on this whole new world it really is.

**Comment by kyuupichan** [comment]
@daveheap you can import the private key from Electrum.  I have done it more than once.  The formats are the same.

**Comment by daveheap** [comment]
thanks so much for your reply but as it's 1.0 am now I'm going to bed but if you get chance to read the thread above I'd really appreciate it. You may see something I've done wrong in all the various attempts 
Many thanks

**Comment by kyuupichan** [comment]
I think you chose the wrong item.  It's not a Standard Wallet, it's the 3rd option (import private key)

**Comment by daveheap** [comment]
Thanks again and what you say "the formats are the same" gives a glimmer of hope except that we've tried the whole recommended process with the following results: 

New / Restore -> Import Bitcoin addresses or private keys - Import Bitcoin Addresses - pasted the private key that belongs to the previous ELECTRUM BITCOIN address -> resulted in error message "Electron Cash Error" - only options are "Open Console" or "Terminate"

Any ideas what we can be doing wrong ??

**Comment by fyookball** [comment]
As I said previously, the private key is probably in the wrong format.   Where did you get this private key from originally?  Did you try putting the privkey into different formats?

**Comment by kyuupichan** [comment]
@daveheap please run from a terminal window with -v option and provide a backtrace

**Comment by daveheap** [comment]
can't do this I'm not a programmer - any chance of hiring one for an hour ?

**Comment by daveheap** [comment]
what's in there is definitely worth an hour's fee for a programmer

**Comment by marceloneil** [comment]
Are you on a mac, pc or linux?

**Comment by daveheap** [comment]
a mac

**Comment by marceloneil** [comment]
Try running this in a terminal window:
```
/Applications/Electron-Cash.app/Contents/MacOS/Electron-Cash -v
```

**Comment by daveheap** [comment]
I did this but it just opened the same "watching only" wallet 
Would it be useful for you to see the output of the terminal ? I have saved it

**Comment by fyookball** [comment]
@daveheap you say you get the same error using multiple different private keys.  Can you give me a test key (without funds) and paste it here please
