### ISSUE TITLE
Unable to start electron-cash connected to testnet

### ISSUE THREAD

**Issue by johnconger** [fyookball/electrum#486]
electron-cash  --testnet 
----stack trace----
ValueError: not enough values to unpack (expected 3, got 1)

Running in verbose mode shows....
electron-cash  --testnet -v
[SimpleConfig] electron-cash directory /home/usr/.electron-cash/testnet
[get_server] unexpected EOF while parsing (<unknown>, line 0)
[Plugins] registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
[Plugins] registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
[Plugins] registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
[Plugins] registering hardware trezor: ('hardware', 'trezor', 'TREZOR wallet')
[profiler] __init__ 0.0036
[Network] blockchains dict_keys([0])
Traceback (most recent call last):
  File "/usr/local/bin/electron-cash", line 4, in <module>
....rest of stack trace

**Comment by fyookball** [comment]
is this latest 3.1.2. ?

**Comment by johnconger** [comment]
The problem occurred under 3.0 - I attempted to upgrade to 3.1.2 and got an installation error

Processing dependencies for Electron-Cash==3.1.2
Searching for pyqt5
Reading https://pypi.python.org/simple/pyqt5/
No local packages or download links found for pyqt5
error: Could not find suitable distribution for Requirement.parse('pyqt5')

-- I attempted to re-install pyqt5 with

sudo apt-get install python3-pyqt5

and linux reports back that I am already on the current version - 

I did not have this problem when I installed 3.0 - Now Electron-cash does not run

Any pointers?

**Comment by fyookball** [comment]
does it work on non testnet now or just doesnt work?

**Comment by johnconger** [comment]
It's not working at all.  I'm getting a pyqt5 error.

electron-cash
.....
pkg_resources.DistributionNotFound: The 'pyqt5' distribution was not found and is required by Electron-Cash

but when i 
sudo apt install python3-pyqt5

i get
python3-pyqt5 is already the newest version (5.5.1+dfsg-3ubuntu4)

I wasn't getting this problem on 3.0

**Comment by johnconger** [comment]
Okay I worked through the PYQT5 problem and now i am NOT getting the error when trying to connect to testnet.  So I'm going to consider this problem solved.  Thanks for your help.

**Comment by marceloneil** [comment]
Yep, testnet was fixed in #397 (3.1 and onwards)
