### ISSUE TITLE
Transaction Would Not Confirm and then it Disappeared

### ISSUE THREAD

**Issue by curt0** [fyookball/electrum#487]
Last week, I exported the private keys from my offline Electrum wallet to an Electron Cash wallet.  In addition, I created two additional Electron Cash wallets: offline wallet and online “watch only”.

On the online computer, I sent some small amounts of BCH back and forth from the first Electron Cash wallet to the “watch only” wallet.  These worked fine.

Then I tried to send the remaining balance from the first wallet to the “watch only” wallet.  Both wallets showed the transaction, waiting for confirmation. I searched for the transaction ID on BlockExplorer and couldn’t find it.

Over 3 hours passed and there was still no confirmation. Maybe this is because I allocated only 1 sat/byte as fee. The transaction information window showed that the expected confirmation time is 25 blocks, transaction size is more than 950 bytes and fee is 9 cents.

I shut down Electron Cash and restarted. When the wallet windows appeared, the unconfirmed transaction appeared for a split-second and then disappeared. There is no trace of the transaction anywhere. Luckily the balance did not get deducted.

I found out, by changing servers, that the transaction re-appeared when I manually selected:

`electrum-bch.adminsehow.com`

I tried several other servers and the transaction did not appear.  I tried electrum-bch.adminsehow.com again, and it would not connect.

What happened to the transaction? Did I do something wrong? Is it safe to submit this transaction again?

**MINOR ISSUE**

Before I did the above, I did the following.  I exported the private keys from my offline Electrum wallet to an Electron Cash wallet and added a password to encrypt it.  I copied the Electron Cash wallet to my online computer.  When I tried to send some BCH, it prompted me for a password.  I entered that password and it rejected it.  I don't know why.

So, I repeated the process from the beginning.  I exported the private keys from my offline Electrum wallet to another Electron Cash wallet and added a password to encrypt it.  I copied this second Electron Cash wallet to my online computer.  When I tried to send some BCH, it sent it right away without asking for a password.  I noticed that the padlock was unlocked.  I don't know why it was unlocked.  I clicked it and added a password.  I tried sending another transaction, it prompted me for the password, I entered it and it was accepted.

Do you think there is a bug?

**IMPORTING PRIVATE KEYS VERSUS OPENING/CONVERTING ELECTRUM WALLETS**

I followed the instructions from here (https://techhelpkb.com/claim-bitcoin-cash-from-electrum-to-an-spv-wallet/) to import private keys, but this does not let me create a watch-only wallet.  Later, I found out that I could have simply opened and converted the Electrum wallets, and created a watch-only wallet.  Can I delete the first wallet and use the converted wallet (with watch only) instead?

**Comment by fyookball** [comment]
which version are you on, for starters?

**Comment by curt0** [comment]
3.1.2

**Comment by fyookball** [comment]
it the tx confirmed now on the blockchain?

**Comment by curt0** [comment]
I don't think so.  It still does not appear on the wallet.  I do not know how to get it to appear.

FYI, Electron Cash is selecting server automatically.  I closed and opened Electron Cash to change the server.  Server is electron cash.cascharia.com.  I manually changed it to cash.checksum0.com and the missing transaction still does not appear.  I changed it to electrum-bch.adminsehow.com and it will not connect (Network circle is red).

**Comment by fyookball** [comment]
your network color is still red?  sounds like firewall / anti virus issue then.

should be green.

**Comment by curt0** [comment]
The network color is green.  It went red when I manually selected electrum-bch.adminsehow.com as the server.  For the servers selected automatically, the network color is green.  I tried electrum-bch.adminsehow.com to see if the missing transaction will appear, but it does not, especially when Electron Cash cannot connect to electrum-bch.adminsehow.com.

**Comment by fyookball** [comment]
could have been a transaction sent with dust limit issue.  i think that may have been patched. was it using very small outputs or something?  Sounds like some nodes have it and some don't.  Maybe try sending from the same outputs if you dont have it and set the fee slightly higher.  Not sure what to tell you

**Comment by curt0** [comment]
The first 3 transactions that I sent were small and they worked.  This fourth transaction, which disappeared, had 6 inputs and 2 outputs and the outputs were not small.

How do I send from the same outputs?  How high should the fee be?  Is there a guideline, such as 1 sat/byte for transactions up to 300 bytes, 2 sat/byte for transactions up to 600 bytes, etc.?

Yes, it does seem that one node, minimally, has this transaction.  It seemed like it was electrum-bch.adminsehow.com.  But Electron-cash will not connect to electrum-bch.adminsehow.com again.

This seems really strange.  Now that several days have passed, is it safe to assume that this transaction is either still in the Mempool of a node, or in a shorter blockchain which is ignored because it is not the longest chain?

Are you confident that nothing will go wrong if I try to send this same amount again?

**Comment by fyookball** [comment]
create a new wallet with the same seed, and do not connect to that troublesome node.  then just send again from the same addresses you were sending from before

**Comment by curt0** [comment]
> addresses  ?

I assume you mean address (singular).  I'll provide the same "Receiving address" from the receiving wallet to the sending wallet.  I'll let you know how it goes.

Can you respond to **MINOR ISSUE** and **IMPORTING PRIVATE KEYS VERSUS OPENING/CONVERTING ELECTRUM WALLETS** in the OP?

**Comment by curt0** [comment]
> Last week, I exported the private keys from my offline Electrum wallet to an Electron Cash wallet. In addition, I created two additional Electron Cash wallets: offline wallet and online “watch only”.
> 
> On the online computer, I sent some small amounts of BCH back and forth from the first Electron Cash wallet to the “watch only” wallet. These worked fine.
> 
> Then I tried to send the remaining balance from the first wallet to the “watch only” wallet. Both wallets showed the transaction, waiting for confirmation. I searched for the transaction ID on BlockExplorer and couldn’t find it.

From which of the above wallets should I get the seed, to create a new wallet?  The first one with the BCH balance imported from Electrum?  Or, the new, second wallet?

**Comment by fyookball** [comment]
>Can you respond to MINOR ISSUE and IMPORTING PRIVATE KEYS VERSUS OPENING/CONVERTING ELECTRUM WALLETS in the OP?

Please create a separate ticket for each issue because otherwise its very hard to communicate.

**Comment by fyookball** [comment]
From which of the above wallets should I get the seed, to create a new wallet? The first one with the BCH balance imported from Electrum? Or, the new, second wallet?

Whichever wallet you are trying to send from.  What I am saying is that if the TX appears and disappears intermmitantly, it may be a bad tx that wont get relayed because of fees or dust or whatever, so the solution is you just connect to a node that doesnt see it with a fresh wallet file.

**Comment by curt0** [comment]
FYI:   I used the Electrum wallet that I had opened and converted with Electron Cash, to send.  I used the same ("second") watch-only wallet that I created last week with Electron Cash, to receive.  I used the same "receiving address" as before.  Electron Cash selected electron.jns.im server.  This time it worked and confirmed.

Thanks for your help!
