### ISSUE TITLE
Showing ghost transaction from the BTC Network

### ISSUE THREAD

**Issue by rafaelbro** [fyookball/electrum#49]
Error where the electron cash is aparently reading a transaction id I made with the BTC network hours after the fork
![image](https://user-images.githubusercontent.com/30268382/28941967-1229b632-7870-11e7-9666-5e43e83b87e7.png)
If I check the transaction ID the wallet showed me I used to send my funds I can see that it only exists in the BTC network
![image](https://user-images.githubusercontent.com/30268382/28942131-9ac2f7f6-7870-11e7-8971-44fff8d87790.png)

**Comment by danny91** [comment]
What server you connected too? Are you sure your on a bcc server.

**Comment by rafaelbro** [comment]
How do I check if I am using the correct server? I thought using electron cash would put me in the correct server

**Comment by danny91** [comment]
tools > network

**Comment by rafaelbro** [comment]
![image](https://user-images.githubusercontent.com/30268382/28944475-14027be8-7879-11e7-8c09-d977ae965123.png)

**Comment by danny91** [comment]
yeh your on the wrong one...  Rightclick on the 651ef99cb9 branch and click follow.

**Comment by rafaelbro** [comment]
It worked now, thanks!
