### ISSUE TITLE
Unable to withdraw BCH from wallet - "incorrect password" when none exists

### ISSUE THREAD

**Issue by CryptDo** [fyookball/electrum#493]
Hello,

I can't get my 5.22 BCH out of my wallet and the recently imported 5.26 BCH do not show up (but the fee was taken out.) The wallet was upgraded to the latest a few days ago, but same result.

The wallet was created by importing a private key. Subsequently I swept a couple of paper wallets with no problem. But the last two, above, I get that error. There is no password and if I try to add one, I get the same error.

**Comment by fyookball** [comment]
i am confused what you're saying.  Sounds like several issues?  First, do you see the correct balance?

**Comment by CryptDo** [comment]
I got it figured out. But yes it was several issues. For some reason I
couldn't send out of the wallet. But I was still able to reimport that tx
on a coinomi wallet (and then that showed up in the Electron Cash wallet).
The other issue was probably my miscalculation. Thanks for getting back to
me.

Best
