### ISSUE TITLE
Password rejected, then on second try, it did not ask for a password

### ISSUE THREAD

**Issue by curt0** [fyookball/electrum#494]
I exported the private keys from my offline Electrum wallet to an Electron Cash wallet and added a password to encrypt it. I copied the Electron Cash wallet to my online computer. When I tried to send some BCH, it prompted me for a password. I entered that password and it rejected it. I don't know why, because I'm very certain that I entered the same and correct password.

So, I repeated the process from the beginning. I exported the private keys from my offline Electrum wallet to another Electron Cash wallet and added a password to encrypt it. I copied this second Electron Cash wallet to my online computer. When I tried to send some BCH, it sent it right away without asking for a password. I noticed that the padlock was unlocked.  Why was it unlocked this time?  I clicked it and added a password. I tried sending another transaction, it prompted me for the password, I entered it and it was accepted.

Do you think there is a bug?

**Comment by fyookball** [comment]
not able to recreate this
