### ISSUE TITLE
Importing Private Keys Versus Opening/Converting Electrum Wallet

### ISSUE THREAD

**Issue by curt0** [fyookball/electrum#495]
I followed the instructions from [https://techhelpkb.com/claim-bitcoin-cash-from-electrum-to-an-spv-wallet/](https://techhelpkb.com/claim-bitcoin-cash-from-electrum-to-an-spv-wallet/) to export private keys from the Electrum wallet and import them to a new Electron Cash wallet.  But, this resulting Electron Cash wallet is strictly an online wallet and does not let me create a watch-only wallet.

Later, I found out that I was able to use Electron Cash to simply open and convert the Electrum wallet, and create a corresponding watch-only wallet.

Can I delete the first wallet (with imported private keys) and use the second wallet (converted from Electrum wallet with watch-only wallet) instead?

**Comment by fyookball** [comment]
If you have electrum, you should have an electrum seed, right?

**Comment by curt0** [comment]
Yes, I have the seed.

**Comment by fyookball** [comment]
so i highly recommend just using the seed in a new electron cash wallet.  No need to mess around with importing keys.

**Comment by curt0** [comment]
I was able to use Electron Cash to simply open the (copy of) Electrum wallet.  It showed a message that it was going to convert the wallet.  Isn't this an even easier way, than to get the seed and create another Electron Cash wallet?

**Comment by fyookball** [comment]
You can try it that way too.
