### ISSUE TITLE
Checksum of Electron-Cash-3.1.2-macosx.dmg

### ISSUE THREAD

**Issue by xavez** [fyookball/electrum#498]
When I execute a `shasum` on the downloaded `Electron-Cash-3.1.2-macosx.dmg`, it is not the same a the one I found here:

https://github.com/fyookball/keys-n-hashes/blob/master/sigs-and-sums/3.1.2/mac/SHA256.Electron-Cash-3.1.2-macosx.dmg.txt

Anyone else has this problem? Any possibility at all that this might be an error?

**Comment by verretor** [comment]
Don't use it if the checksum doesn't match.

**Comment by xavez** [comment]
Not planning on doing that, but I do want to double check what’s going on . . .

**Comment by marceloneil** [comment]
I downloaded the dmg and checked it and it seems fine. Try redownloading. If it still doesn't work compare sha256sums between downloads, you may have a network issue.

**Comment by fyookball** [comment]
shasum is wrong command, you need specifically sha256sum

**Comment by xavez** [comment]
Thanks, that wasn’t clear to me :-). All good.
