### ISSUE TITLE
Address format changes when unsigned transaction file is passed from watch-only to offline wallet

### ISSUE THREAD

**Issue by curt0** [fyookball/electrum#499]
I created a transaction to send BCH from one Electron Cash watch-only wallet to another Electron Cash watch-only wallet, using the new address format.  I saved the file and re-opened it to confirm that the address is the same and in the new format.  The input and output addresses started with “qr” or “qz”.  So far, so good.

I passed the unsigned transaction file to the off-line computer.  I opened the file.  The address was different and was in the legacy format.  The input and output addresses started with “1N”, “1K” and “1F”.

Why?

Should I start over from the beginning and use the legacy address format?

**Comment by kyuupichan** [comment]
Address format is a UI property, and not a property of the transaction. You are seeing it in a different format because the software configuration on your other machine is for a different format.

**Comment by curt0** [comment]
You're right.  I changed the format on the other machine.  Transaction worked.

Thanks.
