### ISSUE TITLE
Electron Cash connects to Electrum BTC servers

### ISSUE THREAD

**Issue by ecdsa** [fyookball/electrum#5]
see 75feac5d1eb027548b3c51803e26b11b4a0ad97b
https://github.com/kyuupichan/electrumx/commit/75feac5d1eb027548b3c51803e26b11b4a0ad97b#commitcomment-23417823

**Comment by tex83rb** [comment]
this can be avoided selecting right chain in network preferences. but should be correct since the start

**Comment by fyookball** [comment]
I think this problem is because we forget to remove code that initially downloads headers from electrum.org  Molecular's suggestion was to not download them.

**Comment by ecdsa** [comment]
no that's not what I am talking about, headers are unrelated

**Comment by fyookball** [comment]
Ok i will re-open this.  Thanks.  Is there a suggested fix?

**Comment by ecdsa** [comment]
yes, see what I wrote in the link above.
the filtering of peers should not rely on the server, that's a really bad design.
you should do it in the client, for example with a checkpoint

**Comment by fyookball** [comment]
from kyuupi:
the stuff I said about verify_header().  In that function, in the mainnet part, if the height is the fork height and the hash is not the fork hash, reject

**Comment by fyookball** [comment]
closing because #86 was opened for this.
