### ISSUE TITLE
Cashaddr not accepted when creating watch-only wallets

### ISSUE THREAD

**Issue by imaginaryusername** [fyookball/electrum#501]
Linux 3.1.2. When pasting Cashaddr addresses into the "create watch-only wallet" box, box doesn't recognize the address and "next" remains disabled. Workaround: Use built-in translation tool to translate to legacy address and it works.

**Comment by kyuupichan** [comment]
Please give basic information like what version you are running.  This works fine in git head.

**Comment by imaginaryusername** [comment]
Sorry, should've have said "Linux 3.1.2", Electron Cash 3.1.2 on Linux. 

It's the "Import Bitcoin Address" window. Just did a little more testing:
1. Cashaddr was not detected ("next" greyed out) both with or without prefix.
2. Legacy format detects just fine.
3. Bitpay format was not detected.

**Comment by marceloneil** [comment]
Doesn't work in 3.1.2 but works in git head
