### ISSUE TITLE
Electron Cash Icon Borrowing Bug via Electrum

### ISSUE THREAD

**Issue by eve83111** [fyookball/electrum#507]
There are huge problems with using Electron Cash when Electrum is installed, including but not limited to icon share problems.

I have Electrum installed, and running Electron Cash 3.1.2 linux portable. I have tried to play around with the icon .png files, tried changing it to a custom icon. Turns out that Electron Cash doesn't use those icons.

I have even deleted the `Electron Cash-3.1.2/icons` folder and nothing happened.

The only explanation is that Electron Cash uses the Electrum icon set. 

This is a big bug, and I suspect many other files are also borrowed from the installed Electrum directory.

It should be addressed ASAP.

**Comment by fyookball** [comment]
can you show me a screenshot of the symptom?

**Comment by eve83111** [comment]
@fyookball  I can't but I will describe it better.

I am using Debian 9. I have installed the latest Electrum wallet, normally with `sudo python3 setup.py install`.

Then I have downloaded Electron Cash 3.1.2 and ran it as portable executable with `./electron-cash`

I have tried customizing the main blue icon just as fun, colored it red, then started electron cash and it still showed it blue. It was strange, because I remembered that the Electrum dev said that Electron Cash uses the same install location as Electrum.

So I have deleted the entire `icons` folder from Electron Cash directory, and I ran it, and nothing happened, the icons still showed.

So I think Electron Cash uses the installed Electrum icon set, since there was no other copy on my computer.

Now I can't delete the Electrum icons too, as that would break that install, but if somebody wants to expeeriment with that, do it.

I think Electrum Cash is very buggy as it uses a lot of files from Electrum just as the dev warned here:
* https://twitter.com/ElectrumWallet/status/891954053110001665
* https://twitter.com/ElectrumWallet/status/891935330235973633

**SOLUTION:** I think the only solution is to completely rename every single "Electrum" or "electrum" string in every single file of Electron cash to electron_cash or something like that, whatever format you guys use.

You can download notepad++, it supports multi-file editing, and open every single text file and rename every  "Electrum" or "electrum" string to "electron_cash" for instance, it would take like 2 minutes:
* https://notepad-plus-plus.org/

**Comment by marceloneil** [comment]
I believe that you're experiencing this issue because Electron Cash doesn't read icons from the folder `icons/`, but rather the file `gui/qt/icons_rc.py`. If you look at the [README](https://github.com/fyookball/electrum#development-version), it describes how to re-compile this file:
>Compile the icons file for Qt:
>```
>sudo apt-get install pyqt5-dev-tools
>pyrcc5 icons.qrc -o gui/qt/icons_rc.py
>```

In terms of Electron Cash being buggy and using Electrum's files, that has since been resolved. Those tweets are pretty old. If you experience any issues with Electron Cash and Electrum living together report them here, however I have no issues running them both side-by-side on my system.

**Comment by eve83111** [comment]
@marceloneil Wow that is a pretty unelegant way to fetch icons, via hex code?

I guess if an icon is missing or modified it recompiles the icons from that?

So then what is the point in having the /gui folder if the icons are read from hex code?

I don't have other issues with Electron Cash, but I'd use the portable EC version. Haven't experienced other issues with it.

**Comment by marceloneil** [comment]
@eve83111 I'm not quite sure why it's like that, but it has something to do with the pyqt resource system.

The QT and kivy implementation of Electron Cash are in the `gui/` folder. So all the layouts, dialog, buttons and UX logic are in there. Electron Cash can actually run as a command-line utility without the need for a gui.
