### ISSUE TITLE
Verifying signature does not work with cashaddr format

### ISSUE THREAD

**Issue by imaginaryusername** [fyookball/electrum#513]
When verifying a message/signature pair: Using cashaddr in the "Address" box results in "Invalid Bitcoin Cash address". If I translate using the translator to legacy format it works fine.

Oddly enough generating signature ("Sign") using cashaddr works just fine. 

Linux - Fedora 27 (from repo) Electron Cash v3.1.2

**Comment by marceloneil** [comment]
I can reproduce the same issue, although I'm getting the error "Wrong Signature" instead of "Invalid Bitcoin Cash address" for using a bitcoin cash address, but using legacy works fine.

**Comment by kyuupichan** [comment]
I believe this was fixed recently

**Comment by marceloneil** [comment]
Yep, works fine in git head
