### ISSUE TITLE
Still Unable to create unsigned (payTo) transaction

### ISSUE THREAD

**Issue by YosefYud** [fyookball/electrum#514]
This issue was raised about a week ago (https://github.com/fyookball/electrum/issues/489), yet the fix seems to not resolve the problem. After updating to 3.1.3 and using the latest code, which includes fix #497 and commit 01a622c (by cloning the repo), an unsigned 'payTo' command returns an error. The error and the steps to reproduce the error, are the same as in issue #489. This is the case for testnet and mainet. 

Your help is greatly appreciated.

**Comment by marceloneil** [comment]
Are you sure you are using 3.1.3? It wasn't released for desktop

**Comment by marceloneil** [comment]
Also, that commit wasn't merged in until after 3.1.3 was released. You would need to run from source to get this to work, or bug @fyookball for a new release.

**Comment by YosefYud** [comment]
True. I am combining the latest source code release (.tar.gz for 3.1.3) and a fresh repo clone which includes the fix for #497

**Comment by marceloneil** [comment]
It should work with [`01a622c`](https://github.com/fyookball/electrum/commit/01a622c8eb34f817d5aad9aac10d017a8bd552fb), although you might get a "transaction fee to high" error if you follow the steps in #489

**Comment by YosefYud** [comment]
Thanks for your prompt response.
The code is a new repo clone + install. My electrum/lib/contacts.py seems to be up to date with  01a622c (Address.from_string(k)), yet the payTo command returns: 

yosef@dacc-ops-04:~/OperatorHot$ python3 /usr/local/bin/electron-cash  --testnet  payto mgRoeWs2CeCEuqQmNfhJjnpX8YvtPACmCX 0.012 --unsigned --fee 0.001 -w /var/Hot/Electron-cash/devCash/Wallet0.dat
Traceback (most recent call last):
  File "/usr/local/bin/electron-cash", line 4, in <module>
    __import__('pkg_resources').run_script('Electron-Cash==3.1.3', 'electron-cash')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.3-py3.5.egg/EGG-INFO/scripts/electron-cash", line 423, in <module>
    result = server.run_cmdline(config_options)
  File "/usr/local/lib/python3.5/dist-packages/jsonrpclib/jsonrpc.py", line 650, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.5/dist-packages/jsonrpclib/jsonrpc.py", line 532, in _request
    check_for_errors(response)
  File "/usr/local/lib/python3.5/dist-packages/jsonrpclib/jsonrpc.py", line 1220, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.3-py3.5.egg/electroncash/wallet.py", line 942, in make_unsigned_transaction | electroncash.util.ExcessiveFee\n')

**Comment by marceloneil** [comment]
Yep, you're getting `ExcessiveFee`. Try lowering the fee

**Comment by YosefYud** [comment]
Interesting. Will test it once again. Thank you

**Comment by YosefYud** [comment]
ExcessiveFee indeed. Thanks for all the help
