### ISSUE TITLE
Bounty for raspbian electron cash package and installation guide ! 

### ISSUE THREAD

**Issue by Olorin22** [fyookball/electrum#517]
Hi fellows! 
I would like to incentivize the making/adapting of the electron cash app to a raspbian OS computer. Basically, it should look like a zip file with all the needed files and an installation guide in order for the wallet on raspbian to run as an offline wallet ( so installation must be doable without an internet connexion) . The whole package should be open source obviously. Tell me how much BCH you would accept for the task. Once we agree, you could post the files here or elsewhere in order for me to release the payment to your submitted adress (after test). 
Hope someone will be interested in the project ! 
Cheers!

**Comment by marceloneil** [comment]
Does the tar.gz from https://electroncash.org not work on raspbian?

**Comment by Olorin22** [comment]
Hi! I pasted it on the desktop and I didn't manage to run it. I've so far never been able to run it on a linux distro. I'm really sucking at it right now. This is why i'm so desesperate...

**Comment by marceloneil** [comment]
Ok, I just finished downloading raspbian, I'm going to test it on a raspberry pi 2 b

**Comment by Olorin22** [comment]
I have a rasbp pi 3.

**Comment by marceloneil** [comment]
Works find on the raspi 2, should be fine for the raspi 3. You just need to install `python3-pyqt5`. You can do this easily online using `apt`, I'm not sure how to do it offline though - you'd have to research that yourself.

Here are some hints for getting your offline wallet going: https://electroncash.readthedocs.io/en/latest/old/coldstorage.html
