### ISSUE TITLE
ELECTRON CASH ONLINE WALLET

### ISSUE THREAD

**Issue by sunnyleow** [fyookball/electrum#518]
Hello,

I have downloaded the MAC application for Electron Cash wallet for Bitcoin Cash, if my PC MAC OS corrupted, how do i re-install and get back my existing BCH balance in my wallet?

**Comment by imaginaryusername** [comment]
As long as you got your mnemonic seed words backed up (written down somewhere) you should be able to restore from that on a fresh copy.
