### ISSUE TITLE
The amount in Electron Cash still not verified for hours!

### ISSUE THREAD

**Issue by eemad1** [fyookball/electrum#52]
On my wallet on Electron Cash the amount is still in history and Not verified for about 24h!
Even if I change the server , it's not working.
Could you please help me to get my BCC.

Thanks,
Imad
![1167885730292043613-account_id 0](https://user-images.githubusercontent.com/30703512/28946366-5aeef2ec-78a2-11e7-9099-60116d552ed5.png)

**Comment by fyookball** [comment]
what does the blockchair block explorer say

**Comment by charleshsu168** [comment]
this issue has been fixed with 2.9.2 release with electrum 
the changes were merged with electron cash source code.
see https://github.com/spesmilo/electrum/issues/2681
you need to compiled the  latest source code

**Comment by fyookball** [comment]
@charleshsu168 i am currently attempting to build android for 2.9.2
