### ISSUE TITLE
README.rst ultimate confusion about which .tar.gz it is talking about

### ISSUE THREAD

**Issue by jidanni** [fyookball/electrum#520]
No matter if one downloads
1. https://github.com/fyookball/electrum/archive/3.1.2.tar.gz or
1. https://electroncash.org/downloads/3.1.2/win-linux/ElectronCash-3.1.2.tar.gz

one will still see a file README.rst and within it still see
> If you downloaded the official package (tar.gz), you can run Electron Cash from its root directory...

Both the people who downloaded (1) and (2) will think:
"He must be talking about me, I downloaded a "tar.gz" package!"

However (1) and (2) are 10 times in size difference. So they indeed must
be in fact different.

OK, now let's take the argument "well those users should know the differences
via the Download page they used!"

Those download pages respectively are:
1. https://github.com/fyookball/electrum/releases
1. https://electroncash.org/#download

The text of the hyperlinks respectively are:
1. Source code (tar.gz)
1. Run From Source Code

So they both must be some kind of source code.

As we see the confusion is _extreme_. My only advice is to change the
README.rst to say
> If you downloaded the official package (tar.gz),
> the one that you got from ...org, the one that is 10 megabytes.
> then ...
> If instead you got the one from ...com, the one that is 1 megabyte,
> then ...

**Comment by marceloneil** [comment]
The github.com one is automatically generated by github, and contains all the source code (includes build scripts). It's essentially a snapshot of the repository at the time of release. The electroncash.org one is packaged and signed by fyookball with all the dependencies and removes unessential scripts. This one can be installed using `pip install ElectronCash.tar.gz`.

I agree that maybe it isn't super clear, although I'm not sure if that many users download from github without understanding this. Maybe replace "Run From Source Code" with something else?

**Comment by jidanni** [comment]
@marceloneil thanks but many users will think "I'll chose the GitHub version rather that one I found on some website" and thus will end up downloading the GitHub version. Especially as both are called "Source code" in their hyperlinks. So they "must be the same".
