### ISSUE TITLE
entropy concerns and improvements

### ISSUE THREAD

**Issue by fyookball** [fyookball/electrum#523]
The following is from reddit user:  u/alexander7k

I was chatting with @fyookball , but I think it's better posted here so that other people can contribute too.

I have a theory that the current Seed Generation algo is insecure and misleading newbies. I am no cryptographer but I know enough about math and random numbers to know what I am talking about.

I am talking about the mnemonic.py file and the make_seed function
1) First Problem

The first problem is with the custom_entropy variable, it's totally misleading. It doesn't add entropy into the seed, it replaces the computer generated entropy limit with the one the user inputs.

This is problematic because it assumes that humans are good at generating entropy. It's false.

Most people will input here their date of birth, their marriage date, their kid's name, so forth... That information carries 0 entropy, since any potential hacker targeting them personally will know that.

The argument that people need custom entropy since the computer PRNG is weak is sort of not good. I have tested my PRNG (on a sample size of 1m), and I have found only 0.5 bits lost after 2,000,000 bits queried.

I doubt any newbie can outperform that. Certainly not with "common passwords".

Secondly the custom_entropy method doesn't add entropy, it actually swaps the PC generated one with the user generated one, but not the entropy only the bit length.

Example: My DOB is: 1980-Jan-05 , I am a newbie and I put that as my custom entropy.

This translates to: 0011000100111001001110000011000000101101010010100110000101101110001011010011000000110101

Which is incorporated into the Seed.

I query a 100 bit seed, the make_seed function will add this 88 bits and ask the computer to generate 12 bits more.

Therefore I assume that I get a 100 bit entropy seed, unfortunately my seed will only be 12 bit strong, but 100 bit long.

Just like the SHA256 hash of the character "0" is 5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91b46729d73a27fb57e9

Yes the hash 256 bit long but the entropy of "0" is literally 0.

There is a cryptographic theory which says that the output entropy of a hash function is maximum as much as much as the input entropy, but probably less due to not being a random oracle

Therefore if a newbie puts there his DOB, he might get a 132 bit long seed, but the actual entropy might be 50-bit or less.

And that is dangerously low, any high end PC can brute-force a seed that weak, hackers are already setting up GPU rigs to brute force Bitcoin private keys.

Consult with cryptographic experts on this if you don't believe me: * https://crypto.stackexchange.com/
2) Second Problem

The other problem with custom_entropy is that it multiplies the PC generated entropy.

This is wrong, multiplication can't produce prime numbers, therefore the actual entropy generated this way is even smaller.
3) Third Problem

The ECDSA function starts from 1 not 0, therefore 2num_bits has only (2num_bits - 1) outcomes . I suggest using this code: my_entropy = ecdsa.util.randrange(pow(2, num_bits) + 1)

Again I have actually tested this, the ECDSA function is a provably discrete uniform probability distribution, over 1m samples the output is indistinguishable from a discrete uniform probability distribution, the bit loss is 0.5 bits after 2,000,000 bits queried, and no autocorrelation between the elements.

Test it yourself: https://pastebin.com/3rFWZ7Wa
4) Fourth Problem

Last but not least the nonce += 1 can just be moved to the end of the loop, otherwise we exclude the first outcome which is illogical, we only need to check a different number if the current one is not compatible.

Thus in my opinion the function should look like this:

def make_seed(self, seed_type='standard', num_bits=132):
    prefix = version.seed_prefix(seed_type)
    my_entropy = ecdsa.util.randrange(pow(2, num_bits) + 1)
    nonce = 0
    while True:
        i =  my_entropy + nonce
        seed = self.mnemonic_encode(i)
        assert i == self.mnemonic_decode(seed)
        if is_old_seed(seed):
            continue
        if is_new_seed(seed, prefix):
            break
        nonce += 1
    print_error('%d words'%len(seed.split()))
    return seed

**Comment by SomberNight** [comment]
Re (1) and (2), newbies don't use `custom_entropy`, it's a little-known CLI option, not exposed to the GUI at all... However, PRs welcome.
Re (3) that code has now changed a bit in upstream and excludes low values completely as they would result in a shorter seed, which is a LOT worse (but highly unlikely) than what you are describing.
Re (4) does it really matter that much?...

**Comment by fyookball** [comment]
re 4) does it?

**Comment by SomberNight** [comment]
Well first of all, the suggested change fairly easily results in an infinite loop, so I did not really take it seriously:

```python
def make_seed(self, seed_type='standard', num_bits=132):
    prefix = version.seed_prefix(seed_type)
    my_entropy = ecdsa.util.randrange(pow(2, num_bits) + 1)
    nonce = 0
    while True:
        i = my_entropy + nonce
        seed = self.mnemonic_encode(i)
        assert i == self.mnemonic_decode(seed)
        if is_old_seed(seed):
            continue
        if is_new_seed(seed, prefix):
            break
        nonce += 1
    print_error('%d words'%len(seed.split()))
    return seed
```

There is a `continue` above `nonce += 1`...

A much easier change to "correct" the problem you observed is to simply initialise `nonce = -1` and keep everything else as is. PRs welcome :)

**Comment by fyookball** [comment]
gonna mark as enhancement for now to keep the repo clean...for some reason OP cannot create github account.  Closing.
