### ISSUE TITLE
Ledger wallet linux support

### ISSUE THREAD

**Issue by cashaddressio** [fyookball/electrum#526]

**Comment by marceloneil** [comment]
Ledger wallet nano S and blue are both supported on linux

**Comment by fyookball** [comment]
what needs to be done to support ledger (not just nano S)?

**Comment by marceloneil** [comment]
Well, I think I'd need either support from someone who owns one of the other devices, or from ledger directly. I've trieid to contact ledger a few times but I gave up after a bit.

**Comment by fyookball** [comment]
@marceloneil contact u/btchip on reddit ... ask him to send you one and ask what he knows about which is not supported.

**Comment by jonasbkarlsson** [comment]
I don't know what problem the creator of the issue had, but I'm aware of two issues.
1) Electron Cash has difficulties finding the Ledger device first time you set up a wallet. After a Ledger wallet is set up, there is no problem connecting to the Ledger device again.
2) If you have two HD wallet accounts, you need two Electron Cash windows. The connection to the Ledger device does not automatically switch to the other window, when you switch window.

I have those issues in both Linux (Ubuntu 16.04) and Windows 10.

Also, as far as I'm aware, there is no difference between Ledger Nano S and Ledger Blue regarding the interface towards Electron Cash.

**Comment by marceloneil** [comment]
@jonasbkarlsson in what use-case would you need two wallets both connected to a ledger? Multisig/standard wallets side-by-side?

**Comment by jonasbkarlsson** [comment]
I probably used the incorrect terminology. In HD-wallet terminology (BIP44), I meant that if I have two different "accounts" (which Electron Cash handles as two wallets), then when I in File->Recent select the other "account", a new window is opened, but it does not seem to share the connection to the Ledger with the previous window. The Ledger icon the lower right corner is red.

**Comment by marceloneil** [comment]
If they contain the same addresses, what's the purpose in having a duplicate?

**Comment by marceloneil** [comment]
Oh I see

**Comment by marceloneil** [comment]
@jonasbkarlsson do you mind creating a new issue (or two) for the outlined problems?

**Comment by emergent-reasons** [comment]
@jonasbkarlsson, @cashaddressio, did you file an issue for the initial wallet setup with ledger or otherwise find a solution? I have never been able to setup a wallet with ledger nano on linux but I have not investigated why. I can file if you have not.
