### ISSUE TITLE
Modularize coin name, symbol, and branding to ease forks

### ISSUE THREAD

**Issue by jidanni** [fyookball/electrum#527]
Perhaps implement https://github.com/spesmilo/electrum/issues/3807 ideas directly in Electron Cash.

**Comment by fyookball** [comment]
BCH was a necessary fork after a multi year scaling debate that should have never happened.  But I'm not really understanding why we need more forks?

**Comment by jidanni** [comment]
All I know is there are a lot of coins, and a lot of wallet families, and this family seems like a cleaner implementation (no interaction with browsers, no [gobbledygook left in .config](https://github.com/Bitcoin-com/Wallet/issues/60)) so maybe it will be a prototype for more wallets, so at least it might as well not have names hardwired in it as much as possible.

**Comment by jidanni** [comment]
It seems just as in the coin world some people unhappy about forks, same with the wallet world,
https://github.com/spesmilo/electrum/issues/3807#issuecomment-362395686 .
