### ISSUE TITLE
Sailfish OS (OS for mobile) version

### ISSUE THREAD

**Issue by MalkavianBilbao** [fyookball/electrum#528]
It would be great to have a native version of Electron Cash for Sailfish OS ( https://sailfishos.org/ ). Is a near pure linux OS of Jolla Ltd ( http://jolla.com ) , business created by ex-Nokia employees wich is having mobiles made at Europe and BRICS (Brazil, Rusia, India, China, Sudafrica).

I read that electrum runs with Python2 and Qt4 and to get it approved Sailfish app the backend must be ported to Python3 and the gui must be implemented in QML and PyOtherSide.

**Comment by marceloneil** [comment]
Electron Cash currently uses Python 3 and QT5, and the gui is implemented in both QT and Kivy (Kivy is the "mobile" UI)

**Comment by fyookball** [comment]
marked as enhancement
