### ISSUE TITLE
Multisig Wallet from Electrum 2.7 not Syncing correctly 

### ISSUE THREAD

**Issue by edit489** [fyookball/electrum#530]
We have a multisig wallet that we used in Electrum 2.7 (and earlier) and when we enter the master public keys into Electron Cash, it doesn't sync correctly. It is missing transactions. We've experienced this before in Electrum, and it seems to be a version issue. There are previous versions of Electrum to download that work with the MPKs, but there are no versions of Electron Cash before 2.9, since that was the version at the time of the fork.

It's a 2 of 4 multisig and we have all 4 MPKs, and we have at least 2 of the 4 private keys. Is there any way to restore the BCH balance in this wallet?

**Comment by kyuupichan** [comment]
Are the addresses in the addresses tab what you expect to see?  Which address has an incorrect balance?  What does it show on a block explorer?

**Comment by kyuupichan** [comment]
So is the balance in the wallet correct?  You're changing from missing transactions to being unable to sign.  So one at a time.  Are all the transactions there and the balances matching?  If not please provide a missing one.

**Comment by kyuupichan** [comment]
Ah I missed the comma.  So does more than 1 address match?  Are you aware that addresses that are used need to be expanded in the tree view?

**Comment by edit489** [comment]
We have 4 MPKs that we used to create a wallet in Electrum 2.6. In Electrum 2.6, it works. In Electron Cash (and all Electrum versions 2.7 and later), it doesn't show all addresses that it shows with the same MPKs in Electrum 2.6. All addresses that are shown in Electron Cash are in the Electrum 2.6 version, but not vice versa. Specifically, there are only 5 change addresses shown in Electron Cash but many more shown in Electrum 2.6.

On the bitcoin side of things, we just download Electrum 2.6 and then create a transaction to move all the coins out to a new wallet. For Electron Cash, we haven't been able to find a way to access these coins.

Any idea how to solve this?

**Comment by kyuupichan** [comment]
You probably need to change the derivation path to the same as a single sig path; unfortunately Electrum has had poor backwards compat for wallets.  I was also bitten by this.

**Comment by kyuupichan** [comment]
Unfortunately this doesn't appear to be exposed in the GUI.  I will try to add the feature.  You could probably edit the wallet file manually if you don't encrypt it.

**Comment by kyuupichan** [comment]
Probably fastest for you to change 

https://github.com/fyookball/electrum/blob/master/lib/base_wizard.py#L220

to m/44'/0'/0' as I believe that's what 2.6 used to use.

**Comment by SomberNight** [comment]
@kyuupichan OP didn't mention anything about using a hardware wallet.

@edit489 can you try restoring a watch-only wallet from the four xpubs, and report back if some addresses are still missing?

**Comment by SomberNight** [comment]
@edit489 
Please confirm whether this is gap limit related, by running the following in the in-app console, and then checking the addresses again:
```
wallet.gap_limit_for_change = 200
wallet.change_gap_limit(200)
wallet.synchronize()
```

**Comment by kyuupichan** [comment]
@SomberNight I didn't mention a hardware wallet either ?!?  Electrum changed how it handles multisig between 2.6 and 2.7; that is why there is confusion / loss of funds access.

**Comment by SomberNight** [comment]
@kyuupichan The line you suggested changing only gets to run for hardware wallets.

**Comment by edit489** [comment]
The problem was fixed by changing the change address gap limit! There are two gap limits that need to be changes - the normal one and the change address gap limit.

Thank you all VERY MUCH for the help. This really helped us to access our BCH.

**Comment by kyuupichan** [comment]
@edit489 if the wallet is still in use I suggest plugging the gap

**Comment by SomberNight** [comment]
Note that if you keep using the wallet the gap won't "plug" itself!
see https://github.com/spesmilo/electrum/issues/3859

**Comment by edit489** [comment]
Thanks guys! Much easier to just make a new wallet. Now that we can access the BCH, we can just make a new one and transfer it out to the new wallet.
