### ISSUE TITLE
Entering seed words on Android doesn't allow you to click Next

### ISSUE THREAD

**Issue by jasonbcox** [fyookball/electrum#535]
I tried recovering a wallet from 12 seed words on Android electron-cash version 3.1.3.1, but the Next button is still grayed out after entering them.  I tried adding them via the quick-select buttons for each seed word as well as entering the entirety of the seed words through the keyboard.  Neither worked.

I'm using a Pixel on Android 8.1.0 (Oreo).

**Comment by jasonbcox** [comment]
Update: Examining `adb logcat` reveals no warnings or errors on the seed words input page.  Also, adding additional words beyond 12 still doesn't enable the Next button.

**Comment by jasonbcox** [comment]
I guess I should mention these seed words were generated with the Bitcoin.com wallet, as apparently seed word generation is not the same between wallets.

**Comment by fyookball** [comment]
Bip39 option can be used for other seed types than electrum/electron but this option is not currently available on android.
