### ISSUE TITLE
Trying to install ElectronCash Wallet on ubuntu 16.04 LTS, but it keeps telling me Error

### ISSUE THREAD

**Issue by watertech666** [fyookball/electrum#538]
I download ElectronCash-3.1.2.tar.gz for linux and copy it to my offline computer. It's ubuntu 16.04 LTS. I tried to setup a cold wallet according to  README.rst: 
root@z-ThinkPad-X61:/home/z/Downloads/ElectronCash# ./electron-cash
Error: Could not import PyQt5 on Linux systems, you may try 'sudo apt-get install python3-pyqt5'
root@z-ThinkPad-X61:/home/z/Downloads/ElectronCash# sudo apt-get install python3-pyqt5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3-pyqt5
Also I tried:
root@z-ThinkPad-X61:/home/z/Downloads/ElectronCash# sudo apt-get install python3-setuptools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python3-setuptools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'python3-setuptools' has no installation candidate
root@z-ThinkPad-X61:/home/z/Downloads/ElectronCash#     python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup
ImportError: No module named 'setuptools'

Please help!

**Comment by imaginaryusername** [comment]
Weird, I went to my 16.04LTS Ubuntu server and python3-pyqt5 is there and installed just fine. Try checking for typos, and if problem persists do an ```apt search pyqt5``` to see if there's any unexpected change in package name you're supposed to install.

**Comment by mclstr** [comment]
This seems to be a common problem. Other posts on the Internet, but no resolution that I could find.

It seems that some names/paths don't match what is expected by the app.

**Comment by fyookball** [comment]
sounds like an env issue
