### ISSUE TITLE
Symbol not found: _getentropy on OS X 10.10.5

### ISSUE THREAD

**Issue by goodc0re** [fyookball/electrum#54]
ElectronCash 2.9.2 crashes immediately when opening. 

OS Version:            Mac OS X 10.10.5 (14F2511)

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Dyld Error Message:
  Symbol not found: _getentropy
  Referenced from: /Applications/Electron-Cash.app/Contents/Frameworks/Python.framework/Versions/2.7/Python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by fyookball** [comment]
I am still struggling to build universally running mac binaries.  Can you try running from source to get a traceback?

**Comment by Aragonite** [comment]
Sorry - but MacOX 10.10 was released 3 years ago!   Upgrades are free with MacOS. No reason why not to upgrade.  One of my Mac runs on 10.11 and I bought it in 2006.... 

I don't recommend being compatible with HW that are more than 10 years old...  MacOS 10.11 should be the lowest to be compatible with...

**Comment by goodc0re** [comment]
Understand Aragonite, yet there are always reasons for some people not to update their OS. Other non-free software does require purchasing updates when updating MacOS. (e.g. Parallels Desktop) 
Updates of other software might restrict / break some functionality the user wishes to retain, etc.

**Comment by fyookball** [comment]
@Aragonite do you know what im doing wrong with my builds ?  It seems like not all the python is bundled into the binary and that its wanting to run some python that exists on the system.
