### ISSUE TITLE
Zero Balance

### ISSUE THREAD

**Issue by andysavage** [fyookball/electrum#540]
Hi, I followed advice here https://bitcointalk.org/index.php?topic=2425976.0 - 

> 1. You could just install ElectronCash (https://www.electroncash.org/#download).. then open your "old" Electrum wallet using Electron Cash... it should automatically find all your BCH.

I successfully imported the keys (all previous transactions show) but my BCH balance is zero. Any ideas why? I definitely had a balance of about 0.1 at the fork.
Thanks
![electron](https://user-images.githubusercontent.com/12832713/35875522-7ad10728-0b67-11e8-8838-cf70b72dd01d.png)

**Comment by imaginaryusername** [comment]
The screenshot you posted shows that you paid "faucethub" 0.11 BCH on 2017-10-10, which was way after the fork, and even labeled the transaction! That also happens to be the transaction that drained your account. Are you sure you didn't do that yourself? If not, did you expose your seed to someone who did that?

**Comment by andysavage** [comment]
Thanks a lot for replying.

I was under the impression that after the fork the two were separate, and that and funds sent via electrum wallet were BTC only. I never sent any BCH to anyone, only BTC yet it seems that all the transactions are showing up also in the electron wallet, as if I had been sending BCH as well as BTC. 

I didn't think it was possible for electrum to send BCH transactions? So far I haven't sent anything using electron wallet. I was expecting it to show my BCH balance! It's weird...

**Comment by andysavage** [comment]
Here is the final transaction showing on blockexplorer
https://blockchair.com/bitcoin-cash/transaction/0ebc80352246df72a4ef4582a4d7d116b973bc2353dfab96dcfd52f7d63e64bf

I sent that to faucethub in BTC only, using electrum. I didn't send BCH, and no BCH was received at the faucethub end, as it would have shown in my BCH balance there.

**Comment by andysavage** [comment]
Also when I put my public keys into blockchair I get nothing found... 
https://blockchair.com/search?q=xpub661MyMwAqRbcFt4SfQMpED528TqYkMTWVG7HaqsCeKNR6M8aw6yYRSgvTV3RPBeJZL6okc6g9dwnmLNHu6c3ionMRLddze3h6EiDRC6fV3R

**Comment by fyookball** [comment]
There is strong replay protection, meaning you are correct: transactions sent on BCH do not play on BTC chain and vice-versa.

What I suspect (and what i've seen before in people having a similar question) is that your funds were not in the address you thought they were in the exact time of the fork.  I suggest you try to trace back your funds to the forking block of the split, and you see exactly where they were at the time of the fork and thus where they are in BCH -- perhaps they are in another wallet or address or account you control.

**Comment by andysavage** [comment]
Thanks again for persisting! 
I never had another wallet, all my transactions were in the same electrum wallet. I only emptied it just before getting electron. It always had a balance, at least .01 up till them. Its weird, all the transactions I ever did in electrum are showing up as BCH transaxtions, eventhose before the fork show up.

**Comment by fyookball** [comment]
of course they show up before the fork -- the chain existed before the fork split.

**Comment by imaginaryusername** [comment]
First: All transactions pre-fork will show up as transactions on BCH too, the two chains share their pre-fork history after all.

I don't think blockchair scans your xpub; however I tried importing your xpub on my client and indeed it was drained 10/10/2017. The destination `1GWKN9EEkstAcu7U24eg6THy6RqCPWMYNq` also seems to be not presenton the BTC chain, which means  `0ebc80352246df72a4ef4582a4d7d116b973bc2353dfab96dcfd52f7d63e64bf` _cannot_ be a transaction replay (not that it's possible anyway).

My best guess instead is that you might have downloaded a fraudulent copy of Electrum (not Electron Cash, since if you followed advice of the bitcointalk thread it'll be November, can't drain your account back in time), or somehow exposed your private key, which caused a malicious actor to drain your account in October. Note that the output is _spent_ even to something that's either a faucet or a giant, messy mixer.

**Comment by andysavage** [comment]
imaginaryusername and fyookball thanks for taking the time. I'll give up on it I think. It seems odd that someone would have access to my electrum wallet and then only drain my BCH, leaving the much higher value BTC alone! I mean, if they had my keys they could take both... 

anyway, I may as well move on and leave it as a mystery. But thanks a lot, I appreciate it. 
All the best
andy
