### ISSUE TITLE
p2pool payout tx crashes electron-cash

### ISSUE THREAD

**Issue by jtoomim** [fyookball/electrum#542]
The following transaction appears to cause Electron-Cash to malfunction and crash.

https://www.blocktrail.com/BCC/tx/dac2db8baca1351dbb0b64250a18f69ffefc61e3b3868fb70a8b68528189a426

Version: Electron-Cash 3.1.2 (Windows .exe)
OS: Windows 10 x64

Steps to reproduce: Create a watching-only wallet that includes the address 1FL9Ln6DTcp9HgTUkc6rFaePqGLn5G4d4M. (Note: the new-wallet utility does not appear to support the cashaddr format.) The problem manifests both when the wallet has private keys and when it does not. The problem manifests both when that address is the only one in the wallet and when other addresses are also present, although the results are clearer when other addresses are present.

When syncing, Electron-cash will not get past the dac2db... transaction. Transactions in that wallet that were included in blocks after the dac2db transaction will not show up in the wallet at all. Exact results for the dac2db... transaction may vary from run to run; sometimes that transaction will not appear at all, and sometimes it will show up as an "unknown" transaction.

As long as dac2db... is in the wallet, getaddressbalance("...") will crash for any address in the wallet, even if the address had nothing to do with the dac2db transaction. Double-clicking on transactions other than the dac2db transaction in the History pane will bring up their details as normal, but double-clicking on the "unknown" transaction will cause it to crash. 

![image](https://user-images.githubusercontent.com/11898859/35912915-f3dc0466-0c38-11e8-9153-65647d99bd07.png)

![image](https://user-images.githubusercontent.com/11898859/35913077-8a5021ca-0c39-11e8-8fd9-638ef0acf3f0.png)

**Comment by bonney92** [comment]
#bitcoincash:qq8x267elu926flwktcd4sp3p8ntykwrf5y79fw3gh

**Comment by jtoomim** [comment]
Other versions of Electrum (e.g. BTC, LTC, DASH) do not appear to have any trouble with p2pool transactions. 

My guess at this point in time is that the electron-cash server is having trouble with the OP_RETURN output in the p2pool coinbase transaction, possibly due to the new address-conversion code, and is sending back malformed data to the electron-cash client. When the client tries to display this malformed data, the client tries to create invalid GUI objects which crashes the GUI.

@kyuupichan @fyookball

**Comment by jtoomim** [comment]
This issue is not present in 2.9.4, which handles p2pool transactions properly:

![image](https://user-images.githubusercontent.com/11898859/36057637-95868516-0e4b-11e8-8b1d-393993ad55ed.png)

**Comment by jtoomim** [comment]
Opening a wallet with 2.9.4, then closing 2.9.4, and reopening the wallet with 3.1.2 will prompt you to convert the wallet to the new format. After the conversion, any preexisting p2pool transactions appear correctly in 3.1.2. However, if you double-click on a p2pool transaction in 3.1.2, it will still crash. (Double-cllicking the transaction in 2.9.4 works properly.)

![image](https://user-images.githubusercontent.com/11898859/36057727-3e4b518a-0e4d-11e8-8de2-14b75cd2fab5.png)

**Comment by jtoomim** [comment]
3.0 also works properly.

**Comment by kyuupichan** [comment]
This is fixed in git head
