### ISSUE TITLE
Unable to do a pay-to-many Tx without using change address.

### ISSUE THREAD

**Issue by Flying-Scotzman** [fyookball/electrum#545]
Version: ElectronCash-3.1.2.exe on Windows 10.
and also happened on Ubuntu 16.04.3.
This bug does not happen on electrum 3.0.6.

So I went to send one input to two addresses, but it creates a 3rd output for the change address even though it's 0. And if I untick "use change address" it still does it with the main recieving address.

So I can't broadcast the tx because it is dust. and had to do a separate tx for each address.
forgive me if i'm a newb and making a mistake. Anyway, keep up the great work. Electron Cash is an awesome wallet.

The 0.001 is the only available input and the entire balance of the wallet.

![txpreview](https://user-images.githubusercontent.com/36317028/36057059-d7995748-0e01-11e8-9803-892dc91d88b2.png)

![txcreate](https://user-images.githubusercontent.com/36317028/36057065-e78cebc4-0e01-11e8-9cd8-e422c91ccc78.png)

**Comment by kyuupichan** [comment]
Also fixed in git head
