### ISSUE TITLE
electron-cash history is not creating proper JSON

### ISSUE THREAD

**Issue by anth-ny** [fyookball/electrum#547]
Using single quotes (') instead of double quotes ("); presenting addresses as <Address 1Mz7153HMuxXTuR2R1t78mGSdzaAtNbBWX>

Version 3.1.2 in Docker with https://github.com/anth-ny/electroncash-docker

**Comment by anth-ny** [comment]
Will check if https://github.com/fyookball/electrum/commit/99ed623d140868d09bb325fcb247f79248cdfa0c or some other recent commit addresses this.

**Comment by kyuupichan** [comment]
Fixed in git head by https://github.com/fyookball/electrum/commit/99ed623d140868d09bb325fcb247f79248cdfa0c
