### ISSUE TITLE
electron-cash listaddresses is not returning valid JSON

### ISSUE THREAD

**Issue by anth-ny** [fyookball/electrum#548]
Returning [<Address 1Mz7153HMuxXTuR2R1t78mGSdzaAtNbBWX>] instead of ["1Mz7153HMuxXTuR2R1t78mGSdzaAtNbBWX"]

Version 3.1.2 being run from Docker with https://github.com/anth-ny/electroncash-docker

**Comment by anth-ny** [comment]
I will check if https://github.com/fyookball/electrum/commit/99ed623d140868d09bb325fcb247f79248cdfa0c addresses this.

**Comment by kyuupichan** [comment]
Fixed in git head.
