### ISSUE TITLE
Invaldi OTP when trying to send transaction

### ISSUE THREAD

**Issue by mrcaptain101** [fyookball/electrum#55]
Hello,

I have been trying to send my BCC to exchange and whenever i do at the end when verifying transaction it says to me invalid otp all though it can't be invalid. Check screenshot below:
http://prntscr.com/g47ddk

Whats the solution to this?

**Comment by fyookball** [comment]
try with 2.9.2

**Comment by mrcaptain101** [comment]
Hello,
it is still saying the same look:
http://prntscr.com/g4da9j

What can i do

**Comment by fyookball** [comment]
you are using f2a.  we dont support 2fa.  Please see here: https://github.com/fyookball/electrum/issues/41
