### ISSUE TITLE
помогите ElectronCash-3.1.2 не синхронизируется 

### ISSUE THREAD

**Issue by artursirekanyan** [fyookball/electrum#555]
уже почти неделю стоит кошелек ElectronCash-3.1.2 , а синхронизация не проходит 
кто сталкивался ? как решить проблему?

**Comment by esclavots** [comment]
Самый простой способ решить эту проблему - использовать фактический биткойн, а не этот поддельный кошелек.

**Comment by danuker** [comment]
@esclavots: What if bitcoin is the fake one, because they overcomplicate with SegWit? More complexity = more attack surface.

**Comment by fyookball** [comment]
@artursirekanyan 

If it does not sync, try deleting "blockchain_headers" and "recent_servers" files from local directory and try again.
