### ISSUE TITLE
Pay-to-many try to use change address when there is no change: dust refused by network

### ISSUE THREAD

**Issue by nirgal** [fyookball/electrum#561]
Hi

While migrating my "imported key" wallet to a regular seed wallet, I tried to pay a transaction and use all the remaining cash to an address in my other wallet.

Something like:

Balance 2 BCH

Pay-to-many:
address1: 1.00 BCH
address2: 0.99 BCH
fees: 0.01 BCH

However, the transaction generated by electrum rather looked like:
address1: 1.00 BCH
address2: 0.99 BCH
change: 0.00 BCH
fees: 0.01 BCH

The change address with 0.0 BCH get the transaction refused after clicking on broadcast with error message "dust".

You can reproduce the behaviour by click pay-to-many, fill 2 external addresses there with all your balance, and click "preview". Note that you might need to set up fees manually. You'll see electrum is trying to send 0.0 BCH to change.

I expected electrum to skip the change address when there is no change left.

**Comment by imaginaryusername** [comment]
I believe this was fixed in #545

**Comment by nirgal** [comment]
Ops, sorry for the noise. Thanks.
