### ISSUE TITLE
Android: Sweep paper wallets

### ISSUE THREAD

**Issue by imaginaryusername** [fyookball/electrum#563]
Is it possible to add a "sweep paper wallets" to electron-cash android? Currently Copay's sweep doesn't work, so Bitcoin.com is the only open wallet that can sweep privkeys. Bitcoin.com also doesn't let you set your own fees while sweeping, which makes it end up using a 0.0001 fee every time - a tragedy. Will be super nice to have this in Electron-cash Android, and I'll tip whoever ends up implementing this.

**Comment by fyookball** [comment]
Android functionality is limited.  We are currently working on a next generation wallet for android.
