### ISSUE TITLE
I can not transfer money from the Electron Cash purse

### ISSUE THREAD

**Issue by bsvrus** [fyookball/electrum#565]
I went to the password in my purse Electron cash portable (I have the amount there after the splitting of the cue balloons) and I want to transfer money (drove the address, amount, commission) I press and send the password as well as the input to the purse itself, but the password-message incorrect password . For the same password in the wallet came in, and I can not send money, what's going on?

**Comment by fyookball** [comment]
this was fixed and will be ready in next release. meanwhile can you generate new wallet with same seed and no pwd
