### ISSUE TITLE
I can use my password to login, but not to send bch

### ISSUE THREAD

**Issue by BruinsM** [fyookball/electrum#570]
So, I imported my privatekeys and set-up electroncash. At first my password worked and I could send money to an exchange, it arrived. Everything looked fine.
But now, I can still login with that same password, but if I try to send money somewhere it says "incorrect password". Anybody knows how to solve this?

**Comment by fyookball** [comment]
will be fixed in next release, coming in 1-2 days.  if you need to send funds before then you can create new wallet from the seed

**Comment by BruinsM** [comment]
Thanks!

**Comment by Siverc** [comment]
Also I have the same problem with the wallet generated with private keys, when I have to send bch on another wallet or any operation I do that asks me the password has always given me "incorrected password" even with version 3.1.5.
I would like to send the BCHs to another wallet generated with the seed, but they are blocked

**Comment by marceloneil** [comment]
@Siverc you need to reimport the private keys in version 3.1.5 - let me know if that works

**Comment by Siverc** [comment]
Thanks marceloneil, I'll try it, I `ll let you know

**Comment by Siverc** [comment]
Hi,
I solved the problem, I deleted the old version 3.1.2 wallet and created a new one (3.1.5) with the same name and inserting the private key in "Import Bitcoin Cash addresses or private keys" so I managed to send the BCH in the other wallet.
Thanks for all

**Comment by marceloneil** [comment]
Great!
