### ISSUE TITLE
Input from multi-sig address crashes wallet

### ISSUE THREAD

**Issue by Warlock314** [fyookball/electrum#572]
I sent some BCH to a multi-signature address, then back to Electron wallet, causing endless synch problem. So I took private key from that address, created a tx to send funds to another address in the wallet hoping to fix the problem. Now the whole wallet is just messed up. I can recover all my funds using the private keys , but it would be better to fix the bug. Here is the tx that started it all: https://blockchair.com/bitcoin-cash/transaction/247838388#o=0

**Comment by imaginaryusername** [comment]
I have received funds from multisig wallets (that I also have control of) before with zero problems. You gotta describe in more details what you actually mean by "endless sync problems" (which version/platform of Electron Cash did you use?) and "just messed up".

**Comment by Warlock314** [comment]
I am using Electron Cash 3.1.2 and I get a "synchronizing..." message in the lower left corner. It gives a "+0.00" for the Amount and "unknown" for the balance. I created a 2 of 2 multisig address using the public key from 2 of the addresses in the wallet. I used the key of those 2 addresses to sign the redeem transaction.

I have never had this issue before, but I did something different in using private/public key pairs from the wallet to create and redeem the multisig address. 

Here is a picture of my wallet with the error: https://imgur.com/a/Dmnlm

**Comment by imaginaryusername** [comment]
Sounds like the problem lies in that the wallet you created is not a multisig wallet, hence it is confused about the P2SH multisig that you created using the keys from it. Will have to wait for @fyookball to dig deeper into how the code works, but my guess is that this use is out of spec and might not need an urgent fix.

**Comment by Warlock314** [comment]
This issue disappeared with version 3.1.6 (wallet works fine now).
