### ISSUE TITLE
Setting Coinchooser to "Privacy" may not be always a good thing

### ISSUE THREAD

**Issue by MohamedKiouaz** [fyookball/electrum#574]
The coinchooser used by Electron Cash takes every single coin from an address and use it as input for the transaction. You cannot make a transaction using only half of the inputs. This is a problem for addresses with > 50 inputs.

[Here ](https://imgur.com/a/2UPfr) is for example what may happen. I did ask for a 25 bits transaction but Electron decided to use 14 unnecessary outputs "for my privacy" moving them to another address even if I didn't ask for it (and I didn't want it in the first place).

[A mainnet case](https://explorer.bitcoin.com/bch/tx/dd8f9d904db660142b2306846e87fef060aec59a170342bcbaef825423ed375a). The goal of the transaction was to send 0.00344600 bch. There is here 17 unnecessary inputs here.

[Unchecking "use change address" does not change the behaviour](https://imgur.com/a/JgyCx), Electron just consolidate everything without my permission.

**Comment by marceloneil** [comment]
You can use the "Coins" tab to be more specific in which inputs you want to use

**Comment by MohamedKiouaz** [comment]
I am not sure the end user is supposed to choose the right outputs between dozens.

For the mainnet case, if he had to choose what coin to spend, he would have spent a lot of time selecting them (probably 60 of them), calculating sum of 0.00015 + 0.00025 + 0.00008 + ... to be equal to the amount he wants to send.

There was a priority feature in electrum, why was it deleted ?

**Comment by kyuupichan** [comment]
You should ask Electrum why it was removed there.  I don't see the problem in the current behaviour; if you don't like it you can select the coin(s) to use yourself.

**Comment by fyookball** [comment]
@kyuupichan i thought you removed priority?

**Comment by kyuupichan** [comment]
I did after it was removed upstream

**Comment by MohamedKiouaz** [comment]
So, I tried to reproduce this on Electrum 3.0.6. 

I used a wallet to create [several coins of 1mBTC using the same address](https://imgur.com/a/DHrti). Then I tried [to send 1.5 mBTC](https://imgur.com/a/ciDmA).

Electrum just selected 2 inputs of 1 mBTC to create a 1.5 mBTC output. It seems logic and I didn't select the coins to spend. It didn't select every single coin from the address like Electron.

This is the expected behaviour in my opinion for someone not looking for privacy or managing a lot of outputs. It works like this because in the option [there is this](https://imgur.com/a/W8E5M).

The "Coin Selection" menu have been here for a while in Electrum (before the fork) and have been deleted from Electron. Maybe the dev just thought "Bitcoin cash has cheap transaction fees, there is no need to use the minimal set of inputs, let's go all in on privacy".

Thanks for the replies guys.

**Comment by marceloneil** [comment]
This is in the [release notes](https://github.com/spesmilo/electrum/blob/360dd5a7aae1fb6da5c83208d5fdd0df11dc7f53/RELEASE-NOTES#L39) for the new version of electrum. Not sure if its useful or not for this conversation.
```
 * The 'privacy' and 'priority' coin selection policies have been
   merged into one. Previously, the 'privacy' policy has been unusable
   because it was was not prioritizing confirmed coins. The new policy
   is similar to 'privacy', except that it de-prioritizes addresses
   that have unconfirmed coins.
```

**Comment by MohamedKiouaz** [comment]
I just tried it. It takes all the outputs from a transaction even if when only one output would be needed. It enhance privacy but it will cost a higher transaction size. Bitcoin Cash can afford this with 1 sat/B fees but I am not sure that Bitcoin can with its filled mempool.

Thanks guys. I think we can close this issue.
