### ISSUE TITLE
bip39 with 24 words

### ISSUE THREAD

**Issue by mpapec** [fyookball/electrum#575]
Is it possible to recover wallet from 24 word seed? I've tried

nature woman insane card rural basket skull innocent select cute song panther rent obey engine myself license vast illness route fringe harbor outside derive

from https://bip39tool.ioncore.xyz/ but it stops with "Seed or key not recognized" error.

**Comment by marceloneil** [comment]
Ok great, I was unsure if I should edit your comment or not *whew*

**Comment by marceloneil** [comment]
It should work fine, make sure you check "BIP39 seed" under"options" in the "I already have a seed" dialog

**Comment by mpapec** [comment]
```
 ./electron-cash restore ?
Enter argument:nature woman insane card rural basket skull innocent select cute song panther rent obey engine myself license vast illness route fringe harbor outside derive
Error: Seed or key not recognized
```

Is it possible that seed dictionaries dont have same words, and thus the error?

**Comment by marceloneil** [comment]
Oh you are using the command-line tool

**Comment by mpapec** [comment]
yes, ```./electron-cash version
3.1.2```

**Comment by marceloneil** [comment]
You can import directly using the gui, but not with the command-line it seems. The website you linked seems to work fine for me though.

**Comment by mpapec** [comment]
Yes, it does import when using GUI, but still not sure why generated addresses differ,

https://bip39tool.ioncore.xyz/ =>
```
1Lg6bew2WprxLak9KHPLKFPMpKkXSaavx7 |  
-- | --
  | 14nMHjU8C7Z5h9VYq7qA6xCcQgePX54DEn |  
  | 1Ms1zHzc9TXeczNjXjsakLGEYii5A1vQgL |  
  | 1Lu3USRFTCh2TA71pZoiYtTen3fijfySBt |  
  | 14WGcaV1CUPgVpnMYfJuft8cnGmM7Dav4v |  
  | 1ERm5kCpwvjEFcWeKuWQChDrQZ9gxbMoVp |  
  | 1MJZA59ykWz13cnQkjJuZ1rvn7Pq7bErbB |  
  | 1Nw3FBnxWjsYN8MuARZThyxdpyvDW9i2yk |  
  | 145H5Y6vFRGKF5SQvHxtReFjeUYMnko62w |  
  | 1q9bf8YCaYCHfXnZMoGFbcaaBX3p9rpzW |  
  | 1LHNXhNs6A8pvfw2mjkcLupGpimZQFjg5S |  
  | 1EKyMcC7i261m1YC23o6gtcAgVWwyeKk3i |  
  | 1EGguPugUTUSpbjF6NSFy4s1nkFYhRRkMQ |  
  | 1A156UW2gjwKzd6GuWdXY2ip9PC6P395J8 |  
  | 1q2UbZYSfZicNLzfdAM9Sj3eenmdBsged |  
  | 12Gc6aqsddjfXYMisFxFxMxhRKNXEz1Usi |  
  | 13mdg89f3g5owycf2bNkjXnn8nKtUhP8Mv |  
  | 14ykeyBGNtnVYiDSDsi1GMazffSRZtCphR |  
  | 1PtiDEUkmNPTp4rHcVVeE4uUzkDS9jri8f |  
  | 1CjhVFkFvkFZcAfCrVZ1DrxuGD6GNeXc8v

```
![image](https://user-images.githubusercontent.com/3878347/36658250-f8ee2600-1acf-11e8-941b-0c3a09ae4784.png)

**Comment by jonasbkarlsson** [comment]
The tool https://bip39tool.ioncore.xyz/  does not support Bitcoin Cash, use https://iancoleman.io/bip39/ instead. It gives the same receiving addresses as Electron Cash.

**Comment by mpapec** [comment]
Tnx!

**Comment by marceloneil** [comment]
Yeah, different derivation path
