### ISSUE TITLE
My History appears in white and I do not know why.

### ISSUE THREAD

**Issue by PatataXXL** [fyookball/electrum#576]
My History appears blank as if I had no any funds in my  wallet. But I have transferred money from mi wallet of hitbtc. In the blockchain apears the transaction as you can see.
[https://blockchain.info/address/1K5XHCn2apMDj9qRLbcUAYKyduMPmQ8Ck6](url)
![captura de pantalla 2](https://user-images.githubusercontent.com/36887587/36730159-b947231a-1bc6-11e8-82d4-2338ab0dc03e.png)

I apologize for my english.

**Comment by marceloneil** [comment]
The link shows a bitcoin transaction, not a bitcoin cash transaction
