### ISSUE TITLE
Email Plugin throws error upon Initialization

### ISSUE THREAD

**Issue by Devar** [fyookball/electrum#578]
This is the trace from an error that happens upon the initialization of the email plugin.

![image](https://user-images.githubusercontent.com/453912/36825990-93a2b270-1d45-11e8-8d26-d7a62ad97a3e.png)

**Comment by marceloneil** [comment]
I'm assuming that you're using the email plugin?

**Comment by Devar** [comment]
Yes, as well as Labelsync.
