### ISSUE TITLE
ImportError: No module named setuptools

### ISSUE THREAD

**Issue by markallisongit** [fyookball/electrum#58]
I am trying to install on lubuntu 16.04. I downloaded the Linux source and extracted. If I run command

`sudo python setup.py install`

I get 

```
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup
ImportError: No module named setuptools
```

**Comment by fyookball** [comment]
can you try installing the module "setuptools" with pip or sudo get-apt install
