### ISSUE TITLE
How to verify the signature?

### ISSUE THREAD

**Issue by EsoEng** [fyookball/electrum#580]
I've Googled for a solution but found none that work. Please could you give me a step-by-step guide to verifying the authenticity/signature of the ElectonCash wallet for Windows?

**Comment by fyookball** [comment]
we can write up a guide.  google gpg

**Comment by EsoEng** [comment]
Thanks, that would be welcome. However, could you please give me just a few steps now so I can get my BCH off an exchange?

I tried entering this code into Powershell: "CertUtil -hashfile ElectronCash-3.1.5.exe SHA1"

The signature I was then able to see in Powershell did not match the one in the Github file for 3.1.5. So, either I'm doing something wrong or the signatures do not match because the ElectronCash exe I downloaded is not authentic (which is unlikely, I'm sure). (I used the text file as I was unable to get the .sig file to do anything, even with Kleopatra.)

Please could you advise?

**Comment by fyookball** [comment]
hash sum is not a sig, those are 2 different things.

easiest for you is verify hash checksum -- its is sha256 not sha1.  Try using 7zip tool , which has free sha256 checker.
