### ISSUE TITLE
BCH Address Translator Label issue

### ISSUE THREAD

**Issue by kwheelz** [fyookball/electrum#582]
Address translator in Electron-Cash has payment protocol and BitPay format listed. BitPay format does not work to send to BitPay wallet, but Payment Protocol format does.

**Comment by fyookball** [comment]
maybe bitpay stopped using proprietary format

**Comment by pieterpoorthuis** [comment]
BitPay is using the Cashaddr format.
For more info see https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests

**Comment by kyuupichan** [comment]
It's called the BitPay format because they invented it.

**Comment by fyookball** [comment]
@kyuupichan should we retire the bitpay format then?

**Comment by kyuupichan** [comment]
What's the rush? Give it at least 3 months more. The might be people with old wallets on their mobiles or tablets
