### ISSUE TITLE
pyqt5

### ISSUE THREAD

**Issue by Kulseng** [fyookball/electrum#584]
when i try to install electron on raspian stretch it tells me i do not have pyqt5, but i have installed it.

**Comment by marceloneil** [comment]
Are you sure that you have installed `python3-pyqt5` and not `python-pyqt5`

**Comment by Kulseng** [comment]
i used the command sudo apt-get install python3-pyqt5. so im pretty sure i did install it for python 3 but i will double check when i get home.

**Comment by eriksank** [comment]
`qt5` may be needed but the `pyqt5` symbol does not seem to exist in the context in which the installer uses it . I only saw one way of getting the installation to complete, which is, removing the entry in `setup.py` in the `setup(...)` function call, from the `install_requires` array around line 40:

```
setup(
    name="Electron Cash",
    version=version.PACKAGE_VERSION,
    install_requires=[
        'pyaes>=0.1a1',
        'ecdsa>=0.9',
        'pbkdf2',
        'requests',
        'qrcode',
        'protobuf',
        'dnspython',
        'jsonrpclib-pelix',
        'PySocks>=1.6.6',
    ],
```

There seems to be some problem with the `pyqt5` symbol itself. There is some part of the environment that omits to define it after installing the debian-level `python3-pyqt5` package. This does not look like something an end user would have to hunt down ...
