### ISSUE TITLE
Add checksums for files on GitHub

### ISSUE THREAD

**Issue by einsteinsfool** [fyookball/electrum#585]
There should be checksums for every file in the Releases section on GitHub so users can verify the files they download as in the motton on the main page of Electron Cash:

> Please, please, PLEASE... take the time to verify
the authenticity of these files before running them.
This protects you from hackers and malware!

I know there are signatures and checksums for files from the Download page of the website but the packages on the website and on GitHub differ as you can see in this issue: #579.

As suggested by **yura-pakhuchiy** (in the mentioned issue), it would be most convenient if checksums/sigs were available in the Releases page on GitHub rather than somewhere in the repository.

**Comment by marceloneil** [comment]
I think @yura-pakhuchiy was referring to [https://electroncash.org]([https://electroncash.org), but it still applies to the releases page.
