### ISSUE TITLE
Error: OSX "Cannot load wallet: Unknown wallet type: 2fa"

### ISSUE THREAD

**Issue by jsmith-dev** [fyookball/electrum#586]
![electrum](https://user-images.githubusercontent.com/10548240/36999128-065252b8-2074-11e8-8c7c-a087231f3c9a.jpeg)

**Comment by marceloneil** [comment]
Look at #41

**Comment by jsmith-dev** [comment]
Possible to paste the solve here? (That's a long thread)

**Comment by marceloneil** [comment]
Unfortunately there is no solve. 2FA isn't supported for bitcoin cash, and likely will not be for the near future.

However, there *is* a way to recover your funds, a tutorial can be found here: https://github.com/fyookball/electrum/issues/41#issuecomment-357468208

**Comment by jsmith-dev** [comment]
Doesn’t apply to me. No funds to recover. This is a first-time install
issue.

OSX has an Electrum Wallet.

Installing Electrum-cash first time and it bauks.

Can machine have both Electrum && Electrum-cash or are they attempting to
access the same local persistent storage?

Julian Smith.

**Comment by marceloneil** [comment]
They should not use any of the same storage. Are you sure you haven't used electron-cash on that system before? Is there anything under `~/.electron-cash/wallets`?

**Comment by jsmith-dev** [comment]
Will email you direct. Thx.

**Comment by jsmith-dev** [comment]
~/.electron-cash/wallets - was populated. Issue closed. Solution.. Make ~/.electron-cash/wallets empty.
