### ISSUE TITLE
TypeError: 'str' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by ProfessorVenkman** [fyookball/electrum#589]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/home/marcel/workspace/electrum/gui/qt/main_window.py", line 2136, in <lambda>
    b.clicked.connect(lambda: self.do_encrypt(message_e, pubkey_e, encrypted_e))
  File "/home/marcel/workspace/electrum/gui/qt/main_window.py", line 2099, in do_encrypt
    hex('error')

TypeError: 'str' object cannot be interpreted as an integer
```

Reporter
------------

This issue was reported by 1 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.1.5  | Linux-4.15.7-1-ARCH-x86_64-with-arch-Arch-Linux | standard | en_US |

Additional Information
------------------------

> Test Description @marceloneil

---

**Comment by marceloneil** [comment]
It works!
