### ISSUE TITLE
did not received my coins

### ISSUE THREAD

**Issue by sofiane11** [fyookball/electrum#59]
i transfered coins to my wallet and they never show on wallet
Have all teh confirmations
18ZFmqBxbzyfJFNsYXeQFYRAtTGRhFjiBX

**Comment by fyookball** [comment]
currently they are only on bitcoin chain not bitcon cash
https://blockchair.com/search?q=18ZFmqBxbzyfJFNsYXeQFYRAtTGRhFjiBX

**Comment by sofiane11** [comment]
Sorry for the stupid question. But How can I pit them back on my bitcoin wallet then? Or will they apear later on my bitcoin cash wallet?

**Comment by fyookball** [comment]
use a bitcoin wallet like Electrum to see them on that chain.  If you tranferered them from some other address that you owned and you did this after the fork, look at that other address, you may have coins on both chains.  www.blockchair.info
