### ISSUE TITLE
HTTP://www.electroncash.org/ does not redirect to HTTPS version

### ISSUE THREAD

**Issue by veox** [fyookball/electrum#60]
The downloads are then done without encryption.

-----

OT: There's a typo in the footer ("Soure"), and can't find the website sources.

**Comment by fyookball** [comment]
i was going to move this to a new host at some point. im not even sure how its doing https. i didnt buy an SSL cert.  why is this important? possible mitm?

**Comment by fyookball** [comment]
all links are https
