### ISSUE TITLE
"Phrase"

### ISSUE THREAD

**Issue by towncryr** [fyookball/electrum#600]
I had my wallet on a hard drive that has been replaced as it 'almost' crashed.  

I am attempting to, on the new drive w/old info, attempt to enter my 'seed' words.  The wallet calls it a 'phrase'.  I do have the seed words but am unable to enter them in ANY configuration, number w/periods, separated by comma, separated by semi-colons, just all written out together.  

NO way I've tried to re-enter the seed words has shown my the 'next' button highlighted.

They give 'no' instructions on HOW to enter these seed words to re-open my wallet and access the BCH therein.

Any suggestions PLEASE?

Roger

**Comment by marceloneil** [comment]
The seed words should be space seperated. Do you know if it is a BIP39 seed?

**Comment by towncryr** [comment]
I set it up several months ago and the HD crashed. I have no idea if or what a BIP39 seed is. I have 12 words, as they were given, is all I know.. 

Let me try spacing them. The reason I did not try that before was some reply said 'no whit space' or something to that effect. 

Let me try 

R 

Seems to have opened it!!!!!!!!!!!!! 

Thank YOU so MUCH!! 

R

**Comment by towncryr** [comment]
U da MAN!! ;-))
