### ISSUE TITLE
The nickname for µBCH is "bits"

### ISSUE THREAD

**Issue by patrikr** [fyookball/electrum#605]
Inventing your own terms will just cause confusion for no good reason, but if you insist on doing this, you need to at least give your users a configuration option where we can choose between the industry standard name and your kooky invention.

**Comment by Devar** [comment]
This is not their own invention but an implementation of BUIP087.

I agree however that I would prefer to have it customizable so that I can call it what I want (as I also prefer µBCH/bits).

**Comment by fyookball** [comment]
>you need to at least give your users a configuration option

I'll consider it.
