### ISSUE TITLE
HELP ALL MY BCC JUST DISAPPEARED FROM MY ELECTRON CASH WALLET!!! 

### ISSUE THREAD

**Issue by luck777sam** [fyookball/electrum#61]
ALL MY BCC JUST DISAPPEARED FROM MY ELECTRON CASH WALLET!!! hi every one, need some help or explanation, because I use electron cash to get my BCC, I follow the instructions of electrum.org I send my BTC from my electrum wallet to a new BTC electrum wallet I wait to the transaccion be completed, so I use my old seed now empty of bitcoins for export to the electron cash, and my BCC appears to my new BCC wallet, so I make two small transfers  of my BCC wallet to bittrex and the transaction was ok,  from here everything ok, when I do the transaction my electron cash BCC wallet start to syncronize and  ALL  THE REST OF MY BCC (ALMOST 90%)  OF MY ELECTRON WALLET JUST DESAPPEARED, AND THE BCC WALLET SHOW ME THE LAST TRANSACTION OF BTC BUT NOTHING ABOUT BCC ALSO MY TWO SMALL TRANSACCIONS OF BCC DISAPPEARED FROM HISTORY ¡¡¡¡¡AND NOW MY BCC WALLET IS EMPTY!!!!!!! WHATS HAPPEN SOUNDS LIKE SOME INTERFERENCE OF THE TWO BLOCKCHAINS some one can helpme pls, thanks : (

**Comment by k2xl** [comment]
Mine too1@!@#!#@!@# PLEASE HELP

**Comment by fyookball** [comment]
sounds like you're on the wrong chain?  Try manually selecting a BCC server like cashcaria

**Comment by k2xl** [comment]
How to do that?

**Comment by fyookball** [comment]
click the green circle on the bottom right to bring up the servers

**Comment by fyookball** [comment]
are you using 2.9.0 or 2.9.2 ?

**Comment by luck777sam** [comment]
2.9.2

**Comment by fyookball** [comment]
did that fix?

**Comment by luck777sam** [comment]
how I have to write cashcaria

**Comment by luck777sam** [comment]
cashcaria.net?

**Comment by luck777sam** [comment]
ok ist working thanks allot
I lose allot of time man searching thousand thanks : )

**Comment by fyookball** [comment]
@luck777sam question: had you previously downloaded 2.9.0 before this?

**Comment by luck777sam** [comment]
yes I download the 2.9.0 first and I update to 2.9.2 this morning

**Comment by fyookball** [comment]
@luck777sam then you had the old header file, that is why you got this.  2.9.2 fixes this.
