### ISSUE TITLE
Received transaction is "Not Verified" on Android

### ISSUE THREAD

**Issue by jonas-lundqvist** [fyookball/electrum#619]
I just installed Electron Cash on my Linux desktop, created a new wallet and transfered a small amount to it.

The transaction was quickly received and while waiting for the first confirmation I installed the Android version from Google Play and restored the wallet from the seed I got from the newly created wallet from my desktop. The transaction shows up after the wallet is synched but it is still labeled "Not Verified" even though it has been confirmed for many (>> 10) blocks.

It is confirmed according to the desktop client.

Device: LG Nexus 5X
Android : 8.1 (stock)
Version of Electron Cash: 3.1.3

**Comment by jonas-lundqvist** [comment]
Hmm. After I fiddled with the network settings some more it seems to be confirmed now.
I tried some different servers and waited...

**Comment by marceloneil** [comment]
Glad you got it working!

For the future, "Not Verified" does not mean "Unconfirmed". "Not Verified" means the transaction hasn't been verified locally with the block headers, which in some cases take a while to sync - especially on a new installation of Electron Cash.

If the "block height" under "network settings" is old and doesn't seem to be increasing, restarting the wallet or manually selecting a new server will likely do the trick.
