### ISSUE TITLE
All my BTC is gone

### ISSUE THREAD

**Issue by k2xl** [fyookball/electrum#62]
Fyookball,

Can you please send me a message. All my BTC were transferred this morning from my electrum wallet to someone else. I had installed electrumcash.org yesterday.

Can you help me figure out what happened and if I accidentally downloaded a malware version? Please let me know how we can chat. I think i just lost a ton of coins and I'm panicing.

**Comment by fyookball** [comment]
i am currently on irc as jon_f  
i will try to help you

**Comment by k2xl** [comment]
Which irc? freenode?

**Comment by fyookball** [comment]
to know if your copy is correct, run a sha1sum and compare to the published checksum
https://github.com/fyookball/keys-n-hashes

Yes freenode

**Comment by k2xl** [comment]
which channel?

**Comment by fyookball** [comment]
after chatting with k2xl, it appears their BTC was hacked since they could not recognize tx.
