### ISSUE TITLE
custom change addresses

### ISSUE THREAD

**Issue by cypherdoc** [fyookball/electrum#620]
when we construct a multi input tx that results in change, please allow us to specify a particular change address destination.  just saying, Armory allows this.

**Comment by SomberNight** [comment]
You can already use pay-to-many to specify all the outputs.
In the `Pay to` field:
```
address,amount
address,amount
...
```
Setting `amount` to `!` means sending the max amount you can. You can combine this with using the `Coins` tab, where you can select the inputs of the txn, so `!` will only spend the rest of the selected inputs (not all the inputs the wallet contains); and this results in exactly what you are asking for.

**Comment by cypherdoc** [comment]
wow, tricky but workable solution.  thanks!

**Comment by rt121212121** [comment]
As there's a way to do this, and no design for a different way nor a volunteer who would implement that design, I'm going to close this as solved via the "tricky but workable solution."
