### ISSUE TITLE
Exception: Invalid sequence

### ISSUE THREAD

**Issue by lucryptive** [fyookball/electrum#627]
3.1.6. portable with ledger nano s. When launching or attempting to send BCH I recieve an Exception: Invalid sequence error.

**Comment by jnchw** [comment]
I'm having the same issue, also on 3.1.6 both portable and standard

**Comment by marceloneil** [comment]
Should be fixed in f42ecb246c805bc4fd14fc531da598163d139d4c, can any of you guys try running this from source?

**Comment by lucryptive** [comment]
Fixed in 3.2 but I am getting errors when sending BCH. I made a new issue for it.
