### ISSUE TITLE
Cannot send BCH from ElectronCash using Trezor: 'TxInputType' object has no attribute 'amount'

### ISSUE THREAD

**Issue by spottedmarley** [fyookball/electrum#63]
Ok, so I had no problems at all creating a new wallet on my Trezor using ElectronCash. I claimed my Trezor BCH directly to my ElectronCash wallet. No problems so far.

Now I would like to send my BCH out to exchange. I start ElectronCash and register my Trezor, no problem, balance is correct. Last TX has 22 confirmations. All looks good.

When I create a send TX I cannot send or sign the TX. I get the following error dialog popup:

'TxInputType' object has no attribute 'amount'

I am definitely filling out the amount and fee correctly. Everything is properly filled out.

Has anybody else had issues sending BCH from EC on Trezor?

SM

**Comment by fyookball** [comment]
are you on latest 2.9.2 version?

**Comment by anduck** [comment]
Fails with latest 2.9.2 and latest "cash" branch too.

**Comment by spottedmarley** [comment]
Yes, I'm using 2.9.2.. in 2.9.0 the send would fail with this different error:

sign_tx() got an unexpected keyword argument 'locktime'

**Comment by fyookball** [comment]
is there some locktime thing you're doing?

**Comment by anduck** [comment]
No, it just doesn't work.

**Comment by fyookball** [comment]
@jhoenicke  any idea?

**Comment by molecular** [comment]
@anduck or @spottedmarley, can you run with "-v" flag and post the output?

**Comment by fyookball** [comment]
from kyuupi: 

You need to remove the locktime= from the trezor plugin
 electrum keeps adding it back and breaking stuff

**Comment by anduck** [comment]
Removed locktime=, can sign now -- but it won't return to Electrum as signed.

**Comment by anduck** [comment]
sign_tx() got an unexpected keyword argument 'locktime'  when using 2.9.2.

**Comment by anduck** [comment]
'TxInputType' object has no attribute 'amount'  when using master/cash.

**Comment by spottedmarley** [comment]
@molecular Here is the output when I attempt to sign:

`[profiler] estimated_size 0.0004
[DeviceMgr] getting client for keystore
[DeviceMgr] scanning devices...
[DeviceMgr] end client for keystore
Traceback (most recent call last):
  File "/home/spot/Electron Cash-2.9.2/gui/qt/util.py", line 582, in run
    result = task.task()
  File "/home/spot/Electron Cash-2.9.2/lib/wallet.py", line 1103, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/spot/Electron Cash-2.9.2/plugins/trezor/plugin.py", line 66, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/home/spot/Electron Cash-2.9.2/plugins/trezor/plugin.py", line 240, in sign_transaction
    inputs = self.tx_inputs(tx, True)
  File "/home/spot/Electron Cash-2.9.2/plugins/trezor/plugin.py", line 307, in tx_inputs
    txinputtype.amount = txin['value']
AttributeError: 'TxInputType' object has no attribute 'amount'`

**Comment by anduck** [comment]
@molecular had the solution! Python-trezor needed updating to master branch. Clone master and setup.py install.

**Comment by spottedmarley** [comment]
Yes! Thank you @molecular and @anduck !

Cloned python-trezor master and installed, also had to update cython3 but I just got my send tx signed and broadcast. Now I just have to wait a few days to get a few BCH confirmations hah.

**Comment by fyookball** [comment]
reopening because we should remove this locktime thing

**Comment by molecular** [comment]
since the original issue was not about the locktime, but about trezorlib being old, I made a new issue #85 for the locktime thing.

So this can be closed to reduce confusion.

**Comment by molecular** [comment]
@spottedmarley can you still reproduce the locktime thing with updated python-trezor at all?

    sign_tx() got an unexpected keyword argument 'locktime'

I made an issue for that: #85, could you be so kind to see if this still occurs and post your results to #85

**Comment by jhoenicke** [comment]
Both problems are caused by an older python-trezor version.  `locktime` and  `amount` were added recently. And amount is absolutely necessary for BIP-143 signatures.

**Comment by molecular** [comment]
@jhoenicke yes, thanks for the input. 

All of #63, #81 and #85 are really "python-trezor < v0.7.13"
