### ISSUE TITLE
Script failed an OP_EQUALVERIFY operation

### ISSUE THREAD

**Issue by Messer4** [fyookball/electrum#632]
Try make Pay To.
Electron version
Version 3.1.6
Testnet
error: {'message': 'the transaction was rejected by network rules.\n\n16: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation)\n[0100000001642d098a4493d9200847a1ccf7c00bc5a62b60df7f381ca828723cc4275ef22a000000006a47304402200da3fd4b91e4277bd76652cfe4053c70c74d63c15615e8bb78d877e6ccc8021302202727651a8f7a718683f6b90e846dfb60f0b2c1af8c95380760fcd6af700e154f41210242b1fdefefacfa365c7ae831e7c429fe7a67c6f4cfd4b0af458728ad98638eb6feffffff0200e1f505000000001976a914aff4a314902715a2946b91381c26a7cb5263a83588acc0858647000000001976a914aff4a314902715a2946b91381c26a7cb5263a83588ac34ae1200]', 'code': -1}

**Comment by kyuupichan** [comment]
What was the issue?  I have heard reports of the same error

**Comment by Messer4** [comment]
When I try send more then 1 tBCH I catch this error from network
