### ISSUE TITLE
Broken localization

### ISSUE THREAD

**Issue by jRazer** [fyookball/electrum#633]
Forgot add a folder with the localizations in the release?

Nothing in `/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.6-py3.5.egg/electroncash`

folder from the Electrum only partially.

**Comment by jRazer** [comment]
Sorry, it`s for electron cash

**Comment by marceloneil** [comment]
This issue has gone undetected from the linux build for something like 5 months (f8b3c6e804183f6bb8f19adbb603dedd1de884c7), but has been fixed in 2cc6026bdecc7a76c8b64be760be1cd84d06d409, which will be included in the next release.
