### ISSUE TITLE
Program doesn't start with non-default LC_MONETARY variable on Linux

### ISSUE THREAD

**Issue by jhaand** [fyookball/electrum#643]
Hi,

I have the following issue. 
What: After entering the password for Electron Cash the program exits. There is no error displayed upon exit. Even with the verbose flag active the terminal doesn't show an error. 

Workaround: Set the LC_MONETARY value from "nl_NL.UTF-8" to the default "C". Then the program starts up normally. 

Environment: Debian Linux (testing) + Electron Cash 3.1.6

Log:
[abc.vom-stausee.de] connected
[electrumx-bch.adminsehow.com] connected
[electrum.leblancnet.us] SSL certificate signed by CA
[electrum.leblancnet.us] connected
[electron.coinucopia.io] connected
[abc1.hsmiths.com] connected
[14.3.38.179] connected
[Kraken] received fx quotes
[electrum.epicinet.net] connected
-- Entered Password
[profiler] load_transactions 0.0004
[profiler] build_reverse_history 0.0000
[profiler] check_history 0.0001
[profiler] write 0.0000
[profiler] save_transactions 0.0009
[Plugins] stopped
[profiler] save_transactions 0.0007
[profiler] write 0.0000
[Daemon] shutting down network
[Network] stopping network
[Network] stopped
[Daemon] stopped

**Comment by rt121212121** [comment]
@jhaand Have you retried with 3.2?  If no response, I'll assume this is resolved. Thanks.
