### ISSUE TITLE
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Russell\\AppData\\Roaming\\ElectronCash\\config'

### ISSUE THREAD

**Issue by ProfessorVenkman** [fyookball/electrum#644]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash_gui\qt\main_window.py", line 2912, in closeEvent
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash_gui\qt\main_window.py", line 2925, in clean_up
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\simple_config.py", line 131, in set_key
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\simple_config.py", line 140, in _set_key_in_user_config
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\simple_config.py", line 205, in save_user_config

OSError: [Errno 22] Invalid argument: 'C:\\Users\\Russell\\AppData\\Roaming\\ElectronCash\\config'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.1.6  | Windows-7-6.1.7601-SP1 | standard | en_AU |

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by rt121212121** [comment]
Is it possible for someone's roaming folder to be deleted or renamed?
```python
    def save_user_config(self):
        if not self.path:
            return
        path = os.path.join(self.path, "config")
        s = json.dumps(self.user_config, indent=4, sort_keys=True)
        with open(path, "w") as f: # <-----------------HERE
            f.write(s)
        os.chmod(path, stat.S_IREAD | stat.S_IWRITE)
```

**Comment by rt121212121** [comment]
Same traceback as #624

**Comment by rt121212121** [comment]
https://msdn.microsoft.com/en-us/library/yeby3zcb.aspx

> Each of these functions returns a pointer to the open file. A null pointer value indicates an error. If filename or mode is NULL or an empty string, these functions trigger the invalid parameter handler, which is described in Parameter Validation. *If execution is allowed to continue, these functions return NULL and set errno to EINVAL*.

What the italicised section means, I have no idea.

**Comment by marceloneil** [comment]
Hmm... It really seems like the file was removed/permissions changed or a filesystem error

**Comment by rt121212121** [comment]
I have decided to treat this as a special case and suppress these likely "device unmounted" errors.  If the wallet gets closed, and the file is no longer accessible, it should suppress the error and let the rest of the logic close down.  Maybe it can save the config if it can't save the wallet, and vice versa.  In the event we add handling to detect device removal

Now, it is arguable whether the Roaming case is the same as a removed USB device, but in this situation they should be treated the same IMO.
