### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by ProfessorVenkman** [fyookball/electrum#645]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash_gui\qt\main_window.py", line 2355, in do_import_labels

AttributeError: 'list' object has no attribute 'items'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.1.6  | Windows-10-10.0.16299 | standard | de_DE |

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by rt121212121** [comment]
This is someone importing a JSON file which does not contain exported labels.  The fix in the pull request does a minimal amount of checking that at least the structure is correct (dictionary, first item is key of type string, and value of type string).
