### ISSUE TITLE
I can't recover my BCH !!!

### ISSUE THREAD

**Issue by criptobeat** [fyookball/electrum#649]
My HD is dead. I have a .csv file with both, the private and public keys. I have installed ELECTRON Wallet in the new HD, but ANY of the private keys (starts with "K" or "L") can't be SWEEPED in the new Electron Wallet.

Please help me

**Comment by fyookball** [comment]
dont sweep. just create new wallet and choose import keys then paste them

**Comment by criptobeat** [comment]
Thanks a Lot for your answer !
