### ISSUE TITLE
My BCC is gone from electron cash 

### ISSUE THREAD

**Issue by astralpie** [fyookball/electrum#65]
To day, my BCC is gone from wallet ... i didnt send it, but when i opened wallet , i see unconfirmd transaction to  wallet 1DabL6RUnbuW9oNoWQKPNa6QoCND6BJVUB , transation ID 0e5ea085d8399cbafa9b13505d2fe0caf10a6c6733805f00f35fac42e17022c7
How its possible ??? my laptop was closed ...  Can You help pls

**Comment by charleshsu168** [comment]
you're looking at btc blockchain explorder.
use bcc blockchain explorder.
https://blockchair.com/bitcoin-cash/address/1DabL6RUnbuW9oNoWQKPNa6QoCND6BJVUB

**Comment by astralpie** [comment]
![fffffffffffffffff](https://user-images.githubusercontent.com/30736964/28988890-cdd0ab74-797a-11e7-819a-849e9388802a.jpg)
I didnt do that transaction ((( how to bring that back ? o cancell ??

**Comment by charleshsu168** [comment]
what server are you connected to?
make sure you're connected to bcc server.

**Comment by astralpie** [comment]
when i open network options, "server" cannot be open ... what should i put in proxy or something. ?

**Comment by charleshsu168** [comment]
deselect auto connect server.

**Comment by charleshsu168** [comment]
you will then see list of servers available. find bcc server. again. this is known bug in 2.9.

**Comment by astralpie** [comment]
![server](https://user-images.githubusercontent.com/30736964/28989284-edf02e1e-797c-11e7-8d78-69b4132228d4.jpg)
which server ??

**Comment by charleshsu168** [comment]
i am not familiar with any of the server on the list.
i recommend you update to latest 2.9.2 and try again.

**Comment by fyookball** [comment]
i dont see this on BCC.  please DELETE blockchain headers file since you started with 2.9.0 - im 99% sure this is the issue

**Comment by astralpie** [comment]
Thx ))) i switch off ssl in proxy options , my balance again have BCC. after i install 2.9.2 version, and put server bcc.arihanc.com. now i dont have unconfirmed transaction. Just all balance. Thank you ! great job !!!
