### ISSUE TITLE
Now, I can't send my BCH from Electron Cash to another BCH Wallet 

### ISSUE THREAD

**Issue by criptobeat** [fyookball/electrum#651]
Dear fyookbal.

I have access to my Electron Wallet, but I can't send my BCH to another wallet. My Electron version is 2.9.2 and has 2FA activated. I read in this forum the next post:

https://www.reddit.com/r/btc/comments/6wf50x/recovering_your_bitcoin_cash_from_a_trustedcoin/

I followeb step by step,Nevertheless the balance in the new wallet ( 2FA Disabled ) is CERO. 

Attached to this Issue, I'm sending both images : Electron 2.9.2 Balance ( with my real balance ) and Electron 3.2 Balance ( with CERO balance ).

Please help me....

Best Regards

![electron 2 9 2 balance 1](https://user-images.githubusercontent.com/38442546/39253418-6e971856-486d-11e8-84ee-01247dcc794a.png)
![electron 3 2 balance 1](https://user-images.githubusercontent.com/38442546/39253429-74bce7ce-486d-11e8-8c04-08c1414d1d4c.png)

**Comment by fyookball** [comment]
doesnt look like the same set of addresses.  I suggest posting in #41 or on that reddit thread.  Maybe some of the people that were active in the github thread can help you.  I am travelling this week and won't be able to personally help you.
