### ISSUE TITLE
BTC accidentally sent to my ElectronCash BCH Wallet

### ISSUE THREAD

**Issue by RFIDsignpost** [fyookball/electrum#652]
Folks,

Another party I do business with, has accidentally sent some of my BTC to my BCH address in this wallet.

I know that the Exodus wallet has a feature that allows you to sweep and somehow recover the cross chain funds.  

Is it possible to do something similar with this wallet, so that I can get back my funds? It's not a large amount, but enough to be annoying.

Thanks,

**Comment by uauac** [comment]
You can recovery your wallet in the electrum by using the seeds you have backed up, or maybe you can just copy your wallet file, then use electrum to open the copyed wallet file, maybe it will work.

**Comment by RFIDsignpost** [comment]
I used the original seeds from the BCH wallet, in the BTC wallet, and that worked.


Thanks,


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by RFIDsignpost** [comment]
I used the original seeds from the BCH wallet, in the BTC wallet, and that worked.

Thanks,

The instructions that I received are: 

a. Open your Electron Cash wallet file with with;
b. Or restore your Electron Cash wallet seed into Electrum.

Then, just send your coins to the address you want.

[1] https://electrum.org/#download

**Comment by marceloneil** [comment]
Yeah, exporting private keys is probably what you should go for
