### ISSUE TITLE
Cannot change the displayed language of 3.2-PORTABLE.

### ISSUE THREAD

**Issue by uauac** [fyookball/electrum#653]
I changed the language then restarted the program, it still displayed in English, and the language setting reset to "Default".

My operating system is windows 10, and version 3.1.6-portable didn't have this problem.

**Comment by marceloneil** [comment]
What language? It's possible it's not very well covered: https://crowdin.com/project/electrum

**Comment by marceloneil** [comment]
@fyookball do you think you can test this? I don't currently have access to a windows vm

**Comment by fyookball** [comment]
yeah it doesnt work.

**Comment by Michelgard** [comment]
Actually impossible to change the language it always returns to default under windows10 and version 3.2

**Comment by marceloneil** [comment]
@rt121212121 I don't know if that is a complete fix, as I think the localizations might not function on windows EXEs anyways

**Comment by rt121212121** [comment]
We'll wait for confirmation I guess before closing.  My assumption would be that the Windows exes are not getting the locales included perhaps.

**Comment by marceloneil** [comment]
Yeah, I looked at the build scripts and it didn't seem like it would work (even with the old locale system), but I haven't been able to fix/test it yet
