### ISSUE TITLE
Electron Cash 3.2 APK does not install if you don't uninstall the Play Store version first

### ISSUE THREAD

**Issue by PrzemekFPL** [fyookball/electrum#658]
Perhaps there should be some information on the website next to the APK download link that you need to uninstall the Play Store version first. I installed Electron Cash from Play Store but it is an old version and does not support the BitPay payment protocol. I used the version 3.2 APK from the website, got a message that it was going to do an upgrade, then it says installation failed, without giving a reason why. However after uninstalling the Play Store version, the APK installs and runs fine.

**Comment by fyookball** [comment]
i think that is just how APKs work with same package

**Comment by marceloneil** [comment]
Yeah, that seems like more of an android issue. It might be a different signing key (@fyookball can maybe confirm, did it change or is it different between apks?), or maybe the play store is just like that.

**Comment by PrzemekFPL** [comment]
Well I initially gave up on Electron Cash because I thought the new version would no longer install on my device (as with the BitPay wallet when they bumped their system requirements).
