### ISSUE TITLE
git clone git://github.com/fyookball/electrum.git creates electrum directory 

### ISSUE THREAD

**Issue by charleshsu168** [fyookball/electrum#66]
in the README's Getting Started, this command: git clone git://github.com/fyookball/electrum.git
creates electrum directory

should be: git clone git://github.com/fyookball/electrum.git electronCash 
to avoid confusion

**Comment by fyookball** [comment]
renaming the repo isn't something i was planning on doing as it referenced in build scripts and other places potentially. thank you for the suggestion though.
