### ISSUE TITLE
OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by ProfessorVenkman** [fyookball/electrum#662]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/usr/lib/python3.6/site-packages/electroncash_gui/qt/util.py", line 585, in on_done
    cb(result)
  File "/usr/lib/python3.6/site-packages/electroncash_gui/qt/main_window.py", line 298, in on_error
    traceback.print_exception(*exc_info)
  File "/usr/lib/python3.6/traceback.py", line 101, in print_exception
    print(line, file=file, end="")

OSError: [Errno 5] Input/output error
```

Reporter
------------

This issue was reported by 1 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.1.6  | Linux-4.15.14-1-ARCH-x86_64-with-arch | standard | en_US |

Additional Information
------------------------

> I used a bitpay wallet link, pasted in to pay.  Dragged the fee slider to the top, clicked "preview."  Clicked "Sign" then clicked "Broadcast" - boom.  Incidentally, the application *seems* to still be running (or at least visible in the background), and the transaction did in fact go through.
> 
> Possibly relevant details: I'm also running Electrum 3.1.2 (mainline bitcoin) and Electrum-LTC 2.9.3.1, alongside this.

---

**Comment by rt121212121** [comment]
```python
    def on_error(self, exc_info):
        if not isinstance(exc_info[1], UserCancelled):
            traceback.print_exception(*exc_info)
            self.show_error(str(exc_info[1]))
```

Something the user did which killed writing to wherever the output is going.
