### ISSUE TITLE
Step-by-Step guide to recover Bitcoin Cash from Electrum

### ISSUE THREAD

**Issue by adrianwaj** [fyookball/electrum#663]
Hi, what's the simplest and most straightforward way to get BitcoinCash out of an Electrum (ie bitcoin) wallet running on my Ubuntu machine? The wallet hasn't changed since the hard fork.

Are there any risks involved? Can they be mitigated?

I am just wondering about the need to run the wallets side-by-side, and would seek to avoid it.

Thank you.

**Comment by fyookball** [comment]
just recreate the same wallet with the same seed on electron cash.

**Comment by adrianwaj** [comment]
Is there an install guide for Ubuntu for ElectrumCash please?

There are no problems running the wallets side-by-side?

Maybe it's better to have them running different seeds.

**Comment by fyookball** [comment]
check the readme.  No problem to run side by side.  If you're paranoid, send the BTC to a new wallet before claiming your BCH.
