### ISSUE TITLE
Is `shutil.copy2` used intentionally in `wallet_backup`?

### ISSUE THREAD

**Issue by alexander255** [fyookball/electrum#665]
I realize that this is a pretty hard question, but is the usage of `shutil.copy2` (vs `shutil.copyfile`) in [`gui/qt/main_window.py#L425`](https://github.com/fyookball/electrum/blob/master/gui/qt/main_window.py#L425) intentional or would it be acceptable to the project if `shutil.copyfile` were used instead? I'm asking in particular because the difference between the two functions is that `shutil.copy2` attempts to copy as much metadata (`chmod`, `mtime` & `xattrs`) as possible, while `shutil.copyfile` copies none of it (just the file contents).

With the Flatpak I'm currently developing setting these attributes does not work, raising an `IOError` with the `errno.ENOTSUP`error code („Operation not supported“), which causes an error message to be displayed when the “Save Copy” option form the “File” menu is used to backup the wallet file (althrough the copy operation itself succeeds).

I realize that the current developers of this project are not who implemented this feature this way originally in 2012 (commit ae991f4407f444e918d4d91cc4baeb9dc53f8c72), but I'm mostly trying to get the opinions of the current developers if they see any value in using `shutil.copy2` here over plain `shutil.copyfile`.

Also @maran: If you happen to indeed be the one who implemented this back in 2012 and if you happen to remember why you did it this way, please add a comment as well. :slightly_smiling_face:

**Comment by rt121212121** [comment]
Pull request merged.

**Comment by maran** [comment]
Just to add; there was no real reasoning behind it, I just figured when making a backup it was probably a good idea to copy as much as possible.
