### ISSUE TITLE
Hash256 of 3.2 apk version is not matched

### ISSUE THREAD

**Issue by JessicaJWL** [fyookball/electrum#666]
Have downloaded version 3.2.apk twice, and use the hash verify software to get the data of hash256, and find hash256 data is different in these two downloads, and they are also not matched with what on the website. Does that mean the version has been changed by someone and is not safe now?

**Comment by fyookball** [comment]
hash works for me.  Must be your software.  What software are you using?  What kind of computer are you on?

**Comment by rt121212121** [comment]
@fyookball Time to close this one, no response from reporter.
