### ISSUE TITLE
Enhancement => unmount after save

### ISSUE THREAD

**Issue by mpapec** [fyookball/electrum#673]
When using EC for air-gaped wallet and USB stick to `save tx` && `save signed tx`
it would be useful to have `unmount after save` option/checkbox
which would as you guess unmount usb drive after it is written to.
(pulling stick out without unmounting is unreliable due to data loss)

**Comment by marceloneil** [comment]
Doesn't mounting/unmounting require root privileges? I imagine this would be a touch implementation. Why not just wrap your command in an alias?

**Comment by mpapec** [comment]
In some cases it doesn't;
https://unix.stackexchange.com/a/145675/39077
https://askubuntu.com/a/491/422764
so it may be nice to have it working when it is possible(and under windows this should not be an issue?)

Regarding alias, I'm not sure how that would work under GUI?

**Comment by rt121212121** [comment]
I'm assuming the wallet is also on the usb, which means that we may as well close the wallet window if it gets unmounted.
