### ISSUE TITLE
sweep all addresses into one question

### ISSUE THREAD

**Issue by evadogstar** [fyookball/electrum#677]
Hello, 

I'm writing some simple PoS. Terminal will use xpub key from Electrum to generate new receiving addresses. The question: After that can I simply import my seed to Electrum to sweep all addresses amounts into one? 

I doubte, because Electrum generate only 20 addresses (and check only 20 for sweep?), but my PoS will generate it indefinitely(?). How to sweep them all to one address at some point with Electrum? 

I need to limit new address generation from one xpub up to `0/999999` or it is not a problem o generate more from the same xpub? 

Thanks!

**Comment by fyookball** [comment]
wallet will generate more and more addresses if it detects they are used.  if there is a series of unused addresess it will stop generating. the number of unused is known as gap limit. for example gap limit of 5 means after 5 consecuctive unused addresess, wallet will assume it reached end and stop generating new ones.

**Comment by haunguyen1996** [comment]
Yêu i đo

Vào 1:29 Th 2, 14 thg 5 2018 fyookball <notifications@github.com> đã viết:

**Comment by evadogstar** [comment]
@fyookball Thank you! Hope it is easy to increase gap limit(?) , because I guess there will big series of unused addresses. Many clients/bots will visit payment page and not actually pay.
