### ISSUE TITLE
ImportError: Loader FrozenImporter cannot handle module electroncash.qrscanner

### ISSUE THREAD

**Issue by ProfessorVenkman** [fyookball/electrum#678]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.2-py3.5.egg\electroncash_gui\qt\main_window.py", line 2727, in settings_dialog
  File "c:\python3.5.4\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 611, in exec_module
  File "c:\python3.5.4\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 444, in get_code

ImportError: Loader FrozenImporter cannot handle module electroncash.qrscanner
```

Reporter
------------

This issue was reported by 2 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.2  | Windows-10-10.0.16299 | standard | nl_NL |
| 3.2  | Windows-10-10.0.16299 | standard | en_US |

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by rt121212121** [comment]
@marceloneil @fyookball Close this?  Without context, who is getting it, and what they are running, I can't see it being worth spending time on this.  qrscanner should be bundled with the installer modules.

**Comment by marceloneil** [comment]
Does qr work well on windows? If so that sounds good
