### ISSUE TITLE
BCH sent to address query

### ISSUE THREAD

**Issue by tordommi** [fyookball/electrum#680]
Hi,

A few hours ago I thought I had sent 1 BCH to legacy address 18cC12roA4MHZQjULXYgkZphu17rgi4iCC. This was a BCH Blender deposit.

However the output address (as far as I can tell) on my wallet transaction details is 1AetzhW7kj4L9TkmQKeqCeUi7uH4Ks6zh8	

The transaction page on BCH Blender says 'waiting for deposit'. I thought the transaction was finished though, it has 25 confirmation. 

All I did was copy and paste the legacy address. 
Have I sent it to the wrong address?
How do I retrieve the payment?

Any help would be really appreciated.

**Comment by fyookball** [comment]
doesnt appear anything was sent to 18cC12roA4MHZQjULXYgkZphu17rgi4iCC

https://blockchair.com/search?q=18cC12roA4MHZQjULXYgkZphu17rgi4iCC

**Comment by tordommi** [comment]
I don't understand.. I thought that was the address I had copied and pasted. Then on the wallet transaction it shows the output address as 1AetzhW7kj4L9TkmQKeqCeUi7uH4Ks6zh8

Is it possible to get the payment returned to me?

**Comment by fyookball** [comment]
some malware replaces clipboard or it could be human mistake.

blockchain payments are not reversible.
