### ISSUE TITLE
Wrong numbers display

### ISSUE THREAD

**Issue by KarolTrzeszczkowski** [fyookball/electrum#684]
Hi! My Electron Cash displays numbers as letters, it might be because of polish convention to use a coma instead of a point to mark floating point numbers. It looks like this:
![zrzut ekranu](https://user-images.githubusercontent.com/11697819/40070854-8d2e3f4e-586f-11e8-8795-743bb149b99c.png)
![zrzut ekranu](https://user-images.githubusercontent.com/11697819/40070873-9f5453b6-586f-11e8-8af0-b94a125e0f8a.png)
while listunspent() gives "value": "0.22711104"
I use Arch - Linux 4.14.40-1-lts, polish locale. 
electron:
>> version()
"3.2"

**Comment by rt121212121** [comment]
The sad news is that this is a problem with your Python or underlying system.  Take for example the Balance which shows as "[Bi,11104".   The code that generates this fractional number is:

```python
from decimal import Decimal

def format_satoshis_plain(x, decimal_point = 8):
    """Display a satoshi amount scaled.  Always uses a '.' as a decimal
    point and has no thousands separator"""
    scale_factor = pow(10, decimal_point)
    return "{:.8f}".format(Decimal(x) / scale_factor).rstrip('0').rstrip('.')

balance_text = format_satoshis_plain(22711104, 5)
```

On my system this shows as "227.11104".  It is impossible unless the underlying Python or OS is corrupted in some way for it to show as letters for the integer part. 

@fyookball This issue should be closed, as it is nothing we can do anything about.

**Comment by KarolTrzeszczkowski** [comment]
Maybe it's in GUI part of electron? If you then try to reinterpret this string as a number accidentally then on a computer with polish locale it will show something funny, as it expects a coma not a dot as decimal.

**Comment by rt121212121** [comment]
1. Find out what version of Python you have on your system, that your Electron Cash runs with.
2. Run it and get the interpreter prompt.
3. Paste in the code above.
4. Type `print(balance_text)`.
5. What do you see?

**Comment by KarolTrzeszczkowski** [comment]
![zrzut ekranu](https://user-images.githubusercontent.com/11697819/40535214-babcbeea-6008-11e8-91ae-40e9be834f1c.png)

**Comment by rt121212121** [comment]
Can you run the Electron Cash code locally, and edit the Python to add print statements at various places of interest?

**Comment by rt121212121** [comment]
Actually, just open the console in EC and type:
```python
window.balance_label.text()
```

**Comment by KarolTrzeszczkowski** [comment]
>> window.balance_label.text()
'Balance: [Bi,11104 mBCH (863.69 PLN)  1 mBCH~3.80 PLN'

**Comment by rt121212121** [comment]
Ok, now in this order (I am running on testnet, so this is play money in my balance):
```
>> c, u, x = window.wallet.get_balance()
>> c
1099977900
>> text =  "Balance" + ": %s "%(window.format_amount_and_units(c))
>> text
'Balance: 10999.779 mBCH (16,431.72 NZD) '
```

**Comment by KarolTrzeszczkowski** [comment]
>> window.balance_label.text()
'Balance: [Bi,11104 mBCH (863.69 PLN)  1 mBCH~3.80 PLN'
>> c, u, x = window.wallet.get_balance()
>> c
22711104
>> text =  "Balance" + ": %s "%(window.format_amount_and_units(c))
>> text
'Balance: \x10$z,11104 mBCH (862.68 PLN) '
>>

**Comment by rt121212121** [comment]
```python
>> from locale import localeconv
>> localeconv()['decimal_point']
'.'
```

**Comment by KarolTrzeszczkowski** [comment]
>> from locale import localeconv
>> localeconv()['decimal_point']
','
>>

**Comment by rt121212121** [comment]
Thanks.  Here's the final bit I hope:
```python
>> num_zeros = window.num_zeros
>> decimal_point = window.decimal_point
>> num_zeros, decimal_point
(0, 5)
>> from locale import localeconv
>> c
1099977900
>> x = int(c)
>> scale_factor = pow (10, decimal_point)
>> integer_part = "{:n}".format(int(abs(x) / scale_factor))
>> integer_part
'10999'
>> dp = localeconv()['decimal_point']
>> fract_part = ("{:0" + str(decimal_point) + "}").format(abs(x) % scale_factor)
>> fract_part = fract_part.rstrip('0')
>> if len(fract_part) < num_zeros: fract_part += "0" * (num_zeros - len(fract_part))
>> (integer_part, dp, fract_part)
('10999', '.', '779')
>> result = integer_part + dp + fract_part
>> result
'10999.779'
```

**Comment by KarolTrzeszczkowski** [comment]
```
>> num_zeros = window.num_zeros
>> decimal_point = window.decimal_point
>> num_zeros, decimal_point
(0, 5)
>> from locale import localeconv
>> c
22711104
>> x = int(c)
>> scale_factor = pow (10, decimal_point)
>> integer_part = "{:n}".format(int(abs(x) / scale_factor))
>> integer_part
'\x88#z'
>> dp = localeconv()['decimal_point']
>> fract_part = ("{:0" + str(decimal_point) + "}").format(abs(x) % scale_factor)
>> fract_part = fract_part.rstrip('0')
>> if len(fract_part) < num_zeros: fract_part += "0" * (num_zeros - len(fract_part))
>> (integer_part, dp, fract_part)
('\x88#z', ',', '11104')
>> result = integer_part + dp + fract_part
>> result
'\x88#z,11104'
>> 
```

**Comment by rt121212121** [comment]
Just to be very clear, the problem line looks like (with numbers substituted):
```python
>> "{:n}".format(int(abs(22711104) / pow (10, 5)))
'227'
```
Note that above you get `'\x88#z'`, which is obviously wrong. Can you double-check? Thanks.

**Comment by KarolTrzeszczkowski** [comment]
```
>> "{:n}".format(int(abs(22711104) / pow (10, 5)))
'X$z'
```

**Comment by KarolTrzeszczkowski** [comment]
```

>> abs(22711104) / pow (10, 5)
227.11104
>> int(abs(22711104) / pow (10, 5))
227
>> "{:n}".format(227)
'Ø#z'
>> 
```
:O 
I runned it in console and it's different 
```
>>> "{:n}".format(227)
'227'
```
yet in electron I also get:
```
>> import sys
>> print (sys.version)
3.6.5 (default, May 11 2018, 04:00:52) 
[GCC 8.1.0]
>> 
```
So there should be no difference

**Comment by rt121212121** [comment]
Here's something to try in both places:

```python
import locale
locale.getlocale()
```

**Comment by KarolTrzeszczkowski** [comment]
![zrzut ekranu](https://user-images.githubusercontent.com/11697819/40537716-e83531ac-600f-11e8-9b0c-eec1c4ae240b.png)

**Comment by rt121212121** [comment]
```
'n' | Number. This is the same as 'd', except that it uses the current locale setting to  insert the appropriate number separator characters.
```

So, let's try:
```python
>> "{:d}".format(227)
```

What's that return?

**Comment by KarolTrzeszczkowski** [comment]
```
>> "{:d}".format(227)
'227'
```
both

**Comment by rt121212121** [comment]
So Python has some weird locale handling bug in number formatting.  It's not something we're ever going to spend time on to debug, as it would involve debugging the Python runtime with Electron Cash running in it on your machine.  Interestingly, Electrum does something different for displaying amounts, maybe we can just copy that.

**Comment by KarolTrzeszczkowski** [comment]
Great :)
Thank you very much, you're the best.
I got to go for now, duty calls.
I'll report this issue back to python o.O

**Comment by marceloneil** [comment]
Glad you found the root cause

**Comment by SomberNight** [comment]
it works in electrum because we worked around it https://github.com/spesmilo/electrum/issues/3294
you guys should follow the issues there :)

**Comment by rt121212121** [comment]
I searched them, but didn't have the right keywords apparently.

**Comment by marceloneil** [comment]
Thanks @SomberNight, I'll cherry-pick the fix
