### ISSUE TITLE
Sweep private keys fails with empty address

### ISSUE THREAD

**Issue by raedah** [fyookball/electrum#69]
When opening the sweep private keys window, there should be an address displayed. In some cases, that address is not displayed and it is not possible to continue. This seems to be the case when the user already has an unconfirmed sweep in progress.

Clicking on the address button displays an error in the console.
Traceback
File gui/qt/util.py, lin 313, in func
i = address.index(str(address_e.text())) + 1
ValueError: '' in not in list

**Comment by fyookball** [comment]
"This seems to be the case when the user already has an unconfirmed sweep in progress."

I am thinking that is how it is supposed to work.

**Comment by molecular** [comment]
I tried to reproduce this but can't.

no problem doing 2 sweep operations after one another. The address input field will be filled with 2 fresh address on 2nd sweep while 1st sweep tx is still uncomfirmed

**Comment by raedah** [comment]
I also can not reliably reproduce this, but it still is occurring frequently. It does not appear to be caused by there being multiple sweep operations, as sometimes it occurs immediately after loading the program.

**Comment by raedah** [comment]
I also tried creating a new wallet by import priv keys, and encounter the same issue. Next button is grayed out, as if it thinks the priv keys I am pasting are not valid, but they are.
