### ISSUE TITLE
Signing after loading tx from file is broken

### ISSUE THREAD

**Issue by kwaaak** [fyookball/electrum#7]
> Traceback (most recent call last):
  File "/home/xubuntu/Desktop/Electron Cash-2.9.0/gui/qt/util.py", line 582, in run
    result = task.task()
  File "/home/xubuntu/Desktop/Electron Cash-2.9.0/lib/wallet.py", line 1103, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/xubuntu/Desktop/Electron Cash-2.9.0/lib/keystore.py", line 113, in sign_transaction
    tx.sign(keypairs)
  File "/home/xubuntu/Desktop/Electron Cash-2.9.0/lib/transaction.py", line 829, in sign
    pre_hash = Hash(self.serialize_preimage(i).decode('hex'))
  File "/home/xubuntu/Desktop/Electron Cash-2.9.0/lib/transaction.py", line 727, in serialize_preimage
    amount = int_to_hex(txin['value'], 8)
KeyError: 'value'

Signing works after deleting https://github.com/fyookball/electrum/blob/cash/lib/transaction.py#L726 and removing "amount" from the line afterwards, but on broadcast you get the error described in https://github.com/fyookball/electrum/issues/6

**Comment by fyookball** [comment]
Yes, loading=> signing needs to be fixed.  I will work on that this week.

**Comment by kwha** [comment]
I've managed to do a successful loading and signing using pickle.dump and pickle.load on self._inputs. This was manually done for a 2 out of 3 multisig electrum wallet.

**Comment by fyookball** [comment]
sounds like it could be useful if you document the process for others

**Comment by fyookball** [comment]
I believe @dabura667 is working on a fix currently.

**Comment by leon-beyer** [comment]
@kwha, @fyookball, I'm facing the same issue, getting an error with a "?" sign as a title and an error saying "value" when trying to sign a 2of2 transaction.
If anyone could send me code for a modified version that does it, or explain step-by-step how to do that process involving self._inputs, I can pay $250 for the solution.

**Comment by kwha** [comment]
@leon-beyer , have you tried @junderw's fix ? If that doesn't work send me an email at marius - rohost - com

**Comment by kwha** [comment]
I've tried #29 and it works.

**Comment by AndersBNielsen** [comment]
Just loaded 2.9.2 and I still get the error ('value') when trying to sign a tx offline

**Comment by dabura667** [comment]
@leon-beyer @junderw would love $250 :-D

**Comment by dabura667** [comment]
@AndersBNielsen hold on a bit. I really should sleep but I think I can write a fix.

**Comment by junderw** [comment]
@leon-beyer If you're feeling generous:
1Eo53QuU62p8xfiHuyWFKX9dfQZXTFwWeT

Hope everything works out for everyone.

**Comment by kwha** [comment]
Seems I missed the fact that I've imported the patch on top of mine. This _should not_ be merged in git.

Anyway, it's an ugly hack but here it goes:

in lib/transaction.py do:

-----------------------------
```
import sys
import struct
import pickle
```
-----------------------------
```
    def inputs(self):
        if self._inputs is None:
            self.deserialize()
        with open('inputs.pkl', 'wb') as output:
            pickle.dump(self._inputs, output, pickle.HIGHEST_PROTOCOL)
        return self._inputs
```
------------------------------------
```
    def sign(self, keypairs):
        try:
          with open('inputs.pkl', 'rb') as input:
              self._inputs = pickle.load(input)
        except IOError:
              print_error("inputs.pkl not found")
        for i, txin in enumerate(self.inputs()):
```
------------------------------------------

What it does, it saves the self._inputs in a file and loads them at sign if the file exists. This works for 2 signatures if the signing is done with the same electron client, otherwise you need to move the inputs.pkl on the second electron client.
