### ISSUE TITLE
NameError: name 'error_code' is not defined

### ISSUE THREAD

**Issue by ProfessorVenkman** [fyookball/electrum#704]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.2-py3.5.egg\electroncash_gui\qt\external_plugins_window.py", line 178, in on_install
  File "site-packages\electron_cash-3.2-py3.5.egg\electroncash_gui\qt\external_plugins_window.py", line 278, in install_plugin_confirmed

NameError: name 'error_code' is not defined
```

Reporter
------------

This issue was reported by 1 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.2  | Windows-10-10.0.17134 | standard | ru_RU |

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by rt121212121** [comment]
Bug only seen when they choose to install a plugin, check the boxes, and finalise the install - and the installation fails and the code goes to show them a message.
