### ISSUE TITLE
Verify message only works with legacy addresses.

### ISSUE THREAD

**Issue by GoodCrossing** [fyookball/electrum#706]
Hello, I was using Electron Cash to test out the sign and verify feature. I put in my message and my address in cashaddr format, and it signed it without any issues. When I went to verify it, it said "Invalid bitcoin cash address"

I converted the address to legacy format and it verified fine. I think the verify tool hasn't been updated to the cashaddr format.

**Comment by rt121212121** [comment]
My reproduction steps:

1. Turn on cashaddr.
2. Copied an address from the Addresses window.
3. Opened Sign/Verify window.
4. Wrote a message.
5. Signed with copied address.
6. Verified it.

It all went fine.  I even closed the window, reopened a new one and pasted in the message, signature and address, and reverified. Still verified fine.  In Electron Cash 3.2, the address processing for signing and verifying is the same. 

I'd suggest that this be closed as non-reproducible unless you, the reporter, can bring further light on the situation.

**Comment by kyuupichan** [comment]
I suspect the OP is running an old version of the software; the bug was present in a prior release

**Comment by rt121212121** [comment]
Duplicate/fixed in #476
