### ISSUE TITLE
Exception: forced exception

### ISSUE THREAD

**Issue by ProfessorVenkman** [fyookball/electrum#707]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "C:\rt121212121\VCS\GIT\Bitcoin\electron-cash\gui\qt\external_plugins_window.py", line 308, in on_install_plugin
    raise Exception("forced exception")

Exception: forced exception
```

Reporter
------------

This issue was reported by 1 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.2  | Windows-10-10.0.17134-SP0 | standard | en_NZ |

Additional Information
------------------------

> Test send Python version.

---

**Comment by rt121212121** [comment]
@fyookball Close me, testing what happens if I add the python version to the report metadata.
