### ISSUE TITLE
BTC tx shows up as unconfirmed tx on Electron cash

### ISSUE THREAD

**Issue by komirad** [fyookball/electrum#71]
I imported my wallet from Electrum. A BTC TX I made using Electrum after the fork shows up as an unconfirmed transaction. When I view this TX on the block explorer, it's a 404. This tx is the one where I transferred out all my BTC before using Electron Cash. And now Electron Cash thinks I have 0 BCH because of this BTC transaction and stops me from spending any BCH.

How can I clear out the tx so that only BCH tx shows up?

![image](https://user-images.githubusercontent.com/3870837/28994841-58f15322-7a0a-11e7-94ec-a5a5bf99bdfc.png)

**Comment by fyookball** [comment]
connect manually to a BCC server
