### ISSUE TITLE
Copying cashaddress on Android in receive window is always in upper-case

### ISSUE THREAD

**Issue by Mktk00** [fyookball/electrum#715]
There a little issue on android with cashaddr, in the receive window, when i choose copy, the format of the cashaddr is it in uppercase and no lowercase.

**Comment by rt121212121** [comment]
Bugs in the existing Android app are not getting any attention, and are pretty much sitting around until the new Android app is finished.  Jonald's policy is to close them for this reason, and to better highlight the stuff that will actually be worked on.  In case anyone volunteers to do this work and will take them on, I will mark them as backlogged so they can be filtered and found when closed.

**Comment by jasonbcox** [comment]
I would also like to point out that CashAddr is case-insensitive: https://www.bitcoinabc.org/2018-01-14-CashAddr/ so the uppercase should not matter.
