### ISSUE TITLE
Crashes and deletes upon opening

### ISSUE THREAD

**Issue by uncleschaeflit** [fyookball/electrum#718]
I have downloaded 3.2 multiple times with the same unfortunate result. I open the .exe, I get to the first screen, make the server choice and then the program closes and disappears. 

Any help would be appreciated. 

Thanks.

**Comment by rt121212121** [comment]
What do you choose?

**Comment by uncleschaeflit** [comment]
I choose the default option of "auto connect."

**Comment by rt121212121** [comment]
Where did you download the exe from?  It deleting itself sounds super dodgy.  I have an recent build from @fyookball which has logging to the console which you can try, but I need to find somewhere it can be uploaded.  Are you on bchchat slack?

**Comment by rt121212121** [comment]
If the exe gets deleted from your desktop, maybe check to see if your virus checker or malware checker is killing and quarantining it.

**Comment by rt121212121** [comment]
Hi, unless you can provide some more information, I'm going to close this issue.  It is almost entirely related that it gets deleted from your desktop and killed.  That effectively proves it's either malware you downloaded from another source, or you have a virus checker or malware checker that's killing/quarantining it.
