### ISSUE TITLE
Trezor Model T not detected

### ISSUE THREAD

**Issue by jooray** [fyookball/electrum#727]
Trezor Model T (new trezor hardware wallet) is not detected. Upstream Electrum already supports the new Model T.

**Comment by marceloneil** [comment]
There is an emulator, I'll look into this soon

**Comment by SomberNight** [comment]
Well for one, https://github.com/spesmilo/electrum/pull/3863/commits/460e88ee536494d9cf9c66b4993d91ea4eccff8a is missing

**Comment by marceloneil** [comment]
@SomberNight I just tested out electrum with the Model T emulator and both work seamlessly together, good job!

**Comment by yura-pakhuchiy** [comment]
@marceloneil which versions of electron cash and python-trezor you have used? Only Trezor 1 works for me, but Trezor T does not.

**Comment by cculianu** [comment]
Ok, @jhoenicke was kind enough to fix this.

This will be out in 3.3.1 -- or you can run from sources today if you are impatient and want it to work.

Thanks jhoenicke!!
