### ISSUE TITLE
This is a malware please don't use this.

### ISSUE THREAD

**Issue by GGYaX** [fyookball/electrum#73]
After importing private key, this software display 0 BCC then in the blockchain, all the fund were transferred to another address. Please don't use this.

**Comment by fyookball** [comment]
are you sure you did the checksum?

**Comment by fyookball** [comment]
I can assure this is isn't written as malware.  Others aren't having problems

**Comment by fyookball** [comment]
https://twitter.com/ViaBTC/status/893744282087047168

**Comment by molecular** [comment]
Please point to the malware code. If you can't, this issue makes no sense here.
