### ISSUE TITLE
Option to turn off sync for all addresses by default (when creating new wallet), and a toggle to check each address’ balance

### ISSUE THREAD

**Issue by gasull** [fyookball/electrum#730]
For privacy reasons, it would be better to check one/chosen addresses at a time instead of disclosing your IP address & every single address in your wallet to the server host.

This could be called ‘Privacy’ mode and have default connection to the Tor network (unless disabled)

This ticket was created from [this Reddit post](https://www.reddit.com/r/btc/comments/8q5z49/electron_cash_request_option_to_turn_off_sync_for/).

**Comment by marceloneil** [comment]
@kyuupichan I think you were talking about this at some point

**Comment by rt121212121** [comment]
Jonald's issue policy is that backlogged enhancements are unlikely to have anyone with spare time to jump on them anytime soon, so they should be closed.  If anyone is looking for something to work on, we will get them to look up closed backlogged enhancements.
