### ISSUE TITLE
Balance corruption

### ISSUE THREAD

**Issue by ThrowawayIssue** [fyookball/electrum#731]
I've imported my private key into Electron Cash 3.2 and instead of a proper balance I see random ASCII characters in both history and in balance on the bottom of the window.
I see that the last transaction is for "e,142xxx" BCH, and my current balance is "[a,320925". "[a" changes on every restart or reconnection.
I'm running Fedora 28, and tried both compiled version from the website and built it myself.

![screenshot_20180611_193233-fs8](https://user-images.githubusercontent.com/40177567/41244862-0ef24dbe-6daf-11e8-8398-2e29bf378673.png)

![screenshot_20180611_193223-fs8](https://user-images.githubusercontent.com/40177567/41244866-11ee010c-6daf-11e8-8303-bb4df64d32ac.png)

**Comment by ThrowawayIssue** [comment]
Calling `getaddressbalance()` with my address in the console returns proper balance.

**Comment by ThrowawayIssue** [comment]
Problem occurs only with `BCH` selected as base unit in the settings. No balance corruption occurs with `mBCH` or `cash`.

**Comment by marceloneil** [comment]
Seems to be related to #684, I'm working on that now.

**Comment by ThrowawayIssue** [comment]
Works now, thanks.
