### ISSUE TITLE
bcc stucked in electron cash

### ISSUE THREAD

**Issue by minergxp** [fyookball/electrum#74]
Hello. My bitcoin cash are stucked in my eléctron cash wallet. when i starts the wallets appears a message that says that my wallet is just for watching. how can i do?
![wallet 1111](https://user-images.githubusercontent.com/30749868/28995273-6444c35c-79bb-11e7-8599-9ab448f90cd0.jpg)

**Comment by fyookball** [comment]
how did you create

**Comment by fyookball** [comment]
sounds like you imported pub key which is obviously watch only
