### ISSUE TITLE
What node path of the BIP32 is ElectronCash using?

### ISSUE THREAD

**Issue by maesitos** [fyookball/electrum#742]
I can't seem to find the deviation the wallet uses for receiving address and change.

**Comment by rt121212121** [comment]
Create a new wallet and change the options.  It gives the opportunity to change the derivation address in there somewhere.

**Comment by rt121212121** [comment]
I'm going to assume you've done this, since it shouldn't be that hard.

**Comment by rt121212121** [comment]
My mistake sorry, the derivation paths are shown in the hardware wallet creation.  If they are shown elsewhere they are hard to find.

```
            _("If you want the wallet to use legacy Bitcoin addresses use m/44'/0'/0'"),
            _("If you want the wallet to use Bitcoin Cash addresses use m/44'/145'/0'"),
```
