### ISSUE TITLE
Version 3.2 in Google Play Store

### ISSUE THREAD

**Issue by jonas-lundqvist** [fyookball/electrum#743]
Hi,
Why isn't v3.2 available in Google Play Store? I can see the v3.2 APK on electroncash.org but only v3.1.3.1 in Play Store.

I assume (by quickly reading the git log) that BitPay invoices is only supported on v3.2, otherwise I will debug further and submit a new issue.

**Comment by fyookball** [comment]
No good reason.  It is just time consuming to format it for the google store so not every update goes there.  Next release I will put on the google play.
