### ISSUE TITLE
How to provide language translations?

### ISSUE THREAD

**Issue by kamk** [fyookball/electrum#746]
Original Electrum uses crowdin.com localization platform. How is going to be with Electrum Cash? Is it okay to provide .po files (translated with [poedit](https://poedit.net) for instance) ?

**Comment by marceloneil** [comment]
Right now we use the electrum localizations, but it might be nice to branch off

**Comment by cculianu** [comment]
We're going to need to as I added a whole slew of new UI strings for iOS.. :/

i also would like for us to think about getting more translations in when we have the bandwidth for it (in particular for iOS which at this point is 50% untranslated).

**Comment by corper** [comment]
@GitCash send 0.001 bch to @marceloneil

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/197/image.png)](https://gitcash.io/claim/marceloneil)
@marceloneil

**Comment by marceloneil** [comment]
I think it would be good to create our own crowdin/transifex/some-other-service localization repo seperate from electrum, because we are growing further apart, and we need more localization for IOS/android. I think @cculianu seconds me on this

**Comment by cculianu** [comment]
I second you on this!

**Comment by rt121212121** [comment]
@fyookball  , I think we currently use the electrum translations, we need to set up the electron cash version of this?

**Comment by marceloneil** [comment]
I think it might be nice to use something other than crowdin though, something less proprietary, but still accessible.

**Comment by rt121212121** [comment]
If we started with crowdin in the short-term it might be more achievable,
and we can transition later?

**Comment by marceloneil** [comment]
I'm not sure, maybe I'll ask in the BCF discord to see what translators their prefer. @kamk do you have a specific preference?

**Comment by kamk** [comment]
Not really. You can apply for [crowdin's free account](https://crowdin.com/page/open-source-project-setup-request) for open-source project. However, for Electrum only few translations are more than 50% complete.
Maybe it would be better to have `.po` files right in repository along with some README document for translators. I'd try in my spare time to prepare something along with CS and SK translations.
Also, according to base (lib/locale/messages.pot) there will be need to change some strings in source regarding words "Electrum", "Bitcoin" and possibly some others.

**Comment by rt121212121** [comment]
If we go with po files in the repo, the barrier to entry becomes higher.  If we apply for crowdin, anyone who wants to contribute can just visit the website and do so.  Not my choice to make, but the latter seems like a big advantage.

**Comment by kamk** [comment]
I think we can go with **crowdin**, so first step to [create an account](https://crowdin.com/page/open-source-project-setup-request) for Electron Cash.

**Comment by cculianu** [comment]
I agree with Roger on this one.. crowdin seem the quickest and most straightforward. Willing to revisit this later.

Right now we're sorely lacking iOS strings.. 

@fyookball  -- want to create an account or shall I?

**Comment by marceloneil** [comment]
Has anyone tried pontoon?

**Comment by rt121212121** [comment]
@cculianu @fyookball We got that account yet?  We need to get this rolling, when someone offers assistance to hep translate, we shouldn't sit around for 19 days letting the offer languish.

**Comment by cculianu** [comment]
I agree with you -- my laptop died and I have been very unproductive on Windows.  New laptop coming in 2 days,.  Will look into it after that point.

**Comment by rt121212121** [comment]
Yeah, laptop deaths are like losing a limb in spirit.

I can also sign up and add everyone else.  I'll push jonald in the channel to sign up, and if he doesn't will do it myself, but if that fails go for it.

**Comment by fyookball** [comment]
i created an account. details are in slack

**Comment by rt121212121** [comment]
You can now edit translations on crowdin
https://crowdin.com/project/electron-cash
