### ISSUE TITLE
Import Bitcoin Private Keys Format

### ISSUE THREAD

**Issue by Behzad781** [fyookball/electrum#751]
Hi,

I want to import a Bitcoin Private key and de XPRV format is not accepted. Can you tell me which would be the right format?. thank you

**Comment by rt121212121** [comment]
Upload a new key created in the same way as your existing one that does not work and I will try it and tell you why it does not work.  Offhand, I cannot tell you.

**Comment by Behzad781** [comment]
The private key is from a Copay/bitpay BTC wallet. I've got the seed, the xPrivKey, requestPrivkey, and the Walletprivkey but none of them works on elctroncash

**Comment by cculianu** [comment]
An XprivKey should definitely always work.  

Make sure you picked "Standard Wallet" in the first menu, then pick "Use public or private keys" (I know, it's confusing as hell).

Attached you will see what I mean.

It should definitely work.  I think you just got (understandably) confused by the menu options.

<img width="447" alt="screen shot 2018-06-25 at 9 43 10 pm" src="https://user-images.githubusercontent.com/266627/41869198-e6347cae-78c0-11e8-8ce3-27592db705d1.png">
<img width="450" alt="screen shot 2018-06-25 at 9 43 44 pm" src="https://user-images.githubusercontent.com/266627/41869197-e60dfd04-78c0-11e8-916f-264098507396.png">

**Comment by rt121212121** [comment]
@Behzad781 If you try us and this works, please let us know, so we can close this issue.

**Comment by Behzad781** [comment]
Thanks a lot. It's working perfect!! you can close this issue
