### ISSUE TITLE
Encryption for watching-only wallets (non-hardware)

### ISSUE THREAD

**Issue by cculianu** [fyookball/electrum#752]
I know there's another hardware-wallets encryption of watching only proposed.

This is presumably a subset of that milestone.

I'm adding it as a separate milestone because perhaps we can at least get this implemented, if we don't end up doing the hardware wallet portion of the previous milestone.

iOS users were asking for this feature.

**Comment by cculianu** [comment]
Wait this is just an issue. How do I add a milestone?

(Confused)

**Comment by marceloneil** [comment]
Look at the side-bar of an issue, you can add an assignee, label, project or milestone

**Comment by cculianu** [comment]
I think I'm too lowly a pleb to be able to do that! :(

**Comment by marceloneil** [comment]
Oh no! You need to ask @fyookball for contributor access, especially if we're merging the ios branch in
