### ISSUE TITLE
Electron Cash 3.3 Portable for Windows no longer works with Trezor One

### ISSUE THREAD

**Issue by Saicere** [fyookball/electrum#756]
Seems that the Trezor library is missing from the build. Opening a wallet created with a Trezor One now just pops up the error message "Cannot find python library for 'trezor'. Make sure you install it with python3".

Attempting to sign a transaction pops up the error "Handler not found for trezor. A library is probably missing."

Attempting to view an address on the Trezor makes Electron Cash crash with the traceback:

File "C:\[...]\electroncash_plugins\trezor\qt_generic.py", line 196, in show_address
    keystore.thread.add(partial(self.show_address, wallet, addrs[0]))
AttributeError: 'TrezorKeyStore' object has no attribute 'thread'

Reverting the executable to 3.1.6 makes it work fine again.

**Comment by cculianu** [comment]
This has been fixed by @jhoenicke in a recent PR.  Look for it to be addressed in 3.3.1 release -- or if impatient -- run from github sources today!

**Comment by cculianu** [comment]
PS: Thanks so much for reporting this and sorry it broke!
