### ISSUE TITLE
iOS server selection isn't saving

### ISSUE THREAD

**Issue by WyseNynja** [fyookball/electrum#759]
The iOS app is working great for me but there is one issue I've noticed. I’m able to deselect “select server automatically” and connect to my own server, but it isn’t saving the server. When I re-opened the app it had "select server automatically" re-checked and a different server selected. Am I missing a “save” button or something? My server is sometimes listed under “connected node, height” but “select server automatically” was back to enabled and a different wallet server was selected.

**Comment by cculianu** [comment]
Yeah this is likely an oversight on my part when implementing the UI.

I'll work on this as it's definitely a bug.  I'll either add a save button or implicitly save the server upon editing (probably the more likely approach is the latter).

Sorry!  Thanks for opening the issue by the way!

**Comment by cculianu** [comment]
Hey thanks for reporting this! I have fixed this bug.  I think I may submit an update to Apple sometime this week so perhaps next week at the latest you'll see it pushed "live".

Thanks again!
