### ISSUE TITLE
Units for "Max static fee"

### ISSUE THREAD

**Issue by WyseNynja** [fyookball/electrum#760]
I'm used to setting fees as satoshi/byte. How does max static fee work?

1 mBCH = 100,000 Satoshis, right?

Does 1 kB = 1000 bytes, or does 1kB = 1024 bytes?

**Comment by cculianu** [comment]
In this app, 1 kB = 1000 bytes (perhaps confusingly -- but in general in the bitcoin world they do it that way.  "1 MB" blocks are just 1 million bytes, etc.

And yes, 1 mBCH = 100,000 satoshis, yes.  

You know what? I actually have no idea what max_fee_rate is for.  I'm looking at the code and it appears to be an old parameter from the BTC days.  I'm doing my research on it now and will let you know.

**Comment by cculianu** [comment]
Ok, Jonald just told me it's there and it used to control the "scale" of the fee slider. So if you set it to .200 mBCH or something the slider would end up having its "max" value pegged to that and everything under max a fraction of that.

So right now the slider's max is 10 sats/byte (which is really the same as a max fee rate of 0.1mBCH/kB). The max fee rate isn't being used.

But Jonald plans on bringing it back very soon -- so we left the parameter there.

Sorry for the confusion.

I'm going to go ahead and close this issue now (as there's no real "action item" for code changes being proposed here) -- but feel free to continue to write here as I will be notified of your messages.
