### ISSUE TITLE
"Unconfirmed" - "Confirmed" - "Unconfirmed"

### ISSUE THREAD

**Issue by ealoe** [fyookball/electrum#77]
Next, I imported the private key into electron and waited for confirmation to receive the bcc. Around 4 am, the balance was available at electroncash, meanwhile I was waiting for the account verification at Kraken to be able to send them. I went to sleep and when I woke up to check the electroncash was "unconfirmed" again, and a "low fee". I did not do anything at all, I did not turn off the pc, nor did I close my wallet, because I do not remember the password I used to encrypt it.

**Comment by fyookball** [comment]
i think that was maybe mallaebility attack on bcc or incorrect server

**Comment by ealoe** [comment]
And what should I do?

**Comment by ealoe** [comment]
this is address: 19hdyXZQVUNMrDFdRmj2tPnbFiS7euEfq9
