### ISSUE TITLE
Bug in PaymentRequest class in lib/paymentrequest.py 

### ISSUE THREAD

**Issue by cculianu** [fyookball/electrum#772]
From lib/paymentrequest.py at line 187:

```
class PaymentRequest:

    def __init__(self, data, error=None):
        self.raw = data
        self.error = error
        self.parse(data)
        self.requestor = None # known after verify
        self.tx = None

    def __str__(self):
        return self.raw
```

^ self.raw above is sometimes a bytes object. This causes python runtime to throw an exception when doing str(request) on a PaymentRequest object (see #770).  

I would like to fix this -- (perhaps if isinstance(self.raw, bytes).. bla).  Or some other approach.

So.. what's the deal here? Suggestions? Should I just fix it by detecting bytes and encoding to string?

**Comment by marceloneil** [comment]
Is it possible to do:
```python
return str(self.raw)
```

**Comment by cculianu** [comment]
Yes. Why not?

Wanted a sanity check on it. I'll double-check tomorrow if any code even calls this function (I suspect it doesn't, else we would have seen this earlier).  So yeah I'll probably fix this tomorrow, then. Thanks for looking at this too.

**Comment by marceloneil** [comment]
It does seem a bit cheeky :stuck_out_tongue:

**Comment by marceloneil** [comment]
Do you know if there is a reason why `self.raw` is sometimes bytes? Does it make sense to fix that instead and assert that it is a string?

**Comment by cculianu** [comment]
Despite my needing to go to bed, I couldn't resist.

It turns out this is definitely a bug.  Sometimes the attr is an str, sometimes a bytes object.  The fix of str(self.raw) is definitely the way to go.  

This bug exists in upstream as well.  I'll be sure to inform them about it.

**Comment by cculianu** [comment]
Oh -- hey Marcel. Didn't see your question.

Actually on closer inspection and from my reading of the code it's supposed to be a bytes object.  The function at the top of the file: get_payment_request basically is responsible for writing to self.raw.  If you read the codepath it puts a bytes object in there in every branch.

So yeah no need to enforce it be a string -- it looks like other code expects a bytes object there.

But good suggestion otherwise (if the above were not the case that would have been the good approach).

**Comment by kyuupichan** [comment]
Guys let's not just push random stuff.  Raw as the name clearly indicates it's bytes.

**Comment by cculianu** [comment]
This isn't "random stuff".  Keep up.  If you don't know what's going on, don't say negative stuff, please. 
 It's demoralizing.

In a python __str__ class method you can't return bytes.  You have to return string.. else you get a TypeError exception.

This isn't random stuff.  This fixes a crash I got on iOS.

The class was buggy. This fixes it.

**Comment by marceloneil** [comment]
It does make sense that `self.raw` is bytes, but why implement `__str__` in the first place? I'm assuming it was just for debugging

**Comment by cculianu** [comment]
Right you are.  The paymentrequest.raw field is actually a bunch of google protocol buffer bytes so .. the 'str' isn't meaningful.   It's just for debugging.  But -- you know -- might as well fix it since it's clearly not to spec.. even for debugging. :)
