### ISSUE TITLE
Android wallet for BCH - balance tab

### ISSUE THREAD

**Issue by School47** [fyookball/electrum#776]
yo guys!
I can see my balance at any currency in electrum wallet for BTC and it is very useful.
for BCH i use electrum, but it is very hard to understand, how much money in USD or other currency in my wallet.
Every time i want to see my balance in USD, i have to go at "send" tab, select "amount" and push"max" button.

**Comment by rt121212121** [comment]
Definitely sounds painful.  I recall this being fixed in the new Android app that is coming.  The existing app will be replaced by the new app.   Closing this because the old app won't be getting changed.  Hope you won't be waiting too long.
