### ISSUE TITLE
androind wallet crashes every time i paste adress and push max button 

### ISSUE THREAD

**Issue by School47** [fyookball/electrum#777]
max button  in "send" tab crush program!  i tested it in 3.3 version.
how can i use application, if i can't just send money?

also if i try to enter bigger BCH, than i have at wallet, aplicaition doesn't care, until i push "pay".
It should correct me before i want to go back to "send"  tab.

**Comment by rt121212121** [comment]
When it crashes, do you get a popup window asking you to submit the exception to us?

**Comment by School47** [comment]
yep, i sent report 2 mins ago.
it crashes if adress field is empty.
Why i left it empty?  Cuz i want to know my balance in USD, and it is the only way i can check my account in USD.
In electrum wallet for BTC there is separate tab "balance" with USD amount of my BCH.

**Comment by rt121212121** [comment]
@marceloneil Here's a report of a exception being sent by OP and not arriving in the issues.

**Comment by rt121212121** [comment]
@School47 Do you run from github source?  Or a source/binary release for some os?

**Comment by School47** [comment]
@rt121212121  i am not a programmist, so i don't know what means OP.
I just downloaded app from google play and tryed to use it. 
After i got some issues and what's why i created this thread.
to repeat bug just open electron cash 3.3, open send tab and in amount field push max button. It will cause crush. Recipient should be empty actually.

Also Electrum for BTC has exactly same bug, but i don't care. The real bitcoin is BCH. and the best wallet for it should be electron cash fo sure.

**Comment by rt121212121** [comment]
@School47 I know it's not the best outcome you go to the effort to report bugs and they won't be fixed, and get closed, but please feel free to submit any future bugs.  But maybe just not for the current android app :-)
