### ISSUE TITLE
Transactions not reliably broadcasted

### ISSUE THREAD

**Issue by tbrannt** [fyookball/electrum#779]
I think electron cash choses its peers randomly on startup. Sometimes I end up with peers that seem to not forward my transactions. I'm not sure how to best handle these bad nodes you sometimes get.. perhaps an automatic rebroadcast mechanism.. or more random peers? Maybe checking peers and banning them if they're not reliable..

Just imagine a newbee paying a bill with bitpay but after sending the tx the money is just gone but not received by bitpay.. this happened e.g. for 2e2e6d02c753c6a28aa2d1eae8ca327fbb3e56c204af14fd593f981fa9501302. I sent it with electron-cash but noone seems to know it.

**Comment by fyookball** [comment]
not sure but if you connect to new node it will be broadcast

**Comment by tbrannt** [comment]
ok, weird. Actually after restarting electron the 2 tx (I created an additional cpfp one) have disappeared from the history. Now sending a new tx gives me "error: {'code': 1, 'the transaction was rejected by network rules.\n\n258: txn-mempool conflict ...

**Comment by fyookball** [comment]
that means its broadcast but for some reason your history didnt update.  try switching servers or maybe your wallet file got corrupted
