### ISSUE TITLE
Can't send my BCC "Not enough funds"

### ISSUE THREAD

**Issue by fresheneesz** [fyookball/electrum#78]
I definitely have enough funds. The best I can see is that my single-address wallet is using itself as a return address, and Electron Cash erroneously thinks that the wallet is empty because the transaction used its only input as its output. It should be able to recognize that the transaction was sent back to myself - the balance in the history recognizes the correct balance.

**Comment by fyookball** [comment]
usually when that happens its because not all tx confirmed

**Comment by fresheneesz** [comment]
@fyookball There's actually a preference setting that's checked by default that prevents spending unconfirmed transactions. I unchecked it and it worked (after a bit of issue with posting to nodes that didn't have the unconfirmed transaction in their mempool yet).
