### ISSUE TITLE
Appear to have just had 1000 BCH rinsed using this thing.

### ISSUE THREAD

**Issue by tetsuobodyhammer** [fyookball/electrum#782]
Trying to transfer my BCH out of this 'wallet'. Knew i should have just waited for a bona fide solution. Copied the Kraken deposit address in, set fund limit, clicked 'Send'. Insert password, 'broadcasting transation', 'error: server failed to respond'. and now when i try again, 'insufficient funds'. 'unconfirmed transation' of 1000 BCH sitting there. How do i get this back, now? Or is kraken going to show this up in a matter of minutes / days / weeks? Anyone else had this issue with this 'electron cash wallet'? Still zero balance in Kraken. I thought from memory that this was instantaneous.

**Comment by cculianu** [comment]
Can you right-click the tx and click 'details', and paste the transaction ID here?

I suspect that the tx never made it to the network and you actually still have all your BCH.

Let me know!

**Comment by tetsuobodyhammer** [comment]
Hi, Thanks for replying. Kraken, of all people, have just replied to my support request with advisory to stand by. Issues with their 'system' again :( Appears the SNAFU has once again come from their side. My bad.

**Comment by cculianu** [comment]
LOL,. ok.  I don't blame you for freaking out. That's a considerable chunk of change there.

Best of luck!
