### ISSUE TITLE
AttributeError: 'ShuffleWidget' object has no attribute 'waiting_timout'

### ISSUE THREAD

**Issue by ProfessorVenkman** [fyookball/electrum#784]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/mnt/d/Upwork/electron_cash/electrum/plugins/shuffle/qt.py", line 112, in tick
    self.coinshuffle_timer_output.setText("{} s to break".format(self.waiting_timout))

AttributeError: 'ShuffleWidget' object has no attribute 'waiting_timout'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.2  | Linux-4.4.0-17134-Microsoft-x86_64-with-Ubuntu-16.04-xenial | standard | en_US |

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by rt121212121** [comment]
This code does not exist in the coinshuffle repo.
