### ISSUE TITLE
KeyboardInterrupt: 

### ISSUE THREAD

**Issue by ProfessorVenkman** [fyookball/electrum#785]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/home/alien/Electron Cash-3.3/gui/qt/__init__.py", line 71, in eventFilter
    def eventFilter(self, obj, event):

KeyboardInterrupt: 
```

Reporter
------------

This issue was reported by 1 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.3  | Linux-4.15.0-24-generic-x86_64-with-debian-stretch-sid | standard | en_US |

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by rt121212121** [comment]
Should this be hitting the exception reporting window in this case?  No.  Can I guarantee that there won't be a KeyboardInterrupt raised somewhere that we want to see via the exception reporting window? No.  Should be fine to ignore this, and there's no local handling in eventFilter or the functions it calls which can be done to catch it in a reasonable way.
