### ISSUE TITLE
 I lost the electroncash password. How to recover?

### ISSUE THREAD

**Issue by ealoe** [fyookball/electrum#79]
Next, I imported the private key into electron and waited for confirmation to receive the bcc. Around 4 am, the balance was available at electroncash, meanwhile I was waiting for the account verification at Kraken to be able to send them. I went to sleep and when I woke up to check the electroncash was "unconfirmed" again, and a "low fee". I did not do anything at all, I did not turn off the pc, nor did I close my wallet, because I do not remember the password I used to encrypt it. 

Address: 19hdyXZQVUNMrDFdRmj2tPnbFiS7euEfq9

**Comment by fyookball** [comment]
i cant help with lost pwd.
