### ISSUE TITLE
Electron Cash uses "electrum" Python package name

### ISSUE THREAD

**Issue by l29ah** [fyookball/electrum#8]
So it cannot be installed system-wide along with Electrum proper.

**Comment by fyookball** [comment]
I realized that might happen -- part of the reason we only released standalone exe not installation exe... but anyway, this would require some refactoring.  I will keep this issue open. thanks.

**Comment by hegjon** [comment]
I am the Fedora maintainer of the Electrum package [1], this issue makes it harder to include Electron Cash in the official Fedora repository.

[1] https://apps.fedoraproject.org/packages/electrum

**Comment by fyookball** [comment]
thanks @hegjon ...will prioritize.

**Comment by moreati** [comment]
How open would you be to a pull request that fixed this ticket? Do you have a particular preference for the new name (e.g. `from electron_cash import ...` vs `from electroncash import ...`) ?

**Comment by moreati** [comment]
@fyookball To repeat my offer: would you like a PR for this ticket? I'm happy to do it, but it's enough work I'd prefer some indication you're interested.

**Comment by fyookball** [comment]
yes please!

**Comment by hegjon** [comment]
I played with the RPM package for Fedora on master. I confirmation that the latest master does not have any conflicts with the Electrum RPM package.

**Comment by fyookball** [comment]
@hegjon excellent, thank you.
