### ISSUE TITLE
How do I solve this bug? 

### ISSUE THREAD

**Issue by ealoe** [fyookball/electrum#80]
Balance confirmed in the network but in the electroncash wallet does not confirm.

19hdyXZQVUNMrDFdRmj2tPnbFiS7euEfq9

**Comment by charleshsu168** [comment]
make sure you are running 2.9.2

**Comment by ealoe** [comment]
Yes, I'm using Electron Cash 2.9.2

**Comment by molecular** [comment]
You might be on the smallblock chain... try switching servers / branches (does it say "chain split detected" in Tools->Network?

If you are on the wrong chaing and nothing else helps, you can try stopping ECash and removing some stuff:

    #> cd ~/.electron-cash && rm -rf blockchain_headers forks recent_servers

(if on win/osx, just delete these files/folders from ElectronCash directory using explorer/finder)

then start again and see what happens.

**Comment by ealoe** [comment]
I can not stop Ecash because I lost the encryption password.

Status: Connected to 10 nodes.
Server: electrum.epicinet.net

**Comment by molecular** [comment]
Looks like you have a problem.

Without the encryption password, you can't sign a transaction afaik.

**Comment by ealoe** [comment]
https://blockchair.com/bitcoin-cash/address/19hdyXZQVUNMrDFdRmj2tPnbFiS7euEfq9

**Comment by charleshsu168** [comment]
you are on wrong network server. it should be electron. you are on electrum.

Status: Connected to 10 nodes.
Server: electrum.epicinet.net

**Comment by ealoe** [comment]
Dude that's right, now I just need to recover the password to transfer.
