### ISSUE TITLE
Cannot get Trezor to work

### ISSUE THREAD

**Issue by BCREAM** [fyookball/electrum#81]
I am using the latest version of TAILS (3.0.1), the latest Electron Cash (2.9.2), and the latest Trezor firmware (1.5.1).

I can see my balance, but whenever I hit send I get this error:

sign_tx() got an unexpected keyword argument 'lock_time'

Any ideas what could be wrong? Thanks!

**Comment by juriise** [comment]
I get the same, plus sometimes 

"Assignment not allowed (no field "amount" in protocol message object)."

also when signing

**Comment by fyookball** [comment]
related? https://github.com/fyookball/electrum/issues/63

**Comment by juriise** [comment]
I got that message too, earlier, but now it is only the "locktime", above

**Comment by molecular** [comment]
#63 was changed to #85 to reduce confusion. So this is probably #85.

**Comment by fyookball** [comment]
@molecular can this be closed

**Comment by molecular** [comment]
@fyookball yes it can be closed
@juriise please follow discussion in #85. Look where @BCREAM has the same problem and johoe tells him how to upgrade to python-trezor >= v0.7.13, which you'll need to do.

**Comment by molecular** [comment]
maybe relevant for people trying to run on tails (I'm running electron-cash on old version of tails): There's a lot of python-dependencies missing. The easiest way to get hold of these was to copy the `packages` folder from https://download.electrum.org/2.9.3/Electrum-2.9.3.tar.gz into the electron-cash source folder.
