### ISSUE TITLE
Why is it still 0.BCH

### ISSUE THREAD

**Issue by pkratitsbest** [fyookball/electrum#816]
I am new to bitcoin.
Basically, I have got a confirmation screenshot from the sender.

They said they sent to:
161Zw8W4R8Dk1XbedBB2hSjWg2KXqqbsib
Which is converted into:
bitcoincash:qqm0g8kx7m8fgz90s77adntxdn50xxmaqu4p39pxza
(Cash address)

But the number is still 0 in that account. Why?

**Comment by marceloneil** [comment]
It doesn't seem like any bitcoin cash has been sent to that address, although there is a balance of bitcoin: https://blockchair.com/bitcoin/address/161Zw8W4R8Dk1XbedBB2hSjWg2KXqqbsib

**Comment by rt121212121** [comment]
In future you can avoid this situation by giving your sender the cash address and they won't be able to send you anything but bitcoin cash.

**Comment by pkratitsbest** [comment]
Thank you.

So how to convert that into bitcoin cash?

**Comment by rt121212121** [comment]
Not really a topic that's easy to answer, or relevant here. 

If you don't have a friend you can ask, who would know, you could try going to a friendly bitcoin cash chat room and asking there and there will be many options: http://ambassador.cash
