### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'retain'

### ISSUE THREAD

**Issue by ProfessorVenkman** [fyookball/electrum#818]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/var/containers/Bundle/Application/43A44BB1-4EB1-4AC2-8EF5-BE1D098B0030/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app_packages/rubicon/objc/runtime.py", line 1065, in _objc_method
    result = f(py_self, *args)
  File "/private/var/containers/Bundle/Application/43A44BB1-4EB1-4AC2-8EF5-BE1D098B0030/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash_gui/ios_native/txdetail.py", line 688, in onCpyBut_
    utils.boilerplate.vc_highlight_button_then_do(self, but, lambda:gui.ElectrumGui.gui.copy_to_clipboard(entry.tx_hash))
  File "/private/var/containers/Bundle/Application/43A44BB1-4EB1-4AC2-8EF5-BE1D098B0030/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash_gui/ios_native/utils.py", line 1651, in vc_highlight_button_then_do
    but.retain()

AttributeError: 'NoneType' object has no attribute 'retain'
```

Reporter
------------

This issue was reported by 4 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.3 (iOS Build: 301)  | Darwin-17.7.0-iPhone10,6-64bit iOS 11.4.1 iPhone (35F676B2-A236-4E48-8FEB-198E738BDF59) | imported_addr | en_UK |
| 3.3 (iOS Build: 301)  | Darwin-17.7.0-iPhone9,3-64bit iOS 11.4.1 iPhone (910580E6-8642-4280-B083-FFF579BB51A4) | imported_addr | en_UK |
| 3.3 (iOS Build: 301)  | Darwin-17.7.0-iPhone10,6-64bit iOS 11.4.1 iPhone (35F676B2-A236-4E48-8FEB-198E738BDF59) | imported_addr | en_UK |
| 3.3 (iOS Build: 301)  | Darwin-17.7.0-iPhone10,6-64bit iOS 11.4.1 iPhone (35F676B2-A236-4E48-8FEB-198E738BDF59) | imported_addr | en_UK |

Additional Information
------------------------

> Traceback (most recent call last):
>   File "_ctypes/callbacks.c", line 234, in 'calling callback function'
>   File "/var/containers/Bundle/Application/43A44BB1-4EB1-4AC2-8EF5-BE1D098B0030/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app_packages/rubicon/objc/runtime.py", line 1065, in _objc_method
>     result = f(py_self, *args)
>   File "/private/var/containers/Bundle/Application/43A44BB1-4EB1-4AC2-8EF5-BE1D098B0030/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash_gui/ios_native/txdetail.py", line 688, in onCpyBut_
>     utils.boilerplate.vc_highlight_button_then_do(self, but, lambda:gui.ElectrumGui.gui.copy_to_clipboard(entry.tx_hash))
>   File "/private/var/containers/Bundle/Application/43A44BB1-4EB1-4AC2-8EF5-BE1D098B0030/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash_gui/ios_native/utils.py", line 1651, in vc_highlight_button_then_do
>     but.retain()
> AttributeError: 'NoneType' object has no attribute 'retain'
> 
> Additional information
> 	•	Electron Cash version: 3.3 (iOS Build: 301)
> 	•	Python version: 3.5.5+ (default, Feb 21 2018, 15:57:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
> 	•	Operating system: Darwin-17.7.0-iPhone10,6-64bit iOS 11.4.1 iPhone (35F676B2-A236-4E48-8FEB-198E738BDF59)
> 	•	Wallet type: imported_addr
> 	•	Locale: en_UK

---

> Can you release my money please

---

**Comment by marceloneil** [comment]
>Can you release my money please

:cry:

**Comment by cculianu** [comment]
LOL I hope he's just trolling.. ha ha
