### ISSUE TITLE
trezor base wallets

### ISSUE THREAD

**Issue by juriise** [fyookball/electrum#82]
With the trezor it is possible to have no password (the password being an extension of the seed). We can call it the base wallet. (and there is also a mode without password you can choose when you initialize the trezor).

If I create a trezor-wallet in electron cash, I can not get past the "password" entry unless I input something. So I can not use the base wallet in electron cash. I don't remember if this was also a problem in electrum.

**Comment by fyookball** [comment]
this might help https://www.reddit.com/r/btc/comments/6s15m8/electron_cash_and_trezor/
