### ISSUE TITLE
electron cash issue

### ISSUE THREAD

**Issue by opustopus** [fyookball/electrum#820]
Hi, yesterday morning my boss sent me a bitcoin cash payment and i have´t recieved it yet and . Can someone help?

Thanks,
Silvio.

**Comment by fyookball** [comment]
ask for the transaction id or the link to the transaction on a block explorer

**Comment by opustopus** [comment]
https://blockchair.com/bitcoin-cash/address/qpm2pu0lzresgsapvycmnpfux896cgl83grlz90p09

**Comment by fyookball** [comment]
is your address in the list of outputs ? (you may need to click more rows to see it).
