### ISSUE TITLE
electron cash has non-existent opcode 'OP_SINGLEBYTE_END'

### ISSUE THREAD

**Issue by markblundeberg** [fyookball/electrum#828]
See address.py line 64, also referred to in transaction.py

This opcode was [taken out of bitcoin in 2010](https://gitorious.org/bitcoin/bitcoind/commit/f1e1fb4bdef878c8fc1564fa418d44e7541a7e83?p=bitcoin:bitcoind.git;a=blobdiff;f=script.h;h=c829ed053ea6793b93dff2f733ab38288fa00f74;hp=20d29312bd995616a0ce30426a9f04b4be596a7c;hb=f1e1fb4bdef878c8fc1564fa418d44e7541a7e83;hpb=d743f0355269e2e03fe3f982e250d07999d72b98).

**Comment by cculianu** [comment]
Yeah but for old tx's it's still needed to decode/view them, no?

**Comment by markblundeberg** [comment]
My understanding is that it never got used. Actually there is a funny story with Electrum servers and this opcode, that even includes an Electrum patch posted on blockchain, supposedly from satoshi himself. https://bitcointalk.org/index.php?topic=271761

Weird huh

**Comment by cculianu** [comment]
Oh wow.. fascinating thread. The actual broken code they paste in from electrum is this very same code we just discussed in #829!!

I’m astounded this has stayed in electrum/electron cash all this time!

I’m going to go ahead and close this issue as I don’t believe keeping the historical opcode in there as a reference is bad necessarily — and other code in the project does use this constant as a boundary for determining invalid/valid opcodes.

If you really want this removed tell me and we can reopen.. but the issue was that buggy #829 really rather than this historical constant in the code....

**Comment by markblundeberg** [comment]
I was wondering why you closed this and I just realized I very poorly explained myself. You're right, it's no problem to have the nonexistent opcode given a name. :-)

Really I intended to draw attention to the usage of OP_SINGLEBYTE_END within script_GetOp() in transaction.py -- the same function discussed in the other issue. As pointed out by the supposed satoshi, OP_SINGLEBYTE_END should not be used in script_GetOp().

Consider if you had the following script: `0 OP_IF OP_SINGLEBYTE_END OP_ELSE 1 OP_ENDIF`. Even though OP_SINGLEBYTE_END is in the 'unexecuted' branch, the combination of 0xf0 then OP_ELSE (0x67) would be misinterpreted as being a 2-byte opcode number 0xf067 = 61543.

I'm not sure whether it's possible to include 0xf0 even in an unexecuted branch, so an example of this may or may not be possible on blockchain.

**Comment by cculianu** [comment]
Hmm.  I don't know if it can be included in an unexecuted branch either.  But I can't believe my brainfart.  You're right.  Interpreting the op_code will lead to garbling of the script.  And I took a look at ElectrumX and it doesn't interpret this.

Sorry.  I just wanted you to explain to me what's going on is all.  Thanks so much.  I am re-opening and will adapt ElectrumX's code to this.

**Comment by cculianu** [comment]
Ok. I got rid of it in my PR #842 .

Thanks so much for bringing this up.  In retrospect I am a little embarrassed I didn't realize what you were saying. It was staring me in the face, really. Thanks for being persistent. :)

**Comment by cculianu** [comment]
Ok, PR #842 merged.  Closing.

**Comment by markblundeberg** [comment]
Heh no worries, we got there in the end. :-)
