### ISSUE TITLE
derivation path for trezor wallets

### ISSUE THREAD

**Issue by juriise** [fyookball/electrum#83]
posted also on reddit

When I create a trezor wallet, the suggested bip44 key derivation path is

m/44'/0'/0'

but it needs to be

m/44'/145'/0'

With that path it produces the same addresses as the beta-wallet.trezor.io produces. It should be the default for trezor wallets. (Should be quality checked, because I don't have a deep understanding of it).

There is a dialog box with the path, with a comment saying "if you don't understand it, don't change it". But I had to, to get the right addresses (the same as beta-wallet.trezor.io uses). This is when you choose standard wallet/hardware wallet in wallet creation. 

Edit: Somewhere on the web someone suggested 44'/145' but with that path, the wallet creation just hangs. Does it have something to do with multi "accounts" that electrum never supported anyway?

**Comment by BCREAM** [comment]
I believe this is only an issue if you have used Trezor's bitcoin cash splitter/claiming tool. However, many people, including myself, choose not to use their web wallet as there is no way to connect to it via Tor. In order for these people to claim their bitcoin cash, they need to use the default derivation path to access their coins.

Maybe we can show both paths and let the user choose which path they want. Maybe something like:
o Default path - XXXXX
o Path if you have used Trezor's splitting tool - XXXXX

This might make things more complicated than they already are though. I have no idea what the percentages are of people that will claim their bitcoin cash using Trezor's splitting tool vs people who will just use Electron Cash. That percentage should be what ultimately determines the default path imo.

**Comment by fyookball** [comment]
i think this is might be outside the scope of what are planning in the immediate future with electron.  When other HD multi coin wallets like jaxx start implementing bip39 with coin_type 145 for Bitcoin Cash, we'll probably want to support importing that way too, and then we can revisit the trezor issue relating to this.  

I'm going to close this for now.  I do not own a trezor so my understanding is limited here.  Im someone wants to provide more information i'll have a look.

**Comment by juriise** [comment]
Sure, by doing it that way you essentially do what trezors "claim" function does. But I suppose people are interested in seeing and using their wallets on the trezor io website and in electron cash at the same time, anyway that is what I have done with electrum and trezor for a few years.

But no problem, it is only a choice of default, I can manage.
