### ISSUE TITLE
Need new EC development chat outside bchchat

### ISSUE THREAD

**Issue by rt121212121** [fyookball/electrum#835]
@fyookball @marceloneil @kyuupichan  @cculianu 

Let's not go into the details here in this issue, because it just serves to attract parasites.

I'd prefer a slack, and not a telegram.  How about a channel in freetrader's btcforks slack?  But we need something outside of bchchat.

**Comment by fyookball** [comment]
i will create a new slack

**Comment by fyookball** [comment]
https://join.slack.com/t/electroncash/shared_invite/enQtNDI0Mjk2MDE0MjQ3LTRkZGE0NDJlZTEwZjVlNDNhYTQ1ZTI1YjI0YTZlYjdiM2JmZTFmNTdlYjRmNGRmODM1MDdhMzkyZDdlNTNkMWU

**Comment by fyookball** [comment]
@marceloneil can you please invite Malcom , Bauerj, and Ghost

**Comment by cculianu** [comment]
Can you invite me too?  calin.culianu@gmail.com

**Comment by fyookball** [comment]
use the link @cculianu

**Comment by cculianu** [comment]
I did.  It said it doesn't know who I am and to get lost because it thinks
I may be suspect.

**Comment by cculianu** [comment]
Nevermind.  I tried it again and it worked now.  Bizarre.

Ok I'm in! Thanks!

**Comment by marceloneil** [comment]
@bauerj @sombernight @mhsmith

Also @alexander255 if you'd like to join we'd love to have you, but if you still have reservations I understand. Maybe we can create an irc-bridge channel or something if you'd be interested in that
