### ISSUE TITLE
Address dialog missing public key, for "Imported Private Key" wallet

### ISSUE THREAD

**Issue by markblundeberg** [fyookball/electrum#836]
Example screenshot below. Normally below 'Address:' there is a 'Pubkey:' field.

I can see in address_dialog.py that if grabbing the pubkey throws any exceptions, it just fails silently and omits the field:
https://github.com/fyookball/electrum/blob/master/gui/qt/address_dialog.py#L64

(If you like I can look into this some more and PR a fix)

![screenshot from 2018-08-26 16-46-57](https://user-images.githubusercontent.com/36528214/44634526-e8520500-a94f-11e8-89ca-c742f6c635d7.png)

**Comment by cculianu** [comment]
Ok yeah.  This was just a bug in the code. For some reason it neglected to think about imported wallets.  This PR addresses the issue.

**Comment by cculianu** [comment]
Fixed.
