### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.sip'

### ISSUE THREAD

**Issue by mschoenebeck** [fyookball/electrum#850]
Fresh Ubuntu 18.04 install...
Fresh electron-cash checkout and build...
Trying to start app throws this error:

> Traceback (most recent call last):
>   File "./electron-cash", line 391, in <module>
>     d.init_gui(config, plugins)
>   File "/home/mschoenebeck/dev/crypto/bch/Electron Cash-3.3.1/lib/daemon.py", line 303, in init_gui
>     gui = __import__('electroncash_gui.' + gui_name, fromlist=['electroncash_gui'])
>   File "/home/mschoenebeck/dev/crypto/bch/Electron Cash-3.3.1/gui/qt/__init__.py", line 36, in <module>
>     from PyQt5.QtGui import *
> ModuleNotFoundError: No module named 'PyQt5.sip'

Why? Do I really need to downgrade my system again to run electron anymore?

**Comment by cculianu** [comment]
Do you have PyQt5 installed?  pip install pyqt5?  Or apt-get pyqt5?

**Comment by mschoenebeck** [comment]
Hey! Thanks for your help. And sorry for late reply..
I have:
python3-pyqt5 is already the newest version (5.10.1+dfsg-1ubuntu2).
Since electron uses python3 that's correct, right?

**Comment by cculianu** [comment]
Hmm.. yeah that's all correct.  Let me see if I can reproduce this...

**Comment by cculianu** [comment]
Hmm.  Can you try pip3 install PyQt5-sip?  Maybe that'll do it..

**Comment by mschoenebeck** [comment]
I installed the missing package.

```
pip3 install PyQt5-sip
Collecting PyQt5-sip
  Downloading https://files.pythonhosted.org/packages/d7/db/06ad1f62a1f80a5df639c322066f03db381c1a6322c02087e75092427838/PyQt5_sip-4.19.12-cp36-cp36m-manylinux1_x86_64.whl (66kB)
    100% |████████████████████████████████| 71kB 1.1MB/s 
Installing collected packages: PyQt5-sip
Successfully installed PyQt5-sip-4.19.12
```
But the problem persists. Do I need to reference the package somehow? All these different python versions and pip-stuff really confuses me..

```

./electron-cash 
Traceback (most recent call last):
  File "./electron-cash", line 391, in <module>
    d.init_gui(config, plugins)
  File "/home/mschoenebeck/dev/crypto/bch/Electron Cash-3.3.1/lib/daemon.py", line 303, in init_gui
    gui = __import__('electroncash_gui.' + gui_name, fromlist=['electroncash_gui'])
  File "/home/mschoenebeck/dev/crypto/bch/Electron Cash-3.3.1/gui/qt/__init__.py", line 36, in <module>
    from PyQt5.QtGui import *
ModuleNotFoundError: No module named 'PyQt5.sip'
```

**Comment by cculianu** [comment]
Honestly I have no idea.  It should "just work".  I don't have Ubuntu 18.  I am on 17.  It works here.

I'm really sorry this is not working.  Perhaps someone else that actually uses Linux daily can chime in (I used to be a Linux geek but I've moved onto macOS these days).

You can maybe try the linux flat pack: https://github.com/fyookball/electrum/issues/825

**Comment by mschoenebeck** [comment]
Thank you very much. I'm also very confused and a little disappointed from Ubuntu 18.04. I always wait some time until I switch to new LTS because of stuff like this.

I will try further and let you guys know! Thanks again.

**Comment by cculianu** [comment]
FYI I just upgraded to Ubuntu 18.04 and it still works fine.

I am not sure what the issue is for you.  

In case you were wondering, here is a list of all the python 3.6.5 module I have installed (listed via pip3 list).  I hope you have PyQt5 in there...!

[python365_modules.txt](https://github.com/fyookball/electrum/files/2377043/python365_modules.txt)

**Comment by eqjjh** [comment]
Same error for me. Using Mint 19, based off Ubuntu 18.04. The same error appears to be mentioned here:
https://aur.archlinux.org/packages/electron-cash/
I tried running those 2 lines
```
sudo pip3 uninstall PyQt5_sip
pip3 install --user PyQt5_sip
```
but it still does not work.

**Comment by cculianu** [comment]
what happens if you blow away (or rename) ~/.local, then reinstall the dependencies for electron cash?

**Comment by cculianu** [comment]
I am confused too!  And yes, I don't have SIP installed.. and it just works.

Hmm.  I noticed you have Electron Cash installed!  Maybe that's conflicting with running from source?  I had problems with that in the past!

Try: 

`pip3 uninstall Electron-Cash`

**Comment by mschoenebeck** [comment]
> what happens if you blow away (or rename) ~/.local, then reinstall the dependencies for electron cash?

I renamed the ".local" folder but it didn't have any effect.

**Comment by cculianu** [comment]
Also try it as root too: sudo -H pip3 uninstall Electron-Cash

**Comment by mschoenebeck** [comment]
I removed Electron-Cash with `sudo -H pip3 uninstall Electron-Cash` and it did work.
However, the problem persists. Just to let you know: I built all Electrum clients from source (BTC, BCH, DASH, LTC) and all worked well on Ubuntu 16.04. I recently made the upgrade to 18.04 and from that point in time I have this "sip"-module error. So I never had trouble with electrum clients being installed all together on one machine.

**Comment by cculianu** [comment]
Yeah sorry about that.  I really don't know what's going on there.

**Comment by afduggirala** [comment]
I only have one version of Electron Cash installed. I installed it via python3 setup.py install. I do however have Electrum installed as well. Is it possible that the Electrum installation is conflicting?
thanks,

**Comment by emergent-reasons** [comment]
I am on Mint 19. For what it's worth, I had some odd QT errors on Mint 18.1 after installing electron cash. Since then I always avoid installing. I just untar and run from `./electron-cash` or `./run_electrum`. It seems likely that Electrum and Electron installations could have silent naming conflicts if they are installed.

Some relevant `pip freeze` content from me (I think the same as yours):
```
PyQt5==5.11.2
PyQt5-sip==4.19.12
```
I never had to explicitly install `PyQt5-sip`. Something else did that.

Some packages that I have installed through apt rather than pip:
```
pyqt5-dev-tools
python3-pyqt5
```

If you are familiar with environment management systems, you could try setting up a new environment to avoid conflicts with requirements for other systems. If you don't know how, I could walk you through it if you ping me on the Electron-Cash slack.

**Comment by emergent-reasons** [comment]
I made a fresh python 3.7 environment with only ipython and requirements installed.

from `~/Electron Cash-3.4.1/` (same behavior on version 3.3.1)

- `./electron-cash`
    - `Error: Could not import PyQt5 on Linux systems, you may try 'sudo apt-get install python3-pyqt5'`
- `pip install pyqt5`
    - You may need `sudo` if you are installing on the OS python.
    - That installs both `PyQt5-sip-4.19.12` and `pyqt5-5.11.2`.
    - If you have problems with that, maybe try:
        - `sudo apt-get install pyqt5-dev-tools python3-pyqt5`
        - `pip install --upgrade pyqt5`
- `./electron-cash`
    - Works for me!
    - Note: If you want to use hardware wallets, there are some additional non-obvious installations you need to do.

Again based on my experience, I recommend not using `setup.py install`, especially if you are going to use both Electron and Electrum.
