### ISSUE TITLE
bizarre public key decompression

### ISSUE THREAD

**Issue by markblundeberg** [fyookball/electrum#852]
I was reading through the ECC code and noticed the bizarre function ECC_YfromX in bitcoin.py, which has a nonsensical loop. Also noticed by these folks:

https://bitcointalk.org/index.php?topic=2553307.0

In Electrum the function is now in ecc.py but still has the same content.

In short: if you feed it an *x* value that is not associated with any points on curve, it iterates up to 128 times trying to find another nearby *x* value that does go on curve. This doesn't make much sense because then you end up decompressing another key. o_O In fact there should be no for-loop at all.

It looks like it doesn't really affect anything since it only gets used in encrypt_message/decrypt_message (where the result is checked) and in bip32 derivation (maybe someone can feed you a bad xpub and it won't be detected properly ... their loss I guess).

**Comment by cculianu** [comment]
This is likely wrong. You mentioned one slack you were up for doing a PR. If so, go for it.

I’m going to post over at Electrum about this.

**Comment by fyookball** [comment]
@markblundeberg interesting... perhaps you should also take a look at how i implemented that in java as it seemed bizarre at the time too as far as finding how to implement that function from existing libraries.  The java version may be inefficient.

**Comment by cculianu** [comment]
@markblundeberg See this reply from the Electrum dudes: https://github.com/spesmilo/electrum/issues/4717#issuecomment-421370834

I don't understand what's going on.  See if it's "harmless" for us too.

If you do issue a PR make sure that calling code wasn't assuming this "bad behavior" would be a valid way to detect a bad key... :)

**Comment by markblundeberg** [comment]
Yes, that's correct, in electrum code the `_ser_to_python_ecdsa_point` will correctly raise exception for bad inputs since the Point constructor always checks if the point is on curve. In the case of electron cash, we actually have a redundant additional check in `encrypt_message` since `ser_to_point` uses the Point constructor.

**Comment by markblundeberg** [comment]
Well as it's harmless, I'll postpone making a PR since I'm a bit nervous about modifying crypto code. Hopefully though one day EC will get a libsecp256k1 integration working as well!

**Comment by cculianu** [comment]
@markblundeberg that would be cool, libsecp256k1 integration.  It wouldn't be too hard, actually, to create a python binding for it.  It would complicate building for some people/platforms though.

I would love for this to happen sooner rather than later. I'm a C/C++ hacker at heard to binding to a native lib is sexy.

The only thing, like I said, that makes me nervous is that it makes electron cash harder to build.  But we can bundle compiled libs for x86_64 for macOS, Windows, and Linux.  It's just the "other" platforms (BSD, other arch's, etc) that may suffer.

**Comment by markblundeberg** [comment]
@cculianu Electrum has an optional libsecp256k1 integration (i.e., uses if installed, otherwise falls back to pure python ecdsa). Seems like quite the hack though, as it runs some monkey patching on the ecdsa module. https://github.com/spesmilo/electrum/blob/master/electrum/ecc_fast.py

**Comment by cculianu** [comment]
Oh wow! I love it!  This is something like what i had in mind (call into ctypes).  Pretty neat that they already did it.

Hmmm.. I'm tempted to bring this into our codebase.. muahaha. 

Thanks for the heads-up!
