### ISSUE TITLE
Error sendind BCC

### ISSUE THREAD

**Issue by cryptoforex** [fyookball/electrum#87]
Appears this error when I try to send BCC to a BCC address.
Thanks.

![image](https://user-images.githubusercontent.com/30776743/29004971-ad7c4c68-7ad1-11e7-98a9-2ae94eee7b8f.png)

**Comment by simonhughes22** [comment]
Same problem. I am making sure eletroncash.cashcaria.com is the selected server.

**Comment by fyookball** [comment]
is this normal txl or 2fa, ms, etc

**Comment by cryptoforex** [comment]
Normal

**Comment by simonhughes22** [comment]
2fa for me

**Comment by cryptoforex** [comment]
Sorry I checked now is 2fa mine also.

**Comment by simonhughes22** [comment]
I am trying to run from source on Mac OSX Sierra but cannot install. It runs fine for me from the installer, but then I get the error when trying to send BCC. I have made sure it's hitting the correct server for BCC.

**Comment by helloluis** [comment]
I have the same issue right now. Im just making a very normal transaction, no 2FA.

**Comment by helloluis** [comment]
I was able to get it working by restarting my Electron Cash client (on Windows)

**Comment by fyookball** [comment]
please read the f2a workaround issue thread.

**Comment by cryptoforex** [comment]
I read the threat I followed the steps and my bcc don't appears in the balance of the new wallets restored from seed without 2fa.
Thanks.

**Comment by cryptoforex** [comment]
Ok Finally solved. Thanks.
