### ISSUE TITLE
Electrum and ElectronCash both on Ubuntu

### ISSUE THREAD

**Issue by CURcoin** [fyookball/electrum#88]
I have already installed Electrum wallet. 
I setup Electron Cash.
After this I got a problem when running Electrum wallet, it runs Install Wizard of Electron Cash instead of Electrum.

How to fix this?
Thank you!

**Comment by fyookball** [comment]
i dont know what commands you are running.  you should do python electron-cash from inside the folder you downlaoded, which should be unique.  dont try to combine electrum and electron in the same root folder

**Comment by CURcoin** [comment]
Electron runs correctly, but electrum - not. I see, that both wallets installed in separate folders, and have separate wallet files.

**Comment by CURcoin** [comment]
I just remove electrum and electron-cash and reinstall electrum. It runs correctly...

than I put this command to install electron cash from the unpacked and renamed to "electron-cash" folder of 2.9.2 version.

> user@Builder:~/Downloads/electron-cash$ python setup.py install
> running install
> error: can't create or remove files in install directory
> 
> The following error occurred while trying to add or remove files in the
> installation directory:
> 
>     [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-28716.write-test'
> 
> The installation directory you specified (via --install-dir, --prefix, or
> the distutils default setting) was:
> 
>     /usr/local/lib/python2.7/dist-packages/
> 
> Perhaps your account does not have write access to this directory?  If the
> installation directory is a system-owned directory, you may need to sign in
> as the administrator or "root" account.  If you do not have administrative
> access to this machine, you may wish to choose a different installation
> directory, preferably one that is listed in your PYTHONPATH environment
> variable.
> 
> For information on other options, you may wish to consult the
> documentation at:
> 
>   https://setuptools.readthedocs.io/en/latest/easy_install.html
> 
> Please make the appropriate changes for your system and try again.

Thank you for your work and answer!!

**Comment by fyookball** [comment]
use sudo

sudo python setup.py install

**Comment by CURcoin** [comment]
Thank you!

sudo python setup.py install
Works good for installation

and
python electron-cash
for start program

Best wishes!
