### ISSUE TITLE
Remove a transaction from Electron-Cash

### ISSUE THREAD

**Issue by shawnpringle** [fyookball/electrum#89]
How do I remove a transaction from Electron-Cash?

**Comment by fyookball** [comment]
"remove"? what u mean

**Comment by shawnpringle** [comment]
Electron-cash stores transactions that were valid over the BTC network and not from BCC.   I wanted to mark this transaction non-existent for it only existed in my electron-cash wallet.

Whereas, I had sent all of my bitcions only and never sent bitcoin cash, when I opened it up, when I finally got electron-cash working, it said that there was a transaction that was waiting for confirmation (which was from the BTC network).   I think Electron-cash should restore from seed and throw away all of the BTC data when it imports a BTC wallet.

There is no way to remove a transaction already sent from the wallet (even when though it was BTC) I don't think they should even be there in the first place.
