### ISSUE TITLE
Lost my BCC

### ISSUE THREAD

**Issue by adsactly** [fyookball/electrum#9]
![major bcc glitch](https://user-images.githubusercontent.com/6323112/28877021-19a60eea-7769-11e7-9886-2dd7d8457fea.jpg)

As you can see we imported the private key to our Electron Cash Wallet. Now our Balance is zero it looks like there was a chain split perhaps its possible for us to switch to that chain to move the 1.81 BCC that are stuck on the wrong chain.

**Comment by bauerj** [comment]
You probably tried to send that on the wrong chain.

Click on the green circle in the lower right hand corner and disable automatic selection. Select a server on the "651ef99cb9@478559" branch, right click and select "Use as server".

The transaction should disappear from your history once you switched the server.

**Comment by adsactly** [comment]
yeah tried that and it didn't fix the problem guess we lost our 1.81 BCC

**Comment by Otaci** [comment]
Please can you post a screenshot of your Network tab?

**Comment by adsactly** [comment]
Looks like everything fixed it self!
