### ISSUE TITLE
Transfer BCC from ELECTRUM to ELECTRON CASH wallet

### ISSUE THREAD

**Issue by taiping194** [fyookball/electrum#91]
On August 7 I tried to claim my BCC from my Electrum "Windows Installer" wallet on PC #1.
1. Installed new Electrum "Portable" wallet on PC #1.
2. Sent all BCC from Electrum Windows Installer wallet to Electrum Portable wallet.
3. Waited for at least 6 confirmations. Electrum Windows Installer wallet shows Zero BTC. Electrum Portable wallet shows correct amount of BTC with 6 confirmations.
4. Installed Electron Cash 2.9.2 wallet (download from official site) on different PC #2.
5. Imported Seed to Electron Cash wallet from Electrum Windows Installer wallet.
6. Electron Cash wallet shows correct amount of BCC. Hallelujah, but . . .

However, I then closed the Electron Cash wallet and opened it again.
Now, it shows 2 more transactions as follows:
"Unconfirmed parent" which shows nearly all BCC sent back to the receiving address on the Electrum Portable wallet, and before that an "Unconfirmed" entry of a small amount of BCC (as transfer fee?).
Therefore, allthough the above 2 transactions have zero confirmations, the Balance in the Electron Cash wallet shows "x" BCC (-y BCC unconfirmed).

I did not send any BCC to anyone, let alone back to my address.
All I did was close the Electron Cash wallet and open it again.

What do I do now (if anything) to obtain the full amount of BCC in my Electron Cash wallet?

Thank you.

**Comment by fyookball** [comment]
can you confirm  youre connected to a bCC server

**Comment by taiping194** [comment]
Hi fyookball -- I left the Electron Cash wallet as automatic, because I assumed this wallet would only be using BCC supported servers. However, I disabled the automatic server and chose a BCC server called electroncash.cashalia.com and now the 2 extra transactions have gone and the BCC balance is correct.
Thank you very much, but why does the Electron Cash wallet have servers which don't seem to be operating correctly?

**Comment by fyookball** [comment]
if you downloaded from 2.9.0 at any point the wrong headers were there.  even if 2.9.2 was used theres still a fix we should do to verify headers.

**Comment by taiping194** [comment]
Please fix the problem -- non-techies like me would appreciate it.

**Comment by wujie234** [comment]
Hi taiping194, it seems like I had similar issues like you did. Non-tech like me can not even find where can i set the server...can you please kindly tell me where can i find the server setting..... thank you thank you.

**Comment by fyookball** [comment]
bottom right corner of the client there is a green or orange or red circle

**Comment by wujie234** [comment]
I tried...My coin didn't show up... :(( I had a situation that BCC showed up but with error like unconfirm parent... two line of history. Then next day two lines are disappeared but coins are not showing up...

**Comment by fyookball** [comment]
which server are you connected to and which address are we talking about

**Comment by taiping194** [comment]
wujie234 - Click on the (normally) green button on the bottom right corner. On the Newtwork window which pops up, on the Overview tab uncheck the box "Select sever automatically." Click on the Server tab and select a server which applies to BCC. Some of these are just numbers, but I found one (can't remember the exact name now) which had something like "bitcoincash" in the name, Then close and reopen the Electron Cash wallet. Worked for me.

**Comment by NoobNeedsHelp** [comment]
![electron 1](https://user-images.githubusercontent.com/30870139/29137761-6e34a70e-7d0f-11e7-808e-f23c7109996e.PNG)
![electron 2](https://user-images.githubusercontent.com/30870139/29137766-70e6f6aa-7d0f-11e7-89c4-fe7d984588dd.PNG)
