### ISSUE TITLE
canot tranfer BCC

### ISSUE THREAD

**Issue by phatty20** [fyookball/electrum#92]
I already updated latest version but it cannot do transection transfer BCC to bittrex and liqui. It has this message come up. what it mean?
![prtscn](https://user-images.githubusercontent.com/30746572/29011060-96c462e4-7b62-11e7-9e41-b0d59ec2b6e0.jpg)

**Comment by fyookball** [comment]
you're using a 2fa wallet. please see issue thread on 2fa

**Comment by phatty20** [comment]
yes. I always use 2fa

**Comment by phatty20** [comment]
yes , I always use 2fa

**Comment by fyookball** [comment]
we dont support 2fa. see workarounds

**Comment by phatty20** [comment]
so, I need to cancel 2fe in electron wallet first right? and then copy the seed to open new in electroncash?

**Comment by fyookball** [comment]
I think so.  for further support, post here #41

**Comment by phatty20** [comment]
how to cancel 2fe in electron wallet? I can not find it

**Comment by phatty20** [comment]
cannot disable 2fe in electron wallet. it's so bad. Electroncash must
update support 2fe wallet.
