### ISSUE TITLE
Syncronization of Electrum Win64

### ISSUE THREAD

**Issue by Boyarov** [fyookball/electrum#94]
I tried first private key with only one transaction before fork, and got BCH very quickly.

Then I added second private key with 80k+ transactions and used long time. More then five days app. syncronizing and still not done. I don't understand which block sycronizing now or how many hours left. Just see slow software network activity on control panel.
1) Where I can see progress? or how can I understand when sync finish?
2) Why first wallet synced very fast? This one transaction was in lasts block.

Thanks

**Comment by fyookball** [comment]
i dont know
