### ISSUE TITLE
Trezor error message when sending from address.

### ISSUE THREAD

**Issue by Windowly** [fyookball/electrum#96]
I get this error message when trying to send BCC from a address on my Trezor (signing with my Trezor).(I'm trying to split my coins.)

I keep on getting this error -- 'NoneType' object has no attribute 'update_status'

**Comment by molecular** [comment]
are you running from source of binary?

**Comment by Windowly** [comment]
Binary

**Comment by molecular** [comment]
plese try 2.9.3 (just out) and report back if you still have the issue

**Comment by Windowly** [comment]
Still the same issue :(

**Comment by molecular** [comment]
The error ('NoneType' object has no attribute 'update_status') points to old python-trezor being used if I recall correctly, but I don't understand how that's possible when using binary. Any ideas?
