### ISSUE TITLE
1st time BCC successfully loaded, 2nd time BCC went missing... Please help! Thank you.

### ISSUE THREAD

**Issue by wujie234** [fyookball/electrum#97]
In order to explain the issues clearly, I would like to explain the whole process i went. (before Aug 1st, I stored btc in Mycelium and paper wallet)
1st time testing electroncash wallet: BCC successful
- Mycelium sent btc to bittrex
- Mycelium seed to restore in electrum (I thought electrum has bcc at the beginning.. then realize I was wrong)
- Mycelium seeds to restore in electroncash, successfully saw same amount of the bcc as the btc 

2nd time: BCC showed up then went missing...
- Paperwallet via blockchain.info send all fund to Mycelium 
- Mycelium send btc to Ledger
- Mycelium seed to restore in electroncash **(HERE STARTED ISSUE)**
  1. firstly the BCC fund didn't showup in electroncash account immediately 
  2. I waited several hours (went sleep and get up) then I happily saw **BCC showed up** in electroncash but somehow showing "Not parenting" or "not patenting" in red. I thought it might be the network slow issue. So I went sleep again.
   3. I waited one more day, log in again... the 2nd time try **BCC disappeared...** It only shows the 1st time testing history. The 2nd time "Not parenting"BCC history two lines are even disappeared. 
I am scared now... Can any one help me with that? Thanks a lot!!!

**Comment by fyookball** [comment]
every time this issue comes up it seems to be that the person isnt connected to the right server

**Comment by wujie234** [comment]
Hi fyookball, if I am not connecting to the right server, what can I do? Can you please give me some advice?   Thank you!
