### ISSUE TITLE
unable to run executable

### ISSUE THREAD

**Issue by bymaximus** [fyookball/electrum#99]
Im getting a windows error  message when trying to run the electrum exe.

![e__electron-cash-2 9 2 exe 2017-08-08 13 10 02](https://user-images.githubusercontent.com/595991/29082123-fe19aaca-7c3a-11e7-8718-16a74cd92349.png)

translated message:
Windows can not access the specified device, path, or file. You may not have the appropriate permissions to access the item.

Already using 'run as administrator', any way to see any log?

**Comment by fyookball** [comment]
is it anti virus blocking it?

**Comment by bymaximus** [comment]
no, tried with it disabled also, any way to enable logs?

**Comment by fyookball** [comment]
I would need to rebuild the binary with logging.  I am travelling but can do that on Friday.  What version of windows is this?  Have you tried running from source?

**Comment by bymaximus** [comment]
windows 10 enterprise, 
yes tried to run from sources, stopped in the step 'python setup.py install', didnt understand how to run it from sources at windows

**Comment by fyookball** [comment]
python setup.py install 

and then

python electron-cash

**Comment by bymaximus** [comment]
C:\Users\felipe\Downloads\Electron-Cash-2.9.2\Electron Cash-2.9.2>C:\Users\felipe\.windows-build-tools\python27\python.exe electron-cash
Error: Could not import PyQt4 on Linux systems, you may try 'sudo apt-get install python-qt4'

**Comment by casper** [comment]
You can download PyQt4 from here:    
http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.1/PyQt4-4.11.1-gpl-Py2.7-Qt4.8.6-x32.exe

The sources for any other needed Windows packages are listed at the top of the file here:   
https://github.com/fyookball/electrum/blob/cash/contrib/build-wine/prepare-wine.sh

**Comment by fyookball** [comment]
Electrum*

**Comment by bymaximus** [comment]
as you can see, i was inside electrum folder, C:\Users\felipe\Downloads\Electron-Cash-2.9.2\Electron Cash-2.9.2>

**Comment by molecular** [comment]
can you right-click the .exe file and look at the permissions?

**Comment by bymaximus** [comment]
here, "todos" same as "all" users
![propriedades de electron-cash-2 9 2 exe 2017-08-14 20 48 25](https://user-images.githubusercontent.com/595991/29296641-f933cee0-8131-11e7-8361-98dd3db60b41.png)

**Comment by fyookball** [comment]
try with new 2.9.3 verbose version
